<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxcartpro
 * @version    2.5.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
?>
<div class="ajaxcartpro_progress--container">
	<div class="ajaxcartpro_progress" style="display: none;">
		<?php if (Mage::getStoreConfig('ajaxcartpro/general/activityindicator')): ?>
			<img src="<?php echo $this->getSkinUrl('images/loader.gif');?>" alt=""/>
		<?php else: ?>
			<img src="<?php echo $this->getSkinUrl('images/loader.gif');?>" alt=""/>
		<?php endif; ?>
	</div>
</div>
