<?php
/**
 * Mageplace Survey
 *
 * @category	Belitsoft
 * @package		Belitsoft_Survey
 * @copyright	Copyright (c) 2012 Mageplace. (http://www.mageplace.com)
 * @license		http://www.mageplace.com/disclaimer.html
 */

?>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<div class="page-title">
	<h1><?php echo $this->__('My Surveys'); ?></h1>
</div>

<?php if( $this->getCollection() && $this->count()): ?>
	<?php echo $this->getToolbarHtml(); ?>
	<table class="data-table" id="my-reviews-table">
		<col width="120" />
		<col />
		<col width="90" />
		<thead>
			<tr>
				<th><?php echo $this->__('Passed'); ?></th>
				<th><?php echo $this->__('Survey name'); ?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->getCollection() as $_survey): ?>
			<tr>
				<td><?php echo $this->dateFormat($_survey->getCreationDate()); ?></td>
				<td><h2 class="product-name"><a href="<?php echo $this->getSurveyLink($_survey); ?>"><?php echo $this->htmlEscape($_survey->getSurveyName()); ?></a></h2></td>
				<td>
					<?php if(Mage::helper('belitsoft_survey')->isCustomerCanEdit()) : ?>
					<a href="<?php echo $this->getSurveyEditLink($_survey); ?>" class="nobr"><?php echo $this->__('Edit'); ?></a>
						<?php if(Mage::helper('belitsoft_survey')->isCustomerCanView()) : ?>
						&nbsp;|&nbsp;
						<?php endif; ?>
					<?php endif; ?>

					<?php if(Mage::helper('belitsoft_survey')->isCustomerCanView()) : ?>
					<a href="<?php echo $this->getSurveyLink($_survey); ?>" class="nobr"><?php echo $this->__('View'); ?></a>
					<?php endif; ?>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<script type="text/javascript">decorateTable('my-reviews-table')</script>
	<?php echo $this->getToolbarHtml() ?>
<?php else: ?>
	<p><?php echo $this->__('You have not passed any survey.'); ?></p>
<?php endif; ?>
<div class="buttons-set">
	<p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()); ?>"><small>&laquo; </small><?php echo $this->__('Back'); ?></a></p>
</div>