<div id="top"></div>
<div class="header-container">
    <div class="header">
        
        <div class="header-left">
 <?php echo $this->getChildHtml('topBar') ?>
            
        </div>
        <div class="header-center">            
			
            <?php if ($this->getIsHomePage()):?>           
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php else:?>
			<a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif
		//Añadido el logo también en el else para que salga en toda la web
	     ?>
      <span class="welcome-msg"><?php echo $this->getWelcome() ?></span>
  	</div>        
        <div class="header-right">
		
            <div class="minicart">
                <?php echo $this->getChildHtml('top_cart') ?>
				<?php echo $this->getChildHtml('store_language') ?>	
            </div>  
			
            <?php echo $this->getChildHtml('currency') ?>  
            <div class="clear"></div>   
            <?php echo $this->getChildHtml('topLinks') ?>  
        </div> 
                <a href="#menu-right" class="friends right"></a>
        <nav id="menu-right">    

        <div class="header-right--mobile">
            <div class="header-left--mobile">
                <?php echo $this->getChildHtml('topBar') ?>
            
        </div>
            <div class="minicart">
                <?php echo $this->getChildHtml('top_cart') ?>
                <?php echo $this->getChildHtml('store_language') ?> 
            </div>  
            
            <?php echo $this->getChildHtml('currency') ?>  
            <div class="clear"></div>   
            <?php echo $this->getChildHtml('topLinks') ?>  
        </div>
        </nav>       
    </div>
    <?php echo $this->getChildHtml('topMenu') ?>
    <!--Añadimos el mini banner superior excepto en la home	-->
    
     <?php if (Mage::app()->getStore()->getId()==2): ?>
	 	<?php if ((Mage::getSingleton('cms/page')->getPageId()!='2') && (Mage::getSingleton('cms/page')->getPageId()!='10')): ?>
			
	    		<div class="banner_class">
					<div class="banner--center">SANTA SPECIA FREE SHIPPING</div>
                    <div class="banner--right"><a target="_blank" rel="shadowbox;width=728 height=230;scroll=none" href="<?php echo $this->getUrl('') ?>santa-special-free-shipping-conditions"><span style="float: right;text-decoration: underline;margin-right: 10px;color: white;">Terms & Conditions</span></a></div>
				</div>		
                <div class="banner_class2">
                    <div class="banner--left2"></div>
                    <div class="banner--center2"><img src="<?php echo  $this->getSkinUrl('images/gift-text2.png');?>" style="width:100%;"/></div>
                    <div class="banner--right2"><a target="_blank" rel="shadowbox;width=728 height=230;scroll=none" href="<?php echo $this->getUrl('') ?>gift-card-page-term"><span style="float: right;text-decoration: underline;margin-right: 10px;color: white;">Terms & Conditions</span></a></div>
                </div>  	
                <span style="text-align: right;font-size: 1em;width: 100%;float: right;">* For non-discounted item orders of 150&euro; and over. Ends Dec, 20 at midnight CET.</span>
    	<?php endif ?>
    <?php elseif (Mage::app()->getStore()->getId()==1): ?>
    	<?php if ((Mage::getSingleton('cms/page')->getPageId()!='2') && (Mage::getSingleton('cms/page')->getPageId()!='10')): ?>
			
	    		<div class="banner_class">
					<div class="banner--left"></div>
					<div class="banner--center"><img src="<?php echo  $this->getSkinUrl('images/gift-text.png');?>" style="width:100%;"/></div>
                    <div class="banner--right"><a target="_blank" rel="shadowbox;width=728 height=230;scroll=none" href="<?php echo $this->getUrl('') ?>santa-special-free-shipping-conditions"><span style="float: right;text-decoration: underline;margin-right: 10px;color: white;">Ver Condiciones</span></a></div>
				</div>
                <div class="banner_class">
                    <div class="banner--left"></div>
                    <div class="banner--center"><img src="<?php echo  $this->getSkinUrl('images/gift-text2.png');?>" style="width:100%;"/></div>
                    <div class="banner--right"><a target="_blank" rel="shadowbox;width=728 height=230;scroll=none" href="<?php echo $this->getUrl('') ?>gift-card-page-term-es"><span style="float: right;text-decoration: underline;margin-right: 10px;color: white;">Ver Condiciones</span></a></div>
                </div>
                <span style="text-align: right;font-size: 1em;width: 100%;float: right;">* Para pedidos que contengan al menos 150&euro; en productos no rebajados. Finaliza el 20 de Diciembre a medianoche CET.</span>		
    	<?php endif ?>
	<?php endif; ?>
		
	<?php echo $this->getChildHtml('topBread') ?>
    <?php echo $this->getChildHtml('topContainer'); ?>
	
</div>