<?php $paisesUE = array ('DE','AT','BE','BG','CY','HR','DK','SK','SI','ES','EE','FI','FR','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','UK','CZ','RO','SE','GB'); ?>
<?php $paisCustomer = Mage::getSingleton('geoip/country')->getCountry(); 
$rutaImagent = Mage::getBaseUrl('media') . 'wysiwyg/ss16/yezzy.jpg';
$rutaBanner = Mage::getBaseUrl('media') . 'wysiwyg/ss16/YEEZY_BLACK-BANNER.jpg';
?>
<?php 
$precio=0;
if(in_array($paisCustomer, $paisesUE)):
	$precio=200 . "€";
else: 
	$precio=165.29 . "€";
endif;
$marca="Adidas By Kanye West";
$titulo="Yeezy Boost 350 BLACK";
?>
<style>
    .box {
        padding: 5px;
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        background: rgba(15,15,15,0.2);
    }
    .cerrar{
        position: absolute;
        right: 14px;
		top: 0;
        font-size: 2em;
        cursor: pointer;
    }
</style>
<?php if($_GET['mensa']):?>
<div id="messages_product_view"><ul class="messages"><li class="success-msg"><ul><li><span>Thanks for your contact.</span></li></ul></li></ul></div>
<?php
endif;
?>
<div style="width:100%; text-align: right; background:url('<?php echo $rutaBanner ?>') no-repeat left center, #fff;height: 388px;">
<!--<div class="yeezy--text" style="float: right; margin: 63px 54px 0px 0px; width: 293px; height: 153px; background:url('<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/texto-yeezy-350tan.png') no-repeat left center;">

</div>-->
</div>

<?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>
<h2 style="text-align: center;">WELCOME TO ELITE YEEZY BOOST 350 BLACK RAFFLE!</h2>
<p style="margin: 3em 0; text-align: center;">
Sign up for a chance to buy a pair of the super coveted sneakers from adidas Originals by Kanye West collab!
</p>
<p style="margin: 3em 0; text-align: center;">
Just click on your preferred size and fill in the form. Since it can be you who’ll be receiving our phone call and email on Friday, please double-check your number and address before hitting the submit button. Fingers (and toes) crossed!
</p>
<?php else:?>
<h2 style="text-align: center;">¡BIENVENID@ A NUESTRA RIFA DE YEEZY BOOST 350 BLACK!</h2>
<p style="margin: 3em 0; text-align: center;">
Para registrarte en el sorteo de las zapatillas diseñadas por Kanye West para adidas Originals, simplemente haz click a tu talla preferida y rellena el formulario. 
</p>
<p style="margin: 3em 0; text-align: center;">
Puesto que puedes ser tú a quien le llamaremos y mandaremos un email de felicitación (y un link privado para poder comprar tus zapatillas) el próximo viernes 19 de febrero, por favor, asegúrate de que tu número de teléfono y dirección de email estén correctos antes de darle a enviar. ¡Mucha suerte!

</p>
<?php endif; ?>
<!--       primera yeezy-->
<ul class="products-grid columns3 first odd" style="width:100%;">
    <li class="item first " style="width: 225px;">
                <map name="mapa4"> 
                    <area alt="Yeezy Subscribe" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol4').style.display = 'block';"> 
                </map> 
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa4">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 6,5UK)- 1 unit available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
                
			<!--onClick="document.getElementById('hol4').style.display = 'block';" -->
    </li>
    <li class="item first " style="width: 225px;">
                <map name="mapa3"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol3').style.display = 'block';"> 
                </map> 
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa3">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 7UK)- 1 unit available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
			<!--onClick="document.getElementById('hol3').style.display = 'block';" -->
    </li>
    <li class="item first " style="width: 225px;">
                <map name="mapa2"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol2').style.display = 'block';"> 
                </map> 
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa2">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 7,5UK)- 2 unit available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
			<!--onClick="document.getElementById('hol2').style.display = 'block';" -->
  	</li>
    <li class="item first " style="width: 225px;">
                <map name="mapa1"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol1').style.display = 'block';"> 
                </map> 
        <img src="<?php echo $rutaImagent?>" width="215" height="215" alt="Yeezy" usemap="#mapa1">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 8UK)- 2 unit available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
            <!--onClick="document.getElementById('hol1').style.display = 'block';" -->
    </li>


    <li class="item first " style="width: 225px;">
                <map name="mapa5"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol5').style.display = 'block';"> 
                </map> 
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa5">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 8,5UK)- 3 unit available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
                
			<!--onClick="document.getElementById('hol4').style.display = 'block';" -->
    </li>
    <li class="item first " style="width: 225px;">
                <map name="mapa6"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol6').style.display = 'block';"> 
                </map> 
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa6">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 9UK)- 3 units available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
			<!--onClick="document.getElementById('hol3').style.display = 'block';" -->
    </li>
    <li class="item first " style="width: 225px;">
                <map name="mapa7"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol7').style.display = 'block';"> 
                </map> 
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa7">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 9,5UK)- 3 units available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
			<!--onClick="document.getElementById('hol2').style.display = 'block';" -->
  	</li>
    <li class="item first " style="width: 225px;">
                <map name="mapa8"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol8').style.display = 'block';"> 
                </map> 
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa8">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 10UK)- 3 units available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
            <!--onClick="document.getElementById('hol1').style.display = 'block';" -->
    </li>


    <li class="item first " style="width: 225px;">
                <map name="mapa9"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol9').style.display = 'block';"> 
                </map> 
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa9">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 10,5UK)- 3 units available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
                
			<!--onClick="document.getElementById('hol4').style.display = 'block';" -->
    </li>
    <li class="item first " style="width: 225px;">
                <map name="mapa10"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol10').style.display = 'block';"> 
                </map> 
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa10">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 11UK)- 1 units available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
			<!--onClick="document.getElementById('hol3').style.display = 'block';" -->
    </li>
    <li class="item first " style="width: 225px;">
                <map name="mapa11"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol11').style.display = 'block';"> 
                </map> 
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa11">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 11,5UK)- 2 unit available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
			<!--onClick="document.getElementById('hol2').style.display = 'block';" -->
  	</li>
    <li class="item first " style="width: 225px;">
                <map name="mapa12"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol12').style.display = 'block';"> 
                </map> 
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa12">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 12UK)- 1 unit available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
            <!--onClick="document.getElementById('hol1').style.display = 'block';" -->
    </li>

</ul>

<!--       ultima yeezy-->

<div class="box simple_contact7" id="hol4" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol4').style.display = 'none';">x</div>
<form id="simple_contact_form8" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="6.5">
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value=""  required  class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value=""   required class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value=""  required  class="required-entry input-text validate-email" type="email" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" required  class="required-entry input-text" type="phone" />
                </div>
                
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<div class="box simple_contact8" id="hol3" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol3').style.display = 'none';">x</div>
<form id="simple_contact_form9" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="7">
                               <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value="" class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value="" class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value="" class="required-entry input-text validate-email2" type="text" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" class="required-entry input-text" type="text" />
                </div>
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
       <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<div class="box simple_contact9" id="hol2" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol2').style.display = 'none';">x</div>
<form id="simple_contact_form9" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="7.5">
                                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value="" class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value="" class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value="" class="required-entry input-text validate-email3" type="text" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" class="required-entry input-text" type="text" />
                </div>
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<div class="box simple_contact10" id="hol1" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol1').style.display = 'none';">x</div>
<form id="simple_contact_form10" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="8">
                               <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value="" class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value="" class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value="" class="required-entry input-text validate-email4" type="text" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" class="required-entry input-text" type="text" />
                </div>
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
       <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<div class="box simple_contact11" id="hol5" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol5').style.display = 'none';">x</div>
<form id="simple_contact_form8" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="8.5">
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value=""  required  class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value=""   required class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value=""  required  class="required-entry input-text validate-email" type="email" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" required  class="required-entry input-text" type="phone" />
                </div>
                
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<div class="box simple_contact12" id="hol6" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol6').style.display = 'none';">x</div>
<form id="simple_contact_form8" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="9">
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value=""  required  class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value=""   required class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value=""  required  class="required-entry input-text validate-email" type="email" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" required  class="required-entry input-text" type="phone" />
                </div>
                
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<div class="box simple_contact13" id="hol7" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol7').style.display = 'none';">x</div>
<form id="simple_contact_form8" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="9.5">
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value=""  required  class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value=""   required class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value=""  required  class="required-entry input-text validate-email" type="email" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" required  class="required-entry input-text" type="phone" />
                </div>
                
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<div class="box simple_contact14" id="hol8" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol8').style.display = 'none';">x</div>
<form id="simple_contact_form8" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="10">
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value=""  required  class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value=""   required class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value=""  required  class="required-entry input-text validate-email" type="email" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" required  class="required-entry input-text" type="phone" />
                </div>
                
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<div class="box simple_contact15" id="hol9" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol9').style.display = 'none';">x</div>
<form id="simple_contact_form8" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="10.5">
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value=""  required  class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value=""   required class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value=""  required  class="required-entry input-text validate-email" type="email" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" required  class="required-entry input-text" type="phone" />
                </div>
                
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<div class="box simple_contact16" id="hol10" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol10').style.display = 'none';">x</div>
<form id="simple_contact_form8" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="11">
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value=""  required  class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value=""   required class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value=""  required  class="required-entry input-text validate-email" type="email" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" required  class="required-entry input-text" type="phone" />
                </div>
                
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<div class="box simple_contact17" id="hol11" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol11').style.display = 'none';">x</div>
<form id="simple_contact_form8" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="11.5">
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value=""  required  class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value=""   required class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value=""  required  class="required-entry input-text validate-email" type="email" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" required  class="required-entry input-text" type="phone" />
                </div>
                
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<div class="box simple_contact18" id="hol12" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol12').style.display = 'none';">x</div>
<form id="simple_contact_form8" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="12">
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value=""  required  class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value=""   required class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value=""  required  class="required-entry input-text validate-email" type="email" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" required  class="required-entry input-text" type="phone" />
                </div>
                
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>
<p style="margin-top: 1em;">
RAFFLE TERMS &amp; CONDITIONS<br>
• The raffle starts on Monday, February 15 at 12.00 noon CET and ends on Thursday, February 18 at the same time.<br>
• By signing up for the raffle (in case you haven’t joined us yet), you automatically sign up for our newsletter.<br>
• You can participate in either our in-store or in our online raffle, only one registration will be allowed.<br>
• Only ONE entry per person is allowed. <u>Any attempt for multiple entries will void all of that participant’s entries, and the participant will be disqualified.</u><br>

• On Friday, February 19, the winners will be announced on our social media, and notified via phone and email, including a private link to finish the purchase. In case the winner doesn’t make the purchase within 24hrs, a new winner will be randomly selected from among all signed up participants.<br>
• Return policy: refund within 14 days of the delivery date. <br>
• In case of a return, a new winner will be randomly selected from among all signed up participants.<br>

</p>
<?php else:?>
<p style="margin-top: 1em;">
CONDICIONES DE LA SUBASTA<br>
• La rifa comenzará el lunes 15 de febrero a las 12.00 del mediodía CET, y terminará el jueves 18 de febrero a la misma hora.<br>
• Al enviar tu solicitud de suscripción (en el caso de que no lo estés ya), te suscribes a nuestro newsletter.<br>
• Solamente te puedes registrar en una de nuestras rifas: online o en nuestra tienda Elite Hombre en Puerto Banús.<br>
• Solo está permitida UNA solicitud de suscripción por persona. <u>Cualquier intento de múltiples registros, resultará en la descalificación del participante.</u><br>
• El viernes 19 de febrero, los ganadores serán anunciados en nuestras redes sociales, y notificados via email y teléfono, incluyendo un link privado para formalizar la compra. En el caso de que el ganador no formalizase la compra en las siguientes 24h, un nuevo ganador será seleccionado de entre los restantes participantes.<br>
• Política de devolución: El plazo de devolución del artículo es de 14 días desde la recepción del mismo. <br>
• En caso de devolución, se seleccionará un nuevo ganador de entre los restantes participantes.<br>

</p>
<?php endif; ?>
</script>