<?php $paisesUE = array ('DE','AT','BE','BG','CY','HR','DK','SK','SI','ES','EE','FI','FR','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','UK','CZ','RO','SE','GB'); ?>
<?php $paisCustomer = Mage::getSingleton('geoip/country')->getCountry(); ?>
<?php 
$precio=0;
if(in_array($paisCustomer, $paisesUE)):
	$precio=200 . "€";
else: 
	$precio=200 . "€";
endif;
$marca="Adidas By Kanye West";
$titulo="Yeezy Boost 750";
$tallas=$arrayName = array('7,5' => '1', '8' => '1', '8,5' => '1', '9' => '1', '9,5' => '1', '10' => '1', '10,5' => '1', '11' => '1', );
$rutaImagen = Mage::getBaseUrl('media') . 'wysiwyg/aw16/miniatura_yeezy-750_11junio.jpg';
$rutaBanner = Mage::getBaseUrl('media') . 'wysiwyg/aw16/banner_yeezy-750_11junio.jpg';
$hoy = strtotime(date("d-m-Y H:i:00",time()));
echo date("d-m-Y H:i:00",time());
$fechaFin = strtotime("11-06-2016 00:00:00");
$fechaInicio = strtotime("05-06-2016 00:00:00");
?>
<style>
        .box {
            padding: 5px;
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            background: rgba(15,15,15,0.2);
        }
        .cerrar{
            position: absolute;
            right: 14px;
            top: 0;
            font-size: 2em;
            cursor: pointer;
        }
    </style>
<?php if($_GET['mensa']):?>
    <div id="messages_product_view"><ul class="messages"><li class="success-msg"><ul><li><span>Thanks for your contact.</span></li></ul></li></ul></div>
    <?php
    endif;
    ?>
    <div style="width:100%; text-align: right; background:url('<?php echo $rutaBanner; ?>') no-repeat left center, #fff;height: 388px;">
    </div>
<?php
if($hoy<$fechaFin && $hoy>$fechaInicio)
{
    ?>
    
    
    

    <?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>
    <h2 style="text-transform: uppercase;">WELCOME TO ELITE <?php echo $titulo; ?> RAFFLE!</h2>
    <p style="margin: 3em 0;">
    Sign up for a chance to buy a pair of the super coveted sneakers from Adidas Originals by Kanye West collab!
    </p>
    <p style="margin: 3em 0;">
    Just click on your preferred size and fill in the form. Since it can be you who’ll be receiving our phone call and email tomorrow, please double-check your number and address before hitting the submit button. Fingers (and toes) crossed!
    </p>
    <?php else:?>
    <p style="margin: 3em 0;">
    Teniendo en cuenta el altísimo interés por las zapatillas de la edición limitada de Adidas Originals por Kanye West, creemos que la forma más justa de venderlas online, es a través de una rifa.
    </p>
    <p style="margin: 3em 0;">
    Simplemente haz click a tu talla preferida y rellena el formulario. Puesto que puedes ser tú a quien le llamaremos y mandaremos un email de felicitación (y un link privado para poder comprar tus zapatillas) mañana mismo, por favor, asegúrate de que tu número de teléfono y dirección de email estén correctos antes de darle a enviar. ¡Mucha suerte!

    </p>
    <?php endif; ?>
    <!--       primera yeezy-->
    <ul class="products-grid columns3 first odd" style="width:100%;">
    <?php 
    $contaddor=0;
    foreach ($tallas as $key => $value):
        ?>
        <li class="item first " style="width: 225px;">
            <map name="mapa<?php echo $contaddor; ?>"> 
                <area alt="Yeezy Subscribe" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol<?php echo $contaddor; ?>').style.display = 'block';"> 
            </map> 
            <img src="<?php echo $rutaImagen; ?>" width="215" height="215" alt="Yeezy" usemap="#mapa<?php echo $contaddor; ?>">
            <div class="moreinfo">
                <div class="product-title">
                    <div class="manuf-list"><?php echo $marca; ?></div>
                    <div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: <?php echo $key; ?>UK)- <?php echo $value; ?> unit available</div>
                </div>
                <div class="price-box">
                    <span class="regular-price" id="product-price-54694"> 
                        <span class="price"><?php echo $precio; ?></span>      
                    </span>
                </div>
            </div>
        </li>
    <?php
    $contaddor = $contaddor++;
    endforeach;
    ?>
    </ul>
    <!-- formularios yeezy-->
    <?php 
    $contaddor2=0;
    foreach ($tallas as $key => $value):
    ?>
    <div class="box simple_contact<?php echo $contaddor2; ?>" id="hol<?php echo $contaddor2; ?>" style="display: none;">
        <div style="background: rgba(255,255,255,0.9);padding: 32px;width: 50%;position: relative;margin: 0 auto;border: 1px solid #000;">
            <div class="cerrar" onClick="document.getElementById('hol<?php echo $contaddor2; ?>').style.display = 'none';">x</div>
                <form id="simple_contact_form<?php echo $contaddor2; ?>" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
                    <fieldset class="group-select">
                        <ul>
                            <li>
                                <input type="hidden" name="talla" value="<?php echo $key; ?>"/>
                                <div class="input-box">
                                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
                 
                                    <input name="name" id="name" title="Name" value=""  required  class="required-entry input-text" type="text" />
                                </div>
                                <div class="input-box">
                                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
                 
                                    <input name="surname" id="surname" title="surname" value=""   required class="required-entry input-text" type="text" />
                                </div>
                                <div class="input-box">
                                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                                    <input name="email" id="email" title="Email" value=""  required  class="required-entry input-text validate-email" type="email" />
                                </div>
                                <div class="input-box">
                                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
                 
                                    <input name="phone" id="phone" title="phone" value="" required  class="required-entry input-text" type="phone" />
                                </div>
                            </li>
                        </ul>
                    </fieldset>
                    <div class="button-set">
                        <p class="required">* Required Fields</p>
                        <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
                 
                    </div>
                </form>
        </div>
    </div>
    <?php
    $contaddor2 = $contaddor2++;
    endforeach;
    ?> 

    <?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>
    <p style="margin-top: 1em;">
    RAFFLE CONDITIONS<br>
    • The raffle starts on Tuesday, December 29 at 11.00 AM CET and ends on Wednesday, December 30 at the same time.<br>
    • By signing up for the raffle (in case you haven’t joined us yet), you automatically sign up for our newsletter.<br>
    • Only ONE entry per person is allowed. <br>
    • The winners will be announced on our social media, and notified via phone and email, including a private link to finish the purchase. In case the winner doesn’t make the purchase within 24hrs, a new winner will be randomly selected from among all signed up participants.<br>
    • Return policy: refund within 14 days of the delivery date. <br>
    • In case of a return, a new winner will be randomly selected from among all signed up participants.<br>
    </p>
    <?php else:?>
    <p style="margin-top: 1em;">
    CONDICIONES DE LA SUBASTA<br>
    • La rifa comenzará el Martes 29 de Diciembre a las 11AM CET y terminará el Miercoles 30 de Diciembre a la misma hora.<br>
    • Al enviar tu solicitud de suscripción (en el caso de que no lo estés ya), te suscribes a nuestro newsletter.<br>
    • Solo se tendrá en cuenta UNA solicitud de suscripción por persona. <br>
    • El ganador será anunciado en nuestras redes sociales, y personalmente via email y teléfono, incluyendo un link privado para formalizar la compra. En caso en que el ganador no formalizase la compra en las siguientes 24h, será seleccionado un nuevo ganador de entre los restantes participantes.<br>
    • Política de devolución: El plazo de devolución del artículo es de 14 días desde la recepción del mismo. <br>
    • En caso de devolución, se seleccionará un nuevo ganador de entre los restantes participantes.<br>
    </p>
    <?php endif; ?>
    </script>
<?php
}
else
{
    if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>
      <p>
        <h2 style="text-align:center;">
          Our <?php echo $titulo; ?> raffle is now closed. 
        </h2>
        <h2 style="text-align:center;">
          We’re going to announce the winners later today. Keep your fingers crossed!
        </h2>
        <br/>
        <br/>
        <br/>
        <br/>
      </p>
      <?php else:?>
      <p style="margin: 3em 0;">
        <h2 style="text-align:center;">
          El sorteo de las $titulo ya está cerrado. 
        </h2>
        <h2 style="text-align:center;">
          Anunciaremos el ganador a lo largo del día de hoy. Crucemos los dedos!!
        </h2>
        <br/>
        <br/>
        <br/>
        <br/>
      </p>
    <?php endif; 
}
?>
