<?php $paisesUE = array ('DE','AT','BE','BG','CY','HR','DK','SK','SI','ES','EE','FI','FR','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','UK','CZ','RO','SE','GB'); ?>
<?php $paisCustomer = Mage::getSingleton('geoip/country')->getCountry(); ?>
<?php 
$precio=0;
if(in_array($paisCustomer, $paisesUE)):
	$precio=200 . "€";
else: 
	$precio=200 . "€";
endif;
$marca="Adidas By Kanye West";
$titulo="Yeezy Boost 750";
$tallas=$arrayName = array('7,5' => '1', '8' => '1', '8,5' => '1', '9' => '1', '9,5' => '1', '10' => '1', '10,5' => '1', '11' => '1', );
?>
<style>
    .box {
        padding: 5px;
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        background: rgba(15,15,15,0.2);
    }
    .cerrar{
        position: absolute;
        right: 14px;
		top: 0;
        font-size: 2em;
        cursor: pointer;
    }
</style>
<?php if($_GET['mensa']):?>
<div id="messages_product_view"><ul class="messages"><li class="success-msg"><ul><li><span>Thanks for your contact.</span></li></ul></li></ul></div>
<?php
endif;
?>
<div style="width:100%; text-align: right; background:url('<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-350tan-rufffle-banner.jpg') no-repeat left center, #fff;height: 388px;">

</div>

<?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>
  <p>
    <h2 style="text-align:center;">
      Our <?php echo $titulo; ?> raffle is now closed. 
    </h2>
    <h2 style="text-align:center;">
      We’re going to announce the winners later today. Keep your fingers crossed!
    </h2>
    <br/>
    <br/>
    <br/>
    <br/>
  </p>
  <?php else:?>
  <p style="margin: 3em 0;">
    <h2 style="text-align:center;">
      El sorteo de las $titulo ya está cerrado. 
    </h2>
    <h2 style="text-align:center;">
      Anunciaremos el ganador a lo largo del día de hoy. Crucemos los dedos!!
    </h2>
    <br/>
    <br/>
    <br/>
    <br/>
  </p>
<?php endif; ?>
