<?php $paisesUE = array ('DE','AT','BE','BG','CY','HR','DK','SK','SI','ES','EE','FI','FR','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','UK','CZ','RO','SE','GB'); ?>
<?php $paisCustomer = Mage::getSingleton('geoip/country')->getCountry(); 
$rutaImagent = Mage::getBaseUrl('media') . 'wysiwyg/ss16/yezzy2.jpg';
$rutaBanner = Mage::getBaseUrl('media') . 'wysiwyg/ss16/YEEZY_BLACK-BANNER.jpg';
?>
<?php 
$precio=0;
if(in_array($paisCustomer, $paisesUE)):
	$precio=200 . "€";
else: 
	$precio=165.29 . "€";
endif;
$marca="Adidas By Kanye West";
$titulo="Yeezy Boost 350 BLACK";
?>
<style>
    .box {
        padding: 5px;
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        background: rgba(15,15,15,0.2);
    }
    .cerrar{
        position: absolute;
        right: 14px;
		top: 0;
        font-size: 2em;
        cursor: pointer;
    }
</style>
<?php if($_GET['mensa']):?>
<div id="messages_product_view"><ul class="messages"><li class="success-msg"><ul><li><span>Thanks for your contact.</span></li></ul></li></ul></div>
<?php
endif;
?>
<div style="width:100%; text-align: right; background:url('<?php echo $rutaBanner ?>') no-repeat left center, #fff;height: 388px;">
<!--<div class="yeezy--text" style="float: right; margin: 63px 54px 0px 0px; width: 293px; height: 153px; background:url('<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/texto-yeezy-350tan.png') no-repeat left center;">

</div>-->
</div>

<?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>
<h2 style="text-align: center;">WELCOME TO ELITE YEEZY BOOST 350 BLACK RAFFLE!</h2>
<p style="margin: 3em 0; text-align: center;">
Sign up for a chance to buy a pair of the super coveted sneakers from adidas Originals by Kanye West collab!
</p>
<p style="margin: 3em 0; text-align: center;">
Just click on your preferred size and fill in the form. Since it can be you who’ll be receiving our phone call and email on Friday, please double-check your number and address before hitting the submit button. Fingers (and toes) crossed!
</p>
<?php else:?>
<h2 style="text-align: center;">¡BIENVENID@ A NUESTRA RIFA DE YEEZY BOOST 350 BLACK!</h2>
<p style="margin: 3em 0; text-align: center;">
Para registrarte en el sorteo de las zapatillas diseñadas por Kanye West para adidas Originals, simplemente haz click a tu talla preferida y rellena el formulario. 
</p>
<p style="margin: 3em 0; text-align: center;">
Puesto que puedes ser tú a quien le llamaremos y mandaremos un email de felicitación (y un link privado para poder comprar tus zapatillas) el próximo viernes 19 de febrero, por favor, asegúrate de que tu número de teléfono y dirección de email estén correctos antes de darle a enviar. ¡Mucha suerte!

</p>
<?php endif; ?>
<!--       primera yeezy-->
<ul class="products-grid columns3 first odd" style="width:100%;">
    <li class="item first " style="width: 225px;    height: 390px;">
                 
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa4">
                <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 6,5UK:<?php else: ?>Ganadores talla 6,5UK:<?php endif ?></div>

                    </div>
				<ul style="margin: 10px 30px;list-style-type: disc;">
               		<li>Travis Travis</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-black-size65.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
                
			<!--onClick="document.getElementById('hol4').style.display = 'block';" -->
    </li>
    <li class="item first " style="width: 225px;    height: 390px;">
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa3">
                <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 7UK:<?php else: ?>Ganadores talla 7UK:<?php endif ?></div>

                    </div>
				<ul style="margin: 10px 30px;list-style-type: disc;">
               		<li>Mónica Speck</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-black-size7.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
			<!--onClick="document.getElementById('hol3').style.display = 'block';" -->
    </li>
    <li class="item first " style="width: 225px;    height: 390px;">
		<img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa2">
                <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 7,5UK:<?php else: ?>Ganadores talla 7,5UK:<?php endif ?></div>

                    </div>
				<ul style="margin: 10px 30px;list-style-type: disc;">
               		<li>Alfredo Gutierrez</li>
                    <li>Kelly Boswell</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-black-size75.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
			<!--onClick="document.getElementById('hol2').style.display = 'block';" -->
  	</li>
    <li class="item first " style="width: 225px;    height: 390px;">
        <img src="<?php echo $rutaImagent?>" width="215" height="215" alt="Yeezy" usemap="#mapa1">
                <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 8UK:<?php else: ?>Ganadores talla 8UK:<?php endif ?></div>

                    </div>
				<ul style="margin: 10px 30px;list-style-type: disc;">
               		<li>Arnesh Sahay</li>
                    <li>Ramon Ruiz</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-black-size8.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
            <!--onClick="document.getElementById('hol1').style.display = 'block';" -->
    </li>

	
	
	
	
    <li class="item first " style="width: 225px;    height: 390px;">               
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa5">
                <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 8,5UK:<?php else: ?>Ganadores talla 8,5UK:<?php endif ?></div>

                    </div>
				<ul style="margin: 10px 30px;list-style-type: disc;">
               		<li>Jake Buckley</li>
                    <li>Timmy le Timmy</li>
					<li>Matthew Chan</li>
					<li>Humberto</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-black-size85.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
                
			<!--onClick="document.getElementById('hol4').style.display = 'block';" -->
    </li>
	
	
    <li class="item first " style="width: 225px;    height: 390px;">
                 
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa6">
                <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 9UK:<?php else: ?>Ganadores talla 9UK:<?php endif ?></div>

                    </div>
				<ul style="margin: 10px 30px;list-style-type: disc;">
               		<li>Alvaro Garcia</li>
                    <li>Kimberly vong</li>
					<li>Shabnam Mohseni</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-black-size9.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
			<!--onClick="document.getElementById('hol3').style.display = 'block';" -->
    </li>
	
	
    <li class="item first " style="width: 225px;    height: 390px;">
                
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa7">
                <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 9,5UK:<?php else: ?>Ganadores talla 9,5UK:<?php endif ?></div>

                    </div>
				<ul style="margin: 10px 30px;list-style-type: disc;">
               		<li>Zenebu Amenewolde</li>
                    <li>Moses Storm</li>
					<li>Keegan Doherty</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-black-size95.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
			<!--onClick="document.getElementById('hol2').style.display = 'block';" -->
  	</li>
	
	
    <li class="item first " style="width: 225px; height: 390px;">
                 
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa8">
                <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 10UK:<?php else: ?>Ganadores talla 10UK:<?php endif ?></div>

                    </div>
				<ul style="margin: 10px 30px;list-style-type: disc;">
               		<li>Joseph Lewis</li>
                    <li>Joseph O'Donovan</li>
					<li>William Patch</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-black-size10.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
            <!--onClick="document.getElementById('hol1').style.display = 'block';" -->
    </li>


    <li class="item first " style="width: 225px;    height: 390px;">
                
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa9">
                <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 10,5UK:<?php else: ?>Ganadores talla 10,5UK:<?php endif ?></div>

                    </div>
				<ul style="margin: 10px 30px;list-style-type: disc;">
               		<li>Shane Watman</li>
                    <li>Jonathan Sanchez</li>
					<li>Eric Shyu</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-black-size105.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
                
			<!--onClick="document.getElementById('hol4').style.display = 'block';" -->
    </li>
	
	
    <li class="item first " style="width: 225px;    height: 390px;">
                
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa10">
                <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 11UK:<?php else: ?>Ganadores talla 11UK:<?php endif ?></div>

                    </div>
				<ul style="margin: 10px 30px;list-style-type: disc;">
               		<li>Angelica Kwon</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-black-size11.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
			<!--onClick="document.getElementById('hol3').style.display = 'block';" -->
    </li>
	
	
    <li class="item first " style="width: 225px;    height: 390px;">
                
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa11">
                <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 11,5UK:<?php else: ?>Ganadores talla 11,5UK:<?php endif ?></div>

                    </div>
				<ul style="margin: 10px 30px;list-style-type: disc;">
               		<li>Angela Wu</li>
					<li>Carmine Feola</li>
					<li>Oren Pesso</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-black-size115.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
			<!--onClick="document.getElementById('hol2').style.display = 'block';" -->
  	</li>
	
	
    <li class="item first " style="width: 225px;    height: 390px;">
                
        <img src="<?php echo $rutaImagent ?>" width="215" height="215" alt="Yeezy" usemap="#mapa12">
                <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 12UK:<?php else: ?>Ganadores talla 12UK:<?php endif ?></div>

                    </div>
				<ul style="margin: 10px 30px;list-style-type: disc;">
               		<li>Robyn McRae</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-black-size12.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
            <!--onClick="document.getElementById('hol1').style.display = 'block';" -->
    </li>

</ul>

<!--       ultima yeezy-->


<?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>
<p style="margin-top: 1em;">
RAFFLE TERMS &amp; CONDITIONS<br>
• The raffle starts on Monday, February 15 at 12.00 noon CET and ends on Thursday, February 18 at the same time.<br>
• By signing up for the raffle (in case you haven’t joined us yet), you automatically sign up for our newsletter.<br>
• You can participate in either our in-store or in our online raffle, only one registration will be allowed.<br>
• Only ONE entry per person is allowed. <u>Any attempt for multiple entries will void all of that participant’s entries, and the participant will be disqualified.</u><br>

• On Friday, February 19, the winners will be announced on our social media, and notified via phone and email, including a private link to finish the purchase. In case the winner doesn’t make the purchase within 24hrs, a new winner will be randomly selected from among all signed up participants.<br>
• Return policy: refund within 14 days of the delivery date. <br>
• In case of a return, a new winner will be randomly selected from among all signed up participants.<br>

</p>
<?php else:?>
<p style="margin-top: 1em;">
CONDICIONES DE LA SUBASTA<br>
• La rifa comenzará el lunes 15 de febrero a las 12.00 del mediodía CET, y terminará el jueves 18 de febrero a la misma hora.<br>
• Al enviar tu solicitud de suscripción (en el caso de que no lo estés ya), te suscribes a nuestro newsletter.<br>
• Solamente te puedes registrar en una de nuestras rifas: online o en nuestra tienda Elite Hombre en Puerto Banús.<br>
• Solo está permitida UNA solicitud de suscripción por persona. <u>Cualquier intento de múltiples registros, resultará en la descalificación del participante.</u><br>
• El viernes 19 de febrero, los ganadores serán anunciados en nuestras redes sociales, y notificados via email y teléfono, incluyendo un link privado para formalizar la compra. En el caso de que el ganador no formalizase la compra en las siguientes 24h, un nuevo ganador será seleccionado de entre los restantes participantes.<br>
• Política de devolución: El plazo de devolución del artículo es de 14 días desde la recepción del mismo. <br>
• En caso de devolución, se seleccionará un nuevo ganador de entre los restantes participantes.<br>

</p>
<?php endif; ?>
</script>