

<style type="text/css">

.language-header-dropdown {
    background: none repeat scroll 0% 0% #FFF;
    padding: 14px;
    display: none;
    position: absolute;
    margin: 0px;
    box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.15);
    
}
.language-header-dropdown ul li a {
    display: block;
    line-height: 28px;
    min-width: 110px;
    margin: 0px;
    padding: 0px 9px;
    color: #8C8C8C;
    transition: #F2F1F0 200ms ease-in-out 0s;
}
.language-header-dropdown ul li a:hover { background:#f5f4f4; text-decoration:none; }

.language-switch {
    line-height: 29px;
    background-repeat: no-repeat;
    background-position: 0% 50%;
    margin-right: 2px;
    float: left;
}
#language {
    color: rgba(108, 108, 108, 0.59);
    display: block;
    padding: 0px 10px;
    position: relative;
    z-index: 2;
}
.language-switch span.current {
    display: inline;
    color: rgba(29, 28, 27, 0.59);
    padding: 0px 12px 0px 5px;
    background: url("http://shopper.queldorei.com/skin/frontend/shopper/default/images/arrow_switch.png") no-repeat scroll 100% 50% transparent;
}
#mobile-lang{display: none;}
</style>
<!-- Currency BOF -->
    <div id="desktop-lang" class="lang-currency-container">
	<?php if(count($this->getStores())>1): ?>
	<?php $currentStore = Mage::app()->getStore()->getName(); ?>
    <span id="language"><?php echo $this->__('Language:') ?>
    	<span class="current" style='color: #1D1C1B;background-size: 7px 4px;'>
    		<?php echo $currentStore; ?></span>
    </span>
    <div class="language-header-dropdown" style='background-color: #fff;'>
    <ul>
	    <?php foreach ($this->getStores() as $_lang): ?>
	    <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
	    <li><a href="<?php echo $_lang->getCurrentUrl() ?>" ><?php echo $this->escapeHtml($_lang->getName()) ?></a></li>
	    <?php endforeach; ?>
    </ul>
    </div>

	<?php endif; ?>
	</div>
 <!-- Currency EOF -->

 <?php if(count($this->getStores())>1): ?>
<div id="mobile-lang" class="form-language">
    <!--<label for="select-language"><?php echo $this->__('Your Language:') ?></label>-->
    <select style="height: 20px;margin-top: 4px;" id="select-language" title="<?php echo $this->__('Your Language') ?>" onchange="window.location.href=this.value">
    <?php foreach ($this->getStores() as $_lang): ?>
        <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
        <option value="<?php echo $_lang->getCurrentUrl() ?>"<?php echo $_selected ?>><?php echo $this->escapeHtml($_lang->getName()) ?></option>
    <?php endforeach; ?>
    </select>
</div>
<?php endif; ?>
