<!--aditionalmiddlelinks-->
<div class="middlebanners">
    <div class="text-banner">
        <div class="titulo-text-banner">
            <?php echo Mage::getStoreConfig('home/additional_links/top_adlink_title')?>
        </div>
        <div class="text-text-banner">
            <?php echo Mage::getStoreConfig('home/additional_links/top_adlink_text')?>
        </div>
    </div>
    <div class="principal-image-banner">
        <a href="<?php echo Mage::getBaseUrl();?><?php echo Mage::getStoreConfig('home/additional_links/top_adlink_princial_image_link')?>">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>banners/<?php echo Mage::getStoreConfig('home/additional_links/top_adlink_principal_image')?>"/>
        </a>
    </div>
    <div class="bloque-imagenes-banner">
        <div class="bloque-dedos-imagenes-banner">
            <div class="bloque-dedos-imagenes-banner-bloque">
                <a href="<?php echo Mage::getBaseUrl();?><?php echo Mage::getStoreConfig('home/additional_links/top_adlink_image_1_link')?>">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>banners/<?php echo Mage::getStoreConfig('home/additional_links/top_adlink_image_1')?>"/>
                    <div class="texto">
                        <?php echo Mage::getStoreConfig('home/additional_links/top_adlink_image_1_text')?>
                    </div>
                </a>
            </div>
            <div class="bloque-dedos-imagenes-banner-bloque">
                <a href="<?php echo Mage::getBaseUrl();?><?php echo Mage::getStoreConfig('home/additional_links/top_adlink_image_2_link')?>">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>banners/<?php echo Mage::getStoreConfig('home/additional_links/top_adlink_image_2')?>"/>
                    <div class="texto">
                        <?php echo Mage::getStoreConfig('home/additional_links/top_adlink_image_2_text')?>
                    </div>
                </a>
            </div>
        </div>
        <div class="bloque-dedos-imagenes-banner">
            <div class="bloque-dedos-imagenes-banner-bloque">
                <a href="<?php echo Mage::getBaseUrl();?><?php echo Mage::getStoreConfig('home/additional_links/top_adlink_image_3_link')?>">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>banners/<?php echo Mage::getStoreConfig('home/additional_links/top_adlink_image_3')?>"/>
                    <div class="texto">
                        <?php echo Mage::getStoreConfig('home/additional_links/top_adlink_image_3_text')?>
                    </div>
                </a>
            </div>
            <div class="bloque-dedos-imagenes-banner-bloque">
                <a href="<?php echo Mage::getBaseUrl();?><?php echo Mage::getStoreConfig('home/additional_links/top_adlink_image_4_link')?>">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>banners/<?php echo Mage::getStoreConfig('home/additional_links/top_adlink_image_4')?>"/>
                    <div class="texto">
                        <?php echo Mage::getStoreConfig('home/additional_links/top_adlink_image_4_text')?>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>