<div class="page-title">
        <h1><?php echo $this->__('Cookies policy')?></h1>
</div>
<?php echo $this->__("Introduction. Definition and function of cookies.<br><br>
Cookie is a file that is downloaded to your computer when you access certain web pages. Cookies allow a website, among other things, to store and retrieve information about the browsing habits of a user or his or her computer and, depending on the information they contain and how they use their equipment, can be used to recognize to user. The User's browser memorizes Cookies on the hard disk only during the current session occupying a minimum memory space and not harming the computer. Cookies do not contain any specific personal information, and most of them are deleted from the hard disk at the end of the browser session (so-called Session Cookies).<br><br>
Most browsers accept Cookies as standard and, regardless of the cookies, allow or inhibit temporary or memorized Cookies in security settings.<br><br>
Without your express consent - through the activation of Cookies in your browser - Gran Calibre<br><br> Will not link in the cookies the data stored with your personal data provided at the time of your request or purchase.<br><br>
<h5>What kind of cookies does this website use?</h5><br><br>
According to the entity that manages them:<br><br>
- Own cookies: These are those that are sent from our own computers or domain.<br>
- Third party cookies: those that are sent from a computer or domain that is not managed by us, but by a third entity.
Depending on the length of time they remain activated:<br>
- Session cookies: These are temporary cookies that remain in your browser until you leave the web page, not being registered on the hard disk of your computer or equivalent device. With it, we analyze the patterns of traffic on the web, which allows us to progressively improve the contents and uses of the web.<br>
- Persistent cookies: are those that are stored on the hard drive for a certain time and are read by our website every time a new visit is made. These cookies expire after the pre-established deadline and are usually used to facilitate the purchase and registration services.<br>
According to its purpose:<br><br>
- Technical Cookies: They are those that allow the user to obtain a satisfactory navigation since they make possible a good operation of the web. For example, they allow you to control traffic and data communication, access restricted areas, carry out the purchase process or request form, use security features, store content for the broadcast of videos or share content through social networks .<br>
- Personalization Cookies: These are the ones that allow the user to access the service with predefined characteristics based on a series of criteria (language, type of browser through which the service is accessed, regional configuration from which the service is accessed, etc. ...).<br>
- Analysis cookies: These are the ones that allow the quantification of the number of users and thus make the statistical measurement and analysis of the users' use of the services provided.<br>
- Advertising Cookies: They are those that allow the management, in the most effective way possible, of the advertising spaces that we offer.<br>
- Behavioral advertising cookies: They are those that store information of the behavior of the users obtained through the continuous observation of their habits of navigation, allowing to develop a specific profile to show advertising in function of the same.<br>
Below we detail the cookies used in our website and the purpose of them:<br><br>
<h5>OWN COOKIES:</h5><br><br>
Name Type Purpose * Excluded / not excluded (from duty of information and consent)<br><br>

* It is understood as cookies excluded from the duty of information and consent that are strictly necessary for the provision of a service strictly requested by the user or those necessary only to allow communication between the user's computer and the network, such as cookies Session, technical cookies and personalization cookies.<br><br>
<h5>THIRD PARTY COOKIES:</h5><br><br>
Name of the provider Purpose of the Cookie Description of the purpose of the Cookie If you want more information about the use of Cookies of this third party (link)<br><br>

These lists are updated as soon as possible when there is some kind of change in the services offered on the web. However, it may happen that during the update the list does not already include a Cookie, although they will always refer to Cookies with the same purposes as those registered in the list.<br><br>
Acceptance of the use of cookies. Obtaining consent and how to disable or delete cookies.<br><br>
The User expressly accepts, for the use of this website, the treatment of the information collected in the form and for the aforementioned purposes. And also recognizes the possibility of refusing to treat such data or information by refusing to use Cookies by selecting the appropriate settings for this purpose in your browser. While this option to block Cookies in your browser may not allow the full use of all the functionality of the Web and the experience on our website is less satisfactory.<br><br>
You can allow, block or delete cookies installed on your computer by configuring the browser options installed on your computer:<br><br>
• Internet Explorer: Windows.microsoft.com/en-us/internet-explorer/delete-manage-cookies#ie=ie-10<br>
• Firefox: support.mozilla.org/kb/Borrar%20cookies<br>
• Chrome: support.google.com/chrome/answer/95647?hl=en<br>
• Safari: www.apple.com/privacy/use-of-cookies/<br>
• Opera: http://help.opera.com/Windows/12.00/en/Cookies.html<br>
If you have questions about this cookie policy, you can contact Gran Calibre At info@elitestores.com.")?>
