<div class="page-title">
        <h1><?php echo $this->__('Help')?></h1>
</div>
<div class="col-left sidebar stickem">
    <div class="block block-account">
        <div class="block-content">
            <ul>
                <li class="current">
                    <a href="#answer1">
                        <?php echo $this->__('TERMS &amp; CONDITIONS')?>
                    </a> 
                </li>
                <li>
                    <a href="#answer2">
                        <?php echo $this->__('PRICES CURRENCY &amp; TAXES')?>
                    </a>                    
                </li>
                <li>
                    <a href="#answer3">
                        <?php echo $this->__('PAYMENT AND PROMO CODES')?>
                    </a>                    
                </li>
                <li>
                    <a href="#answer4">
                        <?php echo $this->__('SHIPPING AND INSURANCE')?>
                    </a>                    
                </li>
                <li>
                    <a href="#answer5">
                        <?php echo $this->__('RETURNS AND EXCHANGES')?>
                    </a>                    
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('contactus');?>">
                        <?php echo $this->__('CONTACT US')?>
                    </a>                    
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="customercontainer">
    
    <dl>
    <dt id="answer1" class="titleSection"><?php echo $this->__('TERMS &amp; CONDITIONS')?></dt>
    <dd><?php echo $this->__('Please read these Terms and Conditions carefully before using our website. By using our services, you agree to bind by these terms and conditions. If you do not accept these terms and conditions, you will not be able to use the Services.'); ?>
		<br><br>
        <p><?php echo $this->__('GRAN CALIBRE S.L. with CIF ESB92889567 and registered address in Conjunto Benabola 8, P.C. 29660, Puerto Banús – Marbella, Spain, is the supplier of the services and activities available in the web store Elitestores.com'); ?>
			<br><br>
			<?php echo $this->__('The products offered on Elitestores.com may be purchased directly on this website.'); ?>
			<br><br>
		</p>
		<h5><?php echo $this->__('ORDERS AND ACCEPTANCE OF YOUR ORDER');?></h5>
		<p><?php echo $this->__('All orders are subject to availability and acceptance. Items in your shopping basket are not reserved and may be purchased by other customers.')?>
			<br><br>
			<?php echo $this->__('Once you have placed an order, you will receive an email with all the relevant details related to it. This email is not an acceptance of your order, just a confirmation that we have received it.')?>
			<br><br>
			<?php echo $this->__('We reserve the right to not accept your order should one of the following reasons occur: that we are unable to obtain authorization for your payment, that shipping restrictions apply to a particular item, or that the item ordered is out of stock or does not satisfy our quality control standards and is withdrawn.')?>
			<br><br>
			<?php echo $this->__('We reserve the right to refuse to process and therefore accept a transaction for any reason or refuse service to anyone at any time at our sole discretion. We will not be responsible for withdrawing any merchandise from the site, whether or not it has been sold, or for removing, screening or suspending any transaction that has already begun.')?>
			<br><br>
			<?php echo $this->__('We make every effort to make sure the details on our site are accurate, however if we do discover a price error in our products in your order, we are under no obligation to accept or fulfill, and we reserve the right to cancel the order in question. If you order a product that is priced incorrectly for any reason, we will inform you via email or phone. If you have already paid for the goods, we will refund you the full amount as soon as possible. In the event that the products are recalled in transit, we will process the refund once the products are returned to us.');?>
		</p>
		<h5><?php echo $this->__('Customer Service');?></h5>
		<p><?php echo $this->__('For any incident or complaint, you can contact our customer care center at the following ');?><a href="'. Mage::getUrl('contactus').'"><?php echo $this->__('link')?></a><?php echo $this->__('. Incidents may also be submitted in writing to our offices in Pol. Industrial Nueva Campana, Nave 96 29660 Marbella, (Málaga), Spain.')?>
		</p>
	</dd>
    <dt id="answer2" class="titleSection titleSection--intext"><?php echo $this->__('PRICES CURRENCY &amp; TAXES')?></dt>
    <dd>
		<p><?php echo $this->__('Prices shown on the site can be displayed in Euros, Pounds or Dollars, with you being able to change the desired currency at any time. The invoice will be issued in Euros (€).')?>
			<br><br>
			<?php echo $this->__('Final credit card and PayPal debited amounts may vary based on currency fluctuations and bank commissions.')?>
			<br><br>
			<?php echo $this->__('Elitestores.com encourages clients to contact their home bank to receive the accurate price conversion and any bank commissions related to the transaction.')?>
			<br><br>
			<?php echo $this->__('Customers purchasing from a country served as Delivered Duty Paid (DDP), will incur relevant import duty and tax. These costs are included in the final purchase price.')?>
			<br><br>
			<?php echo $this->__('Customers purchasing from a country served as Delivered Duty Unpaid (DDU), will be charged for the items purchased and shipping costs only. Import duty or tax costs will be invoiced directly from the currier service. We recommend you to contact your local customs authority to determine a landed cost price prior to purchase completion.')?>
			<br><br>
			<?php echo $this->__('All orders shipped within the EU, and orders under 800$ shipped to the US are served as DDP. All orders shipped outside the EU, except the orders under 800$ shipped to the US, will be served DDU.')?> 
		</p>
	</dd>
    <dt id="answer3" class="titleSection titleSection--intext"><?php echo $this->__('PAYMENT AND PROMO CODES')?></dt>
    <dd>
		<h3><?php echo $this->__('The following payment methods are accepted by Elitestores.com:')?></h3>
		<h5><?php echo $this->__('CREDIT OR DEBIT CARDS')?></h5>
		<p><?php echo $this->__('At Elitestores.com we accept VISA, MASTERCARD or MAESTRO cards.')?>
			<br><br>
			<?php echo $this->__('Elitestores.com clients are guaranteed maximum Credit Card security because all transactions are processed using a secure server. The customer\'s credit card information is sent directly through a totally secure encrypted connection to MultiSafepay, which collect the payment. Elitestores.com doesn´t have access at any time to the customer\'s credit card information.')?>
			<br><br>
			<?php echo $this->__('Elitestores.com customer services will not seek in any way information from your credit card to arrange payment.')?>
			<br><br>
			<?php echo $this->__('Elitestores.com advises clients to apply for E-commerce security PIN CODES provided by Verified by Visa and SecureCode by MasterCard.')?>
			<br><br>
			<?php echo $this->__('If there are sufficient funds and the account information is valid, the order will be processed instantly. Credit cards are charged at the moment that the order is confirmed for both available merchandise and for Pre-order items (which are shipped later in the season when the merchandise arrives).')?>
			<br><br>
			<?php echo $this->__('For more information visit the official website of MultiSafepay www.multisafepay.com')?>
			<br><br>
			<?php echo $this->__('You confirm that the credit/debit card that is being used is yours or that you have been specifically authorized by the owner of the credit/debit card to use it. All credit/debit cardholders are subject to validation checks and authorization by the card issuer. If the issuer of your payment card refuses to authorize a payment to Elitestores.com, we will not be liable for any delay or non-delivery.')?>
		</p>
		<h5><?php echo $this->__('PAYPAL')?></h5>
		<p>
			<?php echo $this->__('Our customers can pay by PayPal. When you select PayPal as the payment method, the page will be automatically redirected to the PayPal payment platform.')?>
			<br><br>
			<?php echo $this->__('Elitestores.com welcomes payments from PayPal accounts. Payments made with accounts verified by PayPal are automatically accepted. Elitestores.com reserves the right to not accept payments that have been made with non verified accounts.')?>
			<br><br>
			<?php echo $this->__('For more information, visit the official PayPal website at www.paypal.com')?>
			<br><br>
			<?php echo $this->__('You confirm that the credit/debit card that is being used is yours or that you have been specifically authorized by the owner of the credit/debit card to use it. All credit/debit cardholders are subject to validation checks and authorization by the card issuer. If the issuer of your payment card refuses to authorize a payment to Elitestores.com, we will not be liable for any delay or non-delivery.')?>
		</p>
		<h5><?php echo $this->__('BANK TRANSFER')?></h5>
		<p>
			<?php echo $this->__('The bank transfer service is the slowest of all payment methods. Once selected, the bank account details will be provided, as well as the amount and reference to be specified in the bank transfer.')?>
			<br><br> 
			<?php echo $this->__('The order will be accepted and the items reserved once we receive justification of the transfer being made.  Please note that up until this point the items are not reserved and could still be sold.')?>
			<br><br>
			<?php echo $this->__('After confirming the transfer has been received in our account, we will proceed to ship the goods.')?>
		</p>
		<h5><?php echo $this->__('PROMOTION CODES')?></h5>
		<p>
			<?php echo $this->__('Promotion codes are not transferable, and there is no cash alternative. All the individual promotion codes cannot be used in conjunction with other promotion codes or offers, and must be used before the published date of expiry.')?>
		</p>
	</dd>
	<dt id="answer4" class="titleSection titleSection--intext"><?php echo $this->__('SHIPPING AND INSURANCE')?></dt>
    <dd>
		<p>
			<?php echo $this->__('Elitestores.com will ship only to the address you selected in the original online order. <br><br>We will not modify the shipping address once an order has been placed.')?>
			<br><br>
			<?php echo $this->__('You will own the goods on and from the later of the point in time when either we receive the payment in full or, we deliver the goods to you.')?>
			<br><br>
			<?php echo $this->__('We aim to dispatch all orders the following working day, 2 days during sale periods. We may offer estimated delivery times. Elitestores.com cannot be held responsible for any delays caused by destinations customs clearance processes.')?>
			<br><br>
			<?php echo $this->__('If a delivery is delayed by any event outside of our control, we will contact you as soon as possible to let you know, and we will take steps to minimize the effect of the delay, however we cannot be held responsible for delays caused by this event.')?>
			<br><br>
			<?php echo $this->__('Elitestores.com ships worldwide using DHL, TNT or Nacex, depending on the destination. Orders are shipped with an official invoice declaring the exact total of merchandise purchased in Euros.')?>
			<br><br>
			<?php echo $this->__('Elitestores.com reserves the right to use an alternative currier if necessary for special circumstances.')?>
		</p>
		<h5><?php echo $this->__('SHIPPING RATE')?></h5>
		<p>
			<?php echo $this->__('To get an estimate, add the desired shipping items to the shopping cart and select the shipping address in the shipping estimator.')?>
		</p>
		<h5><?php echo $this->__('CUSTOMS CLEARENCE')?></h5>
		<p>
			<?php echo $this->__('Elitestores.com will not be responsible for any delivery delay caused by Customs Clearance at destination. The import expenses and any additional taxes will be paid by the client at destination, according to the legislation in the destination country.')?>
			<br><br>
			<?php echo $this->__('If a shipment is refused, we will do what we can to nullify the customs charges and have the shipment returned to Elitestores.com. We cannot guarantee that customs charges can be voided for a refused shipment. If not, we will deduct this amount from your refund. Both the original and return shipping fees, plus any additional customs charges, will be deducted from the refund.')?>
		</p>
		<h5><?php echo $this->__('SHIPMENT RESTRICTIONS')?></h5>
		<p>
			<?php echo $this->__('Due to import restrictions, there are some products not possible to be shipped to certain countries. Should this occur, Elite Store reserves the right to cancel and refund the order.')?>
		</p>
		<h5><?php echo $this->__('SHIPMENT INSURANCE')?></h5>
		<p>
			<?php echo $this->__('Elitestores.com insures each purchase, against theft or accidental damage during the time of transit until it is delivered to your specified delivery address. The goods are your responsibility from the time they are delivered to the address you gave us.')?>
		</p>
		<h5><?php echo $this->__('SHIPMENTS TO RUSSIA')?></h5>
		<p>
			<?php echo $this->__('Customs authorities in Russia have recently tightened restrictions on import shipments to Russia. As a consequence, non-document shipments sent to private individuals now undergo extraordinary scrutiny leading to an increased number of customs holds and delays in delivery. For this reason, Elitestores.com will ship only by National Post. Please note that shipments with this method are much slower.')?>
		</p>
	</dd>
    <dt id="answer5" class="titleSection titleSection--intext"><?php echo $this->__('RETURNS AND EXCHANGES')?></dt>
    <dd>
		<p>
			<b><?php echo $this->__('CANCELLING YOUR ORDER UNDER THE CONSUMER CONTRACTS (INFORMATION, CANCELLATION AND ADDITIONAL CHARGES) REGULATIONS 2013')?></b>
			<br><br>
			<?php echo $this->__('If you are based in the EU under the Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013 (ICACRs), you have the right to cancel your order provided you give us written notice within 14 days.')?>
		</p>
		<h5><?php echo $this->__('Right to Cancel under the ICACRs')?></h5>
		<p>
			<?php echo $this->__('You have the right to cancel your order within 14 days without giving any reason.')?>
			<br><br>
			<?php echo $this->__('The cancellation period will expire 14 days from the day after the day on which the last of the goods where delivered to the given shipment address.')?>
			<br><br>
			<?php echo $this->__('To cancel the order, please notify in writing to Elite- Gran Calibre, Pol. Ind. Nueva Campana, Nave 96, Marbella (Málaga), 29660, Spain, or by ')?><a href="<?php Mage::getUrl('contactus')?>"><?php echo $this->__('contact form')?></a>
			<br><br>
			<?php echo $this->__('You will have to bear the cost of returning the goods. We will be happy to organize the return shipment for you with our curriers, in which case we will then deduct these costs from the amount to refund. If you prefer you can organize your own return shipment.')?>
			<br><br>
			<?php echo $this->__('We will make a full refund, including the original shipping cost, once we receive the returned items. In the event that two different types of shipping were offered, and the client has chosen the more expensive one, Elitestores.com will refund the amount of the less expensive shipping option, independently to the option chosen by the client.')?>
			<br><br>
			<?php echo $this->__('We will make a deduction from the reimbursement for loss in value of any items supplied, if the loss is the result of unnecessary handling on your behalf.')?>
			<br><br>
			<?php echo $this->__('Returns must be sent and notified within 14 days.')?>
			<br><br>
			<?php echo $this->__('Returns must be sent to Elite- Gran Calibre, Pol. Ind. Nueva Campana, Nave 96, Marbella (Málaga), 29660, Spain.')?>
		</p>
		<h5><?php echo $this->__('RETURNS AND EXCHANGES USING OUR FREE COLLECTION SERVICE')?></h5>
		<p>
			<?php echo $this->__('If for any reason clients are not satisfied with an order, the item(s) can be returned for size exchange, store credit or refund within 14 days of the merchandise&apos;s delivery date.')?>
		</p>
		<ol>
			<li style="margin-bottom:20px">
				<b>1. </b>
				<a href="<?php echo Mage::getUrl('contactus') ?>"><?php echo $this->__('Contact us')?></a><?php echo $this->__(' to request a Return Authorization Number (R.A.N.). Please include the Order Number (T#######), the Item Code(s) of the item(s) to be returned, and state if the return is for a size exchange, store credit or a refund. Upon receiving the request, Elitestores.com will send an e-mail with instructions to follow, including the number of return authorization (RAN) and the invoice to be attached for shipping.')?>
			</li>
			<li style="margin-bottom:20px">
				<b>2. </b>
				<?php echo $this->__('Please write the Return Authorization Number (RAN) on the outside of the box and complete the delivery note as instructed by the RAN email.')?>
			</li>

			<li style="margin-bottom:20px">
				<b>3. </b>
				<?php echo $this->__('Shipment for returned items must be picked up for Courier within 7 days following receipt of the e-mail with instructions.')?>
			</li>
			<li style="margin-bottom:20px">
				<b>4. </b>
				<?php echo $this->__('Clients can choose between three compensation options:')?>
					<ul>
						<li>
							<u><?php echo $this->__('Size exchange:')?></u> 
							<?php echo $this->__('Items can be exchanged for a different size or color, or even for a different model.')?>
						</li>
						<li>
							<u><?php echo $this->__('Store Credit:')?></u>
							<?php echo $this->__('A code will be generated with the amount of the refund, this code will be associated to your ID and may be used in a future order.')?>
						</li>
						<li>
							<u><?php echo $this->__('Refund:')?></u>
							<?php echo $this->__('We will proceed with your refund once we have received the returned items. Your refund will be credited to the original form of payment.')?>
							<br><br>
							<?php echo $this->__('If your order has been sent to a destination within the EU, all sales taxes will be refunded. Outside the EU, customs duties and sales taxes are non-refundable through Elitestores.com. However, you may be able to recover these by contacting your local customs bureau directly. As this may not be available for all countries, we recommend that you hire a customs broker if you wish to claim back duties on returned merchandise.')?>
							<br><br>
							<?php echo $this->__('Please note that refunds can take up to 10 working days to show on your account due to varying processing times between payment providers.')?>
							<br><br>
							<?php echo $this->__('In case the order is totally or partially returned for reasons not attributable to Elitestores.com and the final invoice is lower than 500€, you will lose the &quot;free shipping promotion for orders of 500€ and over&quot;; for this reason the original shipping costs will be deducted from the amount to refund.')?>
						</li>
					</ul>
			</li>
		</ol>
		<h5><?php echo $this->__('RETURN POLICY')?></h5>
		<p>
			<?php echo $this->__('Items should be returned unused and with the security tag and designer tags intact.')?>
			<br><br>
			<?php echo $this->__('Items that are returned damaged or spoiled will not be accepted and will be returned to the customer, and the refund will be refused. All accessories, or designer packaging provided such as dust bags, authenticity cards, and leather tags must be returned.')?>
			<br><br>
			<?php echo $this->__('Do not use the shoebox as external packaging for shipping. Please use the Elite Store box.')?>
			<br><br>
			<?php echo $this->__('Pick-ups for all authorized returns must be sent from the same country of the original shipment.')?>
			<br><br>
			<?php echo $this->__('Elitestores.com reserves the right to refuse returns that are unauthorized and/or not submitted according to the instructions in the email authorizing the return. Elitestores.com will not accept returned merchandise that does not follow the terms and conditions of the returns policy. Such items will be returned to the sender at the original shipment address.')?>

		</p>
		<h5><?php echo $this->__('Lingerie and swimwear')?></h5>
		<p>
			<?php echo $this->__('For hygiene reasons we do cannot accept returns of underwear.')?>
			<?php echo $this->__('Swimming costumes, bikini bottoms or briefs must be tried on over underwear. Returns will not be accepted if the protective hygienic strip has been removed. Items that have any sign of use or wear will be returned to the client.')?> 
		</p>
		<h5><?php echo $this->__('Technology')?></h5>
		<p>
			<?php echo $this->__('Technology goods should be returned in their original packaging.')?>
		</p>
		<h5><?php echo $this->__('Beauty')?></h5>
		<p>
			<?php echo $this->__('Skincare products, cosmetics, and hair care must be returned unused, unopened, and in their original packaging, otherwise they will not be accepted.')?>
		</p>
		<h5><?php echo $this->__('Defective Items')?></h5>
		<p>
			<?php echo $this->__('All items are quality controlled and checked for any faults before they are dispatched to customers. Should you receive an item that is not in perfect condition, please contact us immediately. Goods are classified as faulty if they are received damaged, or where a manufacturing fault occurs within six months of purchase. Please note that items that are damaged as a result of wear and tear are not considered to be faulty. Where possible, we will offer to repair faulty items. If you would like to exchange your item, please be aware that we can only replace it for the same product in the same size, subject to availability. You will receive a full refund if the item cannot be repaired or replaced.')?>
		</p>
		<h5><?php echo $this->__('Colors')?></h5>
		<p>
			<?php echo $this->__('Though we make every effort to display all products as accurate as possible, as computer monitors vary, we cannot guarantee that your monitor´s display of any color will be completely accurate.')?>
		</p>
		<h5><?php echo $this->__('Repeated Returns')?></h5>
		<p>
			<?php echo $this->__('We try to make your shopping experience easier by offering a flexible return policy. We do monitor the number of returns made by customers. If we detect continued returns, they can potentially be refused or even lead to the closure of your Elitestores.com account.')?>
		</p>
		<h5><?php echo $this->__('Non Acceptance Upon Delivery')?></h5>
		<p>
			<?php echo $this->__('If for any reason a client refuses to accept an order upon delivery, Elitestores.com will deduct both the original and return shipping costs from the amount to refund.')?>
			<br><br>
			<?php echo $this->__('If a shipment is refused we will do what we can to nullify the customs charges and have the shipment returned to Elitestores.com. We cannot guarantee that customs charges can be voided for a refused shipment. If not, we will deduct this amount from your refund. Both the original and return shipping fees, plus any additional customs charges, will be deducted from the refund.')?>
		</p>
	</dd>
    </dl>
</div>
