<?php 
		if (Mage::app()->getStore()->getId()==2):
?>
<p><h4>Shipping fees:</h4>
<ul>
<li>Free express shipping on orders of 500€ and over.</li>
<li>Applies to both non-discounted and sale items.</li>
<li>Not accumulative to other campaigns, discounts or promotional codes.</li>
<li>In case the order is totally or partially returned for reasons not attributable to Elite Store and the final invoice is lower than 500€, the shipping fees will be deducted from the refund.</li>
</ul></p>
<p><h4>Return fees:</h4>
<ul>
<li>Free express returns for all orders</li>
</ul></p>
<?php
	elseif (Mage::app()->getStore()->getId()==1):
?>
<p><h4>Condiciones de envío:</h4>
<ul>
<li>La promoción de Envíos gratuitos para pedidos superiores a 500€</li> 
<li>Aplicable para todos los productos rebajados y no rebajados.</li>
<li>Esta promoción no es acumulabe con otras promociones aplicables al mismo tiempo (descuentos o códigos promocionales).</li>
<li>En caso en que el pedido sea devuelto total o parcialemente por razones no atribuibles a un error por parte de Elite Store y el importe final facturado sea inferior a los 500 €, el coste del envío será deducido del importe pendiente de devolver.</li>
</ul></p>
<p><h4>Condiciones de retorno:</h4>
<ul>
<li>La devolución de todos los pedidos es gratuita.</li>
</ul></p>
<?php
	endif;
?>