<div class="page-title">
        <h1><?php echo $this->__('Privacy')?></h1>
</div>
<div class="col-left sidebar stickem">
    <div class="block block-account">
        <div class="block-content">
            <ul>
                <li class="current">
                    <a href="#answer1">
                        <?php echo $this->__('USE AND PROCESSING OF PERSONAL DATA')?>
                    </a> 
                </li>
                <li>
                    <a href="#answer2">
                        <?php echo $this->__('SECURITY MEASURES:')?>
                    </a>                    
                </li>
                <li>
                    <a href="#answer3">
                        <?php echo $this->__('EXERCISE OF RIGHTS: ACCESS, RECTIFICATION, CANCELLATION AND OPPOSITION.')?>
                    </a>                    
                </li>
                <li>
                    <a href="#answer4">
                        <?php echo $this->__('MINORS:')?>
                    </a>                    
                </li>
                <li>
                    <a href="#answer5">
                        <?php echo $this->__('TERMS OF USE OF THE WEBSITE:')?>
                    </a>                    
                </li>
                <li>
                    <a href="#answer6">
                        <?php echo $this->__('RESTRICTED ACCESS AREAS:')?>
                    </a>                    
                </li>
                <li>
                    <a href="#answer7">
                        <?php echo $this->__('FORMS:')?>
                    </a>                    
                </li>
                <li>
                    <a href="#answer8">
                        <?php echo $this->__('INTELLECTUAL PROPERTY:')?>
                    </a>                    
                </li>
                <li>
                    <a href="#answer9">
                        <?php echo $this->__('MODIFICATION OF THE PRIVACY POLICY:')?>
                    </a>                    
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="customercontainer">
    
    <dl>
    <dd><?php echo $this->__('The purpose of the Privacy and Data Protection Policy of Elitestores.com is to protect the information on the Internet and the data that the user can introduce on the web, complying with the legislation in force in this matter (Organic Law 15/1999, of December 13, on Data Protection Of Personal Character (LOPD) and Law 34/2002, of July 11, of Service of the Information Society and Electronic Commerce, as well as its development regulations).<br>
The handling and navigation by the web page as well as the subscription of the forms that can be contained in the same, will entail the acceptance by the user of this Privacy and Data Protection Policy.<br>
Both the service recipients and the competent bodies are informed in an express, precise and unequivocal manner of the following aspects concerning the service provider of the information society:<br>
NAME / DENOMINATION SOCIAL: Elitestores.com<br>
ACTIVITY / SOCIAL OBJECT: Fashion Shop
TELEPHONE: 952 82 69 97<br>
CONTACT FORM: <a href="'. Mage::getUrl('contactus').'">contact form</a><br>
WEB ADDRESS: www.elitestores.com')?></dd>
    <dt id="answer1" class="titleSection titleSection--intext"><?php echo $this->__('Use and processing of Personal Data:')?></dt>
    <dd><?php echo $this->__('<p>In compliance with the provisions of the LOPD, we inform you that the data provided, as well as the data derived from its navigation, may be stored in the files owned by Elitestores.com, who will access them for the sole purpose of attending to your request, managing the requested service and maintaining the relationship established in the forms that you subscribe.<br>
These files are duly registered in the Spanish Agency for Data Protection in accordance with current legislation and development regulations.<br>
In addition, the user consents to the processing of their data in order to send commercial and complimentary communications related to our entity through telephone, ordinary mail, fax, email or equivalent electronic media.<br>
In case of not authorizing the processing of your data for the purpose indicated in paragraph (s) above, the user may exercise his right of opposition to the processing of his data under the terms and conditions set forth below in the "Exercise of rights".<br>
Elitestores.com, under their condition of being responsible for the treatment, are obliged to comply with the current legislation on the protection of personal data.<br>
</p>')?></dd>
    <dt id="answer2" class="titleSection titleSection--intext"><?php echo $this->__('Security measures:')?></dt>
    <dd><?php echo $this->__('<p>Elitestores.com Have implemented the technical and organizational security measures necessary to guarantee the security of their personal data and to prevent their alteration, loss and unauthorized treatment and / or access, taking into account the state of the technology, the nature of the data Stored and the risks to which they are exposed, whether arising from human action or the physical or natural environment. All this in accordance with the provisions of art. 9 of the Data Protection Act and Title VIII of the RLOPD.<br>
Also, Elitestores.com have established additional measures in order to reinforce the confidentiality and integrity of the information in their organization. Monitoring, control and evaluation of processes are continuously maintained to ensure respect for data privacy.<br>
However, the user must be aware that the security measures on the Internet are not invulnerable, so that Elitestores.com disclaims any responsibility for those practices in which the user does not assume the appropriate level of security or due diligence or its consequences, as well as causes or damages caused by third parties other than Elitestores.com.</p>')?></dd>
    <dt id="answer3" class="titleSection titleSection--intext"><?php echo $this->__('Exercise of rights: access, rectification, cancellation and opposition.')?></dt>
    <dd><?php echo $this->__('<p>Those individuals who have provided their information to Elitestores.com May be addressed to them, in order to be able to freely exercise their rights of access, rectification, cancellation and opposition to the data incorporated in their files.<br>
The interested party may exercise their rights by means of a written communication addressed to Elitestores.com by <a href="'. Mage::getUrl('contactus').'">contact form </a>, with the reference "DATA PROTECTION POLICY" specifying your data, proving your identity (attach a copy of your ID or passport or other document proving your identity) And the reasons for your request.</p>')?></dd>
    <dt id="answer4" class="titleSection titleSection--intext"><?php echo $this->__('Minors:')?></dt>
    <dd><?php echo $this->__('<p>The services provided by this website are not directed at children under 14 years of age, so that data of these people should not be provided and, if facilitated, they will be destroyed by Elitestores.com As soon as he has knowledge of it. Elitestores.com Are exempt from any liability in case this condition of use of the service is breached.</p>')?></dd>
    <dt id="answer5" class="titleSection titleSection--intext"><?php echo $this->__('Terms of use of the website:')?></dt>
    <dd><?php echo $this->__('<p>The users guarantee and respond, in any case, the truthfulness, accuracy, validity and authenticity of the personal data provided, committing themselves to keep them duly updated.<br>
In the event that the request includes personal data by persons who are not holders thereof, the user must, prior to their inclusion, inform those persons about the Privacy and Data Protection Policy of Elitestores.com. Disclaims any liability arising from the non-compliance of this requirement by users.<br>
The User agrees to use the website and the Services in accordance with the law, this Legal Notice, the Particular Conditions of some Services and with the morality, generally accepted good customs and public order.<br>
The User shall refrain from using any of the Services for illegal purposes or effects, prohibited in this Legal Notice, harmful to the rights and interests of third parties or that in any way may damage, disable, overload, deteriorate or prevent the normal use of The Services, the computer equipment or the documents, files and all kinds of contents stored in any computer equipment (hacking) of Elitestores.com, Of other Users or of any Internet User (hardware and software). The User undertakes not to transmit, disseminate or make available to third parties information, data, content, messages, graphics, drawings, sound and / or image files, photographs, recordings, software and, In general, any kind of material that: 
<br>* is contrary to or violates the fundamental rights and public freedoms recognized constitutionally or in the rest of legislation. 
<br>* It is contrary to the right to honor, personal and family privacy or the image of people. 
<br>* It constitutes illicit, deceptive or disloyal advertising or in any way constitutes unfair competition. 
<br>* Incorporate viruses or other physical or electronic elements that may damage or prevent the normal operation of Elitestores.com network, system or computer equipment (hardware and software). Elitestores.com Or from third parties or that may damage electronic documents and files stored on such computer equipment. 
<br>* Provokes difficulties in the normal operation of the service 
<br>* incites, induces or promotes criminal, demeaning, defamatory, violent, or contrary to the law, morality, good customs or public order 
<br>* incite, induce or promote actions Or discriminatory attitudes based on sex, race, religion, beliefs, age or condition. 
<br>* Make available, incorporate or allow access to products, elements, messages and / or services criminal, violent, offensive or contrary to the law, morality, good customs or public order. 
<br>* It is protected by intellectual or industrial property rights belonging to third parties, without the User having previously obtained from its owners the necessary authorization to carry out the use that it makes or intends to carry out. 
<br>* Violate third-party business rights</p>')?></dd>
<dt id="answer6" class="titleSection titleSection--intext"><?php echo $this->__('Restricted Access Areas:')?></dt>
    <dd><?php echo $this->__('<p>To enter restricted areas, users must have the corresponding access codes. Elitestores.com Reserve the right to accept or reject freely the registration request of any user. The data entered by users must be accurate, up-to-date, truthful and processed and processed in compliance with current legislation on the protection of personal data.<br>
The users will be responsible in all cases for the custody of their access codes, so they will be the exclusive responsibility of any damages that could derive from an abuse of the same, as well as their loss or any other circumstance that could Assume a risk of access of use of the same by unauthorized third parties. Users should immediately notify Elitestores.com So that it proceeds to block and replace it.</p>')?></dd>
<dt id="answer7" class="titleSection titleSection--intext"><?php echo $this->__('Forms:')?></dt>
    <dd><?php echo $this->__('<p>In those cases in which, in order to make a request, it is necessary to fill in a form and click on the submit button, the execution of the request will necessarily imply that the user is informed and expressly consents to and agrees to this Policy Of Privacy and Protection of Data.</p>')?></dd>
    <dt id="answer8" class="titleSection titleSection--intext"><?php echo $this->__('Intellectual property:')?></dt>
    <dd><?php echo $this->__('<p>All elements that integrate the graphic design of websites, menus, navigation buttons, HTML code, and, in general, all the contents and information that the User can access through the web pages Elitestores.com are subject to industrial and intellectual property rights, patents, trademarks or copyright of SJ or third parties. It is expressly prohibited for the User to alter, modify, exploit, reproduce, distribute or publicly communicate or any other right that corresponds to the holder of the right affected.</p>')?></dd>
    <dt id="answer9" class="titleSection titleSection--intext"><?php echo $this->__('Modification of the privacy policy:')?></dt>
    <dd><?php echo $this->__('<p>Elitestores.com Reserve the right to modify their Privacy Policy, according to their own criteria, or motivated by a legislative, jurisprudential or doctrinal change of the Spanish Agency for Data Protection.<br>
Any modification of the Privacy Policy will be published at least 5 days before its effective application. The use of the Web after such changes, will imply the acceptance of these.</p>')?></dd>
    </dl>
</div>
