<div class = "follow-us">
	<br> <br> <h5><?php echo $this->__('SHIPPING FEES:');?></h5>
<?php echo $this->__('Free express shipping on orders of 500€ and over.');?><br>
<?php echo $this->__('For all products, except the items included in Exclusive Offers: E-STOCK.')?><br>
<?php echo $this->__('In case the order is totally or partially returned for reasons not attributable to Elite Store and the final invoice is lower than 500€, the shipping fees will be deducted from the refund.')?><br>
<h5><?php echo $this->__('RETURN FEES:')?></h5>
<?php echo $this->__('Free express returns for all orders.')?><br><br>

<a href="<?php echo $this->getUrl('customer-service')?>"><?php echo $this->__('General terms &amp; conditions')?></a><br>
<a href="<?php echo $this->getUrl('privacy')?>"><?php echo $this->__('Privacy Policy')?></a><br>

</div>