<div class = "follow-us">
	<?php 
    echo "<br> <br> <h5>";
    echo $this->__('10% OFF YOUR PURCHASE TODAY');
    echo "</h5>";
    echo $this->__('10% off all non-discounted items. Non-accumulative with other promo codes. Use ELITENESS code during checkout.');
    echo "<br>";
    echo $this->__('Free express shipping on orders of 500€ and over.');
    echo "<br>";
    echo $this->__('Available worldwide.');
    echo "<br>";
    echo $this->__('Elite reserves the right to withdraw this limited time only offer without notice at any time.');
    echo "<br><br>";
    ?>
<a href="<?php echo $this->getUrl('customer-service')?>">General terms &amp; conditions</a><br>
<a href="<?php echo $this->getUrl('privacy')?>">Privacy Policy</a><br>

</div>