<?php
	
	$manufacturer = $this->getManufacturer();
	
	//Extraemos el nombre correcto
	$resource = Mage::getSingleton('core/resource');
    $readConnection = $resource->getConnection('core_read');
	$query = 'SELECT Option_id FROM ' . $resource->getTableName('manufacturer/manufacturer').' WHERE name_store LIKE "'.$manufacturer->getData('name_store').'"';
	$manufacturerId = $readConnection->fetchOne($query);
	$manufacturerName = Mage::getModel('catalog/product')->getResource()->getAttribute("manufacturer")->getSource()->getOptionText($manufacturerId);
	
	if($manufacturer){
?>


<div class="top-bread"><div class="breadcrumbs">
    <ul>
                    <li class="home">
                            <a href="<?php echo Mage::helper('core/url')->getHomeUrl()?>" title="Ir a la página de Inicio">HOME</a>
                                        &nbsp;<span>&raquo;</span>&nbsp;
                        </li>
                    <li class="category23">
                            <a href="<?php echo Mage::getUrl('manufacturer',array('_secure'=>true))?>"><strong><?php echo $this->__('DESIGNERS') ?></strong></a>
                                    </li>
                                    	&nbsp;<span>&raquo;</span>&nbsp;
                    <li class="category24">
                            <strong><?=$manufacturerName;?></strong>
                                    </li>
            </ul>
</div>                                        
</div>

<?php 
	}
?>