<!-- Comentamos estas lineas para que no aparezca el apartado de diseñadores destacados -->

<!--<h3 class="manufacturer_list_head"><?php //echo $this->__('Featured Manufacturers') ?></h3>-->

<?php
//$featuredManufacturers = $this->getFeaturedManufacturer();


//echo("<ul id='featured_manufacturer'>");
//foreach($featuredManufacturers as $featuredManufacturer)
//{
//	echo("<li><a href='". $this->getManufacturerDetailUrl($featuredManufacturer)."'>".$this->getManufacturerImage($featuredManufacturer)."</a></li>");
//}
//echo("</ul>");
?>

<br><br>
<h3 class="manufacturer_list_head"><?php echo $this->__('All Designers') ?></h3>

<?=$this->generateListCharacter();?>

<ul class="list-capital-letter">
	<?php
		$manufacturers = $this->getManufacturers();
		ksort($manufacturers);
		
		if(count($manufacturers) > 0){
			$letras=array ('0-9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z');
			foreach ($manufacturers as $key=>$manufacturer):
				foreach ($letras as $letra):
					if ((strtoupper($key)[0]==$letra) || (($letra=='0-9') && is_numeric(strtoupper($key)[0]))):
						$diseñadores[$letra][]=array($key,$manufacturer);
					endif;
				endforeach;	
			endforeach;
			
			foreach ($letras as $letra):
				if (count($diseñadores[$letra])!=0):
					echo ("<li>".$letra."</li><ul class='manufacturer_list'>");
					foreach ($diseñadores[$letra] as $diseñador):
						echo ("<li><a href='". $this->getManufacturerDetailUrl($diseñador[1]) . "' title='" . $diseñador[0] . "'>" .$diseñador[0]."</a></li>");
					endforeach;
					echo("</ul>");
				endif;
			endforeach;
			echo ("</ul>");
		}
		
		
		
		
		
		
		
		
		

	?>
	
</ul>
                
        