<!-- Comentamos estas lineas para que no aparezca el apartado de diseñadores destacados -->

<!--<h3 class="manufacturer_list_head"><?php //echo $this->__('Featured Manufacturers') ?></h3>-->

<?php
//$featuredManufacturers = $this->getFeaturedManufacturer();


//echo("<ul id='featured_manufacturer'>");
//foreach($featuredManufacturers as $featuredManufacturer)
//{
//	echo("<li><a href='". $this->getManufacturerDetailUrl($featuredManufacturer)."'>".$this->getManufacturerImage($featuredManufacturer)."</a></li>");
//}
//echo("</ul>");
?>

<br><br>
<h3 class="manufacturer_list_head"><?php echo $this->__('All Designers') ?></h3>

<?=$this->generateListCharacter();?>

<ul class="list-capital-letter">
	<?php
		$manufacturers = $this->getManufacturers();
		$count =0;
		$conta =0;
		$contb =0;
		$contc =0;
		$contd =0;
		$conte =0;
		$contf =0;
		$contg =0;
		$conth =0;
		$conti =0;
		$contj =0;
		$contk =0;
		$contl =0;
		$contm =0;
		$contn =0;
		$conto =0;
		$contp =0;
		$contq =0;
		$contr =0;
		$conts =0;
		$contt =0;
		$contu =0;
		$contv =0;
		$contw =0;
		$contx =0;
		$conty =0;
		$contz =0;
		if(count($manufacturers))
		{
			
/* Listado separado por Letras */
			foreach($manufacturers as $manufacturer)
			{	
			
				$capitalLetter = strtoupper(strtolower($manufacturer->getData('name_store')));
				if (ctype_digit($capitalLetter{0})){
					if ($count == 0){
						echo ("<li>0-9</li><ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						$count=1;
					}else {
						echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
					}
				}
				switch($capitalLetter{0}){
					
					case 'A':
						if ($count==1){
							echo ("</ul></li>");
							}
						if ($counta == 0){
							echo ("<li>A<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
							$counta=1;										
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
					
					case 'B':
						
						if ($countb == 0){
						if (($count==1) || ($counta==1)){
							echo ("</ul></li>");
							}
							echo ("<li >B<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
							$countb=1;										
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
						
					case 'C':
						
						if ($countc == 0){
							if ($count==1 || $counta==1 || $countb==1){
							echo ("</ul></li>");
							}
							echo ("<li >C<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countc=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
						
					case 'D':
						
						if ($countd == 0){
							if ($counta==1 || $countb==1 || $countc==1){
							echo ("</ul></li>");
							}
							echo ("<li >D<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");								
							$countd=1;		
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
						
					case 'E':
						
						if ($counte == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1){
							echo ("</ul></li>");
							}
							echo ("<li >E<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$counte=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
						
					case 'F':
						
						if ($countf == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1){
							echo ("</ul></li>");
							}
							echo ("<li >F<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countf=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
						
					case 'G':
						
						if ($countg == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1){
							echo ("</ul></li>");
							}
							echo ("<li >G<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countg=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
						
					case 'H':
						
						if ($counth == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1){
							echo ("</ul></li>");
							}
							echo ("<li >H<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$counth=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
						
					case 'I':
						
						if ($counti == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1){
							echo ("</ul></li>");
							}
							echo ("<li >I<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$counti=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
					
					case 'J':
						
						if ($countj == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1){
							echo ("</ul></li>");
							}
							echo ("<li >J<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countj=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
						
					case 'K':
						
						if ($countk == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1){
							echo ("</ul></li>");
							}
							echo ("<li >K<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countk=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
						
					case 'L':
						
						if ($countl == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1){
							echo ("</ul></li>");
							}
							echo ("<li >L<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countl=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
						
					case 'M':
						
						if ($countm == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1 || $countl==1){
							echo ("</ul></li>");
							}
							echo ("<li >M<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countm=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
						
					case 'N':
						
						if ($countn == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1 || $countl==1 || $countm==1){
							echo ("</ul></li>");
							}
							echo ("<li >N<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countn=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
						
					case 'O':
						
						if ($counto == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1 || $countl==1 || $countm==1 || $countn==1){
							echo ("</ul></li>");
							}
							echo ("<li >O<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$counto=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
						
					case 'P':
						
						if ($countp == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1 || $countl==1 || $countm==1 || $countn==1 || $counto==1){
							echo ("</ul></li>");
							}
							echo ("<li >P<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countp=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
						
					case 'Q':
						
						if ($countq == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1 || $countl==1 || $countm==1 || $countn==1 || $counto==1 || $countp==1){
							echo ("</ul></li>");
							}
							echo ("<li >Q<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countq=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
					case 'R':
						
						if ($countr == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1 || $countl==1 || $countm==1 || $countn==1 || $counto==1 || $countp==1 || $countq==1){
							echo ("</ul></li>");
							}
							echo ("<li >R<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countr=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
					case 'S':
						
						if ($counts == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1 || $countl==1 || $countm==1 || $countn==1 || $counto==1 || $countp==1 || $countq==1 || $countr==1){
							echo ("</ul></li>");
							}
							echo ("<li >S<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$counts=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
					case 'T':
						
						if ($countt == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1 || $countl==1 || $countm==1 || $countn==1 || $counto==1 || $countp==1 || $countq==1 || $countr==1 || $counts==1){
							echo ("</ul></li>");
							}
							echo ("<li >T<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countt=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
					case 'U':
						
						if ($countu == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1 || $countl==1 || $countm==1 || $countn==1 || $counto==1 || $countp==1 || $countq==1 || $countr==1 || $counts==1 || $countu==1){
							echo ("</ul></li>");
							}
							echo ("<li >U<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countu=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
					case 'V':
						
						if ($countv == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1 || $countl==1 || $countm==1 || $countn==1 || $counto==1 || $countp==1 || $countq==1 || $countr==1 || $counts==1 || $countu==1){
							echo ("</ul></li>");
							}
							echo ("<li >V<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");		
							$countv=1;								
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
					case 'W':
						
						if ($countw == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1 || $countl==1 || $countm==1 || $countn==1 || $counto==1 || $countp==1 || $countq==1 || $countr==1 || $counts==1 || $countu==1 || $countv==1){
							echo ("</ul></li>");
							}
							echo ("<li >W<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countw=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
					case 'X':
						
						if ($countx == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1 || $countl==1 || $countm==1 || $countn==1 || $counto==1 || $countp==1 || $countq==1 || $countr==1 || $counts==1 || $countu==1 || $countv==1 || $countw==1){
							echo ("</ul></li>");
							}
							echo ("<li >X<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$countx=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
					case 'Y':
						
						if ($county == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1 || $countl==1 || $countm==1 || $countn==1 || $counto==1 || $countp==1 || $countq==1 || $countr==1 || $counts==1 || $countu==1 || $countv==1 || $countw==1 || $countx==1){
							echo ("</ul></li>");
							}
							echo ("<li >Y<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$county=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
					case 'Z':
						
						if ($county == 0){
							if ($counta==1 || $countb==1 || $countc==1 || $countd==1 || $counte==1 || $countf==1 || $countg==1 || $counth==1 || $counti==1 || $countj==1 || $countk==1 || $countl==1 || $countm==1 || $countn==1 || $counto==1 || $countp==1 || $countq==1 || $countr==1 || $counts==1 || $countu==1 || $countv==1 || $countw==1 || $countx==1 || $county==1){
							echo ("</ul></li>");
							}
							echo ("<li >Z<ul class='manufacturer_list'><li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");										
							$county=1;
						}else{
							echo ("<li><a href='". $this->getManufacturerDetailUrl($manufacturer) . "' title='" . $manufacturer->getName() . "'>" .strtolower($manufacturer->getData('name_store')) ."</a></li>");
						}
						break;
				
				}
				
				
			}	
			echo "</ul></li>";
		}
		else
		{
			echo $this->__('Designer not found!');
		}
	?>
	
</ul>
                
        