<li class="level0 <?php if (Mage::app()->getStore()->getStoreId()==2) echo 'en'?> nav-10 level-top parent ">
	<a class="level-top" href="<?php echo Mage::getUrl('manufacturer',array('_secure'=>true)); ?>">
		<span><?php echo $this->__('Designers');  ?></span>
	</a>
	
    <ul class="level0 chield chield4">
		<li style="width:30%;" class="level1 nav-10-1 first parent">
			<a href="<?php echo Mage::getUrl('manufacturer',array('_secure'=>true)) ?>">
            	<span><?php echo $this->__('Featured Designers') ?></span>
            </a>
			<ul class="level1">
				<li class="level2 nav-10-1-1 first">
                	<a href="<?php echo Mage::getUrl('alexander-mcqueen',array('_secure'=>true)) ?>">
						<span>Alexander McQueen</span>
					</a>
				</li>
              	<li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('balmain',array('_secure'=>true)) ?>">
						<span>Balmain</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('carven',array('_secure'=>true)) ?>">
						<span>Carven</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('charlotte-olympia',array('_secure'=>true)) ?>">
						<span>Charlotte Olympia</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('delvaux',array('_secure'=>true)) ?>">
						<span>Delvaux</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('dsquared2',array('_secure'=>true)) ?>">
						<span>Dsquared2</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('emilio-pucci',array('_secure'=>true)) ?>">
						<span>Emilio Pucci</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('giorgio-armani',array('_secure'=>true)) ?>">
						<span>Giorgio Armani</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('givenchy',array('_secure'=>true)) ?>">
						<span>Givenchy</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('kenzo',array('_secure'=>true)) ?>">
						<span>Kenzo</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('lanvin',array('_secure'=>true)) ?>">
						<span>Lanvin</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('moncler',array('_secure'=>true)) ?>">
						<span>Moncler</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('pierre-hardy',array('_secure'=>true)) ?>">
						<span>Pierre Hardy</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('versace',array('_secure'=>true)) ?>">
						<span>Versace</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('victoria-beckham',array('_secure'=>true)) ?>">
						<span>Victoria Beckham</span>
					</a>
				</li>
            </ul>
		</li>
		<li style="width:30%;" class="level1 nav-10-2 last parent">
			<a href="<?php echo Mage::getUrl('manufacturer',array('_secure'=>true)) ?>">
				<span><?php echo $this->__('See All'); ?></span>
			</a>
		</li>
	</ul>
</li>