<li class="level0 <?php if (Mage::app()->getStore()->getStoreId()==2) echo 'en'?> nav-10 level-top parent ">
	<a class="level-top" href="<?php echo Mage::getUrl('manufacturer',array('_secure'=>true)); ?>">
		<span><?php echo $this->__('Designers');  ?></span>
	</a>
	
    <ul class="level0 chield chield4">
		<li style="width:30%;" class="level1 nav-10-1 first parent">
			<a href="<?php echo Mage::getUrl('manufacturer',array('_secure'=>true)) ?>">
            	<span><?php echo $this->__('Featured Designers') ?></span>
            </a>
			<ul class="level1">
				<li class="level2 nav-10-1-1 first">
                	<a href="<?php echo Mage::getUrl('alexander-wang',array('_secure'=>true)) ?>">
						<span>Alexander Wang</span>
					</a>
				</li>
              	<li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('alaia',array('_secure'=>true)) ?>">
						<span>Alaïa</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('ami-alexandre-mattiussi',array('_secure'=>true)) ?>">
						<span>AMI</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('giuseppe-zanotti-design',array('_secure'=>true)) ?>">
						<span>Giuseppe Zanotti</span>
					</a>
				</li>
                <!--<li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('delvaux',array('_secure'=>true)) ?>">
						<span>Delvaux</span>
					</a>
				</li>-->
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('les-hommes',array('_secure'=>true)) ?>">
						<span>Les Hommes</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('maison-kitsune',array('_secure'=>true)) ?>">
						<span>Maison Kitsuné</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('moschino',array('_secure'=>true)) ?>">
						<span>Moschino</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('maison-margiela',array('_secure'=>true)) ?>">
						<span>Maison Margiela</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('rick-owens',array('_secure'=>true)) ?>">
						<span>Rick Owens</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('roberto-cavalli',array('_secure'=>true)) ?>">
						<span>Roberto Cavalli</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('sonia-rykiel',array('_secure'=>true)) ?>">
						<span>Sonia Rykiel</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('sophia-webster',array('_secure'=>true)) ?>">
						<span>Sophia Webster</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('temperley-london',array('_secure'=>true)) ?>">
						<span>Temperley London</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('var/city',array('_secure'=>true)) ?>">
						<span>VAR/CITY</span>
					</a>
				</li>
				<li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('y-3',array('_secure'=>true)) ?>">
						<span>Y-3</span>
					</a>
				</li>
            </ul>
		</li>
		<li style="width:30%;" class="level1 nav-10-2 last parent">
			<a href="<?php echo Mage::getUrl('manufacturer',array('_secure'=>true)) ?>">
				<span><?php echo $this->__('See All'); ?></span>
			</a>
		</li>
	</ul>
</li>