<?php
	
	$manufacturer = $this->getManufacturer();
	
	if($manufacturer){
?>
<!-- Codigo añadido para incluir semilla-->

<div class="top-bread"><div class="breadcrumbs">
    <ul>
                    <li class="home">
                            <a href="<?php echo Mage::helper('core/url')->getHomeUrl()?>" title="Ir a la página de Inicio">HOME</a>
                                        &nbsp;<span>&raquo;</span>&nbsp;
                        </li>
                    <li class="category23">
                            <a href="<?php echo $this->getManufacturerCatalogUrl()?>"><strong><?php echo $this->__('DESIGNERS') ?></strong></a>
                                    </li>
                                    	&nbsp;<span>&raquo;</span>&nbsp;
                    <li class="category24">
                            <strong><?=$manufacturer->getData('name_store');?></strong>
                                    </li>
            </ul>
</div>                                        
</div>     
<div class="block block-layered-nav">


<!-- Fin código añadido-->


<div id="manufacturer_left">
    <div class="block-title">
        <strong><span><?php echo $this->__('Product Catalog') ?></span></strong>
    </div>
		<div id="manufacturer_category_tree">
        <ul class="indicador-temporada">
                <li><a href="?catid=206"><?php echo $this->__('Novedades')?></a></li>
                
        </ul>
        <dl id="narrow-by-list">
        	<dt id="filterlabel"><?php echo $this->__('Category')?></dt>
            <dd><?php echo $this->generateCategoryTree($manufacturer);?></dd>
        </dl>
        <script type="text/javascript" >
		 jQuery('#filterlabel<?php echo $i;?>').each(function(){
                                jQuery(this).addClass('active');
                                jQuery(this).toggle(function(){
                                    jQuery(this).removeClass('active').next().slideUp(200);
                                },function(){
                                    jQuery(this).addClass('active').next().slideDown(200);
                                })
                            });
		</script>
	</div>
</div>
</div>
<div id="manufacturer_content">
<div id="manufacturer_description">
<h3><?=$manufacturer->getData('name_store');?></h3>
<?=$this->getManufacturerImage($manufacturer);?>
<p><?=$manufacturer->getDescriptionShort();?></p>
<p><?=$manufacturer->getDescription();?></p>
</div>


<br>
<?php 

	echo $this->getProductListHtml() ;
    } else {
		echo '<h3>prueba'. $this->__('Not found manufacturer !') .'</h3>';
	}
?>
</div>
