<a href="<?php echo $this->getBaseUrl();?>special-sections/runway.html">
    <div title="Runway" class="home--slide">

            <div class="triangulos" id="slide--triangulo">
                    SHOP THE RUNWAY<br/>
                    <span>Our favorite pieces from the SS16 collections</span>
            </div>
    </div>
</a>
<a title="Alexander McQueen" href="<?php echo $this->getBaseUrl();?>alexander-mcqueen/"  class="home--left">
    <div class="triangulos">
            NEW SUMMER SHADES<br/>
        <span>Alexander McQueen</span>
    </div>
</a>

<a title="Anya Hindmarch" href="<?php echo $this->getBaseUrl();?>anya-hindmarch/"  class="home--right">
    <div class="triangulos">
            DON'T MISS BAGS<br/>
        <span>Anya Hindmarch</span>
    </div>
</a>

<a title="Versace" class="home--img" href="<?php echo $this->getBaseUrl();?>versace/" >
    <div class="triangulos" id="triangulo--chungo">
            ENHANCE YOUR SPORTSWEAR
            <span><br/><br/>With brand new Versace V-Race Swiss </span><br/><span style="top: -23px;"> made timepieces</span>
    </div>
</a>
<a title="Pierre Hardy" class="home--img--two" href="<?php echo Mage::getModel('catalog/category')->load(92)->getUrl(); ?>">
    <div class="triangulos" id="triangulo--chungo">
            STATEMENT SNEAKERS
            <span><br/><br/>150+ pairs, including the works of art </span><br/><span style="top: -23px;">by Pierre Hardy</span>
    </div>
</a>

<a title="Stella McCartney" href="<?php echo $this->getBaseUrl();?>adidas-by-stella-mccartne/" class="home--right--last" >
    <div class="triangulos" id="triangulo--final__chungo">
        STYLE YOUR WORKOUT<br/><br/>
        <span>The new season Adidas by Stella McCartney </span><br/><span style="top: -23px;">stands out both in performance and style!</span>
    </div>
</a>

<a title="Y-3" style="float:right;margin-bottom:10px"  href="<?php echo $this->getBaseUrl();?>y-3/" class="home--left--last">
    <div class="triangulos" id="triangulo--final__chungo">
        IT’S TIME TO MOVE<br/><br/>
        <span>With Y-3 runway collection by the legendary </span><br/><span style="top: -23px;"> Yohji Yamamoto, inspired by the body in motion. </span>
    </div>
</a>