<?php
/**
 * Survey for Magento
 *
 * @category   Belitsoft
 * @package    Belitsoft_Survey
 * @author     Belitsoft <bits@belitsoft.com>
 */

/* @var $this Belitsoft_Survey_Block_Frontend_Report_Pickmany */

/* !!!!! File must be as one line text - PDF compatibility !!!!!!!!! */

?><h4><?php echo strip_tags($this->getCurrentQuestion()->getQuestionText(), '<br>'); ?></h4><?php
?><table><?php
?><?php foreach($this->getCurrentQuestion()->getFieldsObjects() as $field): ?><?php
?><tr><td><?php echo $field->getFieldText(); ?></td><?php
?><td style="font-weight:bold;"><?php echo ($this->checkSelected($field) ? '<span style="color:green;">&radic;</span>' : '<span style="color:red;">&times;</span>'); ?></td></tr><?php
?><?php endforeach; ?><?php
?></table>