<?php
/**
 * Survey for Magento
 *
 * @category   Belitsoft
 * @package    Belitsoft_Survey
 * @author     Belitsoft <bits@belitsoft.com>
 */

/* @var $this Belitsoft_Survey_Block_Frontend_Report_Ranking */

/* !!!!! File must be as one line text - PDF compatibility !!!!!!!!! */

?><h4><?php echo strip_tags($this->getCurrentQuestion()->getQuestionText(), '<br>'); ?></h4><?php
?><table><?php
?><?php foreach($this->getCurrentQuestion()->getFieldsObjects() as $field): ?><?php
?><tr><td><?php echo $field->getFieldText(); ?></td><?php
?><td><?php echo $this->getRankingAnswer($field); ?></td></tr><?php
?><?php endforeach; ?><?php
?></table>