
<a title="ALEXANDER WANG SS'16" href="<?= $this->getUrl('new-in-ss16')?>?manufacturer=4830" class="home--slide">
</a>

<a title="SUNGLASSES" href="<?= $this->getUrl('marcobologna')?>"  class="home--left">
	<div class="home--left--triangle">MARCOBOLOGNA<br/>
		<span>Premium denim, exquisite embellishments</span>
	</div>
</a>

<a title="DRESSES" href="<?= $this->getUrl('loewe')?>"  class="home--right">
	<div class="home--right--triangle">LOEWE<br/>
		<span>The new classics</span>
	</div>
</a>

<a title="sweaters" class="home--img" href="<?= $this->getUrl('malone-souliers')?>" >
	<div class="home--img--text">MALONE SOULIERS<span><br/><br/>Traffic shopping stilettos</span>
	</div>
</a>

<a title="accessories" class="home--img--two" href="<?= $this->getUrl('giuseppe-zanotti-design')?>">
	<div class="home--img--left--text">GIUSEPPE ZANOTTI<span><br/><br/>Primed for powerful style</span>
	</div>
</a>

<a title="DSQUARED2" href="<?php echo $this->getUrl('new-in-ss16')?>?manufacturer=601" class="home--right--last" >
	<div class="home--right--last--text">
		<span>Just Landed:</span>
		<br/>DSQUARED2<br/>
		<em>Eclectic edit inspired by nomad travelers</em>
	</div>
</a>

<a title="JEREMY SCOTT" style="float:right;margin-bottom:10px"  href="<?= $this->getUrl('jeremy-scott')?>" class="home--left--last">
	<div class="home--left--triangle">
		<span>Shop the Runway:</span>
		<br/>JEREMY SCOTT<br/>
		<em>Electrifying sixties meets eighties fun</em>
	</div>
</a>

<a href="<?php echo Mage::getUrl('sale') ?>?dir=desc&discount=5355&order=prioridad" class="home--img--all">
                   <div class="banner_clases2">
                        <div class="banner--centere2"><img style="" src="<?php echo $this->getSkinUrl('images/final_bloque1.png')?>" ></div>
                        <div class="banner--righte"><img style="" src="<?php echo $this->getSkinUrl('images/final_bloque2.png')?>"></div>
                    </div>
</a>