<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<div class="menu-movil" >
                <a href="#menu"class="menu-mobile--header"></a>
            </div>
            <nav id="menu">
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php $_menuSelect = $this->renderCategoriesMenuHtml('','level-top') ?>
        <ul>
            <li class="level0 <?php if (Mage::app()->getStore()->getStoreId()==2 || Mage::app()->getStore()->getStoreId()==6) echo 'en'?> first homelink"><a href="<?php echo $this->getBaseUrl(); ?>"><span><?php echo $this->__('home') ?></span></a></li>
            <?php if (Mage::app()->getStore()->getId()==1 || Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getStoreId()==6 || Mage::app()->getStore()->getStoreId()==7): ?>
            <li class="level0 <?php if (Mage::app()->getStore()->getStoreId()==2 || Mage::app()->getStore()->getStoreId()==6) echo 'en'?>"><a href="<?php echo $this->getBaseUrl().'new-in-ss16?dir=desc&order=created_at'; ?>"><span><?php echo $this->__('New In') ?></span></a>
                <ul class="level0 chield chield4">
                    <li class="level1 en nav-1-2 parent seasons">
                        <a href="<?php  echo $this->getBaseUrl().'new-in-ss16?dir=desc&order=created_at';?>"><span><?php echo $this->__("Spring/Summer '16")?></span></a>
                    </li>
                </ul> 
            </li>
            <?php endif; ?>
            <?php if($_menu): ?>
                <?php echo $_menu ?>
            <?php endif ?>
            <?php $additionalLink = themeOptions('additionalLink'); ?>
            <?php $additionalLinkUrl = themeOptions('additionalLinkUrl'); ?>

            <?php if ($block1 = $this->getChildHtml('nav_block1')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block1')->getTitle(); ?>
                <li class="level0 block_li parent" id="designer">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li> 
            <?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block2')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block2')->getTitle(); ?>
                <li class="level0 block_li parent" id="designer">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
            <?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block3')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block3')->getTitle(); ?>
                <li class="level0 block_li parent" id="designer">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
            <?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block4')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block4')->getTitle(); ?>
                <li class="level0 block_li parent" id="designer">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
            <?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block5')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block5')->getTitle(); ?>
                <li class="level0 block_li parent" id="designer">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
            <?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block6')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block6')->getTitle(); ?>
                <li class="level0 block_li parent" id="designer">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
            <?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block7')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block7')->getTitle(); ?>
                <li class="level0 block_li parent" id="designer">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
            <?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block8')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block8')->getTitle(); ?>
                <li class="level0 block_li parent" id="designer">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
            <?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block9')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block9')->getTitle(); ?>
                <li class="level0 block_li parent" id="designer">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
            <?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block10')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block10')->getTitle(); ?>
                <li class="level0 block_li parent last_block" id="designer">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
            <?php endif; ?>              
            
            <?php 
                echo $this->getLayout()->createBlock('core/template')->setTemplate('manufacturer/menu.phtml')->toHtml();
            ?>
            
            
            
            
            
            
            <?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==1): ?>
                <li class="level0 <?php if (Mage::app()->getStore()->getStoreId()==2 || Mage::app()->getStore()->getStoreId()==6): echo 'en'; endif;?> first"><a href="<?php echo Mage::getUrl()?>sale/"><span style="color:rgb(149,0,0);" ><?php echo $this->__('Sale') ?></span></a></li>    
           <?php endif; ?>

           <?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==1): ?>
                <li class="level0 <?php if (Mage::app()->getStore()->getStoreId()==2 || Mage::app()->getStore()->getStoreId()==6): echo 'en'; endif;?> first"><a href="<?php echo Mage::getUrl()?>mid-season-sale-ss16/"><span style="font-weight: bold;"><?php echo $this->__('Mid Season Sale') ?></span></a></li>    
           <?php endif; ?>
           
           
           

            <?php if($additionalLinkUrl && $additionalLink): ?>
                <li class="level0 clearence"><a href="<?php echo $additionalLinkUrl ?>" target="_blank" title="<?php echo $additionalLink ?>"><span title="A blog about fashion, passion and beyond"><?php echo $additionalLink ?></span></a></li>
            <?php endif ?>
            
            <!-- Añadimos enlace a Outlet -->
           <?php if (Mage::app()->getStore()->getId()==1 || Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getStoreId()==6 || Mage::app()->getStore()->getStoreId()==7): ?>
             <li class="level0 <?php if (Mage::app()->getStore()->getStoreId()==2) echo 'en'?> first final"><a href="http://outlet.elitestore.es"><span title="Blog about fashion, passion and beyond"><?php echo $this->__('Outlet') ?></span></a></li> 
           <?php else: ?>
             <li class="level0 first final"><a href="http://www.elitestore.es"><span><?php echo $this->__('Elite Store') ?></span></a></li>    
           <?php endif; ?>  
        </ul>
</nav>
<div class="nav-container">
    <div class="right-bg">
        <ul id="nav">
            <li class="level0 <?php if (Mage::app()->getStore()->getStoreId()==2 || Mage::app()->getStore()->getStoreId()==6) echo 'en'?> first homelink"><a href="<?php echo $this->getBaseUrl(); ?>"><span><?php echo $this->__('home') ?></span></a></li>
            <?php if (Mage::app()->getStore()->getId()==1 || Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getStoreId()==6 || Mage::app()->getStore()->getStoreId()==7): ?>
            <li class="level0 <?php if (Mage::app()->getStore()->getStoreId()==2 || Mage::app()->getStore()->getStoreId()==6) echo 'en'?>"><a href="<?php echo $this->getBaseUrl().'new-in-ss16?dir=desc&order=created_at'; ?>"><span><?php echo $this->__('New In') ?></span></a>
				
                <ul class="level0 chield chield4">
					<li class="level1 en nav-1-1 first parent seasons">
                        <a href="<?php  echo $this->getBaseUrl().'new-in-ss16?dir=desc&order=created_at';?>"><span><?php echo $this->__("Spring/Summer '16")?></span></a>
					</li>
				</ul> 
			</li>
            <?php endif; ?>
            <?php if($_menu): ?>
                <?php echo $_menu ?>
            <?php endif ?>
            <?php $additionalLink = themeOptions('additionalLink'); ?>
            <?php $additionalLinkUrl = themeOptions('additionalLinkUrl'); ?>

            <?php if ($block1 = $this->getChildHtml('nav_block1')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block1')->getTitle(); ?>
            	<li class="level0 block_li parent">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li> 
    		<?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block2')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block2')->getTitle(); ?>
            	<li class="level0 block_li parent">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    		<?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block3')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block3')->getTitle(); ?>
            	<li class="level0 block_li parent">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    		<?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block4')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block4')->getTitle(); ?>
            	<li class="level0 block_li parent">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    		<?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block5')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block5')->getTitle(); ?>
            	<li class="level0 block_li parent">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    		<?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block6')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block6')->getTitle(); ?>
            	<li class="level0 block_li parent">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    		<?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block7')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block7')->getTitle(); ?>
            	<li class="level0 block_li parent">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    		<?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block8')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block8')->getTitle(); ?>
            	<li class="level0 block_li parent">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    		<?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block9')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block9')->getTitle(); ?>
            	<li class="level0 block_li parent">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    		<?php endif; ?> 

            <?php if ($block1 = $this->getChildHtml('nav_block10')): ?>
                <?php $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('nav_block10')->getTitle(); ?>
            	<li class="level0 block_li parent last_block">
                    <a class="level-top" href="#"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    		<?php endif; ?>              
            
			<?php 
				echo $this->getLayout()->createBlock('core/template')->setTemplate('manufacturer/menu.phtml')->toHtml();
			?>
            
            

           <?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==1): ?>
                <li class="level0 <?php if (Mage::app()->getStore()->getStoreId()==2 || Mage::app()->getStore()->getStoreId()==6): echo 'en'; endif;?> first"><a href="<?php echo Mage::getUrl()?>sale/"><span style="color:rgb(149,0,0);" ><?php echo $this->__('Sale') ?></span></a></li>    
           <?php endif; ?>

           <?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==1): ?>
                <li class="level0 <?php if (Mage::app()->getStore()->getStoreId()==2 || Mage::app()->getStore()->getStoreId()==6): echo 'en'; endif;?> first"><a href="<?php echo Mage::getUrl()?>mid-season-sale-ss16/"><span style="font-weight: bold;"><?php echo $this->__('Mid Season Sale') ?></span></a></li>    
           <?php endif; ?>
           
            
            <?php if($additionalLinkUrl && $additionalLink): ?>
                <li class="level0 clearence"><a href="<?php echo $additionalLinkUrl ?>" title="<?php echo $additionalLink ?>" target="_blank" ><span title="A blog about fashion, passion and beyond"><?php echo $additionalLink ?></span></a></li>
            <?php endif ?>
            
            <!-- Añadimos enlace a Outlet -->
           <?php if (Mage::app()->getStore()->getId()==1 || Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getStoreId()==6 || Mage::app()->getStore()->getStoreId()==7): ?>
             <li class="level0 <?php if (Mage::app()->getStore()->getStoreId()==2) echo 'en'?> first final"><a href="http://outlet.elitestore.es"><span><?php echo $this->__('Outlet') ?></span></a></li> 
           <?php else: ?>
             <li class="level0 first final"><a href="http://www.elitestore.es"><span><?php echo $this->__('Elite Store') ?></span></a></li>    
           <?php endif; ?>  
        </ul>
    </div>
</div>