<?php
/**
 * Customer Login Template for Community Edition 1.9 RWD THEME
 *
 * @author     Design:Slider GbR <magento@design-slider.de>
 * @copyright  (C)Design:Slider GbR <www.design-slider.de>
 * @license    OSL <http://opensource.org/licenses/osl-3.0.php>
 * @link       http://www.design-slider.de/magento-onlineshop/magento-extensions/private-sales/
 * @package    DS_PrivateSales
 */

$helper = Mage::helper('privatesales');
/* @var $helper DS_PrivateSales_Helper_Data */

$canShowRegPanel = $helper->canShowRegistrationLoginPanel();
$customRegPanel = ($helper->getShowRegistrationLoginPanel()==2);
$customRegHeader = $helper->getRegistrationPanelHeader();
$customRegText = $helper->getRegistrationPanelText();
$canShowRegButton = $helper->canShowRegistrationPanelButton();
$customButtonText = $helper->getRegistrationPanelButtonText();
$isForgotPasswordEnabled = $helper->canShowForgotPassword();
$isRegistrationEnabled = $helper->canShowRegistration();
?>
<div class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">
    <div class="page-title">
        <h1><?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                <?php echo $this->__('Login or Create an Account') ?>
            <?php else: ?>
                <?php echo $this->__('Login'); ?>
            <?php endif; ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="scaffold-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div<?php if ($canShowRegPanel): ?> class="col2-set"<?php endif; ?>>
            <?php if ($canShowRegPanel && $this->helper('customer')->isRegistrationAllowed()): ?>
                <div class="col-1 new-users">
                    <div class="content">
                        <h2><?php echo ($customRegPanel && strlen($customRegHeader)) ? $customRegHeader : $this->__('New Here?') ?></h2>
                        <?php if ($customRegPanel && strlen($customRegText)): ?>
                            <?php echo nl2br($customRegText); ?>
                        <?php else: ?>
                            <p class="form-instructions"><?php echo $this->__('Registration is free and easy!') ?></p>
                            <ul class="benefits">
                                <li><?php echo $this->__('Faster checkout') ?></li>
                                <li><?php echo $this->__('Save multiple shipping addresses') ?></li>
                                <li><?php echo $this->__('View and track orders and more') ?></li>
                            </ul>
                        <?php endif; ?>
                    </div>
                    <div class="buttons-set">
                        <?php if (!$customRegPanel || $canShowRegButton): ?>
                            <a title="<?php echo ($customRegPanel && strlen($customButtonText)) ? $customButtonText : $this->__('Create an Account') ?>" class="button" href="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>"><span><span><?php echo ($customRegPanel && strlen($customButtonText)) ? $customButtonText : $this->__('Create an Account') ?></span></span></a>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>
            <?php // This column should be col-1 if the registration column is not displayed ?>
            <div class="<?php if ($canShowRegPanel && $this->helper('customer')->isRegistrationAllowed()): ?>col-2<?php else: ?>col-1<?php endif; ?> registered-users">
                <div class="content fieldset">
                    <h2><?php echo $this->__('Already registered?') ?></h2>
                    <p class="form-instructions"><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php if ($isForgotPasswordEnabled): ?>
                            <li>
                                <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                            </li>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                </div>
                <div class="buttons-set">
                    <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                </div>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
        //]]>
    </script>
</div>
