<?php
$auctionbid = $this->getAuctionbid();
$customer = $this->getCustomer();
$cusAdress = $customer->getPrimaryBillingAddress();
if ($auctionbid) {
    $customer_url = $this->getCustomerUrl($auctionbid->getCustomerId());

    $productauction = $this->getProductauction();

    $product = $this->getProduct();
    if ($product) {
        $product_url = $this->getProductUrl($product->getId());

        $listAuctionStatus = Mage::helper('auction')->getListAuctionStatus();
        $listBidStatus = Mage::helper('auction')->getListBidStatus();

        $_helper = Mage::helper('core');

        $start_time = new Zend_Date($productauction->getData('start_date') . ' ' . $productauction->getData('start_time'), null, 'en_GB');
        $end_time = new Zend_Date($productauction->getData('end_date') . ' ' . $productauction->getData('end_time'), null, 'en_GB');

        $bid_date = new Zend_Date($auctionbid->getCreatedDate(), null, 'en_GB');
        ?>
        <div class="box-left">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-account"><?php echo $this->__('Bid Information') ?></h4>
                </div>
                <div class="fieldset">
                    <table class="form-list" cellspacing="0">
                        <tr>
                            <td class="label"><label><?php echo $this->__('Bid Product') ?></label></td>
                            <td><strong><?php echo $auctionbid->getProductName() ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Bidder Name') ?></label></td>
                            <td><strong><?php echo $auctionbid->getBidderName() ?></strong></td>
                        </tr>					
                        <tr>
                            <td class="label"><label><?php echo $this->__('Bid Customer') ?></label></td>
                            <td><strong><?php echo $auctionbid->getCustomerName() ?></strong></td>
                        </tr>				
                        <tr>
                            <td class="label"><label><?php echo $this->__('Bid Price') ?></label></td>
                            <td><strong><?php echo $_helper->currency($auctionbid->getPrice()) ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Bid Date') ?></label></td>
                            <td><strong><?php echo Mage::helper('core')->formatDate($bid_date, 'medium', false) ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Bid Time') ?></label></td>
                            <td><strong><?php echo $auctionbid->getCreatedTime() ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Bid Status') ?></label></td>
                            <td><strong><?php echo $listBidStatus[$auctionbid->getStatus()] ?></strong></td>
                        </tr>	
                        <?php if ($auctionbid->getStatus() == 6) { ?>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Order') ?></label></td>
                                <td><strong><a href="<?php echo $this->getUrl('adminhtml/sales_order/view', array('order_id' => $auctionbid->getOrderId())) ?>" >
                                        <?php echo $this->__('View') ?></strong></td>
                                </a></strong>
                            </tr>					
                        <?php } ?>
                    </table>
                </div>
            </div>
        </div>

        <div class="box-right">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-account"><?php echo $this->__('Customer Information') ?></h4>
                </div>
                <div class="fieldset">
                    <table class="form-list" cellspacing="0">
                        <tr>
                            <td class="label"><label><?php echo $this->__('Customer Name') ?></label></td>
                            <td><strong><?php echo $auctionbid->getCustomerName() ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Customer Email') ?></label></td>
                            <td><strong><?php echo $auctionbid->getCustomerEmail() ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Customer Phone') ?></label></td>
                            <td><strong><?php if($cusAdress) if($cusAdress->getTelephone()!=null && strlen($cusAdress->getTelephone())>0) echo $cusAdress->getTelephone(); ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Customer Address') ?></label></td>
                            <td>
                                <strong>
                                    <?php
                                    if($cusAdress) 
                                        if ($cusAdress->getData()['street'] != null && strlen($cusAdress->getData()['street']) > 0) {
                                            echo $cusAdress->getData()['street'], ', ', $cusAdress->getData()['city'], ', ', Mage::getModel("directory/country")->load($cusAdress->getData()['country_id'])->getName();
                                        }
                                    ?>
                                </strong>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Customer Detail') ?></label></td>
                            <td><strong><a target="_blank" href="<?php echo $customer_url ?>"> <?php echo $this->__('view') ?></a></strong></td>
                        </tr>								
                    </table>
                </div>
            </div>
        </div>
        <div class="clear" >&nbsp;</div>
        <div class="box-right">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-account"><?php echo $this->__('Product Information') ?></h4>
                </div>
                <div class="fieldset">
                    <table class="form-list" cellspacing="0">
                        <tr>
                            <td class="label"><label><?php echo $this->__('Product Name') ?></label></td>
                            <td><strong><?php echo $product->getName() ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Sku') ?></label></td>
                            <td><strong><?php echo $product->getData('sku') ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Price') ?></label></td>
                            <td><strong><?php echo $_helper->currency($product->getData('price')) ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Product Detail') ?></label></td>
                            <td><strong><a target="_blank" href="<?php echo $product_url ?>" > <?php echo $this->__('view') ?></a></strong></td>
                        </tr>					
                    </table>
                </div>
            </div>
        </div>
        <div class="box-left">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-account"><?php echo $this->__('Auction Information') ?></h4>
                </div>
                <div class="fieldset">
                    <table class="form-list" cellspacing="0">
                        <tr>
                            <td class="label"><label><?php echo $this->__('Product Name') ?></label></td>
                            <td><strong><?php echo $productauction->getProductName() ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Current Price') ?></label></td>
                            <td><strong><?php echo $_helper->currency($productauction->getCurrentPrice()) ?></strong></td>
                        </tr>				
                        <tr>
                            <td class="label"><label><?php echo $this->__('Starting Price') ?></label></td>
                            <td><strong><?php echo $_helper->currency($productauction->getData('init_price')) ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Minimum Bid Increment') ?></label></td>
                            <td><strong><?php echo $_helper->currency($productauction->getData('min_interval_price')) ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Maximum Bid Increment') ?></label></td>
                            <td><strong><?php echo ($productauction->getData('max_interval_price') > 0 ) ? $_helper->currency($productauction->getData('max_interval_price')) : $this->__('No limited') ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Start Time') ?></label></td>
                            <td><strong><?php echo Mage::helper('core')->formatDate($start_time, 'medium', true) ?></strong></td>
                        </tr>		

                        <tr>
                            <td class="label"><label><?php echo $this->__('End Time') ?></label></td>
                            <td><strong><?php echo Mage::helper('core')->formatDate($end_time, 'medium', true) ?></strong></td>
                        </tr>					
                        <tr>
                            <td class="label"><label><?php echo $this->__('Status') ?></label></td>
                            <td><strong><?php echo $listAuctionStatus[$productauction->getStatus()] ?></strong></td>
                        </tr>								
                    </table>
                </div>
            </div>
        </div>
        <?php
    }
}?>