<?php
$_coreHelper = $this->helper('core');
$checkoutHelper = Mage::helper('onestepcheckout/checkout');
?>

<table class="onestepcheckout-summary">
    <thead>
        <tr>
            <th class="name"><?php echo $this->__('Product'); ?></th>
            <th class="qty"><?php echo $this->__('Qty'); ?></th>
            <th class="total"><?php echo $this->__('Subtotal'); ?></th>
        </tr>
    </thead>
    <?php foreach($this->getItems() as $item): ?>
    <tr>
        <td class="name">
            <div class="imagen"><img src="<?php echo $this->helper('catalog/image')->init($item->getProduct(), 'thumbnail')->resize(80);?>"/></div>
            <?php echo "<div class='description'><div class='manufacturer'>" . Mage::getModel('catalog/product')->load($item->getProductId())->getAttributeText('manufacturer') . "</div>"; ?>
            <?php echo "<div class='name'>" . $item->getName() . "</div>"; ?>
            <?php if($checkoutHelper->settings['show_custom_options']): ?>
                <?php $options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct()); ?>
                <?php if(isset($options['options']) && count($options['options']) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($options['options'] as $option): ?>
                    <li><b><?php echo $option['label'] . ':</b> ' . $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php if($item->getProduct()->isConfigurable()): ?>

                <?php
                $configurable_options = $item->getProduct()->getTypeInstance(true)->getSelectedAttributesInfo($item->getProduct());
                ?>

                <?php if(is_array($configurable_options) && count($configurable_options) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($configurable_options as $option): ?>
                    <li><b><?php echo $option['label']; ?>:</b> <?php echo $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php endif; ?>

            <?php endif; ?>
        </td>
        <td class="qty"><?php echo $item->getQty(); ?></td>
        <td class="total">
            <?php if($checkoutHelper->settings['display_tax_included']): ?>
            <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item)); ?>
            <?php else: ?>
            <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

<table class="onestepcheckout-totals">
    <?php 
    $sumPartial = 0;
    foreach($this->getTotals() as $total): ?>
    <?php if(!$total->getTitle()){continue;}?>
        <?php
        $fullInfo = $total->getFullInfo();

        if(!empty($fullInfo) && $checkoutHelper->settings['display_full_tax']):
            foreach ($fullInfo as $info):
                $rates = current($info['rates']);
                $amount = $info['amount'];
        ?>
            <tr>
                <td class="title"><?php echo $rates['title'] ?> (<?php echo $rates['percent'] ?>%)</td><td class="value"><?php echo $this->helper('checkout')->formatPrice($amount); ?></td>
            </tr>
        <?php endforeach;
        endif;?>

            <?php

            $code = $total->getCode();
            $value = $total->getValue();
            $partialTitle = "<tr class='partial'><td class='title'>" . $this->__('Partial') . "</td><td class='value'>";
            $partialTitle2 = "</td></tr>";
            


            if($code == 'subtotal')    {
                ?>
                <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
                <td class="title">
                <?php
                    $total_name = $this->__('Subtotal');
                    echo $total_name;
                ?>
                    <td class="value">
                        <?php 
                            $sumPartial=$value;
                            echo $this->helper('checkout')->formatPrice($value); 
                        ?>
                    </td>
                </tr>
                <?php
            }
            elseif($code == 'shipping') {
                ?>
                <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
                <td class="title">
                <?php
                $total_name = $this->__('Shipping');
                echo $total_name;
                
                ?>
                </td>
                    <td class="value">
                        <?php 
                            $sumPartial = $sumPartial + $value;
                            echo $this->helper('checkout')->formatPrice($value); 
                        ?>
                    </td>
                </tr>
                <?php
                echo $partialTitle . $this->helper('checkout')->formatPrice($sumPartial) . $partialTitle2;
                if($checkoutHelper->settings['display_tax_included'])   {
                    $value += $this->getQuote()->getShippingAddress()->getShippingTaxAmount();
                }
                            }
            elseif($code == 'grand_total')    {
                ?>
                <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
                <td class="title">
                <?php
                $total_name = $this->__('Grand total');
                echo $total_name;
                ?>
                </td>
                    <td class="value">
                        <?php 
                            $sumPartial = $sumPartial + $value;
                            echo $this->helper('checkout')->formatPrice($value); 
                        ?>
                    </td>
                </tr>
                <?php
            }
            elseif($code == 'discount')    {
                ?>
                <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
                <td class="title">
                <?php
                $total_name = $this->__('Discount');
                echo $total_name;
                
                ?>
                    <td class="value">
                        <?php 
                            echo $this->helper('checkout')->formatPrice($value); 
                        ?>
                    </td>
                </tr>
                <?php
                $sumPartial = $sumPartial + $value;
                echo $partialTitle . $this->helper('checkout')->formatPrice($sumPartial) . $partialTitle2;
            }
            elseif($code == 'tax')    {
                ?>
                <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
                <td class="title">
                <?php
                $total_name = $this->__('Tax');
                echo $total_name;
                ?>
                    <td class="value">
                        <?php 
                            $sumPartial = $sumPartial + $value;
                            echo $this->helper('checkout')->formatPrice($value); 
                        ?>
                    </td>
                </tr>
                <?php
                echo $partialTitle . $this->helper('checkout')->formatPrice($sumPartial) . $partialTitle2;
            }
            else    {
                ?>
                <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
                <td class="title">
                <?php
                $total_name = $total->getTitle();
                echo $total_name;
                ?>
                    <td class="value">
                        <?php 
                            $sumPartial = $sumPartial + $value;
                            echo $this->helper('checkout')->formatPrice($value); 
                        ?>
                    </td>
                </tr>
                <?php
                echo $partialTitle;
            }

            ?>
    
    <?php endforeach; ?>
</table>
<script type="text/javascript">
//<![CDATA[
var total = <?php echo $this->getGrandTotal();?>;
    if(payment.reloadcallback){
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/paymentrefresh', array('_secure'=>true)); ?>';
        paymentrefresh(url);
        payment.countreload = 0;
        payment.reloadcallback = false;
    }
//]]>
</script>
