<script src="<?php echo $this->getSkinUrl("js/jquery.min-1.11.1.js")?>"></script>  
<script type="text/javascript">
var jshow=$.noConflict();
jshow(document).ready(function(){
 
  jshow("#toolbar-title1").hover(function(){
    jshow("#toolbar-dropdown1").show();

  });
jshow("#toolbar-dropdown1").hover(function(){
    jshow("#toolbar-dropdown1").show();

  });
jshow("#toolbar-title1,#toolbar-dropdown1").mouseleave(function(){
    jshow("#toolbar-dropdown1").hide();

  });

jshow("#toolbar-title2").hover(function(){
    jshow("#toolbar-dropdown2").show();
  });
jshow("#toolbar-dropdown2").hover(function(){
    jshow("#toolbar-dropdown2").show();

  });
jshow("#toolbar-title2,#toolbar-dropdown2").mouseleave(function(){
    jshow("#toolbar-dropdown2").hide();

  });
});
</script>
<style type="text/css">
.over .toolbar-title {
height: 27px;
}
.sorter .view-mode .list {
    margin-right: -10px;
}
#mini-toolbar{
    display: none;
}
</style>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar" id="desktop-toolbar" >
    

    <?php if( $this->isExpanded() ): ?>
    <div class="sorter">
<div class="sort-by toolbar-switch">
            <div class="toolbar-title" id="toolbar-title1">
                <label>Sort By</label>
                <span class="current">
		<?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
		<?php if($this->isOrderCurrent($_key)): ?><?php echo $this->__($_order) ?><?php endif; ?>
		<?php endforeach; ?>
		</span>
            </div>
            <div class="toolbar-dropdown" id="toolbar-dropdown1" style="width:174px;"><ul id="aa">
	<?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <li><a href="<?php echo $this->getOrderUrl($_key, 'asc') ?>"> <?php echo $this->__($_order) ?></a></li>
 	<?php endforeach; ?></ul>images/
            </div>
        </div>
        <div class="sort-order">
                        <?php if($this->getCurrentDirection() == 'desc'): ?>
                <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>"><img src="<?php echo $this->getSkinUrl("images/i_desc_arrow.gif")?>" alt="Set Ascending Direction" class="v-middle" width="27" height="27"></a>
            <?php else: ?>
                <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>"><img src="<?php echo $this->getSkinUrl("images/i_asc_arrow.gif")?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>
            <?php endif; ?>
        </div>
        <?php if( $this->isEnabledViewSwitcher() ): ?>
        <p class="view-mode">
            <?php $_modes = $this->getModes(); ?>
            <?php if($_modes && count($_modes)>1): ?>
            <label><?php echo $this->__('View') ?></label>
            <?php foreach ($this->getModes() as $_code=>$_label): ?>
                <?php if($this->isModeActive($_code)): ?>
                    <strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>&nbsp;
                <?php else: ?>
                    <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>&nbsp;
                <?php endif; ?>
            <?php endforeach; ?>
            <?php endif; ?>
        </p>
 <div class="limiter toolbar-switch">
            <div class="toolbar-title" id="toolbar-title2">
                <label><?php echo $this->__('Show') ?></label>
                
	   <span class="current">
		<?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>		
		<?php if($this->isLimitCurrent($_key)): ?> <?php echo $_limit ?>
		per page
        <?php else: ?>

        <?php endif; ?>
		 <?php endforeach; ?>
	   </span></div>
            <div class="toolbar-dropdown" id="toolbar-dropdown2" style="width:174px;">
                <ul> <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
		<li ><a href="<?php echo $this->getLimitUrl($_key) ?>"><?php echo $_limit ?></a></li>
		
		 <?php endforeach; ?></ul>

            </div>
        </div>
        <?php endif; ?>
    
        
    </div>
    <?php endif; ?>
        <div class="pager">
        <p class="amount">
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
        </p>


    </div>
</div>
<?php endif ?>


<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar" id="mini-toolbar" >
    <?php if( $this->isExpanded() ): ?>
            <div class="sorter">
    <div class="sort-by">
            <label><?php echo $this->__('Sort By') ?></label>
            <select onchange="setLocation(this.value)">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                    <?php echo $this->__($_order) ?>
                </option>
            <?php endforeach; ?>
            </select>
            <?php if($this->getCurrentDirection() == 'desc'): ?>
                <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_desc_arrow.gif') ?>" alt="<?php echo $this->__('Set Ascending Direction') ?>" class="v-middle" /></a>
            <?php else: ?>
                <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_asc_arrow.gif') ?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>
            <?php endif; ?>
    </div>

            
                <?php if( $this->isEnabledViewSwitcher() ): ?>
                <p class="view-mode">
                    <?php $_modes = $this->getModes(); ?>
                    <?php if($_modes && count($_modes)>1): ?>
                    <label><?php echo $this->__('View as') ?>:</label>
                    <?php foreach ($this->getModes() as $_code=>$_label): ?>
                        <?php if($this->isModeActive($_code)): ?>
                            <strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>&nbsp;
                        <?php else: ?>
                            <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>&nbsp;
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <?php endif; ?>
                </p>
                <?php endif; ?> 
                 <div class="limiter" style="margin-top: 10px;">
            <label><?php echo $this->__('Show') ?></label>
            <select onchange="setLocation(this.value)">
            <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                    <?php echo $_limit ?>
                </option>
            <?php endforeach; ?>
            </select> <?php echo $this->__('per page') ?>
        </div>
            </div>
            <?php endif; ?>

           

</div>
<?php endif ?>

