<?php 
				
            	$product = $_product->load($_product->getId());
				$colors= array();
				foreach ($product->getMediaGalleryImages() as $imagem) {
            		if($imagem->getPosition() == '1') {
							$colors[]= $imagem->getFile();
					}
				}
				$sizes = array();
				if($_product->isConfigurable()){
					$allProducts = $_product->getTypeInstance(true)->getUsedProducts(null, $_product);
            		foreach ($allProducts as $subproduct) {
                		if ($subproduct->isSaleable()) {
                    		$sizes[] = $subproduct->getAttributeText('talla');
                		}
            		}
				
				if ((count($colors)>1) && (count($sizes)>0 && $sizes[0]!='UNICA') ){
					?><div class="colorsizeavailable" style="margin-top:155px;height:90px;"><?php
				}else if (count($colors)>1){
					?><div class="colorsizeavailable" style="margin-top:185px;height:60px;"><?php
				}else if (count($sizes)>0 && $sizes[0]!='UNICA') {
					?><div class="colorsizeavailable" style="margin-top:210px;height:35px;"><?php
				}
				
				if (count($colors)>1){
					?>
                    	<div class="colors-available"><?php echo ($this->__('Available Colours'))?></div>
                    <?php    
                    foreach ($colors as $color){
						?><div class="image-color-available"><img style="position:relative;" src="<?php echo Mage::helper('catalog/image')->init($product, 'image', $color)->resize(35); ?>" width="35px" height="35px" alt="" /></div><?php
					}
					
				}
				if (count($sizes)>0 && $sizes[0]!='UNICA'){
						$sizes2=array_unique($sizes);
						//sort($sizes2);
						echo ('<div class="sizes-available"');
						echo ('>'.$this->__('Available Sizes').'</div><div class="size-available">');
						echo implode(", ", $sizes2);
						echo ('</div>');

                	}
				}
				if ((count($colors)>1) || (count($sizes)>0 && $sizes[0]!='UNICA') ){
					echo ('</div>');
				}
				
				
				
        
