<script type="text/javascript">
    //update initPrices function to get/update the prices from the options popup only
    <?php if (!in_array($this->getProduct()->getTypeId(), array('bundle','grouped'))): ?>
	if (typeof(Product) !== 'undefined') {    
	    Product.OptionsPrice.prototype.initPrices = function initPrices() {
	        this.containers[0] = 'product-price-' + this.productId + '_clone';
	        this.containers[1] = 'bundle-price-' + this.productId;
	        this.containers[2] = 'price-including-tax-' + this.productId;
	        this.containers[3] = 'price-excluding-tax-' + this.productId;
	        this.containers[4] = 'old-price-' + this.productId + '_clone';
	    };
	}
	<?php endif; ?>
	var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
	
	//remove options wrapper if product has no custom options; used when adding wishlist item to the cart from the wishlist sidebar and the qty is too high
	<?php if (!$this->getProduct()->getTypeInstance(true)->hasOptions($this->getProduct())): ?>
		GlaceAjax_182('#product-options-wrapper').css({'padding': '0px', 'border-top': '0px'});
	<?php endif; ?>
</script>
<?php echo $this->getChildHtml('', true, true);?>
<?php echo $this->getTierPriceHtml() ?>