<?php
/**
 * Survey for Magento
 *
 * @category   Belitsoft
 * @package    Belitsoft_Survey
 * @author     Belitsoft <bits@belitsoft.com>
 */

/* @var $this Belitsoft_Survey_Block_Frontend_Catdetail */
?>

<?php $_category = $this->getCategory(); ?>

<?php if ($_category): ?>
    <div class="page-title category-title survey-category-title">
        <h1><?php echo $this->escapeHtml($_category->getCategoryName()); ?></h1>
    </div>

    <?php if ($_description = $_category->getCategoryDescription()): ?>
        <div class="category-description std survey-category-description">
            <?php echo $this->filter($_description); ?>
        </div>
    <?php endif; ?>

    <?php echo $this->getSurveyListHtml(); ?>

<?php else: ?>
    <div class="page-title">
        <h1><?php echo $this->__('Error') ?></h1>
    </div>
    <p>
        <?php echo $this->__('The requested Survey category could not be found!') ?>
    </p>
<?php endif; ?>
