<?php
/**
 * Survey for Magento
 *
 * @category   Belitsoft
 * @package    Belitsoft_Survey
 * @author     Belitsoft <bits@belitsoft.com>
 */

/* @var $this Belitsoft_Survey_Block_Frontend_Detail */
?>
<div id="survey-detail-view" class="survey-detail">
    <?php if ($_survey = $this->getSurvey()): ?>
        <div class="page-title survey-title">
            <h1><?php echo $this->escapeHtml($_survey->getSurveyName()); ?></h1>
        </div>

        <?php if ($this->isRestrictedPage()): ?>
            <?php echo $this->getSurveyRestrictedPageText(); ?>
        <?php elseif ($this->isFinishPage()): //if($this->isRestrictedPage()) ?>
            <?php echo $this->filter($_survey->getSurveyFinalPageText()); ?>
            <?php if ($this->isViewMode()): ?>
                <div class="actions">
                    <button type="button" title="<?php echo $this->__('Back'); ?>" class="button"
                            onclick="location.href='<?php echo $this->getBackUrl(); ?>'">
                        <span><span><?php echo $this->__('Back'); ?></span></span>
                    </button>
                </div>
            <?php endif;  //if($this->isViewMode()) ?>
        <?php else: //if($this->isRestrictedPage()) ?>

            <?php if ($_description = $_survey->getSurveyDescription()): ?>
                <div class="survey-description std">
                    <?php echo $this->filter($_description); ?>
                </div>
            <?php endif; //if($_description = $_survey->getSurveyDescription()) ?>

            <?php if ($_survey->getMultipage()): ?>
                <form action="<?php echo $this->getSurveyStartFormActionUrl(); ?>" method="post" id="survey-start">
                    <div class="actions">
                        <button type="submit" title="<?php echo $this->__('Start'); ?>" class="button">
                            <span><span><?php echo $this->__('Start'); ?></span></span>
                        </button>
                    </div>
                </form>
            <?php else: //if($_survey->getMultipage()) ?>
                <?php echo $this->getQuestionsHtml(); ?>
            <?php endif; //if($_survey->getMultipage()) ?>

        <?php endif; //if($this->isFinishPage()) ?>

    <?php else: //if ($_survey = $this->getSurvey()) ?>
        <div class="page-title">
            <h1><?php echo $this->__('Error'); ?></h1>
        </div>
        <p>
            <?php echo $this->__('The requested survey could not be found!'); ?>
        </p>
    <?php endif; //if($_survey = $this->getSurvey()) ?>
</div>