<?php
/**
 * Survey for Magento
 *
 * @category   Belitsoft
 * @package    Belitsoft_Survey
 * @author     Belitsoft <bits@belitsoft.com>
 */

/* @var $this Belitsoft_Survey_Block_Frontend_List */
?>

<?php if ($this->hasSurveys()): ?>
    <h2><?php echo $this->__('Surveys list'); ?></h2>
    <dl class="survey-list">
        <?php foreach ($this->getSurveyCollection() as $survey) : ?>
            <?php $sid = $survey->getId(); ?>
            <dt id="survey-<?php echo $sid; ?>">
                <strong>
                    <?php if (Mage::helper('belitsoft_survey')->numberQuestionsInSurvey($sid)): ?>
                    <a href="<?php echo $this->getSurveyLink($sid); ?>">
                        <?php endif; ?>
                        <?php echo $this->htmlEscape($survey->getSurveyName()); ?>
                        <?php if (Mage::helper('belitsoft_survey')->numberQuestionsInSurvey($sid)): ?>
                    </a>
                <?php endif; ?>
                </strong>
            </dt>
            <dd style="margin-bottom:10px">
                <?php echo $this->getIntro($survey); ?>
            </dd>
        <?php endforeach; ?>
    </dl>
<?php else: ?>
    <p class="survey-items">
        <?php echo $this->__('There are no surveys to display.') ?>
    </p>
<?php endif; ?>
