<?php
/**
 * Survey for Magento
 *
 * @category   Belitsoft
 * @package    Belitsoft_Survey
 * @author     Belitsoft <bits@belitsoft.com>
 */

/* @var $this Belitsoft_Survey_Block_Frontend_Question */
?>

<?php $_survey = $this->getSurvey(); ?>
<?php $_question = $this->getCurrentQuestion(); ?>

<?php if (!$this->isQuestionsList()): ?>
    <div class="page-title survey-title">
        <h1><?php echo $this->escapeHtml($_survey->getSurveyName()); ?></h1>
    </div>
<?php endif; ?>

<?php if (!$this->isFinishPage()): ?>

    <?php if (!$this->isQuestionsList()): ?>
        <form action="<?php echo $this->getSurveyContinueFormActionUrl(); ?>" method="post" id="survey-question-per-page">
    <?php else: //if(!$this->isQuestionsList()) ?>
        <dt>
    <?php endif; //if(!$this->isQuestionsList()) ?>

<div class="survey-question-description std">
	<?php echo $this->filter($_question->getQuestionText()); ?>
</div>

<?php if ($this->isQuestionsList()): ?>
</dt>

<dd style="padding-bottom: 10px; margin-bottom: 10px; border-bottom: 1px solid grey;">
<?php endif; ?>

<div class="options">
	<?php echo $this->getQuestionOptions(); ?>
</div>

<?php if (!$this->isQuestionsList()): ?>
        <div class="actions">
            <?php if ($this->isViewMode()): ?>
                <button type="button" title="<?php echo $this->__('Back'); ?>" class="button"
                        onclick="location.href='<?php echo $this->getBackUrl(); ?>'">
                    <span><span><?php echo $this->__('Back'); ?></span></span>
                </button>
            <?php endif; ?>

            <?php if ($this->isPrevButtonShow()): ?>
                <button type="submit" title="<?php echo $this->__('Prev'); ?>" class="button"
                        onclick="javascript:setStage(this.form, 'prev');">
                    <span><span><?php echo $this->__('Prev'); ?></span></span>
                </button>
            <?php endif; ?>
            <button type="submit" title="<?php echo $this->__('Next'); ?>" class="button"
                    onclick="javascript:setStage(this.form, 'next');">
                <span><span><?php echo $this->__('Next'); ?></span></span>
            </button>
        </div>
        <input type="hidden" name="stage" value="<?php echo $this->getCurrentStage(); ?>"/>
        <input type="hidden" name="curr_stage" value="<?php echo $this->getCurrentStage(); ?>"/>
        </form>

        <script type="text/javascript">
            //<![CDATA[
            <?php if(!$this->isViewMode()): ?>
            var surveyQuestionValidate = new VarienForm('survey-question-per-page');
            <?php endif;  //if(!$this->isViewMode()) ?>
            var setStage = function (form, type) {
                if (type == 'prev') {
                    form.stage.value = (new Number(form.curr_stage.value)).valueOf() - 1;
                    <?php if(!$this->isViewMode()): ?>
                    surveyQuestionValidate.form.select('[class*="validate-"]').each(function (elem) {
                        elem.className = elem.className.replace('validate-', 'not-validate-');
                    });
                    surveyQuestionValidate.form.select('[class="validation-advice"]').each(function (elem) {
                        elem.remove();
                    });
                    <?php endif;  //if(!$this->isViewMode()) ?>
                } else {
                    form.stage.value = (new Number(form.curr_stage.value)).valueOf() + 1;
                }
            };
            //]]>
        </script>
    <?php else:  //if(!$this->isQuestionsList()) ?>
</dd>
<?php endif;  //if(!$this->isQuestionsList()) ?>

<?php else: //if(!$this->isFinishPage()) ?>
    <?php echo $this->filter($_survey->getSurveyFinalPageText()); ?>
    <?php if ($this->isViewMode()): ?>
        <div class="actions">
            <button type="button" title="<?php echo $this->__('Back'); ?>" class="button"
                    onclick="location.href='<?php echo $this->getBackUrl(); ?>'">
                <span><span><?php echo $this->__('Back'); ?></span></span>
            </button>
        </div>
    <?php endif;  //if($this->isViewMode()) ?>
<?php endif; //if(!$this->isFinishPage()) ?>
