<?php if($this->getCurrencyCount()>1): ?>
    <div class="currency">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <?php if($_code==$this->getCurrentCurrencyCode()): 
            	switch ($_code)
            	{
            		case 'USD':?>
            			<span title="<?php echo $_name ?> - <?php echo $_code ?>" class="currency-label"><?php echo "&#36;" ?></span>
            			<?php break;
            		case 'EUR':?>
            			<span title="<?php echo $_name ?> - <?php echo $_code ?>" class="currency-label"><?php echo "&#128;" ?></span>
            			<?php break;
            		case 'GBP':?>
            			<span title="<?php echo $_name ?> - <?php echo $_code ?>" class="currency-label"><?php echo "&#163;" ?></span>
            			<?php break;

            	}?>
                
            <?php else: 
            switch ($_code)
            	{
            		case 'USD':?>
            			<a href="<?php echo $this->getSwitchCurrencyUrl($_code) ?>" title="<?php echo $_name ?> - <?php echo $_code ?>" class="currency-label"><?php echo "&#36;" ?></a>
            			<?php break;
            		case 'EUR':?>
            			<a href="<?php echo $this->getSwitchCurrencyUrl($_code) ?>" title="<?php echo $_name ?> - <?php echo $_code ?>" class="currency-label"><?php echo "&#128;" ?></a>
            			<?php break;
            		case 'GBP':?>
            			<a href="<?php echo $this->getSwitchCurrencyUrl($_code) ?>" title="<?php echo $_name ?> - <?php echo $_code ?>" class="currency-label"><?php echo "&#163;" ?></a>
            			<?php break;

            	}?>    
                
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>