<?php if($this->getCurrencyCount()>1): ?>
    <div class="currency">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <?php if($_code==$this->getCurrentCurrencyCode()): ?>
                <span title="<?php echo $_name ?> - <?php echo $_code ?>" class="currency-code" id="<?php echo $_code ?>" style="background-image: url(<?php echo $this->getSkinUrl('images/').$_code.'.png'?>);"><?php echo $_code ?></span>
            <?php else: ?>    
                <a href="<?php echo $this->getSwitchCurrencyUrl($_code) ?>" class="currency-code" id="<?php echo $_code ?>" style="background-image: url(<?php echo $this->getSkinUrl('images/').$_code.'.png'?>);" title="<?php echo $_name ?> - <?php echo $_code ?>"><?php echo $_code ?></a>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>