
<div title="Armani" class="home--slide">
	<video width="100%" autoplay loop class="video">
	  <source src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>wysiwyg/ss16/Armani_sin_audio-max.mp4" type="video/mp4">
	Your browser does not support the video tag.
	</video>
		<div class="botonera">
			<a href="http://www.elitestore.es/women/bags-for-women.html?dir=asc&manufacturer=631&order=position">
				<div class="boton izq">SHOP NOW</div>
			</a>
		</div>
</div>

<a title="GIUSEPPE ZANOTTI" href="http://www.elitestore.es/giuseppe-zanotti-design/"  class="home--left">
	<div class="home--left--triangle">
		<span>GIUSEPPE ZANOTTI</span><br/>
			NEW ICONS<br/>
		<span>Tone in tone for maximum impact</span>
	</div>
</a>

<a title="CHARLOTTE OLYMPIA" href="http://www.elitestore.es/charlotte-olympia/"  class="home--right">
	<div class="home--right--triangle">
		<span>CHARLOTTE OLYMPIA</span><br/>
			KITTY UNPLUGGED<br/>
		<span>Limited edition. And walk and roll!</span>
	</div>
</a>

<a title="ANNA-KARIN KARLSSON" class="home--img" href="http://www.elitestore.es/anna-karin-karlsson/" >
	<div class="home--img--text">
			THE QUEEN<br/><br/>&amp; The Transcending Skipper<span><br/><br/>New spectacular sunnies by ANNA-KARIN KARLSSON
			</span>
	</div>
</a>
<a title="KENZO" class="home--img--two" href="https://www.elitestore.es/kenzo/">
	<div class="home--img--left--text">
			TICK TOCK:<br/><br/>Get on KENZO time<span><br/><br/>The much awaited new collection is HERE!
			</span>
	</div>
</a>

<a title="PAUL SMITH" href="http://www.elitestore.es/paul-smith/" class="home--right--last" >
	<div class="home--right--last--text">
		<em>#INDEPENDENTMIND</em><br/><br/>PAUL SMITH<br/><br/><em>Tailored free-spirited attitude and<br/>individuality, inspired by independent minds.</em>
	</div>
</a>

<a title="Dsquared2" style="float:right;margin-bottom:10px"  href="http://www.elitestore.es/dsquared2?cat=23" class="home--left--last">
	<div class="home--left--triangle">
		<em>#DIAMONDHEAD</em><br/><br/>DSQUARED2<br/><br/><em>Sporty and seriously flirty. Created with <br/>surfing in Hawaii and couture in mind.</em>
	</div>
</a>