<?php 
            $_product = $this->getProduct();
            $categorias = $this->getCategoriasAptas($_product);
?>
	<div class="close">&#62134;</div>
    <div class="titulo"><?php echo $this->__('Size chart'); ?><span><?php echo $this->__('(Please notice that is a guide only and that measurements many vary according to brand and style)'); ?></span></div>
    <?php foreach ($categorias as $categoria): 
			echo $this->getTabla($categoria, $_product->getData('tallaje'));
    endforeach; ?>
	<div class="botonera">
		<div class="container">
			<div class="title"> <?php echo $this->__('Need help with sizing?');?></div>
			<a href="<?php echo Mage::getBaseUrl().'productcontact/index/form?id='.$this->getProduct()->getId(); ?>"><div class="imagenFlor">&#61999;</div><span><?php echo $this->__('Contact us');?></span></a>
            </div>
        </div>
    </div>
	
	<script type="text/javascript">
		jQuery('.botonera .container a').on('click', function(event){
			event.preventDefault();
			event.stopPropagation();
			jQuery(".modalwindow .border .content").html("<div class='close'>&#62134;</div><div class='loading'><span id='floatingCirclesG-content' class='frame sprite'></span><br/>Loading...</div>");
			var url=jQuery(this).attr('href');
			jQuery.ajax({
				type: "POST",
				url:url,
				data : {baseUrl: MAGE_STORE_URL},
			})
				.done(function(msg) {
				jQuery(".modalwindow .border .content").html(msg);
				})
				.fail(function() {
			  })
				.always(function() {
			  });
		});
	</script>