<?php
	
	$manufacturer = $this->getManufacturer();
	if($manufacturer):
		include("http://www.frivolidays.com/wp-config.php");
		$ruta='http://www.frivolidays.com/category/'.Mage::getModel('catalog/product_url')->formatUrlKey($manufacturer->getManufacturerMagentoName()).'/feed/';
		$feed = simplexml_load_file($ruta);
		if (count($feed->channel->item)>0): ?>
			<div class="blog-bloque">
				
				<?php 
				$i=1;
				foreach ($feed->channel->item as $item):
					if ($i==1):
						$title       = (string) $item->title;
						$description = (string) $item->description;
						$descripcion = substr($description,strpos($description,'<div class="home__blog--texto">')+31,strpos($description,'<a href="')-(strpos($description,'<div class="home__blog--texto">')+31));
						$link        = (string) $item->guid;
						$imagen      = substr($description,strpos($description,'src="')+5,strpos($description,'" class=')-(strpos($description,'src="')+5));
						
						$i++;
					endif;
				endforeach;
				?>	
				
				<a href="<?php echo $link; ?>">
					<div class="post">
						<div class="post-imagen"><img src="<?php echo $imagen; ?>"></div>
						<div class="post-titulo"><?php echo $title; ?></div>
						<div class="post-descripcion"><?php echo $descripcion; ?></div>
						
					</div>
				</a>
			</div>
				
<?php 
			
		endif;
	endif;
?>

