<?php
	
?>


<div class="top-bread"><div class="breadcrumbs">
    <ul>
                    <li>
                            <a href="<?php echo Mage::helper('core/url')->getHomeUrl()?>" title="Ir a la página de Inicio">HOME</a>
                                        <span> </span>
                    </li>
                    <li>
                            <a href="<?php echo Mage::getUrl('manufacturer',array('_secure'=>true))?>"><strong><?php echo $this->__('DESIGNERS') ?></strong></a>
                    </li>
	</ul>
                            
</div>                                        
</div>

<?php 
	
?>