<?php	
	$manufacturer = $this->getManufacturer();
	if($manufacturer):
		//Extraemos el nombre correcto
		
		$manufacturer=Mage::getModel('manufacturer/manufacturer')->loadDataManufacturer($manufacturer);
		$manufacturerName=$manufacturer->getManufacturerMagentoName();				
	?>
    <div class="page-title designer-title">
	    <h1><?php echo $manufacturerName;?></h1>
    </div>
	<?php if($manufacturer->getData('featured')!=0){ ?>
        <div class="designers__description">
            <div class="imagen-manufacturer--logotipo featured">
                 <?php echo $this->getImagemanufacturer2Image($manufacturer);?>  
            </div>
			<div class="designers__description--left">
				<div class="designers__description--title">
					<?php echo $manufacturer->getData('titulodesc1'); ?>
				</div>
				<p><?php echo $manufacturer->getData('descripcion1');?></p>
			</div>
            <div class="imagen-manufacturer">
             <?=$this->getManufacturerImage($manufacturer);?> 
               
            </div>
			<div class="designers__description--right">
				<div class="designers__description--title">
					<?php echo $manufacturer->getData('titulodesc2'); ?>
				</div>
				<p><?php echo $manufacturer->getData('descripcion2');?></p>
			</div>
		</div>     
        <a href="" class="addToDesigners"><?php echo $this->__('+ TO MY FAVOURITES DESIGNERS'); ?></a>
    <?php } else {?>
        <div class="designers__sort__description">
            <div class="imagen-manufacturer--logotipo">
				<div class="imagen-manufacturer--logotipo--center">
					<?php echo $this->getImagemanufacturer2Image($manufacturer);?>
				</div> 
            </div>
            <div class="designers__description--left">
                    <div class="designers__description--title">
                        <?php echo $manufacturer->getData('titulodesc1'); ?>
                    </div>
                        <?php echo $manufacturer->getData('descripcion1');?>
                    <?php echo "<br/><br/>";?>
                    <div class="designers__description--title">
                        <?php echo $manufacturer->getData('titulodesc2'); ?>
                    </div>
                        <?php echo $manufacturer->getData('descripcion2');?>
            </div>
            <div class="imagen-manufacturer" style="background: url('<?php echo $this->getManufacturerImageUrl($manufacturer);?>');">
            </div>
        </div>
    <?php } ?>
              
<?php 
endif;

?>

