<li class="level0 <?php if (Mage::app()->getStore()->getStoreId()==2) echo 'en'?> nav-10 level-top parent ">
	<a class="level-top" href="<?php echo Mage::getUrl('manufacturer'); ?>">
		<span><?php echo $this->__('Designers');  ?></span>
	</a>
	
    <ul class="level0 chield chield4">
		<li style="width:30%;" class="level1 nav-10-1 first parent">
            	<span><?php echo $this->__('Featured Designers') ?></span>
			<ul class="level1">
				<li class="level2 nav-10-1-1 first">
                	<a href="<?php echo Mage::getUrl('alexander-mcqueen') ?>">
						<span>Alexander McQueen</span>
					</a>
				</li>
              	<li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('balmain') ?>">
						<span>Balmain</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('carven') ?>">
						<span>Carven</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('charlotte-olympia') ?>">
						<span>Charlotte Olympia</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('dsquared2') ?>">
						<span>Dsquared2</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('emilio-pucci') ?>">
						<span>Emilio Pucci</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('giorgio-armani') ?>">
						<span>Giorgio Armani</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('givenchy') ?>">
						<span>Givenchy</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('kenzo') ?>">
						<span>Kenzo</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('lanvin') ?>">
						<span>Lanvin</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('moncler') ?>">
						<span>Moncler</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('pierre-hardy') ?>">
						<span>Pierre Hardy</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('versace') ?>">
						<span>Versace</span>
					</a>
				</li>
                <li class="level2 nav-10-1-2">
					<a href="<?php echo Mage::getUrl('victoria-beckham') ?>">
						<span>Victoria Beckham</span>
					</a>
				</li>
            </ul>
		</li>
		<li style="width:30%;" class="level1 nav-10-2 last parent">
			<a href="<?php echo Mage::getUrl('manufacturer') ?>">
				<span><?php echo $this->__('See All'); ?></span>
			</a>
		</li>
	</ul>
</li>