<?php
	
	$manufacturer = $this->getManufacturer();
	if($manufacturer && $manufacturer->getData('featured')):
		$manufacturerName=$manufacturer->getManufacturerMagentoName();
		$stringGeneros=explode(',',$manufacturer->getData('genero'));
		$generos=array();

		if (in_array('WOMEN',$stringGeneros)){
			$generos[]=1002;
		}
		if (in_array('MEN',$stringGeneros)){
			$generos[]=1072;
		}
		if (in_array('KIDS',$stringGeneros)){
			$generos[]=1139;
		}
		
		if (count($generos)>0 && $generos[0]!=''){
			?>
			<div class="designerssubLinks--content" id="designerssubLinksId">
			<?php 
			$i= 1;
			foreach ($generos as $genero):
					
					$categoriaGenero=Mage::getModel('catalog/category')->load($genero);
					$url=$this->getManufacturerDetailUrl($manufacturer).$categoriaGenero->getUrlPath();
					$categoriaNombre=strtoupper ($this->__('SHOP').' '.$manufacturerName.' '.$categoriaGenero->getName());
					?>
					<a class="designerssubLinks<?php echo $i; ?>" <?php if (count($generos)==$i) echo "id='designerssubLinksId'" . $i;?> href="<?php echo $url ?>"><?php echo $categoriaNombre?></a>
					
			<?php 
			$i++;
			endforeach;?>
			</div>
		<?php }	?>
    <div style="clear:both"></div>

	<?php endif; ?>
