<!-- AJAX price slider settings -->
<script type="text/javascript">
_collapse =  <?php echo (int)Mage::getStoreConfig('ajaxlist/frontend/collapse');?> ;
_horizontal_layered_navigation =  <?php echo (int)Mage::getStoreConfig('ajaxlist/frontend/horizontal_mode');?> ;
_use_priceslider =  <?php echo (int)Mage::getStoreConfig("ajaxlist/ajaxlist/use_priceslider") ;?> ;
_ajaxlist_parameter = "<?php echo Mage::helper("ajaxlist")->getAjaxParameter();?>";
_ajax_compare =  <?php echo (int)Mage::getStoreConfig("ajaxlist/ajaxcompare/enable") ;?> ;
</script>