<?php
    $_cartQty = $this->getSummaryCount();
    if(empty($_cartQty)) {
        $_cartQty = 0;
    }
?>

<a href="<?php echo $this->helper('checkout/cart')->getCartUrl(); ?>" data-target-element="#header-cart" class="skip-link skip-cart <?php if($_cartQty <= 0): ?> no-count<?php endif; ?>">
    <span class="icon">
        &#8800;
    </span>
    <!--<span class="label"><?php echo $this->__('Cart'); ?></span>-->
    <span class="count"><?php echo $_cartQty; ?></span>
</a>