
<?php $footerbox2 = Mage::getModel('cms/block')->load('rt001-footer-box2'); ?> 
<?php $footerbox4 = Mage::getModel('cms/block')->load('rt001-footer-box4'); ?> 
<footer>
<?php if(!Mage::helper('mobiledetect')->isMobile()){ ?>
	<!--version desktop-->
	<footer class="desktop">
		<div class="footer--container">	   


		<div class="footer__left--left">
				<div class="foother--grid_1">
					<ul>
						<li><a href="<?php echo $this->getUrl('our-story')?>"><?php echo $this->__('OUR STORY');?></a></li>
                        <li><a href="<?php echo $this->getUrl('customer-service')?>"><?php echo $this->__('CUSTOMER CARE');?></a></li>
						<li><a href="<?php echo $this->getUrl('our-stores')?>"><?php echo $this->__('OUR STORES');?></a></li>						
						<li><a href="<?php echo $this->getUrl('gift-card-multi.html')?>"><?php echo $this->__('GIFT CARD');?></a></li>
					</ul>    
				</div>
		</div>

		<div class="footer__right--left">
				<div class="foother--grid_4">
					<!--<h4><?php echo $footerbox4->getTitle(); ?></h4>-->
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('rt001-footer-box4')->toHtml() ?>  
				</div>
		</div>
		<div class="footer__right--right">
				<div class="foother--grid_5">
					<?php echo $this->getChildHtml("suscribenewsletter"); ?>
				</div>
		</div>

		</div>
		<div class="grid_copy">
			<div class="footer--copy">
				&#169;<?php echo $this->__('2012-2017 ELITE');?>
				<a href="<?php echo $this->getUrl('privacy');?>">
					<div class="footer--copy--left">
						<?php echo $this->__('Privacy & Legal');?>
					</div>
				</a>
			</div>
		</div>
	</footer>        
	<!--fin de la version desktop-->
<?php }else{ ?>
	<!-- version mobile-->
	<footer class="mobile">
		<dl class="acordeon">
			<dt><?php echo  $this->__('SHIPPING TO')?></dt>
				<dd id="paises-mobile" style="display:block">
						<?php echo $this->getChildHtml("footer-zone") ?>
						<?php echo $this->getChildHtml("top-currency-mobile2") ?>
						<?php echo $this->getChildHtml("top-languages-mobile2") ?>
				</dd>
			
			<dt><?php echo  $this->__('GET HOOKED')?></dt>
			<dd style="display: none;"><?php echo $this->getChildHtml("suscribenewsletter"); ?></dd>


			<dt><?php echo  $this->__('STAY TUNED')?></dt>
			<dd style="display: none;"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('rt001-footer-box4')->toHtml() ?></dd>

			<dt><?php echo  $this->__('CUSTOMER CARE')?></dt>
			<dd style="display: none;">
				<a class="productcontact-link" href="<?php echo $this->getUrl('contactus')?>"><?php echo  $this->__('CUSTOMER CARE')?></a>

				<a class="productcontact-link" href="<?php echo $this->getUrl('gift-card-multi')?>'"><?php echo  $this->__('GIFT CARD')?></a>
			</dd>

			<dt><?php echo  $this->__('OUR STORES')?></dt>
			<dd style="display: none;">
				<a class="productcontact-link" href="<?php echo $this->getUrl('our-stores')?>"><?php echo  $this->__('OUR STORES')?></a>
				<a class="productcontact-link" href="<?php echo $this->getUrl('our-story')?>"><?php echo  $this->__('OUR STORY')?></a>
			</dd>

			<dt><?php echo  $this->__('PRIVACY & LEGAL')?></dt>
			<dd style="display: none;">
				<a class="productcontact-link" href="#"><?php echo  $this->__('PRIVACY')?></a>
				<a class="productcontact-link" href="#"><?php echo  $this->__('COPYRIGHT')?></a>
			</dd>
		</dl>
	</footer>    
	<!--fin de la version mobile-->	
<?php } ?>
</footer>  
<?php echo $this->getChildHtml("popup-search") ?>

<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'sticky/sticky-kit.js';?>"></script>

<script type="text/javascript">
    jQuery("#floatingCirclesG-content").sprite({ fps: 12, no_of_frames: 12, rewind: true });
    jQuery("#floatingCirclesG").sprite({ fps: 12, no_of_frames: 12, rewind: true });
</script>