          <!--insertamos el selector de idiomas-->
          <div class="zone-switch">
               <?php echo $this->getChildHtml('top-zone') ?>
          </div>
          <!--insertamos el selector de monedas-->
          <div class="currency-switch">
            <?php echo $this->getChildHtml('top-currency') ?>
          </div>
          <!--insertamos el selector de monedas-->
          <div class="language-switch">
            <?php echo $this->getChildHtml('top-languages') ?>
          </div>