<header>
<?php 
	$movil=Mage::helper('mobiledetect')->isMobile();
	if (!$movil){ ?>
		  <div class="header--content">
			  <!-- LOGO -->

			
				<?php echo $this->getChildHtml('logo') ?>
				
				
			  <div class="header--content--left">		
				<?php echo $this->getChildHtml("headerLeftCabecera") ?>
			  </div>  
			  <div class="header--content--right">
				  <?php echo $this->getChildHtml('headerRightCabecera') ?>   
			  </div>
		  </div>
		  <?php echo $this->getChildHtml('topMenu') ?>
	<?php }else{ ?>
		  <div class="header--content-mobile">
			<?php echo $this->getChildHtml('header-left-mobile') ?>
			<?php echo $this->getChildHtml('logo-mobile') ?>
			<?php echo $this->getChildHtml('header-right-mobile') ?>
		  </div>
	<?php } ?>		
</header>
<?php echo $this->getChildHtml('header-offers') ?>