<?php
	//$catsale = array(1150,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1447);
	//$catout = array(1299,1369,1436);
$catsale = array(-1);
$catout = array(-1);

	$aguja = Mage::getSingleton('catalog/layer')->getCurrentCategory()->getId();
	if (in_array($aguja,$catsale)) 
	{
		?>
		<div class="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'banners/' . Mage::getStoreConfig('weboptions/opciones/sale_logo_img_url') ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></div>
		<?php
	}
	elseif (in_array($aguja,$catout)) 
	{
		?>
		<div class="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'banners/' . Mage::getStoreConfig('weboptions/opciones/outlet_logo_img_url') ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></div>
		<?php
	}
	else{
		?>
		<div class="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></div>
		<?php
	}
	