<div class="rslides--container">	
	<ul class="rslides">
	  	<li>
		  <img src="<?php echo Mage::getBaseUrl('media') ."banners/". Mage::getStoreConfig('home/slider/slider1_img_url');?>" alt=""/>
			<?php echo Mage::getStoreConfig('home/slider/slider1_content');?>
		</li>
	  	<li>
	  		<img src="<?php echo Mage::getBaseUrl('media') ."banners/". Mage::getStoreConfig('home/slider/slider2_img_url');?>" alt=""/>
			<?php echo Mage::getStoreConfig('home/slider/slider2_content');?>
		</li>
	  	<li>
	  		<img src="<?php echo Mage::getBaseUrl('media') ."banners/". Mage::getStoreConfig('home/slider/slider3_img_url');?>" alt=""/>
			<?php echo Mage::getStoreConfig('home/slider/slider3_content');?>
	  </li>
	</ul>
</div>