<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
$store_id = Mage::app()->getStore()->getStoreId();
$locale = Mage::app()->getLocale()->getLocaleCode();
?>

<?php $_menu = $this->getHtml('level-top') ?>
<?php if($_menu): ?>
<div class="bloque-menus">
    <div class="nav-container  <?php echo $locale;?>" id="contenedor">
            
			<div class="nav-container__limit">
				<!-- Insertamos logo pequeño para cabecera reducida -->
				<h1 class="logo_mini">
                    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getTitle() ?>">
                        &#61998;
                    </a>
                </h1>
				
				<!-- Insertamos con Js bloque Header Right -->
                <div class="header--content--right2">
				</div>
				
				
                <div id="contenedormenu">
					<?php echo $this->getChildHtml('menuPpal') ?>
                </div>
            </div>
			
    	</div>
</div>
<?php endif ?>
