<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<dl class="acordeon" >
	<dt class="desplegado"><?php echo $this->__('ITEM DETAILS') ?></dt>
	<dd style="display:block"><?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?><dd>
	<?php if($_product->getSku()!="giftcardmulti"){?>
		<dt><?php echo $this->__('COMPOSITION') ?></dt>
	<?php } ?>
	<dd><?php echo $_helper->productAttribute($_product, nl2br($_product->getComposicion()), 'composicion') ?><dd>
	<dt><?php echo $this->__('SHIPPING') ?></dt>
	<dd><?php echo $this->getShippingInfo(); ?> <a href="<?php echo Mage::getUrl('customer-service');?>"><?php echo $this->__('Click here for more info.') ?></a></dd>
	
	<?php 
	
	$restriccions= $this->getShippingRestrictions();
	if ($restriccions!=""){ 
	?>
		<dt><?php echo $this->__('SHIPPING RESTRICTIONS') ?></dt>
		<dd><?php echo $restriccions; ?> <a href="<?php echo Mage::getUrl('customer-service');?>"><?php echo $this->__('Click here for more info.') ?></a><dd>
	<?php
	}
	?>
	
	<dt><?php echo $this->__('EASY RETURNS') ?></dt>
	<dd><?php echo $this->getReturnsInfo(); ?> <a href="<?php echo Mage::getUrl('customer-service');?>"><?php echo $this->__('Click here for more info.') ?></a><dd>
	<dt><?php echo $this->__('NEED MORE INFO?') ?></dt>
	<dd><?php echo $this->getChildHtml('product-contact'); ?><br><span>Give us a call: + 34 951 31 97 38 (Monday to Friday, 9.30 - 18.00 CET, except Bank Holidays)</span><dd>
</dl>

<div class="titulo-tabs">
	<?php $productName = $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
	<?php $productUrl = $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>
	<?php $productImage = $_product->getImageUrl() ?>
	<p id="p-sin">
		<a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($productUrl); ?>&t=<?php echo urlencode($productName); ?>'" title="<?php echo $this->__('Share on Facebook') ?>">&#xf09a;</a>
		<a href="http://twitter.com/home/?status=<?php echo urlencode($productName . ' (' . $productUrl . ')'); ?>'" title="<?php echo $this->__('Tweet') ?>">&#xf099;</a>
        <!--<a href="https://instagram.com/pin/create/button/?url=<?php echo urlencode($productUrl); ?>&media=<?php echo urlencode($productImage); ?>&description=<?php echo urlencode($productName); ?>" title="<?php echo $this->__('Pin it') ?>">&#xf16d;</a>-->
		<a href="https://pinterest.com/pin/create/button/?url=<?php echo urlencode($productUrl); ?>&media=<?php echo urlencode($productImage); ?>&description=<?php echo urlencode($productName); ?>" title="<?php echo $this->__('Pin it') ?>">&#xf0d2;</a>
		<a href="https://plus.google.com/share?url=<?php echo urlencode($productUrl); ?>'" title="<?php echo $this->__('Share on Google Plus') ?>">&#xf0d5;</a>
        <?php echo $this->getChildHtml("share-via-email")?>
	</p>
</div>