<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php $_layout = themeOptions('layout'); ?>
<?php $enable_ajax = themeOptions('enable_ajax');

//Texto añadido para comprobar repositorio

 ?>

<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<a class="back-to" href="javascript: history.go(-1)"><?php echo $this->__('Return to Previous Page') ?></a>
        
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view layout_<?php echo $_layout ?>">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
        <div id="addedoverlay" style='display:none'> </div>
        <div id='added' style='display:none'></div>
        <div class="product-shop">
            <div class="white-back"> 
                <div class="product-name">
                    <h1><?php 
					
					echo mb_strtolower($_helper->productAttribute($_product, $_product->getName(), 'name'),'UTF-8') ?></h1>
					<?php $producto = Mage::getModel('catalog/product')->load($_product->getId());	?>
                    
					<?php 
					  
						$manufacturers = Mage::getModel('manufacturer/manufacturer')->getManufacturers('');
						$urlManufacturer="";
						$_attribute= $_product->getResource()->getAttribute('manufacturer');
					  	$_options= $_attribute->getSource()->getAllOptions(true, true);
						foreach($_options as $option)
      						if ($option['value'] == $_product->getData('manufacturer'))
          					$nameManufacturer=$option['label'];
						foreach ($manufacturers as $manufacturer){
							if ($manufacturer->getName()==$nameManufacturer){
									 $urlManufacturer = Mage::getUrl($manufacturer->getUrlKey(), array());
						}}
					
					?>
                    
					
					<?php echo "<p class=\"manufacturer-productview\"><a href=\"".$urlManufacturer."\">".mb_strtolower($producto->getAttributeText('manufacturer'),'UTF-8')."</a></p>"; ?>
					<?php if ($producto->getAttributeText('pre_order_item')!='No'):?>
                    	<div class="pre-order-item-view"><?php echo $this->__('PRE-ORDER ITEM')?></div>
                    <?php  endif; ?>
                    <?php echo "<p class=\"ref-prov\">".$_helper->productAttribute($_product, $_product->getRefproveedor(), 'refproveedor')."</p>";?>
					
                </div> <!-- PRODUCT NAME, MANUFACTURER, REF-->
                
              
                 <?php //echo $this->getReviewsSummaryHtml($_product, false, true)?>
                <?php echo $this->getChildHtml('alert_urls') ?>
                <?php echo $this->getChildHtml('extrahint') ?>
                <?php if($_product->getTypeId() != 'bundle'): ?>
                	<?php if ($_product->getSku()!='AQ2659'):?>
                    	<?php echo $this->getPriceHtml($_product); ?>
                    <?php endif; ?>
                <?php else: ?>
                    <?php echo $this->__('Product code:').'<strong>'.$_product->getId().'</strong>'; ?>
                    <?php echo $this->getChildHtml('product_type_data') ?>
                <?php endif;?> 


                <!-- PRICE BOX -->
                
                <div class="addtocont">
                    <?php /*
						Eliminado para que no salga Product Code y Avaliability
						if($_product->getTypeId() != 'bundle'): ?>
                        <span class="product-code"><?php //echo $this->__('Product code:').' <strong>'.$_product->getId().'</strong>'; ?></span>
                        <?php echo $this->getChildHtml('product_type_data') ?>
                    <?php endif;?>
                    <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('productview')->toHtml(); */?>
					
                </div>	 <!-- ADDTOCONT -->
				
                <div class="clear"></div>
				<?php echo $this->getTierPriceHtml() ?>
                
                
                
                
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <div id="container1"><?php echo $this->getChildChildHtml('container1', '', true, true) ?><div class="clear"></div></div>
                <?php endif;?>   <!-- CONTAINER 1 -->
                
                <?php echo $this->getChildHtml('product_type_data_grouped') ?>
                <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                            <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                <span class="or"><?php echo $this->__('OR') ?></span>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                <?php endif; ?>  
                
                
                <div class="clearer"></div>	
                
        <?php $nostock=false; ?>
              			
        <?php if ($_product->isSaleable() && $this->hasOptions()):
				   if ($producto->getSku()=='AQ4832'): 
					 	$nostock=true; ?>
                        <div class="out-of-stock"><?php echo $this->__('Out of Stock')?></div> 
                	<?php elseif (($_product->getAttributeText('no_shop_button')=='No')):?>
                    <?php if ($_product->getSku()!='AQ2659'):?>
            			<div id="container2"><?php echo $this->getChildChildHtml('container2', '', true, true) ?></div>
                    <?php endif; ?>
             <?php else: ?>
			   		<div class="order-by-request"><?php echo $this->getChildHtml('other2');?></div>
			 <?php endif;?>                                 
        <?php else:?>

            <?php if (!($producto->getFinalPrice()<$producto->getPrice()) && ($producto->getTipo()=='152' || $producto->getTipo()=='1000')) :?>
                <div class="order-by-request"><?php echo $this->getChildHtml('other2');?></div>
            <?php else:
				$nostock=true; ?>
                <div class="out-of-stock"><?php echo $this->__('Out of Stock')?></div>
            <?php endif; ?>
            
        <?php endif;?>	 <!-- CONTAINER 2 -->
        </form>
                
                
                
                
                <?php if ($nostock): ?>
                        	<?php 
							$categories = $producto->getCategoryIds();
							foreach($categories as $categoryId){
		    					$_category = Mage::getModel('catalog/category')->load($categoryId);
    							$categoryData = $_category->getData();
								if($categoryData['level']==2){
									switch ($_category->getId()){
										case 23:
											$category_surname=$this->__("for women");
											break;
										case 62:
											$category_surname=$this->__("for men");
											break;
										case 122:
											$category_surname=$this->__("for kids");
											break;
										case 101:
											$category_surname="";
											break;
									}
								}
    							if($categoryData['level']==4){
        							$currentCategory = $_category;
        							break;
    							}
							}
							
							if (Mage::app()->getStore()->getStoreId()==2 || Mage::app()->getStore()->getStoreId()==3){
								$designer_prefix="";
								$designer_sufix=$this->__(' items');
							
							}else{
								$designer_prefix=$this->__('articulos de ');
								$designer_sufix="";
							}
							$category_name=ucfirst(mb_strtolower($currentCategory->getName(),'UTF-8'))." ".$category_surname;	
							$category_url=$currentCategory->getUrl();
							$designer_name=$designer_prefix.ucfirst(mb_strtolower($producto->getAttributeText('manufacturer'),'UTF-8')).$designer_sufix;
							$designer_url=$urlManufacturer;							
							?>
                        
                            <p><?php echo $this->__("This item is out of stock and we can't restock because it belongs to past season.<br/> You can <span style='font-weight:bold;color:red'>find similar items</span> in stock in any of these sections:")?></p>
                            	<ul class="out-of-stock-list">
                                <li><a style="text-transform:none;" href="<?php echo $category_url ?>"><?php echo ($this->__('See More ').$category_name)?></a></li>
                                <li><a style="text-transform:none;" href="<?php echo $designer_url ?>"><?php echo ($this->__('See More ').$designer_name)?></li>
                            
                            </ul>
				<?php else: ?>	
                
                                
                <div class="acordeon">
                    		<dl class="acordeon-datos">
                        
                        
                        <?php
							if($_product->getSku()=='AQ2659'){ // Si tiene descripcion adicional
						?>		
                        	<dt class="activo"><?php echo $this->__('Auction Conditions:') ?></dt>
                        
                        	<dd>
                            	<p><?php echo $this->__('ELITE Marbella and Gran Calibre, S.L. are pleased to announce that one pair of the coveted Adidas Yeezy Boost 350 Black by Kanye West (size 8.5) will be auctioned in support of UNICEF&acute;s Nepal Earthquake Appeal.') ?></p>
<p><?php echo $this->__('The 100 percent of the amount from the auction sale will be donated to UNICEF in order to help children in Nepal.')?></p>
					
								<span style="text-align:center;"><b><a href="/auction-condition" rel="shadowbox[product];width=500px;height=500px;"><?php echo $this->__('Auction Condition')?></a></b></span>

							</dd>
                        <?php
                        	}
						?>
                        
                            
                        
                            
                        <?php
							if($producto->getShortDescription()){ // Si tiene descripcion adicional
						?>		
                        	<dt class="activo"><?php echo $this->__('Quick Overview:') ?></dt>
                        
                        	<dd>					
								<span><?php echo $producto->getShortDescription()?></span> 
							</dd>
                        <?php
                        	}
						?>
                         
                         
                         <?php
							if($producto->getAttributeText('has_video')!='No'){ // Si tiene Video
						?>		
                        	<dt class="activo"><?php echo $this->__('Video:') ?></dt>
                        
                        	<dd>
                            	<style>.video-container {position:relative;padding-bottom:56.25%;padding-top:30px;height:0;overflow:hidden;}.video-container iframe, .video-container object, .video-container embed {position:absolute;top:0;left:0;width:100%;height:100%;}
                                </style>					
								
                                <div class="video-container"><iframe type="text/html" src="http://www.youtube.com/embed/<?php echo $producto->getVideoUrl() ?>?rel=0&autoplay=1" frameborder="0"></iframe></div> 
							</dd>
                        <?php
                        	}
						?>
                         
                         
                         
                        	<dt><?php echo $this->__('Composition:') ?></dt>
                        	<dd><?php echo $producto->getCampoDos() ?></dd>
                        <?php if ($producto->getAttributeText('pre_order_item')!='No'):?>
							<dt class="activo"><?php echo $this->__('PRE-ORDER INFO:') ?></dt>
                        	<dd><?php echo $this->__('PRE-ORDER items are advance of next seasons collection and will be delivered in the estimated date indicated in each case. Pre-orders are treated as FINAL SALE and must be paid in full at the time of order completion.'); ?> <a href="<?php echo Mage::getBaseUrl()?>pre-order-policy"><?php echo $this->__('Click here for more info.') ?></a></dd>
   						<?php  endif;
						if ($producto->getAttributeText('no_shop_button')!='No'):?>
							<dt class="activo"><?php echo $this->__('ORDER BY REQUEST INFO:') ?></dt>
                        	<dd><?php echo $this->__('This item is not available at the moment but if you are interested in we can try to get it for you. Give us your contact details and inform you every step of the process as soon as possible.')?> <a href="/orderrequest?id=<?php echo $producto->getId()?>" rel="shadowbox;width=728 height=700;scroll=none"><?php echo $this->__('Click here to start the process.') ?></a></dd>
						
						<?php endif;
						?>
                        <?php $categorias= $_product->getCategoryIds();
						if (in_array('23',$categorias)){ //Si pertenece a la categoría mujer
							if (in_array('24',$categorias)){ //Si pertenece a la categoría mujer-->ropa
						?>
							<dt><?php echo $this->__('Size Info:') ?></dt>
							<dd><ul>
									<li><?php echo $this->__('Type Sizing:') ?> <strong><?php echo $producto->getCampoNueve() ?></li></strong>
									<li><a href="<?php echo Mage::getBaseUrl()?>tabla-tallas-ropa-mujer" rel="shadowbox;width=780;height=300"><?php echo $this->__('See Size Chart') ?></a></li>
								</ul>
							</dd>
                      	<?php 
							}else if(in_array('59',$categorias)){ //Si pertenece a la categoría mujer-->zapatos
						?>
							<dt><?php echo $this->__('Size Info:') ?></dt>
							<dd><ul>
									<li><?php echo $this->__('Type Sizing:') ?><?php echo $producto->getCampoNueve() ?></li>
									<li><a href="<?php echo Mage::getBaseUrl()?>tabla-tallas-zapatos-mujer" rel="shadowbox;width=880;height=300"><?php echo $this->__('See Size Chart') ?></a></li>
								</ul>
							</dd>
                      	<?php		
							}
						}else if(in_array('62',$categorias)){//Si pertenece a la categoría hombre
							if (in_array('63',$categorias)){//Si pertenece a la categoría hombre-->ropa
						?>
							<dt><?php echo $this->__('Size Info:') ?></dt>
							<dd><ul>
									<li><?php echo $this->__('Type Sizing:') ?><?php echo $producto->getCampoNueve() ?></li>
									<li><a href="<?php echo Mage::getBaseUrl()?>tabla-tallas-ropa-hombre" rel="shadowbox;width=780;height=300"><?php echo $this->__('See Size Chart') ?></a></li>
								</ul>
							</dd>
                      	<?php
							}else if (in_array('92',$categorias)){//Si pertenece a la categoría hombre-->zapatos
						?>
							<dt><?php echo $this->__('Size Info:') ?></dt>
							<dd><ul>
									<li><?php echo $this->__('Type Sizing:') ?><?php echo $producto->getCampoNueve() ?></li>
									<li><a href="<?php echo Mage::getBaseUrl()?>tabla-tallas-zapatos-hombre" rel="shadowbox;width=960;height=300"><?php echo $this->__('See Size Chart') ?></a></li>
								</ul>
							</dd>
                      	<?php
								}
						}
							
						?>
                        	<dt><?php echo $this->__('Shipment Info:') ?></dt>
                        	<dd><span><?php echo $this->__('Elite ships worldwide. The shipping cost will be calculated at the checkout. You will have free shipping if your order is 500 &euro; or more. You can track your order at any time, once it has been shipped. ')?></span><a href="<?php echo Mage::getBaseUrl()?>shipment-information/"><?php echo $this->__('Click here for more info.') ?></a>
                        	</dd>
                        <?php $marcas_gafas_restriccion= array('Adidas by Italia Independent','Alexander McQueen','Coco and Breezy','Etnia Barcelona', 'Gentle Monster', 'Givenchy', 'Grey Ant', 'Italia Independent', 'Kyme', 'Lanvin', 'Linda Farrow', 'Rare', 'Vintage Frame by Corey Shapiro', 'Vuarnet');
						
						if (in_array('225',$categorias) && in_array($producto->getAttributeText('manufacturer'),$marcas_gafas_restriccion)){  //Si pertenece a la categoria Gafas y está en el listado de Marcas restringidas.?>
                        	<dt class="activo"><?php echo $this->__('Shipment Restrictions:') ?></dt>
                        	<dd><span><?php echo $this->__('US Customs authorities does not allow the sale of this item in the <strong>United States</strong>, so Elite decided <strong>not send this article to any destination within the US territory</strong>. Sorry for the inconvenience.')?></span>
                        	</dd>
                        <?php } ?>
                        
                        <?php 
                        	$paiseMX = array ('MX'); 
                        	$paisCustomer = Mage::getSingleton('geoip/country')->getCountry();

                        if ((in_array('59',$categorias) || in_array('92',$categorias) || in_array('150',$categorias)) && in_array($paisCustomer,$paiseMX)){  //Si pertenece a la categoria zapatos en mujer, hombre, niño y a su vez el cliente es de mexico?>
                        	<dt class="activo"><?php echo $this->__('Shipment Restrictions:') ?></dt>
                        	<dd><span><?php echo $this->__('Mexico does not permit foreign importers of shoes to enter therefore Elite is not allowed to send this kind of product to the country.')?></span>
                        	</dd>
                        <?php } ?>
                        
						<?php $paisesUE = array ('DE','AT','BE','BG','CY','HR','DK','SK','SI','ES','EE','FI','FR','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','UK','CZ','RO','SE','GB'); ?>
						    <?php $paisCustomer = Mage::getSingleton('geoip/country')->getCountry(); ?>

						    <?php 						    
						    if (in_array('102',$categorias) && ! in_array($paisCustomer,$paisesUE)){  //Si pertenece a la categoria Perfumes?>
                        	<dt class="activo"><?php echo $this->__('Shipment Restrictions:') ?></dt>
                        	<dd><span><?php echo $this->__('Customs authorities in some countries can find problems with composition of this item, so Elite decided not send this kind of items outside of European Union. If you want we ship this item to another country please contact previously with us. ')?></span><a href="<?php echo Mage::getBaseUrl()?>contact"><?php echo $this->__('Click here.') ?></a>
                        	</dd>
                        <?php } ?>
                        	<dt><?php echo $this->__('Return Info:') ?></dt>
                        	<dd><span><?php echo $this->__('If you are not satisfied with your purchase, the item(s) can be returned for a size exchange, a store credit or a refund within the 14 days after the order is delivered. ')?></span><a href="<?php echo Mage::getBaseUrl()?>return-policy"><?php echo $this->__('Click here for more info.') ?></a>
                        	</dd>
                            <dt><?php echo $this->__('More Info:') ?></dt>
                        	<dd><?php echo $this->getChildHtml('other');?></dd>        
                        	

                        	
                    	</dl>
                </div> <!-- ACORDEON -->
                <?php endif; ?>
                <?php if($_layout == 'horizontal'): ?>
                    <div class="clear"></div> 
                    <?php $use_share = themeOptions('use_share'); ?>
                    <?php $share_code = themeOptions('share_code'); ?>
                    <?php if($use_share && $share_code): ?>  
                        <?php echo $share_code; ?>
                    <?php endif; ?>
                <?php endif; ?>  
                
               
            </div>
            <?php if($_layout != 'horizontal'): ?>
                <div class="product_right">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('productview')->toHtml(); ?>
                    <?php $use_share = themeOptions('use_share'); ?>
                    <?php $share_code = themeOptions('share_code'); ?>
                    <?php if($use_share && $share_code): ?>  
                        <?php echo $share_code; ?>
                    <?php endif; ?>
                </div> 
            <?php endif; ?> <!-- PRODUCT RIGHT -->
        </div> <!-- PRODUCT BOX -->

        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>
        
		


        
    
    <?php if($enable_ajax): ?>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
		var url = jQuery('#product_addtocart_form').attr('action');
		url = url.replace("checkout/cart","ajax/index");    

        var msgHtml;
        var productImg = jQuery('.main-thumbnail').html();
        var windowOver = jQuery('#addedoverlay');
        var windowBox = jQuery('#added');
        var titleForBox = jQuery('#productname').text();   
        var data = {'isAjax':1}
        
        jQuery('#product_addtocart_form').ajaxForm({
            url: url,
            data: data,
            dataType: 'json',
            beforeSubmit: function(){    
                if(productAddToCartForm.validator.validate()){
                    windowOver.show();
                    windowBox.show().css({
                        backgroundImage: "url('<?php echo $this->getSkinUrl('images/loading.gif')?>')"
                    });                    
                }else{
                    return false;
                }
            },
            error: function(data){
	            windowBox.css({
       			      backgroundImage: 'none'
                }).html('<?php echo $this->__('Error') ?>');					   
                windowOver.one('click',function(){
		            hidewindow(windowBox,windowOver);                    
                });	       
                                 
                jQuery('#hidewindow').click(function(){
		            hidewindow(windowBox,windowOver);                    
                });
            },
            success : function(data,statusText,xhr ){
                if(data.status == 'SUCCESS'){
                    if(jQuery('.block-cart')){
                        jQuery('.block-cart').replaceWith(data.sidebar);
                    }
                    if(jQuery('.header .block-cart-header')){
                        jQuery('.header .block-cart-header').replaceWith(data.topcart);
                    }     
                    msgHtml = '<div class="added-content"><div style="float:left;">' + productImg + '</div><em>' + titleForBox + '</em> <?php echo $this->__('was successfully added to your shopping cart.') ?><div style="clear:both;"></div><a id="hidewindow" href="javascript:void(0);"><?php echo $this->__('Continue shopping') ?></a>&nbsp;<a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('View cart & checkout') ?></a></div>';             
                }else{
                    msgHtml = '<div class="added-content"><p class="error-msg" style="margin-bottom:15px;">' + data.message + '</p><a id="hidewindow" href="javascript:void(0);"><?php echo $this->__('Continue shopping') ?></a>&nbsp;<a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('View cart & checkout') ?></a></div>';
                }					   
               
                windowBox.css({
       			      backgroundImage: 'none'
                }).html(msgHtml);					   
                windowOver.one('click',function(){
    	            hidewindow(windowBox,windowOver);                    
                });	       
                                 
                jQuery('#hidewindow').click(function(){
    	            hidewindow(windowBox,windowOver);                    
                });	   
            }
        }); 
        
        function hidewindow(windowBox,windowOver){
            windowOver.fadeOut(400);
            windowBox.fadeOut(400).html('');	
        }

    //]]>
    </script>
    <?php else: ?>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    <?php endif; ?>
    </div>

    <div id="product-collateral" class="product-collateral">
        <?php //echo $this->getChildHtml('info_tabs') ?>
        <?php //echo $this->getChildHtml('product_additional_data') 
		//Se volverán a poner en un futuro, pero en el diseño inicial se eliminan
	 ?>
    </div>
        <?php echo $this->getChildHtml('related_products') ?>
        <?php echo $this->getChildHtml('upsell_products') ?>
</div>


<script>
var $j=jQuery.noConflict();	

	
    $j(document).ready(function() {
		$j('dl.acordeon-datos dd').not('dt.activo + dd').hide();
		$j('dl.acordeon-datos dt').click(function(){
		  
          if ($j(this).hasClass('activo')) {
               $j(this).removeClass('activo');
               $j(this).next().slideUp();
          } else {
               $j('dl.acordeon-datos dt').removeClass('activo');
               $j(this).addClass('activo');
               $j('dl.acordeon-datos dd').slideUp();
               $j(this).next().slideDown();
          }
       });
		/*$j('dl.acordeon-datos dt').click(function() {
    		$j('dl.acordeon-datos dd').slideToggle(400);
    		$j(this).next().slideToggle(400);
    		return false;
    		});
		$j('dl.acordeon-datos dd').hide();
		$j('dl.acordeon-datos dd.activo').show();*/
       });
	$j(document).ready(function() {
		$j('dl.acordeon-datos dd li').click(function(){
				var $span = 'dl.acordeon-datos dd span.titulo'+$j(this).attr('id').substring(5);
//				alert ('ocultar: '+$span);
				if ($j($span).is(":visible")){
					 $j($span).hide("slow");
				}else{
					 $j($span).show("slow");
				}
				for (var i = 1; i < 23; i++){
					var $span2 = 'dl.acordeon-datos dd span.titulo'+i;

					if ($span!=$span2){
//					alert('mostrar:'+$span2);
						$j($span2).show("slow");
					}
				}
		});
	});
	
</script>

