<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php $_layout = themeOptions('layout'); ?>
<?php $enable_ajax = themeOptions('enable_ajax');

//Texto añadido para comprobar repositorio

 ?>

<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<a class="back-to" href="javascript: history.go(-1)"><?php echo $this->__('Return to Previous Page') ?></a>
        
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view layout_<?php echo $_layout ?>">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
        <div id="addedoverlay" style='display:none'> </div>
        <div id='added' style='display:none'></div>
        <div class="product-shop">
            <div class="white-back"> 
                <div class="product-name">
                    <h1><?php 
					
					echo mb_strtolower($_helper->productAttribute($_product, $_product->getName(), 'name'),'UTF-8') ?></h1>
					<?php $producto = Mage::getModel('catalog/product')->load($_product->getId());	?>
                    
					<?php 
					$manufacturers = Mage::getModel('manufacturer/manufacturer')->getManufacturers('');
						foreach ($manufacturers as $manufacturer){
							if ($manufacturer->getName()==$producto->getAttributeText('manufacturer')){
									 $urlManufacturer = Mage::getUrl($manufacturer->getUrlKey(), array());
						
						}}
						
					?>
                    
					
					<?php echo "<p class=\"manufacturer-productview\"><a href=\"".$urlManufacturer."\">".mb_strtolower($producto->getAttributeText('manufacturer'),'UTF-8')."</a></p>"; ?>
					<?php if ($producto->getAttributeText('pre_order_item')!='No'):?>
                    	<div class="pre-order-item-view"><?php echo $this->__('PRE-ORDER ITEM')?></div>
                    <?php  endif; ?>
                    <?php echo "<p class=\"ref-prov\">Ref: ".$_helper->productAttribute($_product, $_product->getRefproveedor(), 'refproveedor')."</p>";?>
					
                </div> <!-- PRODUCT NAME, MANUFACTURER, REF-->
               
				
                 <?php //echo $this->getReviewsSummaryHtml($_product, false, true)?>
                <?php echo $this->getChildHtml('alert_urls') ?>
                <?php echo $this->getChildHtml('extrahint') ?>
                <?php if($_product->getTypeId() != 'bundle'): ?>
                    <?php echo $this->getPriceHtml($_product); ?>
                <?php else: ?>
                    <?php echo $this->__('Product code:').'<strong>'.$_product->getId().'</strong>'; ?>
                    <?php echo $this->getChildHtml('product_type_data') ?>
                <?php endif;?> <!-- PRICE BOX -->
                
                <div class="addtocont">
                    <?php /*
						Eliminado para que no salga Product Code y Avaliability
						if($_product->getTypeId() != 'bundle'): ?>
                        <span class="product-code"><?php //echo $this->__('Product code:').' <strong>'.$_product->getId().'</strong>'; ?></span>
                        <?php echo $this->getChildHtml('product_type_data') ?>
                    <?php endif;?>
                    <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('productview')->toHtml(); */?>
					
                </div>	 <!-- ADDTOCONT -->
				
                <div class="clear"></div>
				<?php echo $this->getTierPriceHtml() ?>
                
                
                
                
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <div id="container1"><?php echo $this->getChildChildHtml('container1', '', true, true) ?><div class="clear"></div></div>
                <?php endif;?>   <!-- CONTAINER 1 -->
                
                <?php echo $this->getChildHtml('product_type_data_grouped') ?>
                <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                            <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                <span class="or"><?php echo $this->__('OR') ?></span>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                <?php endif; ?>  
                
                
                <div class="clearer"></div>				
        		<?php if ($_product->isSaleable() && $this->hasOptions()):
						if (($_product->getAttributeText('no_shop_button')=='No')):?>
            	<div id="container2"><?php echo $this->getChildChildHtml('container2', '', true, true) ?></div>
            		<?php else: ?>
			        	<div class="order-by-request"><?php echo $this->getChildHtml('other2');?></div>
			        <?php endif;?>                                 
        <?php else:?>
        	<div class="order-by-request"><?php echo $this->getChildHtml('other2');?></div>
        <?php endif;?>	 <!-- CONTAINER 2 -->
        </form>
                <div class="acordeon">
                    		<dl class="acordeon-datos">
                            
                            
                        <?php
							if($producto->getShortDescription()){ // Si tiene descripcion adicional
						?>		
                        	<dt class="activo"><?php echo $this->__('Quick Overview:') ?></dt>
                        
                        	<dd>					
								<span><?php echo $producto->getShortDescription()?></span> 
							</dd>
                        <?php
                        	}
						?>
<?php
							if($producto->getAttributeText('es_musica')!='No'){ // Si tiene descripcion adicional
						?>
                        
                        <script type="text/javascript">
							jQuery(function(){
								var ua = navigator.userAgent.toLowerCase();
								var isAndroid = /android/.test(ua);
								var isAndroidDefault = isAndroid && !(/chrome/i).test(ua);
								if(isAndroidDefault){
									alert("Sorry, your browser does not support this implementation of the player. It will be used the standard HTML5 audio player instead")
								}
								jQuery(".audio").mb_miniPlayer({
									width:196,
									inLine:false,
									id3:false,
									downloadPage:null
					//                downloadPage:"map_download.php"
								});
							});
					
						</script>
                        <dt><span class="tracklist"><?php echo $this->__('Tracklist:') ?></span></dt>
                        <dd>
                        	<span style="font-size: 15px;font-weight: bold;">CD 1</span>
                        	<ul>
                            <li id="track1" style="width:100%;float:left;margin-bottom:5px;max-height: 23px;overflow: hidden;"><a id="m5" class="audio {skin:'blue', autoPlay:false, addShadow:true}" href="<?php echo Mage::getBaseUrl('media') ?>mp3/track1.mp3">Close to you (Housono Haruomi) (mp3)</a><span style="margin-left:10px;" class="titulo1">1.- Close to you (Housono Haruomi)</span></li>
                            <li id="track2" style="width:100%;float:left;margin-bottom:5px;max-height: 23px;overflow: hidden;" ><a id="m5" class="audio {skin:'blue', autoPlay:false, addShadow:true}" href="<?php echo Mage::getBaseUrl('media') ?>mp3/track2.mp3">Don't Explain (Elodie Rama)</a><span style="margin-left:10px;" class="titulo2">2.- Don't Explain (Elodie Rama)</span></li>
                            <li id="track3" style="width:100%;float:left;margin-bottom:5px;max-height: 23px;overflow: hidden;" ><a id="m5" class="audio {skin:'blue', autoPlay:false, addShadow:true}" href="<?php echo Mage::getBaseUrl('media') ?>mp3/track3.mp3">Echoes (Oliver Koletzki)</a><span style="margin-left:10px;" class="titulo3">3.- Echoes (Oliver Koletzki)</span></li>
                            <li id="track4" style="width:100%;float:left;margin-bottom:5px;max-height: 23px;overflow: hidden;" ><a id="m5" class="audio {skin:'blue', autoPlay:false, addShadow:true}" href="<?php echo Mage::getBaseUrl('media') ?>mp3/track4.mp3">Ton Regard Eclaire ma vie (Moon Rocket)</a><span style="margin-left:10px;" class="titulo4">4.- Ton Regard Eclaire ma vie (Moon Rocket)</span></li>
                            <li id="track5" style="width:100%;float:left;margin-bottom:5px;max-height: 23px;overflow: hidden;" ><a id="m5" class="audio {skin:'blue', autoPlay:false, addShadow:true}" href="<?php echo Mage::getBaseUrl('media') ?>mp3/track5.mp3">Everybody's gotta learn sometimes (Pink Turtle)</a><span style="margin-left:10px;" class="titulo5">5.- Everybody's gotta learn sometimes (Pink Turtle)</span></li>
                            <li id="track6" style="width:100%;float:left;margin-bottom:5px;max-height: 23px;overflow: hidden;" ><a id="m5" class="audio {skin:'blue', autoPlay:false, addShadow:true}" href="<?php echo Mage::getBaseUrl('media') ?>mp3/track6.mp3">Give us a little love (Fallulah)</a><span style="margin-left:10px;" class="titulo6">6.- Give us a little love (Fallulah)</span></li>
                            <li id="track7" style="width:100%;float:left;margin-bottom:5px;max-height: 23px;overflow: hidden;" ><a id="m5" class="audio {skin:'blue', autoPlay:false, addShadow:true}" href="<?php echo Mage::getBaseUrl('media') ?>mp3/track7.mp3">Carried away (Passion Pit)</a><span style="margin-left:10px;" class="titulo7">7.- Carried away (Passion Pit)</span></li>
                            </ul>
                            <span style="font-size: 15px;font-weight: bold;">CD2</span>
                            <ul>
                            <li id="track8" style="width:100%;float:left;margin-bottom:5px;max-height: 23px;overflow: hidden;" ><a id="m5" class="audio {skin:'blue', autoPlay:false, addShadow:true}" href="<?php echo Mage::getBaseUrl('media') ?>mp3/track8.mp3">Cocaine Blues - Greg Wilson Rmx (Escort)</a><span style="margin-left:10px;" class="titulo14">1.- Cocaine Blues - Greg Wilson Rmx (Escort)</span></li>
                            <li id="track9" style="width:100%;float:left;margin-bottom:5px;max-height: 23px;overflow: hidden;" ><a id="m5" class="audio {skin:'blue', autoPlay:false, addShadow:true}" href="<?php echo Mage::getBaseUrl('media') ?>mp3/track9.mp3">Dr. Funk (Sidechains)</a><span style="margin-left:10px;" class="titulo15">2.- Dr. Funk (Sidechains)</span></li>
                            <li id="track10" style="width:100%;float:left;margin-bottom:5px;max-height: 23px;overflow: hidden;" ><a id="m5" class="audio {skin:'blue', autoPlay:false, addShadow:true}" href="<?php echo Mage::getBaseUrl('media') ?>mp3/track10.mp3">(I Need Ya) L.O.V.E (Fhernando)</a><span style="margin-left:10px;" class="titulo16">3.- (I Need Ya) L.O.V.E (Fhernando)</span></li>
                            <li id="track11" style="width:100%;float:left;margin-bottom:5px;max-height: 23px;overflow: hidden;" ><a id="m5" class="audio {skin:'blue', autoPlay:false, addShadow:true}" href="<?php echo Mage::getBaseUrl('media') ?>mp3/track11.mp3">N.F.M.T - Patrick Podage Rmx (Going Deeper & Blackfeel Wite)</a><span style="margin-left:10px;" class="titulo17">4.- N.F.M.T - Patrick Podage Rmx (Going Deeper & Blackfeel Wite)</span></li>
                            <li id="track12" style="width:100%;float:left;margin-bottom:5px;max-height: 23px;overflow: hidden;" ><a id="m5" class="audio {skin:'blue', autoPlay:false, addShadow:true}" href="<?php echo Mage::getBaseUrl('media') ?>mp3/track12.mp3">To be clear - Zimmer Remix (Moullinex)</a><span style="margin-left:10px;" class="titulo18">5.- To be clear - Zimmer Remix (Moullinex)</span></li>
                            <li id="track13" style="width:100%;float:left;margin-bottom:5px;max-height: 23px;overflow: hidden;" ><a id="m5" class="audio {skin:'blue', autoPlay:false, addShadow:true}" href="<?php echo Mage::getBaseUrl('media') ?>mp3/track13.mp3">Love is the drug - Todd Terje Disco Drug (Roxy Music)</a><span style="margin-left:10px;" class="titulo19">6.- Love is the drug - Todd Terje Disco Drug (Roxy Music)</span></li>
                            <li id="track14" style="width:100%;float:left;margin-bottom:5px;max-height: 23px;overflow: hidden;" ><a id="m5" class="audio {skin:'blue', autoPlay:false, addShadow:true}" href="<?php echo Mage::getBaseUrl('media') ?>mp3/track14.mp3">Love's the only drug - Original (Ultra Nate)</a><span style="margin-left:10px;" class="titulo20">7.- Love's the only drug - Original (Ultra Nate)</span></li>
                            </ul>
                            
                        </dd>    
                        <?php
                        	}
						?>     
                        	<dt><?php echo $this->__('Composition:') ?></dt>
                        	<dd><?php echo $producto->getCampoDos() ?></dd>
                        <?php if ($producto->getAttributeText('pre_order_item')!='No'):?>
							<dt class="activo"><?php echo $this->__('PRE-ORDER INFO:') ?></dt>
                        	<dd><?php echo $this->__('PRE-ORDER items are advance of next seasons collection and will be delivered in the estimated date indicated in each case. Pre-orders are treated as FINAL SALE and must be paid in full at the time of order completion.'); ?> <a href="https://www.elitestore.es/pre-order-policy"><?php echo $this->__('Click here for more info.') ?></a></dd>
   						<?php  endif;
						if ($producto->getAttributeText('no_shop_button')!='No'):?>
							<dt class="activo"><?php echo $this->__('ORDER BY REQUEST INFO:') ?></dt>
                        	<dd><?php echo $this->__('This item is not available at the moment but if you are interested in we can try to get it for you. Give us your contact details and inform you every step of the process as soon as possible.')?> <a href="https://www.elitestore.es/orderrequest?id=<?php echo $producto->getId()?>" rel="shadowbox;width=728 height=700;scroll=none"><?php echo $this->__('Click here to start the process.') ?></a></dd>
						
						<?php endif;
						?>
                        <?php $categorias= $_product->getCategoryIds();
						if (in_array('23',$categorias)){ //Si pertenece a la categoría mujer
							if (in_array('24',$categorias)){ //Si pertenece a la categoría mujer-->ropa
						?>
							<dt><?php echo $this->__('Size Info:') ?></dt>
							<dd><ul>
									<li><?php echo $this->__('Type Sizing:') ?> <strong><?php echo $producto->getCampoNueve() ?></li></strong>
									<li><a href="https://www.elitestore.es/tabla-tallas-ropa-mujer" rel="shadowbox;width=780;height=300"><?php echo $this->__('See Size Chart') ?></a></li>
								</ul>
							</dd>
                      	<?php 
							}else if(in_array('59',$categorias)){ //Si pertenece a la categoría mujer-->zapatos
						?>
							<dt><?php echo $this->__('Size Info:') ?></dt>
							<dd><ul>
									<li><?php echo $this->__('Type Sizing:') ?><?php echo $producto->getCampoNueve() ?></li>
									<li><a href="https://www.elitestore.es/tabla-tallas-zapatos-mujer" rel="shadowbox;width=880;height=300"><?php echo $this->__('See Size Chart') ?></a></li>
								</ul>
							</dd>
                      	<?php		
							}
						}else if(in_array('62',$categorias)){//Si pertenece a la categoría hombre
							if (in_array('63',$categorias)){//Si pertenece a la categoría hombre-->ropa
						?>
							<dt><?php echo $this->__('Size Info:') ?></dt>
							<dd><ul>
									<li><?php echo $this->__('Type Sizing:') ?><?php echo $producto->getCampoNueve() ?></li>
									<li><a href="https://www.elitestore.es/tabla-tallas-ropa-hombre" rel="shadowbox;width=780;height=300"><?php echo $this->__('See Size Chart') ?></a></li>
								</ul>
							</dd>
                      	<?php
							}else if (in_array('92',$categorias)){//Si pertenece a la categoría hombre-->zapatos
						?>
							<dt><?php echo $this->__('Size Info:') ?></dt>
							<dd><ul>
									<li><?php echo $this->__('Type Sizing:') ?><?php echo $producto->getCampoNueve() ?></li>
									<li><a href="https://www.elitestore.es/tabla-tallas-zapatos-hombre" rel="shadowbox;width=960;height=300"><?php echo $this->__('See Size Chart') ?></a></li>
								</ul>
							</dd>
                      	<?php
								}
						}
							
						?>
                        	<dt><?php echo $this->__('Shipment Info:') ?></dt>
                        	<dd><span><?php echo $this->__('Elite ships worldwide. The shipping cost will be calculated at the checkout. You will have free shipping if your order is 500 &euro; or more. You can track your order at any time, once it has been shipped. ')?></span><a href="https://www.elitestore.es/shipment-and-returns"><?php echo $this->__('Click here for more info.') ?></a>
                        	</dd>
                        <?php if ($producto->getAttributeText('solo_envio_ue')!='No'){?>
                        	<dt class="activo"><?php echo $this->__('Shipment Restrictions:') ?></dt>
                        	<dd><span><?php echo $this->__('Customs authorities in some countries can find problems with composition of this item, so Elite decided not send this kind of items outside of European Union. If you want we ship this item to another country please contact previously with us. ')?></span><a href="https://www.elitestore.es/contact"><?php echo $this->__('Click here.') ?></a>
                        	</dd>
                        <?php } ?>
                        	<dt><?php echo $this->__('Return Info:') ?></dt>
                        	<dd><span><?php echo $this->__('If you are not satisfied with your purchase, the item(s) can be returned for a size exchange, a store credit or a refund within the 7 days after the order is delivered. ')?></span><a href="https://www.elitestore.es/return-policy"><?php echo $this->__('Click here for more info.') ?></a>
                        	</dd>
                                    
                        	<dt><?php echo $this->__('Share This:') ?></dt>
                        	<dd>
                        	<script type="text/javascript">var switchTo5x=true;</script>
							<script type="text/javascript" src="https://ws.sharethis.com/button/buttons.js"></script>
							<script type="text/javascript">stLight.options({publisher: "5200dec6-dd73-4fc8-b672-4b1d977c8503", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
                        	<span class='st_fblike_large' displayText='Facebook Like'></span>
							<span class='st_email_large' displayText='Email'></span>
							<span class='st_facebook_large' displayText='Facebook'></span>
							<span class='st_twitter_large' displayText='Tweet'></span>
							<span class='st_googleplus_large' displayText='Google +'></span>
							<span class='st_pinterest_large' displayText='Pinterest'></span>
							<span class='st_sharethis_large' displayText='ShareThis'></span>
                        	</dd>

                        	<dt><?php echo $this->__('More Info:') ?></dt>
                        	<dd><?php echo $this->getChildHtml('other');?></dd>
                    	</dl>
                </div> <!-- ACORDEON -->
                
                <?php if($_layout == 'horizontal'): ?>
                    <div class="clear"></div> 
                    <?php $use_share = themeOptions('use_share'); ?>
                    <?php $share_code = themeOptions('share_code'); ?>
                    <?php if($use_share && $share_code): ?>  
                        <?php echo $share_code; ?>
                    <?php endif; ?>
                <?php endif; ?>  
                
               
            </div>
            <?php if($_layout != 'horizontal'): ?>
                <div class="product_right">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('productview')->toHtml(); ?>
                    <?php $use_share = themeOptions('use_share'); ?>
                    <?php $share_code = themeOptions('share_code'); ?>
                    <?php if($use_share && $share_code): ?>  
                        <?php echo $share_code; ?>
                    <?php endif; ?>
                </div> 
            <?php endif; ?> <!-- PRODUCT RIGHT -->
        </div> <!-- PRODUCT BOX -->

        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>
        
		


        
    
    <?php if($enable_ajax): ?>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
		var url = jQuery('#product_addtocart_form').attr('action');
		url = url.replace("checkout/cart","ajax/index");    

        var msgHtml;
        var productImg = jQuery('.main-thumbnail').html();
        var windowOver = jQuery('#addedoverlay');
        var windowBox = jQuery('#added');
        var titleForBox = jQuery('#productname').text();   
        var data = {'isAjax':1}
        
        jQuery('#product_addtocart_form').ajaxForm({
            url: url,
            data: data,
            dataType: 'json',
            beforeSubmit: function(){    
                if(productAddToCartForm.validator.validate()){
                    windowOver.show();
                    windowBox.show().css({
                        backgroundImage: "url('<?php echo $this->getSkinUrl('images/loading.gif')?>')"
                    });                    
                }else{
                    return false;
                }
            },
            error: function(data){
	            windowBox.css({
       			      backgroundImage: 'none'
                }).html('<?php echo $this->__('Error') ?>');					   
                windowOver.one('click',function(){
		            hidewindow(windowBox,windowOver);                    
                });	       
                                 
                jQuery('#hidewindow').click(function(){
		            hidewindow(windowBox,windowOver);                    
                });
            },
            success : function(data,statusText,xhr ){
                if(data.status == 'SUCCESS'){
                    if(jQuery('.block-cart')){
                        jQuery('.block-cart').replaceWith(data.sidebar);
                    }
                    if(jQuery('.header .block-cart-header')){
                        jQuery('.header .block-cart-header').replaceWith(data.topcart);
                    }     
                    msgHtml = '<div class="added-content"><div style="float:left;">' + productImg + '</div><em>' + titleForBox + '</em> <?php echo $this->__('was successfully added to your shopping cart.') ?><div style="clear:both;"></div><a id="hidewindow" href="javascript:void(0);"><?php echo $this->__('Continue shopping') ?></a>&nbsp;<a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('View cart & checkout') ?></a></div>';             
                }else{
                    msgHtml = '<div class="added-content"><p class="error-msg" style="margin-bottom:15px;">' + data.message + '</p><a id="hidewindow" href="javascript:void(0);"><?php echo $this->__('Continue shopping') ?></a>&nbsp;<a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('View cart & checkout') ?></a></div>';
                }					   
               
                windowBox.css({
       			      backgroundImage: 'none'
                }).html(msgHtml);					   
                windowOver.one('click',function(){
    	            hidewindow(windowBox,windowOver);                    
                });	       
                                 
                jQuery('#hidewindow').click(function(){
    	            hidewindow(windowBox,windowOver);                    
                });	   
            }
        }); 
        
        function hidewindow(windowBox,windowOver){
            windowOver.fadeOut(400);
            windowBox.fadeOut(400).html('');	
        }

    //]]>
    </script>
    <?php else: ?>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    <?php endif; ?>
    </div>

    <div id="product-collateral" class="product-collateral">
        <?php //echo $this->getChildHtml('info_tabs') ?>
        <?php //echo $this->getChildHtml('product_additional_data') 
		//Se volverán a poner en un futuro, pero en el diseño inicial se eliminan
	 ?>
    </div>
        <?php echo $this->getChildHtml('related_products') ?>
        <?php echo $this->getChildHtml('upsell_products') ?>
</div>


<script>
var $j=jQuery.noConflict();	

	
    $j(document).ready(function() {
		$j('dl.acordeon-datos dd').not('dt.activo + dd').hide();
		$j('dl.acordeon-datos dt').click(function(){
		  
          if ($j(this).hasClass('activo')) {
               $j(this).removeClass('activo');
               $j(this).next().slideUp();
          } else {
               $j('dl.acordeon-datos dt').removeClass('activo');
               $j(this).addClass('activo');
               $j('dl.acordeon-datos dd').slideUp();
               $j(this).next().slideDown();
          }
       });
		/*$j('dl.acordeon-datos dt').click(function() {
    		$j('dl.acordeon-datos dd').slideToggle(400);
    		$j(this).next().slideToggle(400);
    		return false;
    		});
		$j('dl.acordeon-datos dd').hide();
		$j('dl.acordeon-datos dd.activo').show();*/
       });
	$j(document).ready(function() {
		$j('dl.acordeon-datos dd li').click(function(){
				var $span = 'dl.acordeon-datos dd span.titulo'+$j(this).attr('id').substring(5);
//				alert ('ocultar: '+$span);
				if ($j($span).is(":visible")){
					 $j($span).hide("slow");
				}else{
					 $j($span).show("slow");
				}
				for (var i = 1; i < 23; i++){
					var $span2 = 'dl.acordeon-datos dd span.titulo'+i;

					if ($span!=$span2){
//					alert('mostrar:'+$span2);
						$j($span2).show("slow");
					}
				}
		});
	});
	
</script>

