<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php $_layout = themeOptions('layout'); ?>
<?php $enable_ajax = themeOptions('enable_ajax'); ?>

<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<a class="back-to" href="javascript: history.go(-1)"><?php echo $this->__('Return to Previous Page') ?></a>
        
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view layout_<?php echo $_layout ?>">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
        <div id="addedoverlay" style='display:none'> </div>
        <div id='added' style='display:none'></div>
        <div id='productname' style='display:none'>
		<?php 
				if(Mage::app()->getStore()->getStoreId() == 1):					
					echo $_helper->productAttribute($_product, $_product->getName(), 'name');
				else:
					$producto = Mage::getModel('catalog/product')->load($_product->getId());	
					echo $producto->getCampoUno();
				endif;
		 ?></div>		
        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>
        
        <div class="product-shop">
            <div class="white-back"> 
                <div class="product-name">
                    <h1><?php 
					if(Mage::app()->getStore()->getStoreId() == 1):	//Codigo para cambio de nombre de producto en ingles/castellano
						echo $_helper->productAttribute($_product, $_product->getName(), 'name');
					else:
						$producto = Mage::getModel('catalog/product')->load($_product->getId());	
						echo $producto->getCampoUno();
					endif; 
					?></h1>
					<?php $producto = Mage::getModel('catalog/product')->load($_product->getId());	?>
                    <?php echo "<p class=\"manufacturer-productview\">".$producto->getAttributeText('manufacturer')."</p>"; ?>
					<?php echo "<p class=\"ref-prov\">Ref: ".$_helper->productAttribute($_product, $_product->getRefproveedor(), 'refproveedor')."</p>";?>
					
                </div>
               
				
                 <?php //echo $this->getReviewsSummaryHtml($_product, false, true)?>
                <?php echo $this->getChildHtml('alert_urls') ?>
                <?php echo $this->getChildHtml('extrahint') ?>
                <?php if($_product->getTypeId() != 'bundle'): ?>
                    <?php echo $this->getPriceHtml($_product); ?>
                <?php else: ?>
                    <?php echo $this->__('Product code:').'<strong>'.$_product->getId().'</strong>'; ?>
                    <?php echo $this->getChildHtml('product_type_data') ?>
                <?php endif;?>
                
                <div class="addtocont">
                    <?php /*
						Eliminado para que no salga Product Code y Avaliability
						if($_product->getTypeId() != 'bundle'): ?>
                        <span class="product-code"><?php //echo $this->__('Product code:').' <strong>'.$_product->getId().'</strong>'; ?></span>
                        <?php echo $this->getChildHtml('product_type_data') ?>
                    <?php endif;?>
                    <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('productview')->toHtml(); */?>
					
                </div>
				
                <div class="clear"></div>
				<?php echo $this->getTierPriceHtml() ?>
                
                
                
                
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <div id="container1"><?php echo $this->getChildChildHtml('container1', '', true, true) ?><div class="clear"></div></div>
                <?php endif;?>   
                
                <?php echo $this->getChildHtml('product_type_data_grouped') ?>
                <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                            <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                <span class="or"><?php echo $this->__('OR') ?></span>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                <?php endif; ?>  
                
                
                <div class="clearer"></div>				
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <div id="container2"><?php echo $this->getChildChildHtml('container2', '', true, true) ?></div>
        <?php endif;?>
        </form>
                        <div class="acordeon">
                    <dl class="acordeon-datos">
                        <?php
							if((Mage::app()->getStore()->getStoreId() == 1) && ($producto->getCampoTres())){ // Si tiene descripcion adicional en Español
						?>		
                        <dt class="activo"><?php echo $this->__('Quick Overview:') ?></dt>
                        
                        <dd>					
							<span> <?php echo $producto->getCampoTres()?></span> 
						</dd>
                        <?php
                        	}else if ($producto->getCampoSeis()){ //Si tiene descripcion adicional en Ingles
						?>
                        <dt class="activo"><?php echo $this->__('Quick Overview:') ?></dt>
                        <dd>
                        	<span><?php echo $producto->getCampoSeis() ?></span>
                        </dd>
						<?php
                        	}
						?>
     
                        <dt class="activo"><?php echo $this->__('Composition:') ?></dt>
                        <dd><?php echo $producto->getCampoDos() ?></dd>
     					<?php $categorias= $_product->getCategoryIds();
						if (in_array('23',$categorias)){ //Si pertenece a la categoría mujer
							if (in_array('24',$categorias)){ //Si pertenece a la categoría mujer-->ropa
						?>
								<dt><?php echo $this->__('Size Info:') ?></dt>
								<dd><ul>
										<li><?php echo $this->__('Type Sizing:') ?><?php echo $producto->getCampoOcho() ?></li>
										<li><a href="http://www.elitestore.es/tabla-tallas-ropa-mujer" rel="shadowbox;width=780;height=300"><?php echo $this->__('See Size Chart') ?></a></li>
									</ul>
								</dd>
                      	<?php 
							}else if(in_array('59',$categorias)){ //Si pertenece a la categoría mujer-->zapatos
						?>
								<dt><?php echo $this->__('Size Info:') ?></dt>
								<dd><ul>
										<li><?php echo $this->__('Type Sizing:') ?><?php echo $producto->getCampoOcho() ?></li>
										<li><a href="http://www.elitestore.es/tabla-tallas-zapatos-mujer" rel="shadowbox;width=880;height=300"><?php echo $this->__('See Size Chart') ?></a></li>
									</ul>
								</dd>
                      	<?php		
							}
						}else if(in_array('62',$categorias)){//Si pertenece a la categoría hombre
							if (in_array('63',$categorias)){//Si pertenece a la categoría hombre-->ropa
						?>
								<dt><?php echo $this->__('Size Info:') ?></dt>
								<dd><ul>
										<li><?php echo $this->__('Type Sizing:') ?><?php echo $producto->getCampoOcho() ?></li>
										<li><a href="http://www.elitestore.es/tabla-tallas-ropa-hombre" rel="shadowbox;width=780;height=300"><?php echo $this->__('See Size Chart') ?></a></li>
									</ul>
								</dd>
                      	<?php
							}else if (in_array('92',$categorias)){//Si pertenece a la categoría hombre-->zapatos
						?>
								<dt><?php echo $this->__('Size Info:') ?></dt>
								<dd><ul>
										<li><?php echo $this->__('Type Sizing:') ?><?php echo $producto->getCampoOcho() ?></li>
										<li><a href="http://www.elitestore.es/tabla-tallas-zapatos-hombre" rel="shadowbox;width=960;height=300"><?php echo $this->__('See Size Chart') ?></a></li>
									</ul>
								</dd>
                      	<?php
								}
						}
							
						?>
                        <dt><?php echo $this->__('Share This:') ?></dt>
                        <dd>
                        	<script type="text/javascript">var switchTo5x=true;</script>
							<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
							<script type="text/javascript">stLight.options({publisher: "5200dec6-dd73-4fc8-b672-4b1d977c8503", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
                        	<span class='st_fblike_large' displayText='Facebook Like'></span>
							<span class='st_email_large' displayText='Email'></span>
							<span class='st_facebook_large' displayText='Facebook'></span>
							<span class='st_twitter_large' displayText='Tweet'></span>
							<span class='st_googleplus_large' displayText='Google +'></span>
							<span class='st_pinterest_large' displayText='Pinterest'></span>
							<span class='st_sharethis_large' displayText='ShareThis'></span>
                        </dd>

                        <dt><?php echo $this->__('More Info:') ?></dt>
                        <dd><?php echo $this->getChildHtml('other');?></dd>
                    </dl>
                </div>
                
                <?php if($_layout == 'horizontal'): ?>
                    <div class="clear"></div> 
                    <?php $use_share = themeOptions('use_share'); ?>
                    <?php $share_code = themeOptions('share_code'); ?>
                    <?php if($use_share && $share_code): ?>  
                        <?php echo $share_code; ?>
                    <?php endif; ?>
                <?php endif; ?>  
                
               
            </div>
            <?php if($_layout != 'horizontal'): ?>
                <div class="product_right">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('productview')->toHtml(); ?>
                    <?php $use_share = themeOptions('use_share'); ?>
                    <?php $share_code = themeOptions('share_code'); ?>
                    <?php if($use_share && $share_code): ?>  
                        <?php echo $share_code; ?>
                    <?php endif; ?>
                </div> 
            <?php endif; ?>
        </div>
		


        
    
    <?php if($enable_ajax): ?>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
		var url = jQuery('#product_addtocart_form').attr('action');
		url = url.replace("checkout/cart","ajax/index");    

        var msgHtml;
        var productImg = jQuery('.main-thumbnail').html();
        var windowOver = jQuery('#addedoverlay');
        var windowBox = jQuery('#added');
        var titleForBox = jQuery('#productname').text();   
        var data = {'isAjax':1}
        
        jQuery('#product_addtocart_form').ajaxForm({
            url: url,
            data: data,
            dataType: 'json',
            beforeSubmit: function(){    
                if(productAddToCartForm.validator.validate()){
                    windowOver.show();
                    windowBox.show().css({
                        backgroundImage: "url('<?php echo $this->getSkinUrl('images/loading.gif')?>')"
                    });                    
                }else{
                    return false;
                }
            },
            error: function(data){
	            windowBox.css({
       			      backgroundImage: 'none'
                }).html('<?php echo $this->__('Error') ?>');					   
                windowOver.one('click',function(){
		            hidewindow(windowBox,windowOver);                    
                });	       
                                 
                jQuery('#hidewindow').click(function(){
		            hidewindow(windowBox,windowOver);                    
                });
            },
            success : function(data,statusText,xhr ){
                if(data.status == 'SUCCESS'){
                    if(jQuery('.block-cart')){
                        jQuery('.block-cart').replaceWith(data.sidebar);
                    }
                    if(jQuery('.header .block-cart-header')){
                        jQuery('.header .block-cart-header').replaceWith(data.topcart);
                    }     
                    msgHtml = '<div class="added-content"><div style="float:left;">' + productImg + '</div><em>' + titleForBox + '</em> <?php echo $this->__('was successfully added to your shopping cart.') ?><div style="clear:both;"></div><a id="hidewindow" href="javascript:void(0);"><?php echo $this->__('Continue shopping') ?></a>&nbsp;<a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('View cart & checkout') ?></a></div>';             
                }else{
                    msgHtml = '<div class="added-content"><p class="error-msg" style="margin-bottom:15px;">' + data.message + '</p><a id="hidewindow" href="javascript:void(0);"><?php echo $this->__('Continue shopping') ?></a>&nbsp;<a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('View cart & checkout') ?></a></div>';
                }					   
               
                windowBox.css({
       			      backgroundImage: 'none'
                }).html(msgHtml);					   
                windowOver.one('click',function(){
    	            hidewindow(windowBox,windowOver);                    
                });	       
                                 
                jQuery('#hidewindow').click(function(){
    	            hidewindow(windowBox,windowOver);                    
                });	   
            }
        }); 
        
        function hidewindow(windowBox,windowOver){
            windowOver.fadeOut(400);
            windowBox.fadeOut(400).html('');	
        }

    //]]>
    </script>
    <?php else: ?>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    <?php endif; ?>
    </div>

    <div id="product-collateral" class="product-collateral">
        <?php //echo $this->getChildHtml('info_tabs') ?>
        <?php //echo $this->getChildHtml('product_additional_data') 
		//Se volverán a poner en un futuro, pero en el diseño inicial se eliminan
	 ?>
    </div>
        <?php echo $this->getChildHtml('related_products') ?>
        <?php echo $this->getChildHtml('upsell_products') ?>
</div>


<script>
var $j=jQuery.noConflict();	

	
    $j(document).ready(function() {
		$j('dl.acordeon-datos dd').not('dt.activo + dd').hide();
		$j('dl.acordeon-datos dt').click(function(){
		  
          if ($j(this).hasClass('activo')) {
               $j(this).removeClass('activo');
               $j(this).next().slideUp();
          } else {
               $j('dl.acordeon-datos dt').removeClass('activo');
               $j(this).addClass('activo');
               $j('dl.acordeon-datos dd').slideUp();
               $j(this).next().slideDown();
          }
       });
		/*$j('dl.acordeon-datos dt').click(function() {
    		$j('dl.acordeon-datos dd').slideToggle(400);
    		$j(this).next().slideToggle(400);
    		return false;
    		});
		$j('dl.acordeon-datos dd').hide();
		$j('dl.acordeon-datos dd.activo').show();*/
       });

	
</script>

