<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('ORDER BY REQUEST'); ?>

 <?php if($_product->isSaleable()): ?>       
                   
    <div class="add-to-cart">
       
        <button url="<?php echo $this->getUrl("orderbyrequest/index/form")?>?id=<?php echo $_product->getId()?>" id="product-orderbyrequest-button" class="button button--shikoba button--text-thick button--border-medium button--text-upper button--size-s" title="<?php echo $buttonTitle ?>" ><i class="button__icon icon icon-cart"></i><span><?php echo $buttonTitle ?></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
