<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxcartpro
 * @version    2.5.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
?>

<script type="text/javascript">
//<![CDATA[
    var aw_ajaxcartpro_proganim = '<?php echo Mage::getStoreConfig('ajaxcartpro/general/progressanimation') ?>';
    var aw_ajaxcartpro_cartanim = '<?php echo Mage::getStoreConfig('ajaxcartpro/general/cartanimation') ?>';
    var aw_base_url = '<?php echo Mage::getBaseUrl() ?>';

    AW_ACP = {
        cartURL : '<?php echo Mage::getUrl('checkout/cart')?>',
        useProgress : <?php echo intval(Mage::getStoreConfig('ajaxcartpro/general/showprogressanimation')) ?>,
        useConfirmation : <?php echo intval(Mage::getStoreConfig('ajaxcartpro/general/confirmation')) ?>,
        isCartPage :  <?php echo intval(strpos(Mage::app()->getFrontController()->getRequest()->getPathInfo(),'/checkout/') !== false
                                        && strpos(Mage::app()->getFrontController()->getRequest()->getPathInfo(),'/checkout/onepage/success') === false
                                        && strpos(Mage::app()->getFrontController()->getRequest()->getPathInfo(),'/checkout/cart/configure') === false) ?>,
        isProductPage: <?php echo Mage::registry('current_product') ? 1 :0 ?>,
        theme : '<?php echo Mage::getDesign()->getTheme('template')?>',
        onRender : [],
        hasFileOption : <?php echo Mage::helper('ajaxcartpro')->hasFileOption() ? 'true' : 'false' ?>,
        secureUrlOnFrontend: <?php echo Mage::getStoreConfig('web/secure/use_in_frontend'); ?>,
        wishlistVersionMatch: <?php echo $this->getWishlistVersionMatch() ?>,
        counterBegin :<?php echo (int)Mage::getStoreConfig('ajaxcartpro/general/countdown') ?>,
        disabled: <?php echo $this->getIsDisabled() ?>,
        disabledForProducts: <?php echo $this->getDisabledForProducts() ?>,
        disabledForWLItems: <?php echo $this->getDisabledWishlistItems() ?>,
        _isCartConfigurePage: <?php echo intval(strpos(Mage::app()->getFrontController()->getRequest()->getPathInfo(),'/checkout/cart/configure') !== false) ?>
    }

    if(window.location.href.match('https://') && !AW_ACP.cartURL.match('https://')){
        AW_ACP.cartURL = AW_ACP.cartURL.replace('http://', 'https://')
    }

<?php
    if (file_exists(BP."/js/aw_ajaxcartpro/custom.js")) {
        @readfile(BP."/js/aw_ajaxcartpro/custom.js");

        $package = Mage::getDesign()->getPackageName();
        $theme = Mage::getDesign()->getTheme('template');
        @readfile(BP."/js/aw_ajaxcartpro/".$package."/".$theme."/custom.js");
    }
?>
//]]>
</script>
