<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxcartpro
 * @version    2.5.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<div id="acp_configurable_block">
    <?php $_product = $this->getProduct() ?>
    <div id="acp-overlay"></div>
    <script type="text/javascript">
        optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
        optionsPrice.productType = '<?php echo $_product->getTypeId() ?>';
    </script>
    <?php
    $addToCartUrlParams = Mage::helper('ajaxcartpro/catalog')
            ->getAddToCartUrlAdditional($_product->getId(), array('_secure' => Mage::app()->getRequest()->isSecure()));
    ?>
    <form action="<?php echo $this->getAddToCartUrl($_product, $addToCartUrlParams); ?>" method="post"
          id="product_addtocart_form_acp"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" value="<?php echo $_product->getId() ?>" name="product">
        <input type="hidden" value="1" name="awacp_options_form" />
        <?php echo $this->getChildHtml('product_js');?>
        <div id="acp_product_options">
            <div class="product-options" id="product-options-wrapper" style="margin:0">
                <div class="product-name"><?php 
				if(Mage::app()->getStore()->getStoreId() == 1):					
					echo $_helper->productAttribute($_product, $_product->getName(), 'name');
				else:
					$producto = Mage::getModel('catalog/product')->load($_product->getId());	
					echo $producto->getCampoUno();
				endif;
				
				//echo $_product->getName() ?></div>
                <div style="display:none">
                    <?php echo $this->getChildHtml('product_type_data') ?>
                </div>
                <?php echo str_replace('var ', '', $this->getChildHtml('product_options'));?>
                <?php echo $this->__($this->getChildHtml('product_configurable_options'));?>
                <?php echo $this->__($this->getChildHtml('product_downloadable_options'));?>
                <?php echo $this->getChildHtml('product_price');?>
                <div style="margin:5px 0px 20px 20px">
                    <a href="#" id="aw_acp_continue" onclick="return false;" style="float:left; margin: 0 5px">
                        <?php echo $this->__('Cancel')?>
                    </a>
                    <a href="#" id="aw_acp_checkout" class="focus" onclick="acpSubmit(); return false;" style="float:left; margin: 0 5px">
                        <?php echo $this->__('Add to cart')?>
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>
