<?php 
/************************  AJAX FILTERS **********************************/
?>
<div id="left-layered-navigation-container">
    <?php echo $this->getChildHtml('ajax_layered_navigation_left'); ?>
</div>    
<div class="col-main">
    <!-- start global messages -->
    <?php echo $this->getChildHtml('global_messages') ?>
    <!-- end global messages -->
    <!-- start content -->
    <?php echo $this->getChildHtml('content') ?>
    <!-- end content -->
</div>
