<div id="top"></div>
<div class="header-container">
    <div class="header">
        
        <div class="header-left">
 <?php echo $this->getChildHtml('topBar') ?>
            
        </div>
        <div class="header-center">            
			
            <?php if ($this->getIsHomePage()):?>           
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php else:?>
			<a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif
		//Añadido el logo también en el else para que salga en toda la web
	     ?>
      <span class="welcome-msg"><?php echo $this->getWelcome() ?></span>
  	</div>        
        <div class="header-right">
		
            <div class="minicart">
                <?php echo $this->getChildHtml('top_cart') ?>
				<?php echo $this->getChildHtml('store_language') ?>	
            </div>  
			
            <?php echo $this->getChildHtml('currency') ?>  
            <div class="clear"></div>   
            <?php echo $this->getChildHtml('topLinks') ?>  
        </div> 
                <a href="#menu-right" class="friends right"></a>
        <nav id="menu-right">    

        <div class="header-right--mobile">
            <div class="header-left--mobile">
                <?php echo $this->getChildHtml('topBar') ?>
            
        </div>
            <div class="minicart">
                <?php echo $this->getChildHtml('top_cart') ?>
                <?php echo $this->getChildHtml('store_language') ?> 
            </div>  
            
            <?php echo $this->getChildHtml('currency') ?>  
            <div class="clear"></div>   
            <?php echo $this->getChildHtml('topLinks') ?>  
        </div>
        </nav>       
    </div>
    <?php echo $this->getChildHtml('topMenu') ?>
    <!--Añadimos el mini banner superior excepto en la home	-->
    
     
	 	<?php //if ((Mage::getSingleton('cms/page')->getPageId()!='2') && (Mage::getSingleton('cms/page')->getPageId()!='10')): ?>
			
	    		
                    <div class="banner_class">
                        <div class="bloque banner--bloque1"></div>
						<div class="bloque banner--bloque2"></div>
                        <div class="bloque banner--bloque3"></div>
						<div class="banner--bloque4">
							<a rel="shadowbox;width=728 height=230;scroll=none" href="http://www.elitestore.es/promotion-fees/"><?php echo $this->__('*Terms & conditions')?></a>
						</div>                        
                    </div>
                
    	<?php //endif ?>
    	
	<?php echo $this->getChildHtml('topBread') ?>
    <?php echo $this->getChildHtml('topContainer'); ?>
	
</div>