<?php


Mage::app()->loadArea('frontend');
$layout = Mage::getSingleton('core/layout');

//load default xml layout handle and generate blocks
$layout->getUpdate()->load('default'); 
$layout->generateXml()->generateBlocks();
$baseUrl = (isset($_POST['baseUrl']) ? $_POST['baseUrl'] : null);
$store_id = 2;//Mage::app()->getStore()->getStoreId();

$retorno = "";

?>
		<ul id="nav">

	        <li class="menu-principal">
	        	<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->load(531)->getUrlPath(); ?>"><?php echo 'WOMEN'; ?></a>
	        	<div class="sheet">
	        		<ul>
	        			<li>
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStore($store_id)->load(532)->getUrlPath(); ?>"><?php echo 'NEW IN'; ?></a>
	        			</li>
	        			<li>
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(532)->getUrlPath(); ?>"><?php echo 'CLOTHING'; ?></a>
	        			</li>
	        			<li>
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(533)->getUrlPath(); ?>"><?php echo  'SHOES'; ?></a>
	        			</li>
	        			<li>
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(534)->getUrlPath(); ?>"><?php echo  'BAGS'; ?></a>
	        			</li>
	        			<li>
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(535)->getUrlPath(); ?>"><?php echo  'ACCESSORIES'; ?></a>
	        			</li>
	        			<li class="red">
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(355)->getUrlPath(); ?>"><?php echo  'SALE'; ?></a>
	        			</li>

	        		</ul>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/ss16/negra.jpg"/>
	        					<div class="title">
	        						#JUSTLANDED: <span>Lanvin SS16!</span>
	        					</div>
	        					<div class="shop">
	        						-&nbsp;SHOP NOW&nbsp;-
	        					</div>
	        				</div>

	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/fw15/blanca.jpg"/>
	        					<div class="title">
	        						FW15 Trend: <span>Shearling jackets</span>
	        					</div>
	        					<div class="shop">
	        						-&nbsp;SHOP NOW&nbsp;-
	        					</div>
	        				</div>
	        	</div>
	        </li>
	        <li class="menu-principal">
	        	<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(10)->getUrlPath(); ?>"><?php echo  'MEN'; ?></a>
	        	<div class="sheet">
	        		<ul>
	        			<li>
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(10)->getUrlPath(); ?>"><?php echo  'NEW IN'; ?></a>
	        			</li>
	        			<li>
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(15)->getUrlPath(); ?>"><?php echo  'CLOTHING'; ?></a>
	        			</li>
	        			<li>
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(89)->getUrlPath(); ?>"><?php echo  'SHOES'; ?></a>
	        			</li>
	        			<li>
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(90)->getUrlPath(); ?>"><?php echo  'BAGS'; ?></a>
	        			</li>
	        			<li>
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(91)->getUrlPath(); ?>"><?php echo  'ACCESSORIES'; ?></a>
	        			</li>
	        			<li class="red">
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(360)->getUrlPath(); ?>"><?php echo  'SALE'; ?></a>
	        			</li>

	        		</ul>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/fw15/blanco.jpg"/>
	        					<div class="title">
	        						#JUSTLANDED: Givenchy SS16!
	        					</div>
	        					<div class="shop">
	        						-&nbsp;SHOP NOW&nbsp;-
	        					</div>
	        				</div>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/ss16/negro.jpg"/>
	        					<div class="title">
	        						FW15 Trend: Graphics Tees
	        					</div>
	        					<div class="shop">
	        						-&nbsp;SHOP NOW&nbsp;-
	        					</div>
	        				</div>
	        		</div>
	        </li>
	        <li class="menu-principal">
	        	<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'KIDS'; ?></a>
	        	<div class="sheet">
	        		<ul>
	        			<li>
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'NEW IN'; ?></a>
	        			</li>
	        			<li>
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(66)->getUrlPath(); ?>"><?php echo  'CLOTHING'; ?></a>
	        			</li>
	        			<li>
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(68)->getUrlPath(); ?>"><?php echo  'ACCESSORIES'; ?></a>
	        			</li>
	        			<li class="red">
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(356)->getUrlPath(); ?>"><?php echo  'SALE'; ?></a>
	        			</li>

	        		</ul>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/ss16/negrita.jpg"/>
	        					<div class="title">
	        						#COMINGSOON: Moschino SS16!
	        					</div>
	        					<div class="shop">
	        						-&nbsp;SHOP NOW&nbsp;-
	        					</div>
	        				</div>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/fw15/blanquita.jpg"/>
	        					<div class="title">
	        						Cute Down Jackets: Moncler
	        					</div>
	        					<div class="shop">
	        						-&nbsp;SHOP NOW&nbsp;-
	        					</div>
	        				</div>
	        		</div>
	        </li>
	        <li class="menu-principal">
	        	<a href="<?php echo $baseUrl. 'manufacturer/';?>"><?php echo  'DESIGNERS'; ?></a>
	        	<div class="sheet designers" id="design">
	        		<div class="lista">	
		        		<div class="title">
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'FEATURED DESIGNERS'; ?></a>
	        			</div>
		        			<ul>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'Balmain';?></a>
			        			</li>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'Dsquared2'; ?></a>
			        			</li>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'Giorgio Armani'; ?></a>
			        			</li>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'Giuseppe Zanotti'; ?></a>
			        			</li>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'Givenchy'; ?></a>
			        			</li>
		        			</ul>
		        			<ul>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'Lanvin'; ?></a>
			        			</li>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'Moncler'; ?></a>
			        			</li>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'Moschino'; ?></a>
			        			</li>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'Roberto Cavalli'; ?></a>
			        			</li>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPathKey(); ?>"><?php echo  'Versace'; ?></a>
			        			</li>
		        			</ul>
		        		</div>
		        	<div class="lista">	
		        		<div class="title">
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'DESIGNERS OF THE WEEK'; ?></a>
	        			</div>
		        		
		        			<ul>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'Alexander Wang'; ?><div class="new-design">NEW</div></a>
			        			</li>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'Carven'; ?></a>
			        			</li>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'MSGM'; ?></a>
			        			</li>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'Rick Owens'; ?></a>
			        			</li>
			        			<li>
			        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo  'Sophia Webster'; ?></a>
			        			</li>
		        			</ul>
		        		</div>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/ss16/mochila.jpg"/>
	        					<div class="title">
	        						Alexander Wang
	        					</div>
	        					<div class="shop">
	        						-&nbsp;SHOP NOW&nbsp;-
	        					</div>
	        				</div>
	        		</div>
	        </li>
	        <li>
	        	<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . '../../blog2/';?>"><?php echo  'ELITE UNIVERSE'; ?></a>
	        </li>
	        <li class="red">
	        	<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(354)->getUrlPathKey(); ?>"><?php echo  'SALE'; ?></a>
	        </li>
	        <li>
	        	<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(179)->getUrlPathKey(); ?>"><?php echo  'OUTLET'; ?></a>
	        </li>
		</ul>


