<ul class="rslides">
	  	<li>
		  <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/slider/slider01.jpg';//{{media url=/wysiwyg/slider/slider01.jpg}}?>" alt="">
			<div class="texto-slider">
				<div class="texto--mini">Indulge in</div>
				<div class="texto--maxi">NEW SEASON LANVIN</div>
				<div class="separator--slider--main"></div>
				<div class="texto--amplio">Fresh contemporary tailoring meets head-turning neo 80’s individuality. The last Resort collection by Alber Elbaz has just landed on our virtual shelves! Step into the new season with our handpicked edit.</div>
				<div class="btn-izq--slider">EXPLORE</div>
				<div class="btn-der--slider">INDULGE IN</div>
			</div>
		</li>
	  	<li>
	  		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/slider/slider02.jpg';?>" alt="">
			<div class="texto-slider">
				<div class="texto--mini">This season</div>
				<div class="texto--maxi">BLACK IS THE NEW BLACK</div>
				<div class="separator--slider--main"></div>
				<div class="texto--amplio">Curated fashion edit for all black everything lovers.</div>

				<div class="btn-izq--slider">FOR HER</div>
				<div class="btn-der--slider">FOR HIM</div>
			</div>
		</li>
	  	<li>
	  		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/slider/slider03.jpg';?>" alt="">
			<div class="texto-slider">
			    <div class="texto--mini">Currently trending</div>
			    <div class="texto--maxi">KNITS WITH ATTITUDE</div>
			    <div class="btn-izq--slider">SHOP</div>
			    <div class="btn-der--slider">THE EDIT</div>
			</div>
	  </li>
	</ul>
	<div class="estrecho">
		<div class="texto--banner">
		     <ul>
		           <li id="0"><span>FREE EXPRESS SHIPPING</span>Worldwide, for all orders of 500€ and over.</li>
		           <li style="display: none;" id="1"><span>#JUSTLANDED: JEREMY SCOTT RUNWAY</span> Sixties meets eighties vibe, bold prints, and electrifying mix of colors!</li>
		           <li style="display: none;" id="2"><span>FURTHER REDUCTIONS:</span>Now with an EXTRA 20% off all sale items!</li>

		     </ul>
		</div>
		<ul class="bloquesSueltos">
		  <li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/bloquesSueltos/bloque01.jpg';?>" alt=""></li>
		  <li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/bloquesSueltos/bloque02.jpg';?>" alt=""></li>
		  <li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/bloquesSueltos/bloque03.jpg';?>" alt=""></li>
		</ul>
		<div class="linea2"></div>
		<div class="titulo-editors-pics"></div>
		<?php echo $this->getChildHtml("carousel");?>
		<div class="linea"></div>
		<!--{{block type="quotemodule/quoteformblock" name="quoteform_quoteformblock" template="quotemodule/quoteform.phtml"}}-->
	</div>