

<?php 
$urlString = Mage::helper('core/url')->getCurrentUrl();
$url = Mage::getSingleton('core/url')->parseUrl($urlString);
$path = $url->getPath();
$tienda = Mage::app()->getWebsite()->getCode();//Mage::getBaseUrl();

$listadoPaises = $this->getZones();//listado de paises obtenidos de magento por el block de sendto

$leng = Mage::app()->getLocale()->getLocaleCode();

$moneda = Mage::app()->getStore()->getCurrentCurrencyCode();
$ultima="http://192.168.1.201:8080/elitestore192/as/es/index.php";
?>
<div class="page-title category-title">
        <h1>Languaje, Shipping and Currency</h1>
                            
</div>
<div class="block-title" id="slayer-catalog">
        <strong><span id="catalog--block--title">Select a continent</span></strong>
</div>

<div id="data">
            <div id="lista_country" style="display: block;">
                <div id="pnlContinents" style="text-align:center;">
                    <img id="imgWorldmap" src="<?php echo $this->getSkinUrl('images/mapa/worldmap.jpg');?>" data-width="749" usemap="#mapWorldmap" data-scale="1">
                    <map id="mapWorldmap" name="mapWorldmap">


                        <area id="world_AM" alt="América" shape="poly" coords="127,118,99,108,106,95,126,81,155,76,187,72,211,76,226,65,255,63,285,50,310,48,345,44,377,43,475,45,485,61,462,99,387,121,356,133,357,152,309,177,288,197,277,216,293,231,313,239,332,263,323,275,350,282,357,298,391,313,390,341,375,380,355,413,336,448,338,458,351,470,338,486,315,489,284,464,172,244,154,215" onclick="displayStates('U.S.A. & Canada');" onmouseover="overContinent('AM',<?php echo "'" . $this->getSkinUrl() . "'";?>);" onmouseout="overContinent('', <?php echo "'" . $this->getSkinUrl() . "'";?>);"  title="América" class="pitingo" href="#U.S.A. & Canada">


                        <area id="world_AF" alt="Africa" shape="poly" coords="470,180,456,188,446,198,436,217,431,240,432,261,443,286,469,297,489,290,492,306,503,314,506,323,513,337,514,357,517,375,528,405,539,421,558,420,591,413,628,397,659,366,640,338,633,309,634,276,633,255,588,226,568,196,528,183,507,173" onclick="displayStates('Global');" onmouseover="overContinent('AF',<?php echo "'" . $this->getSkinUrl() . "'";?>);" onmouseout="overContinent('', <?php echo "'" . $this->getSkinUrl() . "'";?>);"  title="Africa" href="#Global">


                        <area id="world_EU" alt="Europa" shape="poly" coords="472,183,454,176,455,160,465,151,456,129,457,113,476,103,506,78,535,71,559,70,580,71,598,81,595,105,588,139,581,155,567,165,551,178,541,186,515,164,520,180,500,171,532,179,495,169" onclick="displayStates('Europa');" onmouseover="overContinent('EU',<?php echo "'" . $this->getSkinUrl() . "'";?>);" onmouseout="overContinent('', <?php echo "'" . $this->getSkinUrl() . "'";?>);" title="Europa" href="#Europa">


                        <area id="world_AS" alt="Asia" shape="poly" coords="914,74,963,132,936,164,881,159,866,195,850,221,855,264,820,244,808,270,788,292,788,317,730,306,677,267,671,234,642,248,618,260,598,247,593,217,575,192,559,177,564,159,586,137,583,94,585,76,594,53,643,43,812,42" onclick="displayStates('Asia');" onmouseover="overContinent('AS', <?php echo "'" . $this->getSkinUrl() . "'";?>);" onmouseout="overContinent('', <?php echo "'" . $this->getSkinUrl() . "'";?>);" title="Asia" href="#Asia">


                        <area id="world_OC" alt="Oceania" shape="poly" coords="895,475,975,417,980,371,1019,339,986,312,917,293,858,289,830,300,791,337,777,376,768,426"  onclick="displayStates('Oceania');" onmouseover="overContinent('OC', <?php echo "'" . $this->getSkinUrl() . "'";?>);" onmouseout="overContinent('', <?php echo "'" . $this->getSkinUrl() . "'";?>);" title="Oceania" href="#Oceania">


                    </map>
                </div>
            </div>
</div>
<div class="content selfclear" id="content" data-hires="true">
<?php 
foreach ($listadoPaises as $nombreZona => $paises):
    if($nombreZona!="hispana"):
    ?>
        
            <div class="section selfclear" id="<?php echo $nombreZona?>_mideast">
            <a name="<?php echo $nombreZona?>">
                <h2><?php echo $nombreZona?></h2>
            </a>
                <ul>
                <?php
                    foreach ($paises as $datosPais):
                        foreach ($datosPais as $nombrePais => $codigoPais):
                            if($codigoPais!=""):
                                    if ($leng=='es_ES'){
        									if($nombreZona=="Asia"){
                                                ?>
                                                <li onclick="setCountry(<?php echo "'" . $nombrePais . "'" ; ?>, <?php echo "'" .$this->getSkinUrl() . 'images/flags/flags_iso/16/' . strtolower($codigoPais) .".png'"; ?>, <?php echo "'" .$leng . "'" ; ?>, <?php echo "'" .$moneda . "'" ; ?>, <?php echo "'" . Mage::getUrl('sendto/index/setStates') . "'" ; ?>, <?php echo "'4'" ; ?>, <?php echo "'".$ultima."'"; ?>)">

                                                <br/><a href="<?php echo Mage::app()->getStore(4)->getBaseUrl();?>">
                                                <?php
                                            }
        									elseif($nombreZona=="China"){
                                                ?>
                                                <li onclick="setCountry(<?php echo "'" . $nombrePais . "'" ; ?>, <?php echo "'" .$this->getSkinUrl() . 'images/flags/flags_iso/16/' . strtolower($codigoPais) .".png'"; ?>, <?php echo "'" .$leng . "'" ; ?>, <?php echo "'" .$moneda . "'" ; ?>, <?php echo "'" . Mage::getUrl('sendto/index/setStates') . "'" ; ?>, <?php echo "'6'" ; ?>, <?php echo "'".$ultima."'" ; ?>)">

                                                <br/><a href="<?php echo Mage::app()->getStore(6)->getBaseUrl();?>">
                                                <?php
                                            }
        									elseif($nombreZona=="Europa"){
                                                ?>
                                                <li onclick="setCountry(<?php echo "'" . $nombrePais . "'" ; ?>, <?php echo "'" .$this->getSkinUrl() . 'images/flags/flags_iso/16/' . strtolower($codigoPais) .".png'"; ?>, <?php echo "'" .$leng . "'" ; ?>, <?php echo "'" .$moneda . "'" ; ?>, <?php echo "'" . Mage::getUrl('sendto/index/setStates') . "'" ; ?>, <?php echo "'8'" ; ?>, <?php echo "'".$ultima."'" ; ?>)">

                                                <br/><a href="<?php echo Mage::app()->getStore(8)->getBaseUrl();?>">
                                                <?php
                                            }
        									elseif($nombreZona=="Oceania"){
                                                ?>
                                                <li onclick="setCountry(<?php echo "'" . $nombrePais . "'" ; ?>, <?php echo "'" .$this->getSkinUrl() . 'images/flags/flags_iso/16/' . strtolower($codigoPais) .".png'"; ?>, <?php echo "'" .$leng . "'" ; ?>, <?php echo "'" .$moneda . "'" ; ?>, <?php echo "'" . Mage::getUrl('sendto/index/setStates') . "'" ; ?>, <?php echo "'10'" ; ?>, <?php echo "'".$ultima."'" ; ?>)">

                                                <br/><a href="<?php echo Mage::app()->getStore(10)->getBaseUrl();?>">
                                                <?php
                                            }
        									elseif($nombreZona=="U.S.A. & Canada"){
                                                ?>
                                                <li onclick="setCountry(<?php echo "'" . $nombrePais . "'" ; ?>, <?php echo "'" .$this->getSkinUrl() . 'images/flags/flags_iso/16/' . strtolower($codigoPais) .".png'"; ?>, <?php echo "'" .$leng . "'" ; ?>, <?php echo "'" .$moneda . "'" ; ?>, <?php echo "'" . Mage::getUrl('sendto/index/setStates') . "'" ; ?>, <?php echo "'12'" ; ?>, <?php echo "'".$ultima."'" ; ?>)">

                                                <br/><a href="<?php echo Mage::app()->getStore(12)->getBaseUrl();?>">
                                                <?php
                                            }
        									else{
                                                ?>
                                                <li onclick="setCountry(<?php echo "'" . $nombrePais . "'" ; ?>, <?php echo "'" .$this->getSkinUrl() . 'images/flags/flags_iso/16/' . strtolower($codigoPais) .".png'"; ?>, <?php echo "'" .$leng . "'" ; ?>, <?php echo "'" .$moneda . "'" ; ?>, <?php echo "'" . Mage::getUrl('sendto/index/setStates') . "'" ; ?>, <?php echo "'2'" ; ?>, <?php echo "'".$ultima."'" ; ?>)">

                                                <br/><a href="<?php echo Mage::app()->getStore(2)->getBaseUrl();?>">
                                                <?php
                                            }
        								}else{
        									if($nombreZona=="Asia"){
        									   ?>
                                                <li onclick="setCountry(<?php echo "'" . $nombrePais . "'" ; ?>, <?php echo "'" .$this->getSkinUrl() . 'images/flags/flags_iso/16/' . strtolower($codigoPais) .".png'"; ?>, <?php echo "'" .$leng . "'" ; ?>, <?php echo "'" .$moneda . "'" ; ?>, <?php echo "'" . Mage::getUrl('sendto/index/setStates') . "'" ; ?>, <?php echo "'3'" ; ?>, <?php echo "'".$ultima."'" ; ?>)">

                                                <br/><a href="<?php echo Mage::app()->getStore(3)->getBaseUrl();?>">
                                                <?php
                                            }
        									elseif($nombreZona=="China"){
        										?>
                                                <li onclick="setCountry(<?php echo "'" . $nombrePais . "'" ; ?>, <?php echo "'" .$this->getSkinUrl() . 'images/flags/flags_iso/16/' . strtolower($codigoPais) .".png'"; ?>, <?php echo "'" .$leng . "'" ; ?>, <?php echo "'" .$moneda . "'" ; ?>, <?php echo "'" . Mage::getUrl('sendto/index/setStates') . "'" ; ?>, <?php echo "'5'" ; ?>, <?php echo "'".$ultima."'" ; ?>)">

                                                <br/><a href="<?php echo Mage::app()->getStore(5)->getBaseUrl();?>">
                                                <?php
                                            }
        									elseif($nombreZona=="Europa"){
        										?>
                                                <li onclick="setCountry(<?php echo "'" . $nombrePais . "'" ; ?>, <?php echo "'" .$this->getSkinUrl() . 'images/flags/flags_iso/16/' . strtolower($codigoPais) .".png'"; ?>, <?php echo "'" .$leng . "'" ; ?>, <?php echo "'" .$moneda . "'" ; ?>, <?php echo "'" . Mage::getUrl('sendto/index/setStates') . "'" ; ?>, <?php echo "'7'" ; ?>, <?php echo "'".$ultima."'" ; ?>)">

                                                <br/><a href="<?php echo Mage::app()->getStore(7)->getBaseUrl();?>">
                                                <?php
                                            }
        									elseif($nombreZona=="Oceania"){
        										?>
                                                <li onclick="setCountry(<?php echo "'" . $nombrePais . "'" ; ?>, <?php echo "'" .$this->getSkinUrl() . 'images/flags/flags_iso/16/' . strtolower($codigoPais) .".png'"; ?>, <?php echo "'" .$leng . "'" ; ?>, <?php echo "'" .$moneda . "'" ; ?>, <?php echo "'" . Mage::getUrl('sendto/index/setStates') . "'" ; ?>, <?php echo "'9'" ; ?>, <?php echo "'".$ultima."'" ; ?>)">

                                                <br/><a href="<?php echo Mage::app()->getStore(9)->getBaseUrl();?>">
                                                <?php
                                            }
        									elseif($nombreZona=="U.S.A. & Canada"){
        										?>
                                                <li onclick="setCountry(<?php echo "'" . $nombrePais . "'" ; ?>, <?php echo "'" .$this->getSkinUrl() . 'images/flags/flags_iso/16/' . strtolower($codigoPais) .".png'"; ?>, <?php echo "'" .$leng . "'" ; ?>, <?php echo "'" .$moneda . "'" ; ?>, <?php echo "'" . Mage::getUrl('sendto/index/setStates') . "'" ; ?>, <?php echo "'11'" ; ?>, <?php echo "'".$ultima."'" ; ?>)">

                                                <br/><a href="<?php echo Mage::app()->getStore(11)->getBaseUrl();?>">
                                                <?php
                                            }
        									else{
        										?>
                                                <li onclick="setCountry(<?php echo "'" . $nombrePais . "'" ; ?>, <?php echo "'" .$this->getSkinUrl() . 'images/flags/flags_iso/16/' . strtolower($codigoPais) .".png'"; ?>, <?php echo "'" .$leng . "'" ; ?>, <?php echo "'" .$moneda . "'" ; ?>, <?php echo "'" . Mage::getUrl('sendto/index/setStates') . "'" ; ?>, <?php echo "'1'" ; ?>, <?php echo "'".$ultima."'" ; ?>)">

                                                <br/><a href="<?php echo Mage::app()->getStore(1)->getBaseUrl();?>">
                                                <?php
                                            }
        								}
                                        ?>
                                            <img src="<?php echo $this->getSkinUrl() . 'images/flags/flags_iso/16/' . strtolower($codigoPais); ?>.png" alt="">
                                            <span>
                                                <span>
                                                <?php echo $nombrePais; ?>
                                                </span>
                                            </span>
                                        </a>
                                    </li>
                                    <?php
                            endif;
                        endforeach;
                    endforeach;
                ?>
                </ul>
            </div>

<?php 
endif;
endforeach;


?>
        </div>
