<div class="right__sidebar">
<title><?php echo Mage::app()->getFrontController()->getRequest()->getRouteName(); ?></title>
    <ul>
        <li>
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" . Mage::getStoreConfig('weboptions/opciones/account_sidebar1_img_url');?>" alt=""/>
        </li>
        <li>
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" . Mage::getStoreConfig('weboptions/opciones/account_sidebar2_img_url');?>" alt=""/>
        </li>
        <li>
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" . Mage::getStoreConfig('weboptions/opciones/account_sidebar3_img_url');?>" alt=""/>
        </li>
    </ul>
</div>