<?php
/**
 * Survey for Magento
 *
 * @category   Belitsoft
 * @package    Belitsoft_Survey
 * @author     Belitsoft <bits@belitsoft.com>
 */

/* @var $this Belitsoft_Survey_Block_Frontend_Question_Default */

$question = $this->getCurrentQuestion();
$id = $question->getQuestionId();
?>
<div class="survey_question">
<textarea class="textarea question_default required-entry validate-text"
	style="height:10em; width:98%;" cols="5" rows="3"
	name="default_<?php echo $id; ?>"
	id="default_<?php echo $id; ?>"<?php echo ($this->isViewMode() ? ' disabled="true"' : ''); ?>><?php echo $this->getSelected("default_".$id); ?></textarea>
</div>
