<?php
/**
 * Survey for Magento
 *
 * @category   Belitsoft
 * @package    Belitsoft_Survey
 * @author     Belitsoft <bits@belitsoft.com>
 */

/* @var $this Belitsoft_Survey_Block_Frontend_Question_Pickmany */
?>
<ul class="survey_question">
<?php $i=0; $count=count($this->getFieldsObjects()); ?>
<?php foreach($this->getFieldsObjects() as $field): ?>
<?php $id = $field->getId(); $question_id = $field->getQuestionId(); ?>
	<li class="<?php echo (($count-1==$i)?'last ':'').($i%2?'even':'odd'); ?>">
		<input type="checkbox"
			name="pickmany_<?php echo $question_id; ?>[]"
			class="checkbox question_pickmany validate-one-required-by-name"
			id="question_pickmany_<?php echo $id; ?>"
			value="<?php echo $id; ?>"<?php echo $this->getPickmanySelected('pickmany_'.$question_id, $id); ?><?php echo ($this->isViewMode() ? ' disabled="true"' : ''); ?> />
		<span class="label">
			<label for="question_pickmany_<?php echo $id; ?>"><?php echo $field->getFieldText(); ?></label>
		</span>
	</li>
<?php $i++; endforeach; ?>
</ul>