<div class="footer-social-container">
    <div class="footer-social">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('follow_us')->toHtml(); ?>
        <div class="clear"></div>
    </div>
</div>
<div class="footer-container">
    <div class="aditional-footer">
	
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links')->toHtml(); ?>
	
	

        <?php echo $this->getChildHtml('bottomContainer') ?>
        <div class="f-right">
            <div class="footer-right">
                
                <div class="right-conteiner">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_time')->toHtml(); ?>
                    <?php if(themeOptions('topbtn')): ?>                    
                        <div id="message"><a href="#top" id="top-link"><?php echo $this->__('Back to top') ?></a></div> 
                    <?php endif; ?>
                    <div style="clear: both;"></div>
                </div>                
            </div>
        </div>
        
        <div class="f-left footer-left">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_shipping')->toHtml(); ?>
            <div class="right-conteiner">
                    <?php echo $this->getChildHtml('newsletter') ?>
                    <div class="clear"></div>
                </div>
        </div>
        <div style="clear: both;"></div>
    </div>  
	
	
	<div class="footer">
        <?php echo $this->getChildHtml('bottomContainer') ?>
        <div class="f-left">
            <?php //echo $this->getChildHtml('footer_links') ?><br />
            <?php echo $this->getCopyright() ?>&nbsp;&nbsp;
            <?php //echo $this->getChildHtml('cms_footer_links') ?>
        </div>
        <div class="f-right">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('verifi')->toHtml(); ?>
        </div>
    </div>
	
</div>  
    
