<div class="footer-social-container">
    <div class="footer-social">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('follow_us')->toHtml(); ?>
        <div class="clear"></div>
    </div>
</div>
<div class="footer-container">
    <div class="aditional-footer">
	
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links')->toHtml(); ?>
	
	<!--LINKS DEL FOOTER
<div class="shippingreturns">
<div class="shippingpolicy" style="width: 140px; float: left;">
<h4 style="font-weight: none !important;">Nuestras Ofertas</h4>
<ul class="policy">
<li><a href="#">New products</a></li>
<li><a href="#">Top sellers</a></li>
<li><a href="#">Specials</a></li>
<li><a href="#">Manufacturers</a></li>
<li><a href="#">Suppliers</a></li>
<li><a href="#">Specials</a></li>
<li><a href="#">Service</a></li>
</ul>
</div>
<div class="shippingpolicy" style="width: 150px; float: left;">
<h4 style="font-weight: none !important;">Informacion de envio</h4>
<ul class="policy"> 
<li><a href="#">Returns</a></li>
<li><a href="#">Delivery</a></li>
<li><a href="#">Service</a></li>
<li><a href="#">Gift Cards</a></li>
<li><a href="#">Mobile</a></li>
<li><a href="#">Gift Cards</a></li>
<li><a href="#">Manufacturers</a></li></ul></div>
<div class="shippingpolicy" style="width: 150px; float: left;">
<h4 style="font-weight: none !important;">Cuenta</h4>
<ul class="policy">
<li><a href="#">Your Account</a></li>
<li><a href="#">information</a></li>
<li><a href="#">Addresses</a></li>
<li><a href="#">Discount</a></li>
<li><a href="#">Orders history</a></li>
<li><a href="#">Addresses</a></li>
<li><a href="#">Search Terms</a></li></ul></div>
<div class="shippingpolicy" style="width: 150px; float: left;">
<h4 style="font-weight: none !important;">Soporte</h4>
<ul class="policy">
<li><a href="#">Site Map</a></li>
<li><a href="#">Search Terms</a></li>
<li><a href="#">Advanced Search</a></li>
<li><a href="#">Mobile</a></li>
<li><a href="#">Contact Us</a></li>
<li><a href="#">Mobile</a></li>
<li><a href="#">Addresses</a></li></ul></div></div>  -->

        <?php echo $this->getChildHtml('bottomContainer') ?>
        <div class="f-right">
            <div class="footer-right">
                <div class="right-conteiner">
                    <?php echo $this->getChildHtml('newsletter') ?>
                    <div class="clear"></div>
                </div>
                <div class="right-conteiner">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_time')->toHtml(); ?>
                    <?php if(themeOptions('topbtn')): ?>                    
                        <div id="message"><a href="#top" id="top-link"><?php echo $this->__('Back to top') ?></a></div> 
                    <?php endif; ?>
                    <div style="clear: both;"></div>
                </div>                
            </div>
        </div>
        
        <div class="f-left footer-left">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_shipping')->toHtml(); ?>
        </div>
        <div style="clear: both;"></div>
    </div>  
	
	
	<div class="footer">
        <?php echo $this->getChildHtml('bottomContainer') ?>
        <div class="f-left">
            <?php //echo $this->getChildHtml('footer_links') ?><br />
            <?php echo $this->getCopyright() ?>&nbsp;&nbsp;
            <?php //echo $this->getChildHtml('cms_footer_links') ?>
        </div>
        <div class="f-right">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('verifi')->toHtml(); ?>
        </div>
    </div>
	
</div>  
    
