<div id="top"></div>
<div class="header-container">
    <div class="header">
        
        <div class="header-left">
 <?php echo $this->getChildHtml('topBar') ?>
            
        </div>
        <div class="header-center">            
			
            <?php if ($this->getIsHomePage()):?>           
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php else:?>
			<a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif
		//Añadido el logo también en el else para que salga en toda la web
	     ?>
      <span class="welcome-msg"><?php echo $this->getWelcome() ?></span>
  	</div>        
        <div class="header-right">
		
            <div class="minicart">
                <?php echo $this->getChildHtml('top_cart') ?>
				<?php echo $this->getChildHtml('store_language') ?>	
            </div>  
			
            <?php echo $this->getChildHtml('currency') ?>  
            <div class="clear"></div>   
            <?php echo $this->getChildHtml('topLinks') ?>  
        </div>      
    </div>
    <?php echo $this->getChildHtml('topMenu') ?>
    
	
	<!--Añadimos el mini banner superior excepto en la home	-->
	<?php if (Mage::app()->getStore()->getStoreId()==2):?>
		<?php if ((Mage::getSingleton('cms/page')->getPageId()!='2') && (Mage::getSingleton('cms/page')->getPageId()!='10')): ?>
			<div class="promotion-bar"><a href="http://www.elitestore.es/sale"><img src=<?php echo ($this->getUrl('media',array('_secure'=>true)).'wysiwyg/final-clearance/minibanner-final-clearance.gif');?> alt="" /></a>
            <span style="float: right;font-size: 11px;"><?php echo $this->__('*Your 10% extra discount will be applied automatically during checkout!')?></span></div>
    	<?php endif ?>
	<?php elseif (Mage::app()->getStore()->getStoreId()==1):?>
    	<?php if ((Mage::getSingleton('cms/page')->getPageId()!='2') && (Mage::getSingleton('cms/page')->getPageId()!='10')): ?>
    		<div class="promotion-bar"><a href="http://www.elitestore.es/sale"><img src=<?php echo ($this->getUrl('media',array('_secure'=>true)).'wysiwyg/final-clearance/minibanner-final-clearance.gif');?> alt="" /></a><span style="float: right;font-size: 11px;"><?php echo $this->__('*Your 10% extra discount will be applied automatically during checkout!')?></span></div>
            
    	<?php endif ?>
    <?php endif; ?>
	<?php echo $this->getChildHtml('topBread') ?>
    <?php echo $this->getChildHtml('topContainer'); ?>
	
</div>