<?php   
class Elite_SuscribersPromo_Block_Index extends Mage_Core_Block_Template{   
	
	public function getCoupon(){
		$rule = Mage::getModel('salesrule/rule')->load(5); 
		$generator = Mage::getModel('salesrule/coupon_massgenerator');
		$generator->setFormat( Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_ALPHANUMERIC );
		$generator->setDash(0);
		$generator->setLength(8);
		$generator->setPrefix('');
		$generator->setSuffix('');
		$rule->setCouponCodeGenerator($generator);
		$rule->setCouponType( Mage_SalesRule_Model_Rule::COUPON_TYPE_AUTO );
		$coupon = $rule->acquireCoupon();
		$coupon->setType(Mage_SalesRule_Helper_Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED)->save();
		$code = $coupon->getCode();
		return $code;
	}
	
	public function sendCoupon($email,$nombre,$coupon,$storeId){
		$data= array('email'=>$email,
					'name'=> $nombre,
					'coupon'=>$coupon);
		$this->sendmail($data,$storeId);
	}

	public function sendmail($data,$storeId) {
		$translate = Mage::getSingleton('core/translate');
        $translate->setTranslateInline(false);
		$template = Mage::getStoreConfig('newsletter/suscriberspromo/email_template',$storeId);
		$mailTemplate = Mage::getModel('core/email_template');
		$sender = Mage::getStoreConfig('newsletter/suscriberspromo/email_identity',$storeId);
		$mailTemplate->setDesignConfig(array('area'=>'frontend', 'store'=>$storeId))
                ->sendTransactional(
                    $template,
					$sender,
					$data['email'],
					$data['name'],
					$data,
					$storeId
                );
		$translate->setTranslateInline(true);
		return $this;
	}
}