<?php
/**
 *
 * @category MultiSafepay
 * @package  MultiSafepay_Msp
 */
?>
<?php
/**
 * @see Mage_Checkout_Block_Agreements
 */
?>
<?php if (!$this->getAgreements()) return; ?>
<form action="" id="checkout-agreements" onsubmit="return false;">
    <?php foreach ($this->getAgreements() as $_a): ?>
        <div class="agreement-content"<?php echo ($_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '') ?>>
            <?php if ($_a->getIsHtml()): ?>
                <?php echo $_a->getContent() ?>
            <?php else: ?>
                <?php echo nl2br($this->htmlEscape($_a->getContent())) ?>
            <?php endif; ?>
        </div>
    <?php endforeach ?>
</form>
