<?php if ($this->getMode() == 'grid'): ?>
    <script type="text/javascript">
    //<![CDATA[
        var auctionTimeCounters = new Array();
        var i = 0;
    //]]>
    </script>	
    <?php $_productCollection = $this->getLoadedProductCollection() ?>
    <?php if (!$_productCollection->count()): ?>
        <div class="note-msg">
            <?php echo $this->__('There are no available products for auctioning at this time.') ?>
        </div>
    <?php else: ?>
        <?php 
            $_helper = $this->helper('catalog/output');
            $now_time = Mage::getModel('core/date')->timestamp(time());
            $modelAuction = Mage::getModel('auction/productauction');
            $showprice = Mage::getStoreConfig('auction/general/show_price');
            $delay = Mage::getStoreConfig('auction/general/delay_time');
            echo $this->getToolbarHtml();
        ?>
        <div class="listing-type-grid catalog-listing category-products" id="gridauction">
            <?php $_collectionSize = $_productCollection->count() ?>
            <?php $_columnCount = $this->getColumnCount(); ?>
            <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">

                <?php
                $i = 0;
                foreach ($_productCollection as $_product):
                    ?>
                    <?php $auction = $modelAuction->loadAuctionByProductId($_product->getId()) ?>
                    <?php $lastBid = $auction->getLastBid() ?>
                    <?php $totalBid = $auction->getTotalBid() ?>
                    <?php $currentPrice = $lastBid->getPrice() ? $lastBid->getPrice() : $auction->getInitPrice() ?>	
                    <?php $end_time = strtotime($auction->getEndTime() . ' ' . $auction->getEndDate()) ?>	
                    <?php $url_history = $this->getHistoryUrl($auction); ?>
                    <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image">
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210); ?>" 
                                 alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" 
                                 title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                        </a>
                        <div>
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                            <?php 
                                if($showprice!='0')
                                    echo $this->getPriceHtml($_product, true) 
                            ?>
                            <div class="timeleft" id="timeleft_<?php echo $_product->getId() ?>"> </div>	
                            <div id="auction_info_<?php echo $_product->getId() ?>">				
                                <div class="row"> <center>
                                        <span class="current_price" id="current_price<?php echo $_product->getId() ?>">
                                            <?php echo Mage::helper('core')->currency($currentPrice) ?>
                                        </span> </center>
                                    <div class="clear"></div>
                                </div>
                                <div class="row"> <center>
                                        <span class="bidder" id="bidder<?php echo $_product->getId() ?>">
                                            <?php echo $lastBid ? $lastBid->getBidderName() : $this->__('None') ?>
                                        </span> </center>
                                    <div class="clear"></div>
                                </div>	
                                <input type="hidden" id="codecolor<?php echo $_product->getId() ?>" name="codecolor" value="0"  >		
                                <input type="hidden" id="current_bid_id_<?php echo $_product->getId() ?>" value="<?php echo $lastBid->getId() ?>" />
                            </div>
                            <div id="results_update_auction_<?php echo $_product->getId() ?>" style="display:none;">
                            </div>
                        </div>
                        <script type="text/javascript">
                            //<![CDATA[
                        <?php
                        if (!is_numeric($delay)) {
                            $delay = 3;
                        }
                        ?>
                            auctionTimeCounters[i] = new AuctionTimeCounter('<?php echo $now_time ?>', '<?php echo $end_time ?>', '<?php echo $auction->getId() ?>', '<?php echo $this->__(' day, ') ?>', '<?php echo $this->__(' days, ') ?>', '<?php echo $this->__(' month, ') ?>', '<?php echo $this->__(' months, ') ?>', '<?php echo $this->__(' year, ') ?>', '<?php echo $this->__(' years, ') ?>');
                            auctionTimeCounters[i].setTimeleft('timeleft_<?php echo $_product->getId() ?>');
                            updateAuctionListInfo('auction_info_<?php echo $_product->getId() ?>', '<?php echo Mage::getBaseUrl('js') ?>magestore/auction.php?<?php echo http_build_query(array('tmpl' => 'auctionlistinfo')) ?>', '<?php echo $_product->getId() ?>', '<?php echo $auction->getId() ?>',<?php echo ($delay * 1000) ?>);
                                i++;
                                setBackground('current_price', '<?php echo $_product->getId() ?>');
                                setBackground('bidder', '<?php echo $_product->getId() ?>');
                                //]]>
                        </script>		
                        <div id="init_price<?php echo $_product->getId() ?>" style="display: none;">
                            <?php echo Mage::helper('core')->currency($auction->getInitPrice()) ?>
                        </div>
                    </li>

                <?php endforeach ?>
                    </ul>
                    <script type="text/javascript">
                        decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])
                <?php
                $baseCurrency = Mage::app()->getStore()->getBaseCurrency();
                $currCurrency = Mage::app()->getStore()->getCurrentCurrency();
                ?>
                var currencyConvert = new CurrencyConvert('<?php echo $baseCurrency->format(1000, array(), false) ?>', '<?php echo $currCurrency->format(1000, array(), false) ?>',<?php echo Mage::app()->getStore()->convertPrice(1) ?>);

            </script>
        </div>
        <?php echo $this->getToolbarHtml() ?>
    <?php endif; ?>
    <style type="text/css">	
    <?php echo Mage::getStoreConfig('auction/design/css') ?>
    </style>

<?php else: ?>
    <script type="text/javascript">
    //<![CDATA[
        var auctionTimeCounters = new Array();
        var i = 0;
    //]]>
    </script>	
    <?php $_productCollection = $this->getLoadedProductCollection() ?>
    <?php $_helper = $this->helper('catalog/output') ?>
        <?php if (!$_productCollection->count()): ?>
        <div class="note-msg">
        <?php echo $this->__('There are no available products for auctioning at this time.') ?>
        </div>
    <?php else: ?>
        <?php $_iterator = 0;
            $now_time = Mage::getModel('core/date')->timestamp(time()); 
            $modelAuction = Mage::getModel('auction/productauction');
            $showprice = Mage::getStoreConfig('auction/general/show_price');
            $delay = Mage::getStoreConfig('auction/general/delay_time');
            echo $this->getToolbarHtml() ?>
            <div class="category-products" id="listauction">
                <?php $_collectionSize = $_productCollection->count() ?>
                <ol class="products-list" id="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <?php $auction = $modelAuction->loadAuctionByProductId($_product->getId()) ?>
                    <?php $lastBid = $auction->getLastBid() ?>
                    <?php $totalBid = $auction->getTotalBid() ?>
                    <?php $currentPrice = $lastBid->getPrice() ? $lastBid->getPrice() : $auction->getInitPrice() ?>	
                    <?php $end_time = strtotime($auction->getEndTime() . ' ' . $auction->getEndDate()) ?>	
                    <?php $url_history = $this->getHistoryUrl($auction); ?>
                    <li class="item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif; ?>">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                        <div class="product-shop">
                            <div class="f-fix">
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                                <?php if($showprice!=0)
                                        echo $this->getPriceHtml($_product, true) 
                                ?>
                                <div class="clear">&nbsp;</div>
                                <div class="desc std">
                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="link-more"><?php echo $this->__('Learn More') ?></a>
                                </div>					
                                <div class="timeleft" id="timeleft_<?php echo $_product->getId() ?>"> </div>	
                                <div id="auction_info_<?php echo $_product->getId() ?>">				
                                    <div class="row">
                                        <span class="current_price" id="current_price<?php echo $_product->getId() ?>">
                                            <?php echo Mage::helper('core')->currency($currentPrice) ?>
                                        </span>
                                        <div class="clear">&nbsp;</div>
                                    </div>
                                    <div class="row">
                                        <span class="bidder" id="bidder<?php echo $_product->getId() ?>">
                                            <?php echo $lastBid ? $lastBid->getBidderName() : $this->__('None') ?>
                                        </span>
                                        <div class="clear">&nbsp;</div>
                                    </div>	
                                    <input type="hidden" id="codecolor<?php echo $_product->getId() ?>" name="codecolor" value="0"  >		
                                    <input type="hidden" id="current_bid_id_<?php echo $_product->getId() ?>" value="<?php echo $lastBid->getId() ?>" />
                                </div>
                                <div id="results_update_auction_<?php echo $_product->getId() ?>" style="display:none;"></div>
                            </div>
                        </div>
                    </li>
                    <script type="text/javascript">
                        //<![CDATA[
                        <?php
                        if (!is_numeric($delay)) {
                            $delay = 3;
                        }
                        ?>
                        auctionTimeCounters[i] = new AuctionTimeCounter('<?php echo $now_time ?>', '<?php echo $end_time ?>', '<?php echo $auction->getId() ?>', '<?php echo $this->__(' day, ') ?>', '<?php echo $this->__(' days, ') ?>', '<?php echo $this->__(' month, ') ?>', '<?php echo $this->__(' months, ') ?>', '<?php echo $this->__(' year, ') ?>', '<?php echo $this->__(' years, ') ?>');
                        auctionTimeCounters[i].setTimeleft('timeleft_<?php echo $_product->getId() ?>');
                        updateAuctionListInfo('auction_info_<?php echo $_product->getId() ?>', '<?php echo Mage::getBaseUrl('js') ?>magestore/auction.php?<?php echo http_build_query(array('tmpl' => 'auctionlistinfo')) ?>', '<?php echo $_product->getId() ?>', '<?php echo $auction->getId() ?>',<?php echo ($delay * 1000) ?>);
                            i++;
                            setBackground('current_price', '<?php echo $_product->getId() ?>');
                            setBackground('bidder', '<?php echo $_product->getId() ?>');
                            //]]>
                    </script>
                    <div id="init_price<?php echo $_product->getId() ?>" style="display: none;">
                    <?php echo Mage::helper('core')->currency($auction->getInitPrice()) ?>
                    </div>
                <?php endforeach ?>
            </ol>
            <script type="text/javascript">
                decorateGeneric($$('.grid-row'), ['last', 'odd', 'even']);

        <?php
        $baseCurrency = Mage::app()->getStore()->getBaseCurrency();
        $currCurrency = Mage::app()->getStore()->getCurrentCurrency();
        ?>
                var currencyConvert = new CurrencyConvert('<?php echo $baseCurrency->format(1000, array(), false) ?>', '<?php echo $currCurrency->format(1000, array(), false) ?>',<?php echo Mage::app()->getStore()->convertPrice(1) ?>);
            </script>
        </div>
        <?php echo $this->getToolbarHtml() ?>
    <?php endif; ?>

    <style type="text/css">	
    <?php echo Mage::getStoreConfig('auction/design/css') ?>
    </style>

<?php endif; ?>
