<?php if (($_shippingRateGroups = $this->getEstimateRates())): ?>
			
					<?php foreach ($_shippingRateGroups as $code => $_rates): ?>
						<dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
						<dd>
							<ul>
							<?php foreach ($_rates as $_rate): ?>
								<li<?php if ($_rate->getErrorMessage()) echo ' class="error-msg"';?>>
								   <?php if ($_rate->getErrorMessage()): ?>
										<?php echo $this->escapeHtml($_rate->getErrorMessage()) ?>
								   <?php else: ?>
										<input name="estimate_method" type="radio" value="<?php echo $this->escapeHtml($_rate->getCode()) ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio" />
										<label for="s_method_<?php echo $_rate->getCode() ?>"><span></span><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
										<?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
										<?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
										<?php echo $_excl; ?>
										<?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
											(<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
										<?php endif; ?>
										</label>
								   <?php endif ?>
								</li>
							<?php endforeach; ?>
							</ul>
						</dd>
					<?php endforeach; ?>
				</dl>
<?php endif; ?>