<?php


Mage::app()->loadArea('frontend');
$layout = Mage::getSingleton('core/layout');

//load default xml layout handle and generate blocks
$layout->getUpdate()->load('default'); 
$layout->generateXml()->generateBlocks();
$baseUrl = (isset($_POST['baseUrl']) ? $_POST['baseUrl'] : null);
$store_id = 2;//Mage::app()->getStore()->getStoreId();

$retorno = "";

?>
		<ul id="nav">

	        <li class="menu-principal">
	        	<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->load(1002)->getUrlPath(); ?>" class="menu-principal-a blanco"><?php echo $this->__('WOMEN'); ?></a>
	        	<div class="sheet">
	        		<ul>
	        		 <?php if(Mage::getStoreConfig('menu/women/women_link1_text')!=""){ ?>

						<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/women/women_link1_link'); ?>" 
							<?php 
								if(strtolower(Mage::getStoreConfig('menu/women/women_link1_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/women/women_link1_text'); ?></a>
	        			</li>

	        		 <?php }?>
	        		 <?php if(Mage::getStoreConfig('menu/women/women_link2_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/women/women_link2_link'); ?>"<?php 
								if(strtolower(Mage::getStoreConfig('menu/women/women_link2_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/women/women_link2_text'); ?></a>
	        			</li>

	        		 <?php }?>
	        		 <?php if(Mage::getStoreConfig('menu/women/women_link3_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/women/women_link3_link'); ?>"<?php 
								if(strtolower(Mage::getStoreConfig('menu/women/women_link3_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/women/women_link3_text'); ?></a>
	        			</li>

	        		 <?php }?>
	        		 <?php if(Mage::getStoreConfig('menu/women/women_link4_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/women/women_link4_link'); ?>"<?php 
								if(strtolower(Mage::getStoreConfig('menu/women/women_link4_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/women/women_link4_text'); ?></a>
	        			</li>

	        		 <?php }?>
	        		 <?php if(Mage::getStoreConfig('menu/women/women_link5_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/women/women_link5_link'); ?>"<?php 
								if(strtolower(Mage::getStoreConfig('menu/women/women_link5_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/women/women_link5_text'); ?></a>
	        			</li>

	        		 <?php }?>
	        		 <?php if(Mage::getStoreConfig('menu/women/women_link6_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/women/women_link6_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/women/women_link6_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/women/women_link6_text'); ?></a>
	        			</li>

	        		 <?php }?>	        			

	        		</ul>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/women/women_img1_img');?>"/>
	        					<div class="title">
	        						<?php echo Mage::getStoreConfig('menu/women/women_img1_title');?>
	        					</div>
	        					<div class="shop">
	        						<?php echo Mage::getStoreConfig('menu/women/women_img1_text');?>
	        					</div>
	        				</div>

	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/women/women_img2_img');?>"/>
	        					<div class="title">
	        						<?php echo Mage::getStoreConfig('menu/women/women_img2_title');?>
	        					</div>
	        					<div class="shop">
	        						<?php echo Mage::getStoreConfig('menu/women/women_img2_text');?>
	        					</div>
	        				</div>
	        	</div>
	        </li>
	        <li class="menu-principal">
	        	<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(1072)->getUrlPath(); ?>" class="menu-principal-a blanco"><?php echo $this->__('MEN'); ?></a>
	        	<div class="sheet">
	        		<ul>

	        		 <?php if(Mage::getStoreConfig('menu/men/men_link1_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/men/men_link1_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/men/women_link1_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/men/men_link1_text'); ?></a>
	        			</li>
	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/men/men_link2_text')!=""){ ?>

	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/men/men_link2_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/men/men_link2_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/men/men_link2_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/men/men_link3_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/men/men_link3_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/men/men_link3_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/men/men_link3_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/men/men_link4_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/men/men_link4_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/men/men_link4_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/men/men_link4_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/men/men_link5_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/men/men_link5_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/men/men_link5_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/men/men_link5_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/men/men_link6_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/men/men_link6_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/men/men_link6_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/men/men_link6_text'); ?></a>
	        			</li>

	        		<?php } ?>

	        		</ul>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/men/men_img1_img');?>"/>
	        					<div class="title">
	        						<?php echo Mage::getStoreConfig('menu/men/men_img1_title');?>
	        					</div>
	        					<div class="shop">
	        						<?php echo Mage::getStoreConfig('menu/men/men_img1_text');?>
	        					</div>
	        				</div>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/men/men_img2_img');?>"/>
	        					<div class="title">
	        						<?php echo Mage::getStoreConfig('menu/men/men_img2_title');?>
	        					</div>
	        					<div class="shop">
	        						<?php echo Mage::getStoreConfig('menu/men/men_img2_text');?>
	        					</div>
	        				</div>
	        		</div>
	        </li>
	        <li class="menu-principal">
	        	<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(1139)->getUrlPath(); ?>" class="menu-principal-a blanco"><?php echo $this->__('KIDS'); ?></a>
	        	<div class="sheet">
	        		<ul>

	        		<?php if(Mage::getStoreConfig('menu/kids/kids_link1_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/kids/kids_link1_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/kids/kids_link1_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/kids/kids_link1_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/kids/kids_link2_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/kids/kids_link2_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/kids/kids_link2_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/kids/kids_link2_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/kids/kids_link3_text')!=""){ ?>

	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/kids/kids_link3_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/kids/kids_link3_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/kids/kids_link3_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/kids/kids_link4_text')!=""){ ?>

	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/kids/kids_link4_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/kids/kids_link4_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/kids/kids_link4_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/kids/kids_link5_text')!=""){ ?>

	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/kids/kids_link5_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/kids/kids_link5_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/kids/kids_link5_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/kids/kids_link6_text')!=""){ ?>

	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/kids/kids_link6_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/kids/kids_link6_text'))==strtolower("SALE")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/kids/kids_link6_text'); ?></a>
	        			</li>

	        		<?php } ?>

	        		</ul>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/kids/kids_img1_img');?>"/>
	        					<div class="title">
	        						<?php echo Mage::getStoreConfig('menu/kids/kids_img1_title');?>
	        					</div>
	        					<div class="shop">
	        						<?php echo Mage::getStoreConfig('menu/kids/kids_img1_text');?>
	        					</div>
	        				</div>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/kids/kids_img2_img');?>"/>
	        					<div class="title">
	        						<?php echo Mage::getStoreConfig('menu/kids/kids_img2_title');?>
	        					</div>
	        					<div class="shop">
	        						<?php echo Mage::getStoreConfig('menu/kids/kids_img2_text');?>
	        					</div>
	        				</div>
	        		</div>
	        </li>
	        <li class="menu-principal">
	        	<a href="<?php echo $baseUrl. 'manufacturer/';?>" class="menu-principal-a blanco"><?php echo $this->__('DESIGNERS'); ?></a>
	        	<div class="sheet designers" id="design">
	        		<div class="lista">	
		        		<div class="title">
	        				<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(11)->getUrlPath(); ?>"><?php echo $this->__('FEATURED DESIGNERS'); ?></a>
	        			</div>
		        			<ul>

	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link1_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_featured_link1_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link1_text'); ?></a>
	        					</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link2_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_featured_link2_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link2_text'); ?></a>
	        					</li>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link3_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_featured_link3_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link3_text'); ?></a>
	        					</li>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link4_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_featured_link4_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link4_text'); ?></a>
	        					</li>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link5_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_featured_link5_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link5_text'); ?></a>
	        					</li>
		        			</ul>
		        			<ul>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link6_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_featured_link6_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link6_text'); ?></a>
	        					</li>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link7_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_featured_link7_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link7_text'); ?></a>
	        					</li>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link8_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_featured_link8_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link8_text'); ?></a>
	        					</li>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link9_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_featured_link9_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link9_text'); ?></a>
	        					</li>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link10_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_featured_link10_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link10_text'); ?></a>
	        					</li>

	        		<?php } ?>

		        			</ul>
		        		</div>
		        	<div class="lista">	
		        		<div class="title">
	        				<a href="<?php echo $baseUrl.'designer-of-week/'; ?>"><?php echo $this->__('DESIGNERS OF THE WEEK'); ?></a>
	        			</div>
		        		
		        			<ul>

	        		<?php if(Mage::getStoreConfig('menu/designers/designers_week_link1_link')!=""){ ?>

		        				<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_week_link1_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_week_link1_text'); ?><?php if(Mage::getStoreConfig('menu/designers/designers_week_link1_new')) echo '<div class="new-design">NEW</div>'?></a>
	        					</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_week_link2_link')!=""){ ?>
			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_week_link2_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_week_link2_text'); ?>
	        							<?php 
	        								$variable = Mage::getStoreConfig('menu/designers/designers_week_link2_new');	
	        									echo '<div class="new-design">NEW</div>';
	        							?>
	        								
	        						</a>
	        					</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_week_link3_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_week_link3_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_week_link3_text'); ?><?php if(Mage::getStoreConfig('menu/designers/designers_week_link3_new')) echo '<div class="new-design">NEW</div>'?></a>
	        					</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_week_link4_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_week_link4_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_week_link4_text'); ?><?php if(Mage::getStoreConfig('menu/designers/designers_week_link4_new')) echo '<div class="new-design">NEW</div>'?></a>
	        					</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_week_link5_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_week_link5_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_week_link5_text'); ?><?php if(Mage::getStoreConfig('menu/designers/designers_week_link5_new')) echo '<div class="new-design">NEW</div>'?></a>
	        					</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_week_link6_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::getStoreConfig('menu/designers/designers_week_link6_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_week_link6_text'); ?><?php if(Mage::getStoreConfig('menu/designers/designers_week_link6_new')) echo '<div class="new-design">NEW</div>'?></a>
	        					</li>

	        		<?php } ?>
		        			</ul>
		        		</div>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/designers/designers_img1_img');?>"/>
	        					<div class="title">
	        						<?php echo Mage::getStoreConfig('menu/designers/designers_img1_title'); ?>
	        					</div>
	        					<div class="shop">
	        						<?php echo Mage::getStoreConfig('menu/designers/designers_img1_text'); ?>
	        					</div>
	        				</div>
	        		</div>
	        </li>
	        <li class="menu__principal__sinsabana">
	        	<a href="<?php echo $baseUrl . '../../blog2/';?>" class="menu-principal-a blanco"><?php echo $this->__('ELITE UNIVERSE'); ?></a>
	        </li>
	        <li class="menu__principal__sinsabana">
	        	<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(1150)->getUrlPath(); ?>" class="menu-principal-a rojo"><?php echo $this->__('SALE'); ?></a>
	        </li>
	        <li class="menu__principal__sinsabana">
	        	<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->setStoreId($store_id)->load(1298)->getUrlPath(); ?>" class="menu-principal-a blanco"><?php echo $this->__('OUTLET'); ?></a>
	        </li>
		</ul>