<?php

Mage::app()->loadArea('frontend');
$layout = Mage::getSingleton('core/layout');

//load default xml layout handle and generate blocks
$layout->getUpdate()->load('default'); 
$layout->generateXml()->generateBlocks();
$baseUrl = (isset($_POST['baseUrl']) ? $_POST['baseUrl'] : null);


$retorno = "";

?>
		<ul id="nav" class="desktop">

	        <li class="menu-principal">
	        	<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->load(1002)->getUrlPath(); ?>" title="<?php echo Mage::getStoreConfig('eliteseo/eliteseolinktitles/link_mujer')?>"><?php echo Mage::getModel('catalog/category')->load(1002)->getName(); ?></a>
	        	<div class="sheet">
	        		<ul>
	        		 <?php if(Mage::getStoreConfig('menu/women/women_link1_text')!=""){ ?>

						<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/women/women_link1_link'); ?>" 
							<?php 
								if(strtolower(Mage::getStoreConfig('menu/women/women_link1_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/women/women_link1_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/women/women_link1_text'); ?></a>
	        			</li>

	        		 <?php }?>
	        		 <?php if(Mage::getStoreConfig('menu/women/women_link2_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/women/women_link2_link'); ?>"<?php 
								if(strtolower(Mage::getStoreConfig('menu/women/women_link2_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/women/women_link2_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/women/women_link2_text'); ?></a>
	        			</li>

	        		 <?php }?>
	        		 <?php if(Mage::getStoreConfig('menu/women/women_link3_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/women/women_link3_link'); ?>"<?php 
								if(strtolower(Mage::getStoreConfig('menu/women/women_link3_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/women/women_link3_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/women/women_link3_text'); ?></a>
	        			</li>

	        		 <?php }?>
	        		 <?php if(Mage::getStoreConfig('menu/women/women_link4_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/women/women_link4_link'); ?>"<?php 
								if(strtolower(Mage::getStoreConfig('menu/women/women_link4_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/women/women_link4_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/women/women_link4_text'); ?></a>
	        			</li>

	        		 <?php }?>
	        		 <?php if(Mage::getStoreConfig('menu/women/women_link5_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/women/women_link5_link'); ?>"<?php 
								if(strtolower(Mage::getStoreConfig('menu/women/women_link5_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/women/women_link5_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/women/women_link5_text'); ?></a>
	        			</li>

	        		 <?php }?>
	        		 <?php if(Mage::getStoreConfig('menu/women/women_link6_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/women/women_link6_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/women/women_link6_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/women/women_link6_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/women/women_link6_text'); ?></a>
	        			</li>

	        		 <?php }?>	 
					 <?php if(Mage::getStoreConfig('menu/women/women_link7_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/women/women_link7_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/women/women_link7_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/women/women_link7_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/women/women_link7_text'); ?></a>
	        			</li>

	        		 <?php }?>	
					 <?php if(Mage::getStoreConfig('menu/women/women_link8_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/women/women_link8_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/women/women_link8_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/women/women_link8_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/women/women_link8_text'); ?></a>
	        			</li>

	        		 <?php }?>						 

	        		</ul>
                    <div class="temp">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/women/women_img1_img');?>"/>
                        <div class="title">
                            <?php echo Mage::getStoreConfig('menu/women/women_img1_title');?>
                        </div>
                        <a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/women/women_img1_link'); ?>">
                            <div class="shop">
                                <?php echo Mage::getStoreConfig('menu/women/women_img1_text');?>
                            </div>
                        </a>
                    </div>
                    <div class="temp">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/women/women_img2_img');?>"/>
                        <div class="title">
                            <?php echo Mage::getStoreConfig('menu/women/women_img2_title');?>
                        </div>
                        <a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/women/women_img2_link'); ?>">
                            <div class="shop">
                                <?php echo Mage::getStoreConfig('menu/women/women_img2_text');?>
                            </div>
                        </a>
                    </div>
                </div>
	        </li>
	        <li class="menu-principal">
	        	<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->load(1072)->getUrlPath(); ?>" title="<?php echo Mage::getStoreConfig('eliteseo/eliteseolinktitles/link_hombre')?>"><?php echo Mage::getModel('catalog/category')->load(1072)->getName(); ?></a>
	        	<div class="sheet">
	        		<ul>

	        		 <?php if(Mage::getStoreConfig('menu/men/men_link1_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/men/men_link1_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/men/women_link1_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/men/women_link1_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/men/men_link1_text'); ?></a>
	        			</li>
	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/men/men_link2_text')!=""){ ?>

	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/men/men_link2_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/men/men_link2_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/men/men_link2_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/men/men_link2_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/men/men_link3_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/men/men_link3_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/men/men_link3_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/men/men_link3_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/men/men_link3_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/men/men_link4_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/men/men_link4_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/men/men_link4_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/men/men_link4_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/men/men_link4_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/men/men_link5_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/men/men_link5_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/men/men_link5_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/men/men_link5_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/men/men_link5_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/men/men_link6_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/men/men_link6_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/men/men_link6_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/men/men_link6_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/men/men_link6_text'); ?></a>
	        			</li>

	        		<?php } ?>
					<?php if(Mage::getStoreConfig('menu/men/men_link7_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/men/men_link7_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/men/men_link7_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/men/men_link7_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/men/men_link7_text'); ?></a>
	        			</li>

	        		<?php } ?>
					<?php if(Mage::getStoreConfig('menu/men/men_link8_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/men/men_link8_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/men/men_link8_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/men/men_link8_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/men/men_link8_text'); ?></a>
	        			</li>

	        		<?php } ?>

	        		</ul>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/men/men_img1_img');?>"/>
	        					<div class="title">
	        						<?php echo Mage::getStoreConfig('menu/men/men_img1_title');?>
	        					</div>
                                <a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/men/men_img1_link'); ?>">
                                    <div class="shop">
                                        <?php echo Mage::getStoreConfig('menu/men/men_img1_text');?>
                                    </div>
                                </a>
	        				</div>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/men/men_img2_img');?>"/>
	        					<div class="title">
	        						<?php echo Mage::getStoreConfig('menu/men/men_img2_title');?>
	        					</div>
                                <a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/men/men_img2_link'); ?>">
                                    <div class="shop">
                                        <?php echo Mage::getStoreConfig('menu/men/men_img2_text');?>
                                    </div>
                                </a>
	        				</div>
	        		</div>
	        </li>
	        <li class="menu-principal">
	        	<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->load(1139)->getUrlPath(); ?>" title="<?php echo Mage::getStoreConfig('eliteseo/eliteseolinktitles/link_kids')?>"><?php echo Mage::getModel('catalog/category')->load(1139)->getName(); ?></a>
	        	<div class="sheet">
	        		<ul>

	        		<?php if(Mage::getStoreConfig('menu/kids/kids_link1_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/kids/kids_link1_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/kids/kids_link1_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/kids/kids_link1_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/kids/kids_link1_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/kids/kids_link2_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/kids/kids_link2_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/kids/kids_link2_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/kids/kids_link2_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/kids/kids_link2_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/kids/kids_link3_text')!=""){ ?>

	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/kids/kids_link3_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/kids/kids_link3_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/kids/kids_link3_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/kids/kids_link3_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/kids/kids_link4_text')!=""){ ?>

	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/kids/kids_link4_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/kids/kids_link4_text'))==strtolower("SALE")||
                                    strtolower(Mage::getStoreConfig('menu/kids/kids_link4_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/kids/kids_link4_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/kids/kids_link5_text')!=""){ ?>

	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/kids/kids_link5_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/kids/kids_link5_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/kids/kids_link5_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/kids/kids_link5_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/kids/kids_link6_text')!=""){ ?>

	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/kids/kids_link6_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/kids/kids_link6_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/kids/kids_link6_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/kids/kids_link6_text'); ?></a>
	        			</li>

	        		<?php } ?>
					<?php if(Mage::getStoreConfig('menu/kids/kids_link7_text')!=""){ ?>

	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/kids/kids_link7_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/kids/kids_link7_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/kids/kids_link7_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/kids/kids_link7_text'); ?></a>
	        			</li>

	        		<?php } ?>
					<?php if(Mage::getStoreConfig('menu/kids/kids_link8_text')!=""){ ?>

	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/kids/kids_link8_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/kids/kids_link8_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/kids/kids_link8_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/kids/kids_link8_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		</ul>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/kids/kids_img1_img');?>"/>
	        					<div class="title">
	        						<?php echo Mage::getStoreConfig('menu/kids/kids_img1_title');?>
	        					</div>
                                <a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/kids/kids_img1_link'); ?>">
                                    <div class="shop">
                                        <?php echo Mage::getStoreConfig('menu/kids/kids_img1_text');?>
                                    </div>
                                </a>
	        				</div>
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/kids/kids_img2_img');?>"/>
	        					<div class="title">
	        						<?php echo Mage::getStoreConfig('menu/kids/kids_img2_title');?>
	        					</div>
                                <a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/kids/kids_img1_link'); ?>">
                                    <div class="shop">
                                        <?php echo Mage::getStoreConfig('menu/kids/kids_img2_text');?>
                                    </div>
                                </a>
	        				</div>
	        		</div>
	        </li>
	        <li class="menu-principal">
	        	<a href="<?php echo $baseUrl. 'manufacturer/';?>" title="<?php echo Mage::getStoreConfig('eliteseo/eliteseolinktitles/link_designers')?>"><?php echo  $this->__('DESIGNERS'); ?></a>
	        	<div class="sheet designers" id="design">
	        		<div class="lista">	
		        		<div class="title">
	        				<?php echo $this->__('FEATURED DESIGNERS'); ?>
	        			</div>
		        			<ul>

	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link1_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_featured_link1_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link1_text'); ?></a>
	        					</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link2_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_featured_link2_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link2_text'); ?></a>
	        					</li>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link3_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_featured_link3_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link3_text'); ?></a>
	        					</li>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link4_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_featured_link4_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link4_text'); ?></a>
	        					</li>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link5_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_featured_link5_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link5_text'); ?></a>
	        					</li>
		        			</ul>
		        			<ul>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link6_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_featured_link6_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link6_text'); ?></a>
	        					</li>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link7_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_featured_link7_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link7_text'); ?></a>
	        					</li>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link8_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_featured_link8_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link8_text'); ?></a>
	        					</li>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link9_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_featured_link9_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link9_text'); ?></a>
	        					</li>


	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link10_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_featured_link10_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link10_text'); ?></a>
	        					</li>

	        		<?php } ?>

		        			</ul>
		        		</div>
		        	<div class="lista">	
		        		<div class="title">
	        				<?php echo $this->__('DESIGNERS OF THE WEEK'); ?>
	        			</div>
		        		
		        			<ul>

	        		<?php if(Mage::getStoreConfig('menu/designers/designers_week_link1_link')!=""){ ?>

		        				<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_week_link1_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_week_link1_text'); ?><?php if(Mage::getStoreConfig('menu/designers/designers_week_link1_new')) echo '<div class="new-design">NEW</div>'?></a>
	        					</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_week_link2_link')!=""){ ?>
                        <li>
                            <a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_week_link2_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_week_link2_text'); ?><?php if(Mage::getStoreConfig('menu/designers/designers_week_link2_new')) echo '<div class="new-design">NEW</div>'?></a>
                        </li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_week_link3_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_week_link3_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_week_link3_text'); ?><?php if(Mage::getStoreConfig('menu/designers/designers_week_link3_new')) echo '<div class="new-design">NEW</div>'?></a>
	        					</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_week_link4_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_week_link4_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_week_link4_text'); ?><?php if(Mage::getStoreConfig('menu/designers/designers_week_link4_new')) echo '<div class="new-design">NEW</div>'?></a>
	        					</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_week_link5_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_week_link5_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_week_link5_text'); ?><?php if(Mage::getStoreConfig('menu/designers/designers_week_link5_new')) echo '<div class="new-design">NEW</div>'?></a>
	        					</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/designers/designers_week_link6_link')!=""){ ?>

			        			<li>
	        						<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_week_link6_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_week_link6_text'); ?><?php if(Mage::getStoreConfig('menu/designers/designers_week_link6_new')) echo '<div class="new-design">NEW</div>'?></a>
	        					</li>

	        		<?php } ?>
		        			</ul>
						</div>
						<div class="designers__flotante">
						<?php if(Mage::getStoreConfig('menu/designers/designers_featured_link11_text')!=""){ ?>
								<span>
									<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_featured_link11_link'); ?>" class="gris"><?php echo Mage::getStoreConfig('menu/designers/designers_featured_link11_text'); ?></a>
								</span>

						<?php } ?>
						</div>
		        		
	        				<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/designers/designers_img1_img');?>"/>
	        					<div class="title">
	        						<?php echo Mage::getStoreConfig('menu/designers/designers_img1_title'); ?>
	        					</div>
                                <a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/designers/designers_img1_link'); ?>">
                                    <div class="shop">
                                        <?php echo Mage::getStoreConfig('menu/designers/designers_img1_text'); ?>
                                    </div>
                                </a>
	        				</div>
	        		</div>
	        </li>
	        <li class="menu-principal">
	        	<a href="<?php echo $baseUrl . 'our-story';?>" title="<?php echo Mage::getStoreConfig('eliteseo/eliteseolinktitles/link_universoelite')?>"><?php echo  $this->__('ELITE UNIVERSE'); ?></a>
	        	<div class="sheet" id="euniverse">
	        		<ul>

	        		 <?php if(Mage::getStoreConfig('menu/universe/universe_link1_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/universe/universe_link1_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/universe/universe_link1_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/universe/universe_link1_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/universe/universe_link1_text'); ?></a>
	        			</li>
	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/universe/universe_link2_text')!=""){ ?>

	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/universe/universe_link2_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/universe/universe_link2_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/universe/universe_link2_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/universe/universe_link2_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/universe/universe_link3_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/universe/universe_link3_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/universe/universe_link3_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/universe/universe_link3_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/universe/universe_link3_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/universe/universe_link4_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/universe/universe_link4_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/universe/universe_link4_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/universe/universe_link4_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/universe/universe_link4_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/universe/universe_link5_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/universe/universe_link5_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/universe/universe_link5_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/universe/universe_link5_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/universe/universe_link5_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/universe/universe_link6_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/universe/universe_link6_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/universe/universe_link6_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/universe/universe_link6_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/universe/universe_link6_text'); ?></a>
	        			</li>

	        		<?php } ?>
					<?php if(Mage::getStoreConfig('menu/universe/universe_link7_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/universe/universe_link7_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/universe/universe_link7_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/universe/universe_link7_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/universe/universe_link7_text'); ?></a>
	        			</li>

	        		<?php } ?>
					<?php if(Mage::getStoreConfig('menu/universe/universe_link8_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::getStoreConfig('menu/universe/universe_link8_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/universe/universe_link8_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/universe/universe_link8_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/universe/universe_link8_text'); ?></a>
	        			</li>

	        		<?php } ?>

	        		</ul>
	        				<div class="temp">

									<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/universe/universe_img1_img');?>"/>
									<div class="title">
										<?php echo Mage::getStoreConfig('menu/universe/universe_img1_title');?>
									</div>
                                <a href="<?php echo Mage::getStoreConfig('menu/universe/universe_img1_link');?>">
									<div class="shop">
										<?php echo Mage::getStoreConfig('menu/universe/universe_img1_text');?>
									</div>
								</a>
	        				</div>
	        				<div class="temp">

									<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/universe/universe_img2_img');?>"/>
									<div class="title">
										<?php echo Mage::getStoreConfig('menu/universe/universe_img2_title');?>
									</div>
                                <a href="<?php echo Mage::getStoreConfig('menu/universe/universe_img2_link');?>">
									<div class="shop">
										<?php echo Mage::getStoreConfig('menu/universe/universe_img2_text');?>
									</div>
								</a>
	        				</div>
	        		</div>
	        </li>
	        <li class="menu-principal sinwidth">
	        	<a href="<?php echo $baseUrl.Mage::getModel('catalog/category')->load(1298)->getUrlPath();?>" title="<?php echo Mage::getStoreConfig('eliteseo/eliteseolinktitles/link_ofertasexclusivas')?>"><?php echo $this->__('EXCLUSIVE OFFERS'); ?></a>
				<div class="sheet" id="exclusive">
				<div class="exclusiveblock">
				<div class="secciones yellow">
	        		<ul>

	        		<?php if(Mage::getStoreConfig('menu/exclusive/exclusive_link1_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/exclusive/exclusive_link1_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/exclusive/exclusive_link1_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/exclusive/exclusive_link1_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/exclusive/exclusive_link1_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/exclusive/exclusive_link2_text')!=""){ ?>
	        			
	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/exclusive/exclusive_link2_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/exclusive/exclusive_link2_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/exclusive/exclusive_link2_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/exclusive/exclusive_link2_text'); ?></a>
	        			</li>

	        		<?php } ?>
	        		<?php if(Mage::getStoreConfig('menu/exclusive/exclusive_link3_text')!=""){ ?>

	        			<li>
	        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl() . Mage::getStoreConfig('menu/exclusive/exclusive_link3_link'); ?>" <?php 
								if(strtolower(Mage::getStoreConfig('menu/exclusive/exclusive_link3_text'))==strtolower("SALE")||strtolower(Mage::getStoreConfig('menu/exclusive/exclusive_link3_text'))==strtolower("REBAJAS")) 
								{
									echo"class ='rojo'"; 
								}
									
								else 
								{
									echo"class ='gris'";
								}
							?>><?php echo Mage::getStoreConfig('menu/exclusive/exclusive_link3_text'); ?></a>
	        			</li>

	        		<?php } ?>
							
					</ul>
				</div>
					<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/exclusive/exclusive_img1_img');?>"/>
	        					<div class="title">
	        						<?php echo Mage::getStoreConfig('menu/exclusive/exclusive_img1_title');?>
	        					</div>
	        					<div class="shop">
	        						<?php echo Mage::getStoreConfig('menu/exclusive/exclusive_img1_text');?>
	        					</div>
	        				</div>
					</div>
					<div class="exclusiveblock">

							<div class="temp">
	        					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "banners/" .Mage::getStoreConfig('menu/exclusive/exclusive_img2_img');?>"/>
	        					<div class="title">
	        						<?php echo Mage::getStoreConfig('menu/exclusive/exclusive_img2_title');?>
	        					</div>
	        					<div class="shop">
	        						<?php echo Mage::getStoreConfig('menu/exclusive/exclusive_img2_text');?>
	        					</div>
	        				</div>					
	        	</div>
	        </li>
		</ul>
		
		<script>
		
		
		</script>