<?php
/**
 * Onepage Checkout Login Template for Community Edition 1.4 - 1.6.2
 * 
 * @author     Design:Slider GbR <magento@design-slider.de>
 * @copyright  (C)Design:Slider GbR <www.design-slider.de>
 * @license    OSL <http://opensource.org/licenses/osl-3.0.php>
 * @link       http://www.design-slider.de/magento-onlineshop/magento-extensions/private-sales/
 * @package    DS_PrivateSales
 */

$helper = Mage::helper('privatesales');
/* @var $helper DS_PrivateSales_Helper_Data */

$isForgotPasswordEnabled = $helper->canShowForgotPassword();
$isRegistrationEnabled = $helper->canShowRegistration();
?>
<div<?php if ($this->getQuote()->isAllowedGuestCheckout() || $isRegistrationEnabled): ?> class="col2-set"<?php endif; ?>>
    <?php echo $this->getChildHtml('login_before')?>

    <?php if ($this->getQuote()->isAllowedGuestCheckout() || $isRegistrationEnabled): ?>
        <div class="col-1">

        <?php if ($isRegistrationEnabled): ?>
            <h3><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo Mage::helper('checkout')->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo Mage::helper('checkout')->__('Register to Create an Account') ?><?php endif; ?></h3>
        <?php elseif ($this->getQuote()->isAllowedGuestCheckout()): ?>
            <h3><?php echo Mage::helper('checkout')->__('Checkout as Guest') ?></h3>
        <?php endif; ?>

        <?php if ($isRegistrationEnabled): ?>
            <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <p><?php echo Mage::helper('checkout')->__('Register with us for future convenience:') ?></p>
            <?php else: ?>
                <p><strong><?php echo Mage::helper('checkout')->__('Register and save time!') ?></strong><br />
                <?php echo Mage::helper('checkout')->__('Register with us for future convenience:') ?></p>
                <ul>
                    <li><?php echo Mage::helper('checkout')->__('Fast and easy check out') ?></li>
                    <li><?php echo Mage::helper('checkout')->__('Easy access to your order history and status') ?></li>
                </ul>
            <?php endif; ?>
        <?php endif; ?>

        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <ul class="form-list">
                <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <li class="control">
                    <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo Mage::helper('checkout')->__('Checkout as Guest') ?></label>
                </li>
                <?php endif; ?>

                <?php if ($isRegistrationEnabled): ?>
                    <li class="control">
                        <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" /><label for="login:register"><?php echo Mage::helper('checkout')->__('Register') ?></label>
                    </li>
                <?php endif; ?>

            </ul>
            
            <?php if ($isRegistrationEnabled): ?>
                <h4><?php echo Mage::helper('checkout')->__('Register and save time!') ?></h4>
                <p><?php echo Mage::helper('checkout')->__('Register with us for future convenience:') ?></p>
                <ul class="ul">
                    <li><?php echo Mage::helper('checkout')->__('Fast and easy check out') ?></li>
                    <li><?php echo Mage::helper('checkout')->__('Easy access to your order history and status') ?></li>
                </ul>
            <?php endif; ?>

        <?php elseif ($isRegistrationEnabled): ?>
            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
        <?php endif; ?>
    </div>
    <?php endif; ?>

    <div class="col-2">
        <h3><?php echo Mage::helper('checkout')->__('Login') ?></h3>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
        <fieldset>
            <h4><?php echo Mage::helper('checkout')->__('Already registered?') ?></h4>
            <p><?php echo Mage::helper('checkout')->__('Please log in below:') ?></p>
            <ul class="form-list">
                <li>
                    <label for="login-email" class="required"><em>*</em><?php echo Mage::helper('checkout')->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                    </div>
                </li>
                <li>
                    <label for="login-password" class="required"><em>*</em><?php echo Mage::helper('checkout')->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                    </div>
                </li>
            </ul>
        </fieldset>
        </form>
    </div>
</div>
<div<?php if ($this->getQuote()->isAllowedGuestCheckout() || $isRegistrationEnabled): ?> class="col2-set"<?php endif; ?>>
    <?php if ($this->getQuote()->isAllowedGuestCheckout() || $isRegistrationEnabled): ?>
        <div class="col-1">
            <div class="buttons-set">
                <p class="required">&nbsp;</p>
                <button type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo ($this->getQuote()->isAllowedGuestCheckout() ? Mage::helper('checkout')->__('Continue') : Mage::helper('checkout')->__('Register')) ?></span></span></button>
            </div>
        </div>
    <?php endif; ?>
    <div class="col-2">
        <div class="buttons-set">
            <p class="required"><?php echo Mage::helper('checkout')->__('* Required Fields') ?></p>
            
            <?php if ($isForgotPasswordEnabled): ?>
                <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo Mage::helper('checkout')->__('Forgot your password?') ?></a>
            <?php endif; ?>

            <button type="submit" class="button" onclick="onepageLogin(this)"><span><span><?php echo Mage::helper('checkout')->__('Login') ?></span></span></button>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
