<?php
/**
 * Survey for Magento
 *
 * @category   Belitsoft
 * @package    Belitsoft_Survey
 * @author     Belitsoft <bits@belitsoft.com>
 */

/* @var $this Belitsoft_Survey_Block_Frontend_Report_Ranking */
?><div class="entry-edit survey-info">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">
			<?php echo $this->getCurrentQuestion()->getQuestionText(); ?>
		</h4>
	</div>
	<div class="fieldset fieldset-wide" id="base_fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list"><tbody>
			<?php foreach($this->getCurrentQuestion()->getFieldsObjects() as $field): ?>
			<tr>
				<td class="label survey-quest-title"><?php echo $field->getFieldText(); ?></td>
	    		<td class="value survey-quest-value"><?php echo $this->getRankingAnswer($field); ?></td>
    		</tr>
			<?php endforeach; ?>
			</tbody></table>
		</div>
	</div>
</div>