
<div title="Armani" class="home--slide">
	<video width="100%" autoplay loop class="video">
	  <source src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>wysiwyg/ss16/Armani_sin_audio-max.mp4" type="video/mp4">
	Your browser does not support the video tag.
	</video>
		<div class="botonera">
			<a href="http://www.elitestore.es/women/bags-for-women.html?dir=asc&manufacturer=631&order=position">
				<div class="boton izq">SHOP NOW</div>
			</a>
		</div>
</div>

<a title="SUNGLASSES" href="<?php echo Mage::getModel('catalog/category')->load(92)->getUrl(); ?>"  class="home--left">
	<div class="home--left--triangle">SHOE SPOTLIGHT: SLIP ON<br/>
		<span>Sports luxe &amp; versatility to the max</span>
	</div>
</a>

<a title="PALAZZO EMPIRE" href="<?php echo Mage::getModel('catalog/category')->load(61)->getUrl(); ?>?manufacturer=663"  class="home--right">
	<div class="home--right--triangle">PALAZZO EMPIRE<br/>
		<span>Versace ultimate iconic accessory</span>
	</div>
</a>

<a title="MYKITA x ELITE" class="home--img" href="<?php echo Mage::getModel('catalog/product')->load(69922)->getProductUrl(); ?>" >
	<div class="home--img--text"><span class="subirtexto">EXCLUSIVE: <br/><br/></span>LIMITED EDITION<span><br/><br/>Only 20 pairs worldwide!</span>
	</div>
</a>
<a title="WEDGES" class="home--img--two" href="<?php echo Mage::getModel('catalog/category')->load(177)->getUrl(); ?>">
	<div class="home--img--left--text">TRENDING: WEDGES<span><br/><br/>One of each please!</span>
	</div>
</a>

<a title="EMILIO PUCCI" href="<?php echo Mage::getModel('catalog/category')->load(23)->getUrl(); ?>?manufacturer=659" class="home--right--last" >
	<div class="home--right--last--text">
		<br/>EMILIO PUCCI<br/>
		<em>Nonchalance as an attitude: The Pilot Episode by Massimo Giorgetti</em>
	</div>
</a>

<a title="ROBERTO CAVALLI" style="float:right;margin-bottom:10px"  href="<?php echo Mage::getModel('catalog/category')->load(62)->getUrl(); ?>?manufacturer=3100" class="home--left--last">
	<div class="home--left--triangle">
		<br/>ROBERTO CAVALLI<br/>
		<em>Free-spirited seventies vibes with a rebellious touch of rock’n’roll</em>
	</div>
</a>