<?php $paisesUE = array ('DE','AT','BE','BG','CY','HR','DK','SK','SI','ES','EE','FI','FR','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','UK','CZ','RO','SE','GB'); ?>
<?php $paisCustomer = Mage::getSingleton('geoip/country')->getCountry(); ?>
<?php 
$precio=0;
if(in_array($paisCustomer, $paisesUE)):
	$precio=252 . "€";
else: 
	$precio=208.26 . "€";
endif;
$marca="Adidas By Kanye West";
$titulo="Yeezy Boost 350 Moonrock";
?>
<style>
    .box {
        padding: 5px;
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        background: rgba(15,15,15,0.2);
    }
    .cerrar{
        position: absolute;
        right: 14px;
		top: 0;
        font-size: 2em;
        cursor: pointer;
    }
</style>
<?php if($_GET['mensa']):?>
<div id="messages_product_view"><ul class="messages"><li class="success-msg"><ul><li><span>Thanks for your contact.</span></li></ul></li></ul></div>
<?php
endif;
?>
<div style="width:100%; text-align: right; background:url('<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-boost-350.png') no-repeat left center, #fff;height: 342px;">
<div style="float:right; margin: 126px 60px 0px 0px;;">
    <span style=" color: grey; font: lighter 3.5em/100% 'Open Sans';">YEEZY BOOST 350</span><br/>
    <span style="font: lighter 2.8em/100% 'Open Sans';color: grey;letter-spacing: 2.8px;">MOONROCK RAFFLE</span>
</div>
</div>

<?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>
<p style="margin: 3em 0;">
Due to extremely high demand and the limited edition character of the sneakers, we believe the most fair way of selling the new Yeezy Boost 350 online, is a raffle. Sign up for a chance to buy a pair!
</p>
<p style="margin: 3em 0;">
Just click on your preferred size and fill in the form. Since it can be you who’ll be receiving our phone call and email on Monday, please double-check your number and address before hitting the submit button. We wish you the best of luck. Fingers (and toes) crossed!
</p>
<?php else:?>
<p style="margin: 3em 0;">
Teniendo en cuenta el altísimo interés por las zapatillas de la edición limitada, creemos que la forma más justa de vender las nuevas Yeezy Boost 350 Moonrock online, es a través de una rifa. 
</p>
<p style="margin: 3em 0;">
Simplemente haz click a tu talla preferida y rellena el formulario. Puesto que puedes ser tú a quien le llamaremos y mandaremos un email de felicitación (y un link privado para hacer la compra) el lunes, por favor, asegúrate de que tu número y dirección de email estén correctos antes de darle a enviar. De deseamos la mejor de las suertes. ¡Dedos cruzados!


</p>
<?php endif; ?>
<!--       primera yeezy-->
<ul class="products-grid columns3 first odd" style="width:100%;">
    <li class="item first " style="width: 225px;">
                <map name="mapa4"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol4').style.display = 'block';"> 
                </map> 
        <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_0.jpg" width="215" height="215" alt="Yeezy" usemap="#mapa4">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 7UK)- 2 units available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
                
			<!--onClick="document.getElementById('hol4').style.display = 'block';" -->
    </li>
    <li class="item first " style="width: 225px;">
                <map name="mapa3"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol3').style.display = 'block';"> 
                </map> 
        <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_0.jpg" width="215" height="215" alt="Yeezy" usemap="#mapa3">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 8UK)- 3 units available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
			<!--onClick="document.getElementById('hol3').style.display = 'block';" -->
    </li>
    <li class="item first " style="width: 225px;">
                <map name="mapa2"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol2').style.display = 'block';"> 
                </map> 
        <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_0.jpg" width="215" height="215" alt="Yeezy" usemap="#mapa2">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 9UK)- 2 units available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
			<!--onClick="document.getElementById('hol2').style.display = 'block';" -->
  	</li>
    <li class="item first " style="width: 225px;">
                <map name="mapa1"> 
                    <area alt="Pulsa para ver la página de mis amigos" shape="RECT" coords="135,10,203,27" href="#" onClick="document.getElementById('hol1').style.display = 'block';"> 
                </map> 
        <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_0.jpg" width="215" height="215" alt="Yeezy" usemap="#mapa1">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list"><?php echo $marca; ?></div>
            			<div class="product-name" style="line-height: 1.0em;"><?php echo $titulo; ?><br/> (size: 10UK)- 1 units available</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price"><?php echo $precio; ?></span>      
		              </span>
	      			</div>
    			</div>
            <!--onClick="document.getElementById('hol1').style.display = 'block';" -->
    </li>

</ul>

<!--       ultima yeezy-->

<div class="box simple_contact7" id="hol4" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    /* text-align: center; */
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol4').style.display = 'none';">x</div>
<form id="simple_contact_form8" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="7">
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value=""  required  class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value=""   required class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value=""  required  class="required-entry input-text validate-email" type="email" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" required  class="required-entry input-text" type="phone" />
                </div>
                
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<div class="box simple_contact8" id="hol3" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    /* text-align: center; */
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol3').style.display = 'none';">x</div>
<form id="simple_contact_form9" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="8">
                               <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value="" class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value="" class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value="" class="required-entry input-text validate-email2" type="text" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" class="required-entry input-text" type="text" />
                </div>
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
       <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<div class="box simple_contact9" id="hol2" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    /* text-align: center; */
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol2').style.display = 'none';">x</div>
<form id="simple_contact_form9" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="9">
                                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value="" class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value="" class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value="" class="required-entry input-text validate-email3" type="text" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" class="required-entry input-text" type="text" />
                </div>
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<div class="box simple_contact10" id="hol1" style="display: none;">
<div style="    background: rgba(255,255,255,0.9);
    /* text-align: center; */
    padding: 32px;
    width: 50%;
    position: relative;
    margin: 0 auto;
    border: 1px solid #000;">
 <div class="cerrar" onClick="document.getElementById('hol1').style.display = 'none';">x</div>
<form id="simple_contact_form10" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="10">
                               <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value="" class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="surname"><?php echo $this->__('Your Surname') ?><span class="required">*</span></label><br />
 
                    <input name="surname" id="surname" title="surname" value="" class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value="" class="required-entry input-text validate-email4" type="text" />
                </div>
                <div class="input-box">
                    <label for="phone"><?php echo $this->__('Your Phone') ?><span class="required">*</span></label><br />
 
                    <input name="phone" id="phone" title="phone" value="" class="required-entry input-text" type="text" />
                </div>
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
       <button type="submit" title="Add to Cart" class="button btn-cart"><span><span>Submit</span></span></button>
 
    </div>
</form>
 </div>
</div>
<?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>
<p style="margin-top: 1em;">
RAFFLE CONDITIONS<br>
• The raffle starts on Saturday, November 14 at 11.00 AM CET and ends on Monday, November 16 at 11.00 AM CET.<br>
• By signing up for the raffle (in case you haven’t joined us yet), you automatically sign up for our newsletter.<br>
• Only ONE entry per person is allowed. <br>
• The winners will be announced on our social media, and notified via phone and email, including a private link to finish the purchase. In case the winner doesn’t make the purchase within 24hrs, a new winner will be randomly selected from among all signed up participants.<br>
• Return policy: refund within 14 days of the delivery date. <br>
• In case of a return, a new winner will be randomly selected from among all signed up participants.<br>
</p>
<?php else:?>
<p style="margin-top: 1em;">
CONDICIONES DE LA SUBASTA<br>
• La subasta comenzará el Sabado 14 de Noviembre a las 11AM (CET) y terminará el Lunes 16 de Noviembre a las 11AM (CET).<br>
• Al enviar su solicitud de inscripción (en el caso en que no lo esté ya), usted será automaticamente inscrito en nuestra lista de newsletter.<br>
• Solo se tendrá en cuenta 1 solicitud de suscripción por persona. <br>
• El ganador será anunciado en nuestras redes sociales, y personalmente via email y teléfono, incluyendo un link privado para formalizar la compra. En caso en que el ganador no formalizase la compra en las siguientes 24h, será seleccionado un nuevo ganador de entre los restantes participantes.<br>
• Política de devolución: El plazo de devolución del artículo es de 14 días desde la recepción del mismo. <br>
• En caso de devolución, se seleccionará un nuevo ganador de entre los restantes participantes.<br>
</p>
<?php endif; ?>
</script>