<style type="text/css">
#mobile-currency{display: none;}

</style>
<?php if($this->getCurrencyCount()>1): ?>

 <div class="lang-currency-container">
                
<!-- LANGUAGES BOF -->
<!-- LANGUAGES EOF -->                
<!-- Currency BOF -->
<div id="desktop-currency" class="header-switch currency-switch">
    <span id="currency">Currency:<span class="current" style='color: #1D1C1B;background-size: 7px 4px;'><?php echo $this->getCurrentCurrencyCode(); ?></span>
    </span>
    <div class="header-dropdown" style='background-color: #fff;'>
   	<ul >
    <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
    <li><a href="<?php echo $this->getSwitchCurrencyUrl($_code)?>" ><?php echo $_name."-".$_code ?></a></li>
    <?php endforeach; ?>
    </ul>
    
    </div>
</div>
 <select style="height:20px;margin-top: 4px;" id="mobile-currency" name="currency" title="<?php echo $this->__('Select Your Currency') ?>" onchange="setLocation(this.value)">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <option value="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>>
                <?php echo $_name ?> - <?php echo $_code ?>
            </option>
        <?php endforeach; ?>
        </select>
<!-- Currency EOF -->
 </div>

 
<?php endif; ?>