<div id="top"></div>
<div class="header-container">
    <div class="header">
        
        <div class="header-left">
 <?php echo $this->getChildHtml('topBar') ?>
            
        </div>
        <div class="header-center">            
			
            <?php if ($this->getIsHomePage()):?>           
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php else:?>
			<a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif
		//Añadido el logo también en el else para que salga en toda la web
	     ?>
      <span class="welcome-msg"><?php echo $this->getWelcome() ?></span>
  	</div>        
        <div class="header-right">
		
            <div class="minicart">
                <?php echo $this->getChildHtml('top_cart') ?>
				<?php echo $this->getChildHtml('store_language') ?>	
            </div>  
			
            <?php echo $this->getChildHtml('currency') ?>  
            <div class="clear"></div>   
            <?php echo $this->getChildHtml('topLinks') ?>  
        </div> 
                <a href="#menu-right" class="friends right"></a>
        <nav id="menu-right">    

        <div class="header-right--mobile">
            <div class="header-left--mobile">
                <?php echo $this->getChildHtml('topBar') ?>
            
        </div>
            <div class="minicart">
                <?php echo $this->getChildHtml('top_cart') ?>
                <?php echo $this->getChildHtml('store_language') ?> 
            </div>  
            
            <?php echo $this->getChildHtml('currency') ?>  
            <div class="clear"></div>   
            <?php echo $this->getChildHtml('topLinks') ?>  
        </div>
        </nav>       
    </div>
    <?php echo $this->getChildHtml('topMenu');
	
    // Redirección a Z2 de todos los paises excepto la UE
$paisesUE = array ('DE','AT','BG','CY','HR','DK','SK','SI','ES','EE','FI','GR','HU','IE','LV','LT','LU','MT','NL','PL','PT','UK','CZ','RO','SE','GB');
$paisCustomer = Mage::getSingleton('geoip/country')->getCountry();
$remoteAddr = Mage::helper('core/http')->getRemoteAddr(false);
if (in_array($paisCustomer,$paisesUE)):		
    if ((Mage::app()->getStore()->getStoreId()==2) || (Mage::app()->getStore()->getStoreId()==1)):
    	if ((Mage::getSingleton('cms/page')->getPageId()!='2') && (Mage::getSingleton('cms/page')->getPageId()!='10')): 
        ?>
                    <a href="<?php echo $this->getUrl('sale-ss16')?>">
                        <div class="banner_class-noz2">
                            <div class="banner_class__container">
                                <div class="banner_class__container--flotante imagen1">
                                    
                                </div>
                                <div class="banner_class__container--flotante imagen2">
                                    
                                </div>
                                <div class="banner_class__container--flotante imagen3">
                                    
                                </div>
                            </div>
                        </div>
                    </a>
<?php        endif;
    endif;
else:
    if ((Mage::getSingleton('cms/page')->getPageId()!='2') && (Mage::getSingleton('cms/page')->getPageId()!='10')):
            ?>
                            <div class="banner_class-vip10">
                                <div class="texto"><div class="minitexto">+ use </div><div class="codigo">10VIPONLY</div><div class="minitexto"> code for an </div><div class="supertexto">EXTRA <span class="Mastexto">10%</span> off!</div></div>
                            </div>
        <?php
    endif;
endif;
    ?>
	<!-- fin de mini banner-->
   <?php echo $this->getChildHtml('topBread') ?>
    <?php echo $this->getChildHtml('topContainer'); ?>
	
</div>