<div class="account">
	<?php 
		$customer = Mage::getSingleton('customer/session')->getCustomer();
		echo '<a href="' . $this->getBaseUrl() . 'customer/account">' . $this->__('Hello ') . $customer->getGender() . $customer->getFirstname() . '</a>'; 
	?>
</div>
<div class="bigpoint">&#149;</div>
<div class="logout">
	<a href="<?php echo $this->getBaseUrl()?>customer/account/logout">
		<?php echo $this->__('Logout') ?>
	</a>
</div>