      <div class="login">
        <a href="<?php echo Mage::getUrl('customer/account/login'); ?>">sign IN</a> 
      </div>
      <div class="bigpoint">&#149;</div>
      <div class="register">
        <a href="<?php echo Mage::getUrl('customer/account/login'); ?>">
          <?php echo $this->__('Register') ?>
        </a>
      </div>
<div class="sabana-login-modal">
	<div id="login-modal" class="modal-window">
	  <div id="login-modal-content">
		<div id="signup-box">
			<!--Popup referente a registro, si es la primera vez que te registras en la web-->
			<div class="modulo">
			  <h1>Register</h1> 
			  <form  urlcart="<?php echo Mage::getBaseUrl()?>ajaxcartpro/cart/show" urllogin="<?php echo Mage::getBaseUrl()?>ajaxcontrol/index/updatelogin" action="<?php echo Mage::getUrl('customer/account/createPost/')?>" method="post" id="signup-form" class="site-form" onsubmit="return false">
					<div class="formcontent">
					<div class="gender">
						<input type="checkbox" name="rememberme" value="rememberme" class="input-checkbox" id="rememberme" title="<?php echo $this->__('Remember me') ?>"  placeholder="<?php echo $this->__('Ms.') ?>"><label for="rememberme"><span></span><?php echo $this->__('Ms.') ?></label>
					 </div>
					 <div class="gender">
						<input type="checkbox" name="rememberme" value="rememberme" class="input-checkbox" id="rememberme" title="<?php echo $this->__('Remember me') ?>"  placeholder="<?php echo $this->__('Mrs.') ?>"><label for="rememberme"><span></span><?php echo $this->__('Mrs.') ?></label>
					 </div>
					 <div class="gender">
						<input type="checkbox" name="rememberme" value="rememberme" class="input-checkbox" id="rememberme" title="<?php echo $this->__('Remember me') ?>"  placeholder="<?php echo $this->__('Mr.') ?>"><label for="rememberme"><span></span><?php echo $this->__('Mr.') ?></label>
					 </div>
					  <div class="field">
						  <div class="input-box">
							  <input type="text" name="firstname" id="firstname" class="input-text validate-email required-entry" placeholder="<?php echo $this->__('FIRST NAME*') ?>"/>
						  </div>
					  </div>
					  <div class="field">
						  <div class="input-box">
							  <input type="text" name="lastname" id="lastname" class="input-text validate-email required-entry" placeholder="<?php echo $this->__('LAST NAME*') ?>"/>
						  </div>
					  </div>
					  <div class="field">
						  <div class="input-box">
							  <input type="email" name="email" id="email_address" class="input-text validate-email required-entry" placeholder="<?php echo $this->__('EMAIL ADDRESS*') ?>"/>
						  </div>
					  </div>
					  <div class="field">
						  <div class="input-box">
							  <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" placeholder="<?php echo $this->__('PASSWORD*') ?>"/>
						  </div>
					  </div>
					  <div class="field">
						  <div class="input-box">
							  <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" placeholder="<?php echo $this->__('CONFIRM PASSWORD*') ?>"/>
						  </div>
					  </div>
					</div>
					<div class="forgot-your-password-content">
					  <?php echo $this->__('* Required fields') ?>
					</div>
					<div class="confirmnews" id="news">
						<input type="checkbox" name="rememberme" value="rememberme" class="input-checkbox" id="rememberme" title="<?php echo $this->__('Remember me') ?>"  placeholder="<?php echo $this->__('Ms.') ?>"><label for="rememberme"><span></span><?php echo $this->__('I\'d love to receive ELITE fashion news and exclusive offers via email') ?></label>
					 </div>
					 <div class="confirmnews" id="termsandcondition">
						<input type="checkbox" name="rememberme" value="rememberme" class="input-checkbox" id="rememberme" title="<?php echo $this->__('Remember me') ?>"  placeholder="<?php echo $this->__('Ms.') ?>"><label for="rememberme"><span></span><?php echo $this->__('I agree to ELITE terms and Conditions and Privacy Policy') ?></label>
					 </div>
					
				  <button type="submit" class="action-button action-button-no-arrow" title="<?php echo $this->__('Login') ?>" name="send" id="send2">
					  <span>
						<?php echo $this->__('submit') ?>
					  </span>
				  </button>
					<div class="need-account-link-content">
					  Already registered? <a href="#" id="already-registered-link"> Click here to SIGN IN.</a>
					</div>
			  </form>
		  </div>
		  <div class="modulo izquierda">
				<img src="<?php echo $this->getSkinUrl('images/imagen-register.png');?>"/>
				<h1><?php echo $this->__('BENEFITS OF') ?><br/><?php echo $this->__('HAVING AN ELITE ACCOUNT') ?></h1>
				<p class="texto__register">
					-Faster checkout<br/>
					-Orders status, tracking and history<br/>
					-My wishlist, you can add all the goodies you fell for to<br/>
					-My fave designer list with "just arrived" email alerts<br/>
					-Fashion news and exclusive offers via email<br/>
				</p>
		  </div>
		</div>
		<!--Primer popup para el login de la aplicacion el referente a login-->
		<div id="login-box">
			<div class="modulo-normal">
			  <h1><?php echo $this->__('Login') ?></h1>
			  <div class="texto"><?php echo $this->__('Already REGISTERED? Please SIGN IN here') ?></div> 
			  <form urllogin="<?php echo Mage::getBaseUrl()?>ajaxcontrol/index/updateLogin" urlcart="<?php echo Mage::getBaseUrl()?>ajaxcartpro/cart/show"  action="<?php echo Mage::getUrl('customer/account/loginPost/') ?>" method="post" id="login-form" class="site-form" onsubmit="return false">
				  <div class="formcontent">
					 <div class="field">
						<input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text" title="<?php echo $this->__('Email Address') ?>" placeholder="<?php echo $this->__('EMAIL ADDRESS') ?>"/>
					 </div>
					 <div class="field">
						<input type="password" name="login[password]" class="input-text" id="pass" title="<?php echo $this->__('Password') ?>"  placeholder="<?php echo $this->__('PASSWORD') ?>"/>
					 </div>
					 <div class="rememeber">
						<input type="checkbox" name="rememberme" value="rememberme" class="input-checkbox" id="rememberme" title="<?php echo $this->__('Remember me') ?>"  placeholder="<?php echo $this->__('Remember me') ?>"><label for="rememberme"><span></span><?php echo $this->__('Remember me') ?></label>
					 </div>
				  </div>
				  <div class="forgot-your-password-content">
					  <a href="#" id="forgot-your-password" class="small"><?php echo $this->__('Forgot Your Password?') ?></a>
				  </div>
				  <button type="submit" class="action-button action-button-no-arrow" title="<?php echo $this->__('Login') ?>" name="send" id="send2">
					  <span>
						<?php echo $this->__('submit') ?>
					  </span>
				  </button>
				  <div class="need-account-link-content">
					  <div class="align--left">New to ELITE?</div><div class="align--right"><a href="#" id="need-account-link"> Click here to REGISTER.</a></div>
				  </div>
			   </form>
			</div>
		</div>
	<!--Primer popup para el login de la aplicacion el referente a login-->
		<div id="forgot-box">
			<div class="modulo-normal">
				<h1><?php echo $this->__('Retrieve your')?><br/><?php echo $this->__('password here') ?></h1>
				<form  urlcart="<?php echo Mage::getBaseUrl()?>ajaxcartpro/cart/show" urllogin="<?php echo Mage::getBaseUrl()?>ajaxcontrol/index/updatelogin" action="<?php echo Mage::helper('customer')->getForgotPasswordUrl() ?>" method="post" id="forgot-form" class="site-form" onsubmit="return false">
					<div class="texto">
						<?php echo $this->__('Please enter your email address below. <br/>We\'ll send you a link to reset your password.') ?>
					</div>
					<div class="formcontent">
					  <div class="field">
						<input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" placeholder="<?php echo $this->__('EMAIL ADDRESS') ?>"/>
					  </div>
					</div>
					<?php echo $this->getChildHtml('form.additional.info'); ?>
				  <div class="forgot-your-password-content">
					<a href="#" id="back-to-login" class="small">
					  <small>&laquo; </small>
					  <?php echo $this->__('Back to SIGN IN') ?>
					</a>
				  </div>
					<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button">
						  <span>
							<?php echo $this->__('submit') ?>
						  </span>
					</button>
				</form>
			</div>
		</div>
			
		</div>
	<div id="error-mensaje"></div>
	  <a id="close_x" class="close" href="#">X</a>
	  <script type="text/javascript">
	  //<![CDATA[
		  var dataForm = new VarienForm('login-form', true);
	  //]]>
	  </script>
	</div>
</div>