      <div class="login">
        <button class="link-signin-cabecera" data-href="<?php echo Mage::getUrl('customer/account/login'); ?>"><?php echo $this->__('sign IN') ?></div> 
      </button>
      <div class="bigpoint">&#149;</div>
      <div class="register">
        <button class="link-register-cabecera" datahref="<?php echo Mage::getUrl('customer/account/login'); ?>">
          <?php echo $this->__('Register') ?>
        </button>
      </div>
