<?php
class Elite_Ipstoreswitcher_Helper_Data extends Mage_Core_Helper_Abstract
{
	const DEFAULT_STORE = 1;
 
    /**
     * countries to store relation
     * default is English
     * @var array
	 *retornamos el id del store
     */
    protected $_countryToStore = array(
		'DE' => array('7', 'en_eu', 'EUR'), 
		'AT' => array('7', 'en_eu', 'EUR'), 
		'BE' => array('7', 'en_eu', 'EUR'), 
		'BG' => array('7', 'en_eu', 'EUR'), 
		'CY' => array('7', 'en_eu', 'EUR'), 
		'HR' => array('7', 'en_eu', 'EUR'), 
		'DK' => array('7', 'en_eu', 'EUR'), 
		'SK' => array('7', 'en_eu', 'EUR'), 
		'SI' => array('7', 'en_eu', 'EUR'), 
		'ES' => array('8', 'es_eu', 'EUR'), 
		'EE' => array('7', 'en_eu', 'EUR'), 
		'FI' => array('7', 'en_eu', 'EUR'), 
		'FR' => array('7', 'en_eu', 'EUR'), 
		'GR' => array('7', 'en_eu', 'EUR'), 
		'HU' => array('7', 'en_eu', 'EUR'), 
		'IE' => array('7', 'en_eu', 'EUR'), 
		'IT' => array('7', 'en_eu', 'EUR'), 
		'LV' => array('7', 'en_eu', 'EUR'), 
		'LT' => array('7', 'en_eu', 'EUR'), 
		'LU' => array('7', 'en_eu', 'EUR'), 
		'MT' => array('7', 'en_eu', 'EUR'), 
		'NL' => array('7', 'en_eu', 'EUR'), 
		'PL' => array('7', 'en_eu', 'EUR'), 
		'PT' => array('7', 'en_eu', 'EUR'), 
		'GB' => array('7', 'en_eu', 'EUR'), 
		'CZ' => array('7', 'en_eu', 'EUR'), 
		'RO' => array('7', 'en_eu', 'EUR'), 
		'SE' => array('7', 'en_eu', 'EUR'), 
		'AF' => array('1', 'en', 'EUR'),
		'BH' => array('1', 'en', 'EUR'),
		'BD' => array('1', 'en', 'EUR'),
		'BT' => array('1', 'en', 'EUR'),
		'KH' => array('1', 'en', 'EUR'), 
		'IR' => array('1', 'en', 'EUR'),
		'IQ' => array('1', 'en', 'EUR'), 
		'IL' => array('1', 'en', 'EUR'), 
		'JP' => array('1', 'en', 'EUR'), 
		'JO' => array('1', 'en', 'EUR'),
		'KZ' => array('1', 'en', 'EUR'),
		'KW' => array('1', 'en', 'EUR'), 
		'KG' => array('1', 'en', 'EUR'), 
		'LA' => array('1', 'en', 'EUR'), 
		'LB' => array('1', 'en', 'EUR'), 
		'MV' => array('1', 'en', 'EUR'), 
		'MN' => array('1', 'en', 'EUR'),
		'NP' => array('1', 'en', 'EUR'),
		'NC' => array('1','en', 'AUD'), 
		'KP' => array('1', 'en', 'EUR'), 
		'QA' => array('1', 'en', 'EUR'), 
		'RU' => array('1', 'en', 'EUR'),
		'TJ' => array('1', 'en', 'EUR'),
		'TH' => array('1', 'en', 'EUR'), 
		'UZ' => array('1', 'en', 'EUR'),
		'VN' => array('1', 'en', 'EUR'), 
		'CN' => array('1', 'en', 'EUR'),  
		'HK' => array('1', 'en', 'EUR'),  
		'MO' => array('1', 'en', 'EUR'),   
		'MM' => array('1', 'en', 'EUR'),
		'SG' => array('1', 'en', 'EUR'),  
		'TW' => array('1', 'en', 'EUR'), 
		'AI' => array('1','en', 'AUD'),
		'AU' => array('1','en', 'AUD'),  
		'BN' => array('1','en', 'AUD'), 
		'CC' => array('1','en', 'AUD'), 
		'CK' => array('1','en', 'AUD'),  
		'FJ' => array('1','en', 'AUD'),  
		'PF' => array('1','en', 'AUD'),  
		'HM' => array('1','en', 'AUD'),  
		'ID' => array('1','en', 'AUD'),  
		'KI' => array('1','en', 'AUD'),  
		'MY' => array('1','en', 'AUD'),  
		'MH' => array('1','en', 'AUD'),  
		'NR' => array('1','en', 'AUD'),  
		'NZ' => array('1','en', 'AUD'),  
		'NU' => array('1','en', 'AUD'),  
		'NF' => array('1','en', 'AUD'),  
		'MP' => array('1','en', 'AUD'),  
		'PW' => array('1','en', 'AUD'),  
		'PG' => array('1','en', 'AUD'),  
		'PH' => array('1','en', 'AUD'),  
		'PN' => array('1','en', 'AUD'),  
		'WS' => array('1','en', 'AUD'),  
		'SB' => array('1','en', 'AUD'),  
		'TL' => array('1','en', 'AUD'),  
		'TK' => array('1','en', 'AUD'),  
		'TO' => array('1','en', 'AUD'),  
		'TV' => array('1','en', 'AUD'),  
		'UM' => array('1','en', 'AUD'),  
		'VU' => array('1','en', 'AUD'),  
		'WF' => array('1','en', 'AUD'),  
		'CA' => array('1','en','CAD'),
		'GL' => array('1','en','USD'), 
		'NO' => array('1','en','USD'), 
		'US' => array('1','en','USD'), 
		'DZ' => array('1','en','EUR'),  
		'AS' => array('1','en','EUR'),  
		'AO' => array('1','en','EUR'), 
		'AQ' => array('1','en','EUR'),  
		'AG' => array('1','en','EUR'),  
		'AR' => array('1','en','EUR'),  
		'AW' => array('1','en','EUR'),  
		'BS' => array('1','en','EUR'), 
		'BB' => array('1','en','EUR'),  
		'BZ' => array('1','en','EUR'),  
		'BJ' => array('1','en','EUR'),  
		'BM' => array('1','en','EUR'),  
		'BO' => array('1','en','EUR'),  
		'BW' => array('1','en','EUR'),  
		'BV' => array('1','en','EUR'),  
		'BR' => array('1','en','EUR'),  
		'IO' => array('1','en','EUR'),  
		'VG' => array('1','en','EUR'),  
		'BF' => array('1','en','EUR'),  
		'BI' => array('1','en','EUR'),  
		'CM' => array('1','en','EUR'),  
		'CV' => array('1','en','EUR'),  
		'KY' => array('1','en','EUR'),  
		'CF' => array('1','en','EUR'),  
		'TD' => array('1','en','EUR'),  
		'CL' => array('1','en','EUR'),  
		'CX' => array('1','en', 'aud'), 
		'CO' => array('1','en','EUR'),  
		'KM' => array('1','en','EUR'),  
		'CG' => array('1','en','EUR'), 
		'CD' => array('1','en','EUR'),  
		'CR' => array('1','en','EUR'), 
		'CU' => array('1','en','EUR'),  
		'CI' => array('1','en','EUR'),  
		'DJ' => array('1','en','EUR'),  
		'DM' => array('1','en','EUR'),  
		'DO' => array('1','en','EUR'),  
		'EC' => array('1','en','EUR'),  
		'EG' => array('1','en','EUR'),  
		'SV' => array('1','en','EUR'),  
		'GQ' => array('1','en','EUR'),  
		'ER' => array('1','en','EUR'),  
		'ET' => array('1','en','EUR'),  
		'GF' => array('1','en','EUR'),  
		'TF' => array('1','en','EUR'),  
		'GA' => array('1','en','EUR'),  
		'GM' => array('1','en','EUR'),  
		'GE' => array('1','en','EUR'),  
		'GH' => array('1','en','EUR'),  
		'GD' => array('1','en','EUR'),  
		'GP' => array('1','en','EUR'),  
		'GU' => array('1','en','EUR'),  
		'GT' => array('1','en','EUR'),  
		'GN' => array('1','en','EUR'),  
		'GW' => array('1','en','EUR'),  
		'GY' => array('1','en','EUR'),  
		'HT' => array('1','en','EUR'),  
		'HN' => array('1','en','EUR'),  
		'IN' => array('1','en','EUR'), 
		'JM' => array('1','en','EUR'),  
		'KE' => array('1','en','EUR'),  
		'LS' => array('1','en','EUR'),  
		'LR' => array('1','en','EUR'),  
		'LY' => array('1','en','EUR'),  
		'MW' => array('1','en','EUR'),  
		'ML' => array('1','en','EUR'),  
		'MQ' => array('1','en','EUR'),  
		'MR' => array('1','en','EUR'),  
		'MG' => array('1','en','EUR'),  
		'MU' => array('1','en','EUR'),  
		'YT' => array('1','en','EUR'),  
		'MX' => array('1','en','EUR'),  
		'FM' => array('1','en','EUR'),  
		'MS' => array('1','en','EUR'),  
		'MA' => array('1','en','EUR'),  
		'MZ' => array('1','en','EUR'),  
		'NA' => array('1','en','EUR'),  
		'AN' => array('1','en','EUR'),  
		'NI' => array('1','en','EUR'),  
		'NE' => array('1','en','EUR'),  
		'NG' => array('1','en','EUR'),  
		'OM' => array('1','en','EUR'),  
		'PK' => array('1','en','EUR'), 
		'PS' => array('1','en','EUR'),  
		'PA' => array('1','en','EUR'), 
		'PY' => array('1','en','EUR'), 
		'PE' => array('1','en','EUR'),  
		'PR' => array('1','en','EUR'),  
		'QA' => array('1','en','EUR'),  
		'RW' => array('1','en','EUR'),  
		'RE' => array('1','en','EUR'),  
		'BL' => array('1','en','EUR'),  
		'SH' => array('1','en','EUR'),  
		'KN' => array('1','en','EUR'),  
		'LC' => array('1','en','EUR'),  
		'SA' => array('1','en','EUR'),  
		'SN' => array('1','en','EUR'),  
		'SC' => array('1','en','EUR'),  
		'SL' => array('1','en','EUR'),  
		'SO' => array('1','en','EUR'),  
		'ZA' => array('1','en','EUR'),  
		'GS' => array('1','en','EUR'),  
		'KR' => array('1','en','EUR'),  
		'LK' => array('1','en','EUR'),  
		'VC' => array('1','en','EUR'),  
		'SD' => array('1','en','EUR'),  
		'SR' => array('1','en','EUR'),  
		'SZ' => array('1','en','EUR'),  
		'SY' => array('1','en','EUR'),  
		'ST' => array('1','en','EUR'),  
		'TZ' => array('1','en','EUR'),  
		'TG' => array('1','en','EUR'),  
		'TT' => array('1','en','EUR'),  
		'TN' => array('1','en','EUR'),  
		'TR' => array('1','en','EUR'),  
		'TC' => array('1','en','EUR'),  
		'VI' => array('1','en','EUR'),  
		'UG' => array('1','en','EUR'),  
		'AE' => array('1','en','EUR'),  
		'UY' => array('1','en','EUR'),  
		'VE' => array('1','en','EUR'),  
		'EH' => array('1','en','EUR'),  
		'YE' => array('1','en','EUR'),  
		'ZM' => array('1','en','EUR'),  
		'ZW' => array('1','en','EUR'), 
		'default' => array('1','en','EUR')
    );
 
    /**
     * get store view name by country
     * @param $country
     * @return bool
     */
    public function getStoreByCountry($country)
    {
        if (isset($this->_countryToStore[$country])) 
		{
            return $this->_countryToStore[$country];
        }
        return $this->_countryToStore['default'];
    }
}
	 