

<?php $footerbox1 = Mage::getModel('cms/block')->load('rt001-footer-box1'); ?> 
<?php $footerbox2 = Mage::getModel('cms/block')->load('rt001-footer-box2'); ?> 
<?php $footerbox3 = Mage::getModel('cms/block')->load('rt001-footer-box3'); ?> 
<?php $footerbox4 = Mage::getModel('cms/block')->load('rt001-footer-box4'); ?> 

<footer>
    <div class="footer--container">	   


    <div class="footer__left--left">
            <div class="foother--grid_1">
               <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('rt001-footer-box2')->toHtml() ?>    
            </div>
    </div>

    <div class="footer__right--left">
            <div class="foother--grid_4">
	            <!--<h4><?php echo $footerbox4->getTitle(); ?></h4>-->
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('rt001-footer-box4')->toHtml() ?>  
            </div>
    </div>
    <div class="footer__right--right">
            <div class="foother--grid_5">
	            <!--<h4><?php echo $footerbox4->getTitle(); ?></h4>-->
				<?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?>
            </div>
    </div>

    </div>
    <div class="grid_copy">
		<div class="footer--copy">
            &#169;2012-2015 ELITE
            <div class="footer--copy--left">
                Privacy &amp; Legal
            </div>
        </div>
    </div>
</footer>           
	

<div class="popup--search">
    <div id="searchContainer" class="expanded">

        <form role="search" action="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>catalogsearch/result/?q=parka" method="get" name="simpleSearch" id="primary-search" class="search-box empty">
            <fieldset>
                <legend class="visually-hidden">Search Catalog</legend>
                <input type="text" id="q" name="q" value="" placeholder="Looking for..." autocomplete="off">
                <label class="labelForIe" for="q">Looking for...</label>
                <input type="submit" name="search-submit" value="Search" id="search-submit">
                <button type="submit" name="search-submit" value="" id="search-submit-2" class="search-icon">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" preserveAspectRatio="xMinYMin" viewBox="0 0 82 82" enable-background="new 0 0 82 82" xml:space="preserve">
                    <g class="search-svg">
                    <path d="M78.896,73.879L62.631,57.615C67.566,51.772,70.55,44.229,70.55,36C70.55,17.501,55.5,2.45,37,2.45S3.45,17.501,3.45,36
                    S18.5,69.55,37,69.55c8.115,0,15.564-2.896,21.373-7.709l16.279,16.28C75.238,78.707,76.007,79,76.773,79
                    c0.769,0,1.537-0.293,2.123-0.879C80.066,76.95,80.066,75.05,78.896,73.879 M37,64.325C21.381,64.325,8.675,51.618,8.675,36
                    S21.381,7.675,37,7.675S65.325,20.382,65.325,36S52.619,64.325,37,64.325" shape-rendering="geometricPrecision"></path>
                    </g>
                    </svg>
                </button>
                <div class="close"><span class="close">X</span></div>
            </fieldset>
        </form>

        <div class="search-recommendations search-box"></div>
    </div>
</div>

    
