<?php
/*
* This template is injected in to form.additional.info block of checkout.onepage.billing
* to provide the third "collect in store" option. You may need to move this around in your theme's styling.
*/
?>
<?php if(Mage::getStoreConfig('carriers/collectinstore/active')): ?>
    	<li class="control" id="collectinstore" >
        	<input type="radio" name="billing[use_for_shipping]" id="billing:collect_in_store" value="2" title="<?php echo $this->__(Mage::getStoreConfig('carriers/collectinstore/name')) ?>" onclick="$('shipping:same_as_billing').checked = true;" class="radio" /><label for="billing:collect_in_store"><?php echo $this->__(Mage::getStoreConfig('carriers/collectinstore/name')) ?></label>
    	</li>

	<script type="text/javascript">
		// Move the collect in store option to desired location.	
		document.observe("dom:loaded", function() {
			if( $( 'co-billing-form' ) ) {
				var collectBillingForm = $( 'co-billing-form' ).select('ul.form-list')[0]
				if( parent ){
					collectBillingForm.appendChild( $( 'collectinstore' ) );
				}
			}
		});
	</script>
<?php endif; ?>
