<?php
/**
 * Survey for Magento
 *
 * @category   Belitsoft
 * @package    Belitsoft_Survey
 * @author     Belitsoft <bits@belitsoft.com>
 */

/* @var $this Belitsoft_Survey_Block_Frontend_Questions */
?>

<?php $_survey = $this->getSurvey(); ?>
<?php $_questions = $this->getQuestions(); ?>

    <div class="survey-questions-list-title">
        <h3><?php echo $this->__('Questions'); ?></h3>
    </div>

    <form action="<?php echo $this->getSurveyContinueFormActionUrl(); ?>" method="post"
          id="<?php echo $this->getFormId(); ?>">
        <dl class="survey-questions-list">
            <?php foreach ($_questions as $_question): ?>
                <?php echo $this->getQuestionHtml($_question); ?>
            <?php endforeach; ?>
        </dl>

        <div class="actions">
            <?php if ($this->isViewMode()): ?>
                <button type="button" title="<?php echo $this->__('Back'); ?>" class="button"
                        onclick="location.href='<?php echo $this->getBackUrl(); ?>'">
                    <span><span><?php echo $this->__('Back'); ?></span></span>
                </button>
            <?php endif; ?>

            <button type="submit" title="<?php echo(!$this->isViewMode() ? $this->__('Submit') : $this->__('Next')); ?>"
                    class="button" id="<?php echo $this->getFormId(); ?>_submit_button">
                <span><span><?php echo(!$this->isViewMode() ? $this->__('Submit') : $this->__('Next')); ?></span></span>
            </button>
        </div>
    </form>

<?php if (!$this->isViewMode()): ?>
    <script type="text/javascript">

        <?php if($this->isAjax()): ?>
        Validation.addMethods({
            onSubmit: function (ev) {
                Event.stop(ev);
                if (this.validate()) {
                    var buttonSubmit = $('<?php echo $this->getFormId(); ?>_submit_button')
                    buttonSubmit.addClassName('disabled');
                    buttonSubmit.disabled = true;
                    buttonSubmit.insert({after: '<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" />'});
                    new Ajax.Request($('<?php echo $this->getFormId(); ?>').action + '?isAjax=1&strip_tags=<?php echo (int)$this->isReturnAlert(); ?>', {
                        loaderArea: true,
                        asynchronous: true,

                        parameters: $('<?php echo $this->getFormId(); ?>').serialize(),

                        onComplete: function (transport) {
                            $('survey-detail-view').hide();
                            if (transport.responseText) {
                                <?php if($this->isReturnAlert()) : ?>
                                alert(transport.responseText);
                                <?php else:?>
                                $('survey-detail-view').update(transport.responseText).show();
                                <?php endif;?>
                            }
                        }
                    });
                }
            }
        });
        <?php endif; ?>

        var surveyQuestionValidate = new VarienForm('<?php echo $this->getFormId(); ?>');

    </script>
<?php endif; ?>