<?php
/*<table>
    <tr>
        <td><h2><?php echo $this->__("Introduciendo...") ?></h2></td>
        <td>&nbsp;</td>
        <td><img src='<?php echo $this->getSkinUrl('images/servired/mastercard_secuercode.png') ?>' width='116' /></td>
    </tr>
    <tr>
        <td colspan='3'>&nbsp;</td>
    </tr>
    <tr>
        <td colspan='3'><?php echo $this->__("MasterCard (r) SecureCode(tm) es un nuevo servicio de MasterCard y de su emisor de tarjeta que proporciona proteccion adicional cuando usted realiza compras online. No hay necesidad de obtener una nueva tarjeta MasterCard o Maestro(r). Usted escoge su propio MasterCard SecureCode personal y este nunca es compartido con ningun comercio. Un codigo privado significa proteccion adicional contra el uso no autorizado de su tarjeta de credito y de debito cuando usted compre online.") ?><td>
    </tr>
    <tr>
        <td colspan='3'>&nbsp;</td>
    </tr>
    <tr>
        <td colspan='3'><?php echo $this->__('Cada vez que pague online con su tarjeta MasterCard o Maestro, una ventana que proviene de su emisor de tarjeta se abre preguntandole por su SecureCode personal, tal como su banco le pregunta en el cajero automatico. En segundos, su emisor de tarjeta confirma que es usted y le permite completar su compra.') ?></td>
    </tr>
    <tr>
        <td colspan='3'>&nbsp;</td>
    </tr>
    <tr>
        <td><img src='<?php echo $this->getSkinUrl('images/servired/mastercard.png') ?>' width='72' /></td>
        <td><?php echo $this->__('Para obtener mas informacion sobre MasterCard SecureCode dirijase a <a href="http://www.mastercardsecurecode.com">www.mastercardsecurecode.com</a>') ?></td>
        <td><img src='<?php echo $this->getSkinUrl('images/servired/maestro.png') ?>' width='72' /></td>
    </tr>
    <tr>
        <td colspan='3' align='center'><button class='form-button' onclick='window.close()'><?php echo $this->helper('page')->__('Cerrar ventana') ?></button></td>
    </tr>
</table>*/?>
Por su seguridad, nuestra pasarela de pago utiliza los sistemas de comercio electrónico seguro  <img src='<?php echo $this->getSkinUrl('images/servired/verified_visa.jpg') ?>' /> para 
tarjetas <img src='<?php echo $this->getSkinUrl('images/servired/visa.jpg') ?>' />   y  <img src='<?php echo $this->getSkinUrl('images/servired/mastercard2.jpg') ?>' />
para tarjetas <img src='<?php echo $this->getSkinUrl('images/servired/ambas.jpg') ?>' /> por lo que la pasarela le redirigirá a su propio banco como emisor de la tarjeta, en donde deberá seguir los pasos que 
se le vaya indicando para garantizar la identidad del comprador y la legitimidad de la transacción. Cada banco tiene su propio sistema de comercio electrónico seguro: tarjeta de coordenadas, PIN, 
código por SMS de su banco, mensaje personal solo conocido por comprador, …. 
Para activar este servicio en su tarjeta  <img src='<?php echo $this->getSkinUrl('images/servired/visa.jpg') ?>' /> y/o <img src='<?php echo $this->getSkinUrl('images/servired/mastercard2.jpg') ?>' />
 deberá contactar con su banco. De no tener activado el sistema de comercio electrónico seguro, no podrá realizar su compra o deberá cambiar la forma de pago. 
 
 <button class='form-button' onclick='window.close()'><?php echo $this->helper('page')->__('Cerrar ventana') ?></button>

 