<?php
/*<table>
    <tr>
        <td><h2><?php echo $this->__("Introduciendo...") ?></h2></td>
        <td>&nbsp;</td>
        <td><img src='<?php echo $this->getSkinUrl('images/servired/mastercard_secuercode.png') ?>' width='116' /></td>
    </tr>
    <tr>
        <td colspan='3'>&nbsp;</td>
    </tr>
    <tr>
        <td colspan='3'><?php echo $this->__("MasterCard (r) SecureCode(tm) es un nuevo servicio de MasterCard y de su emisor de tarjeta que proporciona proteccion adicional cuando usted realiza compras online. No hay necesidad de obtener una nueva tarjeta MasterCard o Maestro(r). Usted escoge su propio MasterCard SecureCode personal y este nunca es compartido con ningun comercio. Un codigo privado significa proteccion adicional contra el uso no autorizado de su tarjeta de credito y de debito cuando usted compre online.") ?><td>
    </tr>
    <tr>
        <td colspan='3'>&nbsp;</td>
    </tr>
    <tr>
        <td colspan='3'><?php echo $this->__('Cada vez que pague online con su tarjeta MasterCard o Maestro, una ventana que proviene de su emisor de tarjeta se abre preguntandole por su SecureCode personal, tal como su banco le pregunta en el cajero automatico. En segundos, su emisor de tarjeta confirma que es usted y le permite completar su compra.') ?></td>
    </tr>
    <tr>
        <td colspan='3'>&nbsp;</td>
    </tr>
    <tr>
        <td><img src='<?php echo $this->getSkinUrl('images/servired/mastercard.png') ?>' width='72' /></td>
        <td><?php echo $this->__('Para obtener mas informacion sobre MasterCard SecureCode dirijase a <a href="http://www.mastercardsecurecode.com">www.mastercardsecurecode.com</a>') ?></td>
        <td><img src='<?php echo $this->getSkinUrl('images/servired/maestro.png') ?>' width='72' /></td>
    </tr>
    <tr>
        <td colspan='3' align='center'><button class='form-button' onclick='window.close()'><?php echo $this->helper('page')->__('Cerrar ventana') ?></button></td>
    </tr>
</table>*/?>
For your security, our payment gateway uses secure e-commerce systems <img src='<?php echo $this->getSkinUrl('images/servired/verified_visa.jpg') ?>' /> for <img src='<?php echo $this->getSkinUrl('images/servired/visa.jpg') ?>' /> cards and  <img src='<?php echo $this->getSkinUrl('images/servired/mastercard2.jpg') ?>' />
for <img src='<?php echo $this->getSkinUrl('images/servired/ambas.jpg') ?>' /> cards so the gateway will redirect you to your own bank as the card issuer, where you should follow the steps 
indicating it will go to ensure the identity of the buyer and the legitimacy of the transaction. Each bank has its own secure e-commerce system: code card, PIN,
SMS code for your bank, personal message only known buyer .... 
To activate this service on your card  <img src='<?php echo $this->getSkinUrl('images/servired/visa.jpg') ?>' /> and/or <img src='<?php echo $this->getSkinUrl('images/servired/mastercard2.jpg') ?>' />
 you should contact your bank. Not have enabled secure e-commerce system, you can not make your purchase or you need to change the method of payment. 
 
 <button class='form-button' onclick='window.close()'>Close Window</button>

 