<?php 
/*<table>
	<tr>
		<td><strong><?php echo $this->__("La misma tarjeta anade mas seguridad on-line.") ?></strong></td>
		<td>&nbsp;</td>
		<td><img src='<?php echo $this->getSkinUrl('images/servired/verifiedbyvisa.png') ?>' /></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__("Verified by Visa es un nuevo servicio que permite comprar on-line con una confianza anadida.") ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__("A traves de un simple proceso de verificacion, Verified by Visa confirma su identidad cuando hace una compra en las tiendas on-line, adscritas al sistema Verified by Visa. Es practico y funciona con su propia tarjeta Visa.") ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__('Y ademas Verified by Visa es de facil uso. Usted registra su tarjeta solo una vez y crea su propia contrasena. Cuando con dicho sistema hace una compra on-line, aparece una ventana de Verified by Visa. Simplemente introduzca su contrasena y haga clic. Su identidad sera verificada y la compra asegurada.') ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__('Para activar Verified by Visa en su tarjeta Visa, o para mas informacion, contacte con la entidad emisora de su tarjeta. <a href="http://www.visa.com/verified">visa.com/verified</a>.') ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3' align='center'><button class='form-button' onclick='window.close()'><?php echo $this->__('Cerrar ventana') ?></button></td>
	</tr>
</table>*/
?>
Por su seguridad, nuestra pasarela de pago utiliza los sistemas de comercio electrónico seguro  <img src='<?php echo $this->getSkinUrl('images/servired/verified_visa.jpg') ?>' /> para 
tarjetas <img src='<?php echo $this->getSkinUrl('images/servired/visa.jpg') ?>' />   y  <img src='<?php echo $this->getSkinUrl('images/servired/mastercard2.jpg') ?>' />
para tarjetas <img src='<?php echo $this->getSkinUrl('images/servired/ambas.jpg') ?>' /> por lo que la pasarela le redirigirá a su propio banco como emisor de la tarjeta, en donde deberá seguir los pasos que 
se le vaya indicando para garantizar la identidad del comprador y la legitimidad de la transacción. Cada banco tiene su propio sistema de comercio electrónico seguro: tarjeta de coordenadas, PIN, 
código por SMS de su banco, mensaje personal solo conocido por comprador, …. 
Para activar este servicio en su tarjeta  <img src='<?php echo $this->getSkinUrl('images/servired/visa.jpg') ?>' /> y/o <img src='<?php echo $this->getSkinUrl('images/servired/mastercard2.jpg') ?>' />
 deberá contactar con su banco. De no tener activado el sistema de comercio electrónico seguro, no podrá realizar su compra o deberá cambiar la forma de pago. 
 
 <button class='form-button' onclick='window.close()'><?php echo $this->helper('page')->__('Cerrar ventana') ?></button>