<?php 
/*<table>
	<tr>
		<td><strong><?php echo $this->__("La misma tarjeta anade mas seguridad on-line.") ?></strong></td>
		<td>&nbsp;</td>
		<td><img src='<?php echo $this->getSkinUrl('images/servired/verifiedbyvisa.png') ?>' /></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__("Verified by Visa es un nuevo servicio que permite comprar on-line con una confianza anadida.") ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__("A traves de un simple proceso de verificacion, Verified by Visa confirma su identidad cuando hace una compra en las tiendas on-line, adscritas al sistema Verified by Visa. Es practico y funciona con su propia tarjeta Visa.") ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__('Y ademas Verified by Visa es de facil uso. Usted registra su tarjeta solo una vez y crea su propia contrasena. Cuando con dicho sistema hace una compra on-line, aparece una ventana de Verified by Visa. Simplemente introduzca su contrasena y haga clic. Su identidad sera verificada y la compra asegurada.') ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__('Para activar Verified by Visa en su tarjeta Visa, o para mas informacion, contacte con la entidad emisora de su tarjeta. <a href="http://www.visa.com/verified">visa.com/verified</a>.') ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3' align='center'><button class='form-button' onclick='window.close()'><?php echo $this->__('Cerrar ventana') ?></button></td>
	</tr>
</table>*/
?>
For your security, our payment gateway uses secure e-commerce systems <img src='<?php echo $this->getSkinUrl('images/servired/verified_visa.jpg') ?>' /> for <img src='<?php echo $this->getSkinUrl('images/servired/visa.jpg') ?>' /> cards and  <img src='<?php echo $this->getSkinUrl('images/servired/mastercard2.jpg') ?>' />
for <img src='<?php echo $this->getSkinUrl('images/servired/ambas.jpg') ?>' /> cards so the gateway will redirect you to your own bank as the card issuer, where you should follow the steps 
indicating it will go to ensure the identity of the buyer and the legitimacy of the transaction. Each bank has its own secure e-commerce system: code card, PIN,
SMS code for your bank, personal message only known buyer .... 
To activate this service on your card  <img src='<?php echo $this->getSkinUrl('images/servired/visa.jpg') ?>' /> and/or <img src='<?php echo $this->getSkinUrl('images/servired/mastercard2.jpg') ?>' />
 you should contact your bank. Not have enabled secure e-commerce system, you can not make your purchase or you need to change the method of payment.
 
 <button class='form-button' onclick='window.close()'>Close Window</button>