<?php
/**
 * Products Carousel - Magento Extension
 *
 * @package:     ProductsCarousel
 * @category:    EcommerceTeam
 * @copyright:   Copyright 2012 EcommerceTeam Inc. (http://www.ecommerce-team.com)
 * @version:     1.0.0
 */

$_product = $this->getProduct();

?>
<li>
    <div class="product-wrap">
        <div class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(235, 345); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></div>
        <div class="product-info" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
				<?php echo $_product->getAttributeText('manufacturer');?>
				<div class="separator"></div>
				<span><?php echo $_product->getName();?></span>
			</a>
        </div>
    </div>
</li>