<?php if($this->getCurrencyCount()>1): ?>
    <div class="currency">
            <div class="btn-group">
                         <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
                             <?php if($_code == $this->getCurrentCurrencyCode()): 
                                $currency_symbol = Mage::app()->getLocale()->currency($_code)->getSymbol();?>

                                <a class="dropdown-toggle" data-toggle="dropdown" id="dropdownCurrencySelected" href="#"><?php echo $_code ?> 
                                    <span class="caret"></span>
                                </a>
                            <?php endif; ?>                  
                        <?php endforeach; ?>
                <ul class="currencyList" id="currencyListview">
                    <?php foreach ($this->getCurrencies() as $_code => $_name): 
                        $currency_symbol = Mage::app()->getLocale()->currency($_code)->getSymbol();?>
                        <li>
                            <a href="<?php echo $this->getSwitchCurrencyUrl($_code)?>">
                             <?php echo $_code ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
    </div>
<?php endif; ?>