
<?php if($this->getCurrencyCount()>1): ?>

 <div class="lang-currency-container">
                
<!-- LANGUAGES BOF -->
<!-- LANGUAGES EOF -->                
<!-- Currency BOF -->

 <select style="height:20px;margin-top: 4px;" id="mobile-currency" name="currency" title="<?php echo $this->__('Select Your Currency') ?>" onchange="setLocation(this.value)">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <option value="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>>
                <?php echo $_name ?> - <?php echo $_code ?>
            </option>
        <?php endforeach; ?>
        </select>
<!-- Currency EOF -->
 </div>

 
<?php endif; ?>