<?php 

	if(count($this->getStores())>1): ?>
	<div class="language-switcher">
		<div class="btn-group">
		    <?php foreach ($this->getStores() as $_lang): ?>
		    					<?php if($_lang->getName() == Mage::app()->getStore()->getName()): ?>

	                                <a class="dropdown-toggle" data-toggle="dropdown" id="dropdownCurrencySelected" href="#"><?php echo $this->htmlEscape($_lang->getName()) ?>
	                                </a>
	                            <?php endif; ?>
		    <?php endforeach; ?>
		    		<ul class="currencyList" id="currencyListview">
	                    <?php foreach ($this->getStores() as $_lang): ?>
	                    	<?php if($_lang->getName() != Mage::app()->getStore()->getName()): ?>
		                        <li>
		                            <a href="<?php echo $_lang->getCurrentUrl() ?>" title="<?php echo $this->htmlEscape($_lang->getName()) ?>">
		                             <?php echo $this->htmlEscape($_lang->getName()) ?>
		                            </a>
		                        </li>
		                    <?php endif; ?>
	                    <?php endforeach; ?>
	                </ul>
		</div>
	</div>
<?php endif; ?>

