<?php 
 $cookie = Mage::getSingleton('core/cookie');
 $banderita = $cookie->get('geoip_bandera');
 $nombre = $cookie->get('geoip_nombre');
 $countryCode = Mage::getStoreConfig('general/country/default');
 $countyName = Mage::app()->getLocale()->getCountryTranslation($countryCode);
if($banderita != ""):
    ?>
    <div class="btn-groupl">
            <button class="dropdown-toggle" data-toggle="dropdown" id="dropdownSelected" onclick="location.href = '<?php echo Mage::getUrl('sendto');?>'" style="color:rgb(255, 255, 255)">
                    <div class="imagen" style="background:url('<?php echo $this->getSkinUrl("images/flags/flags_iso/16/" . strtolower($banderita) .".png");?>')repeat scroll 94px 63px; width: 12px; height: 12px; float: left; border-radius: 6px; margin-top: 5px;">
                    </div>
                    <span>
                        <?php echo $nombre ?>
                    </span>
            </button>
    </div>
<?php
else:
    if($countryCode != ""):
        ?>
        <div class="btn-groupl">
            <button class="dropdown-toggle" data-toggle="dropdown" id="dropdownSelected" onclick="location.href = '<?php echo Mage::getUrl('sendto');?>'" style="color:rgb(255, 255, 255)">
                    <div class="imagen" style="background:url('<?php echo $this->getSkinUrl('images/flags/flags_iso/16/' . strtolower($countryCode) .".png");?>')repeat scroll 94px 63px; width: 12px; height: 12px; float: left; border-radius: 6px; margin-top: 5px;">
                    </div>
                    <span>
                        <?php echo $countyName ?>
                    </span>
            </button>
        </div>
    <?php
    endif;
endif;?>
