<?php if($this->canShowBlock()): ?>
<div class="block adv-search-nav">
    <div class="block-content">
        <?php echo $this->getStateHtml() ?>
        <?php if($this->canShowOptions()): ?>
 <?php ?><p class="block-subtitle"><?php echo $this->__('Shopping Options') ?></p><?php ?>
            <dl id="narrow-by-list">
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount()): ?>
					<?php if($this->__($_filter->getName() == "Category")): ?>
                    	<dt><a href="JavaScript:void(0);">Type</a></dt>
                        <?php 
						$category_model = Mage::getModel('catalog/category');
						$_category = $category_model->load(9); 
						$all_child_categories = $category_model->getResource()->getAllChildren($_category);
						?>
                        <dd>
                            <ol>
								<?php
									foreach($all_child_categories as $id):
										$childCategory = $category_model->load($id);
										if($childCategory->getName() == "shop" || ($childCategory->getEntityId() == 10 || $childCategory->getEntityId() == 11 || $childCategory->getEntityId() == 12 || $childCategory->getEntityId() == 13 || $childCategory->getEntityId() == 14 
										|| $childCategory->getEntityId() == 16 || $childCategory->getEntityId() == 17 || $childCategory->getEntityId() == 18 || $childCategory->getEntityId() == 19) ):
										else:
											echo "<li>";
											echo '<a href="/shop.php?cat='.$childCategory->getEntityId().'" id='.$childCategory->getEntityId().'>'.$childCategory->getName().' <span class="product-items">('.Mage::getModel("catalog/category")->load($id)->getProductCount().')</span></a>';
											echo "</li>";
		
										endif;
									endforeach;
                                ?>
                            </ol>
                        </dd>
 
                    <?php else: ?>
                        <dt><a href="JavaScript:void(0);"><?php echo $_filter->getName() ?></a></dt>
                        <dd><?php echo str_replace(array('?','/?'),array('shop.php?','/shop.php?'),$_filter->getHtml()) ?></dd>
                    <?php endif; ?>
                <?php endif; ?>
            
                <?php endforeach; ?>
            </dl>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>

<script type="text/javascript">
//<![CDATA[
		$j("dl#narrow-by-list> dd:visible").hide();
		$j(document).ready(function(){
		$j("dl#narrow-by-list> dt a").addClass('test1');
	});
		$j("dl#narrow-by-list> dt a").click(function(){
		if($j(this).hasClass('test1')){
			$j("dl#narrow-by-list> dt a").addClass('test1').removeClass('test2');
			$j("dl#narrow-by-list> dd:visible").slideUp("fast");
			$j(this).parent().next().slideDown("fast");
			$j(this).removeClass('test1').addClass('test2')	
		}
		else
		{
		$j("dl#narrow-by-list> dt a").addClass('test1').removeClass('test2');
		$j(this).removeClass('test2').addClass('test1')
		$j(this).parent().next().slideUp("fast");	
		}
});
//]]>
</script> 