
<?php if($this->canShowBlock()): ?>
<?php $layer = themeOptions('layer');
	  $categories= $this->getLayer()->getCurrentCategory()->load()->getPath();
	  $categoriesIds = explode('/', $categories);
	  
	  unset($categoriesIds[0]);
	   ?>
      
<div class="block block-layered-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Shopping Options') ?></span></strong>
    </div>
    <div class="block-content">
        <?php echo $this->getStateHtml() ?>
        <?php if($this->canShowOptions()): ?>
        <?php if (Mage::app()->getStore()->getId()==1 || Mage::app()->getStore()->getId()==2): //Si se trata de Elitestore.es  ?>
        <!-- Insertamos selector para secciones especiales -->
	        <?php if (in_array(23,$categoriesIds)): //Mujer ?>
            <dl id="narrow-by-list">
            	<dt id="filterlabel0" class="active odd"><?php echo $this->__('Inspiration');?></dt>
                    <dd class="odd">
                        <ol>
                        	<li><a href="http://www.elitestore.es/special-sections/bold-and-gold.html"><?php  echo $this->__('Bold & Gold')?></a></li>
                            <li><a href="http://www.elitestore.es/special-sections/back-to-black.html?cat=238"><?php  echo $this->__('Back to Black')?></a></li>
                            <li><a href="http://www.elitestore.es/special-sections/color-explosion.html"><?php  echo $this->__('Colour Explosion')?></a></li>
                            
                            
    					</ol>
					</dd>
                    
                    <script type="text/javascript">   
                             
                            jQuery('#filterlabel0').each(function(){
                                jQuery(this).addClass('active');
                                jQuery(this).toggle(function(){
                                    jQuery(this).removeClass('active').next().slideUp(200);
                                },function(){
                                    jQuery(this).addClass('active').next().slideDown(200);
                                })
                            });                        
                                            
                    </script>                     
				</dl>
            	
            <?php elseif(in_array(62,$categoriesIds)): //Hombre ?>
            	<dl id="narrow-by-list">
                    <dt id="filterlabel0" class="active odd"><?php echo $this->__('Inspiration');?></dt>
                        <dd class="odd">
                            <ol>
                            	<li><a href="http://www.elitestore.es/special-sections/ss15-trend-graphic-t-shirts.html"><?php  echo $this->__('Graphic T-Shirts')?></a></li>
                            	<li><a href="http://www.elitestore.es/special-sections/back-to-black.html?cat=237"><?php  echo $this->__('Back to Black')?></a></li>
                                <li><a href="http://www.elitestore.es/special-sections/lets-get-the-party-started.html"><?php  echo $this->__('Let’s Party!')?></a></li>
                               
                                
                    		</ol>
                        </dd>
                    
                    <script type="text/javascript">   
                             
                            jQuery('#filterlabel0').each(function(){
                                jQuery(this).addClass('active');
                                jQuery(this).toggle(function(){
                                    jQuery(this).removeClass('active').next().slideUp(200);
                                },function(){
                                    jQuery(this).addClass('active').next().slideDown(200);
                                })
                            });                        
                                            
                    </script>                     
                                                                                                                         
				</dl> 
            <?php endif ?>
      	<?php endif; ?>
            <dl id="narrow-by-list">

                <?php $_filters = $this->getFilters() ?>
                <?php $i=0; foreach ($_filters as $_filter): $i++; ?>
                <?php if($_filter->getItemsCount() && $_filter->getName()!='Temporada' && $_filter->getName()!='Season'): //Para que no se muestre el fitro con los demás?>
                    <dt id="filterlabel<?php echo $i;?>"><?php echo $this->__($_filter->getName()) ?></dt>
                    <dd><?php echo $_filter->getHtml() ?></dd>
                    
                    <script type="text/javascript" >
					   
                        <?php if($layer == 2): ?>     
                            jQuery('#filterlabel<?php echo $i;?>').each(function(){
                                jQuery(this).addClass('active');
                                jQuery(this).toggle(function(){
                                    jQuery(this).removeClass('active').next().slideUp(200);
                                },function(){
                                    jQuery(this).addClass('active').next().slideDown(200);
                                })
                            });                        
                        <?php elseif($layer == 1): ?>     
                            jQuery('#filterlabel<?php echo $i;?>').each(function(){
                                jQuery(this).next().hide();
                                jQuery(this).toggle(function(){
                                    jQuery(this).addClass('active').next().slideDown(200);
                                },function(){
                                    jQuery(this).removeClass('active').next().slideUp(200);
                                })
                            });    
                        <?php endif; ?>
						
						<?php if ($_filter->getName()=='Size' || $_filter->getName()=='Talla' || $_filter->getName()=='Price' || $_filter->getName()=='Precio'): /* Añadimos esta sentencia para ocultar las opciones de talla disponibles o rangos de precios */?>			
						    jQuery('#filterlabel<?php echo $i;?>').each(function(){
								jQuery(this).removeClass('active').next().hide();
							});
						<?php endif; ?>
                    </script>                     
                <?php endif; ?>
                <?php endforeach; ?>
            </dl>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
