<?php
$pais_origen=Mage::getSingleton('geoip/country')->getCountry();
$storeId = Mage::app()->getStore()->getStoreId();
if ($this->isActivePopUp()):
?>
<script type="text/javascript">
    <?php if (is_numeric($this->getCookieLifeTime())): ?>
    EsNewsSubscribers.setCookieLiveTime(<?php echo $this->getCookieLifeTime(); ?>);
    <?php endif; ?>
    <?php if ($this->getCookieName()): ?>
    EsNewsSubscribers.setCookieName('<?php echo $this->getCookieName(); ?>');
    <?php endif; ?>
    EsNewsSubscribers.setBaseUrl('<?php echo $this->getBaseUrl(); ?>');
</script>


    
<div id="esns_background_layer">
    <div id="esns_box">
    	<a href="http://www.elitestore.es/sale/"><div id="<?php if ($storeId==2):?>esns_box_layer<?php elseif ($storeId==1):?>esns_box_layer<?php endif;?>"><span class="aclaration">*Your 10% extra discount will be applied automatically during checkout!</span>
		
    </div></a>
        <div id="esns_box_close"></div>
    </div>
</div>

<?php endif; ?>