<?php
if ($this->isActivePopUp()):
?>
<script type="text/javascript">
    <?php if (is_numeric($this->getCookieLifeTime())): ?>
    EsNewsSubscribers.setCookieLiveTime(<?php echo $this->getCookieLifeTime(); ?>);
    <?php endif; ?>
    <?php if ($this->getCookieName()): ?>
    EsNewsSubscribers.setCookieName('<?php echo $this->getCookieName(); ?>');
    <?php endif; ?>
    EsNewsSubscribers.setBaseUrl('<?php echo $this->getBaseUrl(); ?>');
</script>


    
<div id="esns_background_layer">
    <a style="width:100%;height:100%;" href="http://www.elitestore.es/sale">
    <div id="esns_box_layer">
        <div id="esns_box_close"></div>
        
    </div>
    </a>
</div>


<?php endif; ?>