<?php
$pais_origen=Mage::getSingleton('geoip/country')->getCountry();
$storeId = Mage::app()->getStore()->getStoreId();
if ($this->isActivePopUp()):
?>
<script type="text/javascript">
    <?php if (is_numeric($this->getCookieLifeTime())): ?>
    EsNewsSubscribers.setCookieLiveTime(<?php echo $this->getCookieLifeTime(); ?>);
    <?php endif; ?>
    <?php if ($this->getCookieName()): ?>
    EsNewsSubscribers.setCookieName('<?php echo $this->getCookieName(); ?>');
    <?php endif; ?>
    EsNewsSubscribers.setBaseUrl('<?php echo $this->getBaseUrl(); ?>');
</script>


    
<div id="esns_background_layer">
    <div id="esns_box">
    <?php if ($storeId==2):?>
    	<a href=""><div id="esns_box_layer"><span class="aclaration">*10% discount will be applied automatically during checkout. Promotion not accumulative to others. Only for current season .Not for Outlet.</span>
	<?php elseif ($storeId==1):?>
    	<a href=""><div id="esns_box_layer"><span class="aclaration">*El descuento será aplicado automáticamente al formalizar su compra. Esta promoción no podrá ser añadida a ninguna otra promoción existente. Esta promoción solo será aplicable para artículos de temporada, no outlet.</span>	
    <?php endif;?>
    </div></a>
    
        <div id="esns_box_close"></div>
    </div>
</div>

<?php endif; ?>