<?php
if ($this->isActivePopUp()):
?>
<script type="text/javascript">
    <?php if (is_numeric($this->getCookieLifeTime())): ?>
    EsNewsSubscribers.setCookieLiveTime(<?php echo $this->getCookieLifeTime(); ?>);
    <?php endif; ?>
    <?php if ($this->getCookieName()): ?>
    EsNewsSubscribers.setCookieName('<?php echo $this->getCookieName(); ?>');
    <?php endif; ?>
    EsNewsSubscribers.setBaseUrl('<?php echo $this->getBaseUrl(); ?>');
</script>


    
<div id="esns_background_layer">
    
    <div id="<?php if (Mage::app()->getStore()->getStoreId()==2): ?>esns_box_layer<?php elseif (Mage::app()->getStore()->getStoreId()==1):?>esns_box_layer_es<?php endif; ?>">
        <div id="esns_box_close"></div>
        <!--<object style="margin-top:350px; margin-left:45px; box-shadow:black 0px 0px 10px" type="application/x-shockwave-flash" data="http://www.oneplusyou.com/bb/files/countdown/countdown.swf?co=ff0000&bgcolor=FFFFFF&date_month=10&date_day=12&date_year=2014&un=PROMOTION ENDS&size=normal&mo=10&da=12&yr=2014" width="250" height="80"><param name="movie" value="http://www.oneplusyou.com/bb/files/countdown/countdown.swf?co=ff0000&bgcolor=FFFFFF&date_month=10&date_day=12&date_year=2014&un=PROMOTION ENDS&size=normal&mo=10&da=12&yr=2014" /><param name="bgcolor" value="#FFFFFF" /></object>-->
    </div>
    
</div>


<?php endif; ?>