<?php
if ($this->isActivePopUp()):
?>
<script type="text/javascript">
    <?php if (is_numeric($this->getCookieLifeTime())): ?>
    EsNewsSubscribers.setCookieLiveTime(<?php echo $this->getCookieLifeTime(); ?>);
    <?php endif; ?>
    <?php if ($this->getCookieName()): ?>
    EsNewsSubscribers.setCookieName('<?php echo $this->getCookieName(); ?>');
    <?php endif; ?>
    EsNewsSubscribers.setBaseUrl('<?php echo $this->getBaseUrl(); ?>');
</script>
<div id="esns_background_layer">
    <div id="esns_box">
    

    		<a href="<?php Mage::getUrl()?>sale?dir=desc&discount=5355&order=prioridad"><div id="esns_box_layer">
            	
            </div></a>
        <div id="esns_box_close"></div>

        
    </div>
</div>

<?php endif;?>