<?php
$pais_origen=Mage::getSingleton('geoip/country')->getCountry();
$storeId = Mage::app()->getStore()->getStoreId();
if ($this->isActivePopUp()):
?>
<script type="text/javascript">
    <?php if (is_numeric($this->getCookieLifeTime())): ?>
    EsNewsSubscribers.setCookieLiveTime(<?php echo $this->getCookieLifeTime(); ?>);
    <?php endif; ?>
    <?php if ($this->getCookieName()): ?>
    EsNewsSubscribers.setCookieName('<?php echo $this->getCookieName(); ?>');
    <?php endif; ?>
    EsNewsSubscribers.setBaseUrl('<?php echo $this->getBaseUrl(); ?>');
</script>


    
<div id="esns_background_layer">
    
    <a href="http://www.elitestore.es/sale/"><div id="<?php if ($storeId==2):?>esns_box_layer<?php else:?>esns_box_layer_es<?php endif;?>">
        <div id="esns_box_close"></div>
    </div></a>
    
</div>

<?php endif; ?>