<?php
$pais_origen=Mage::getSingleton('geoip/country')->getCountry();
$storeId = Mage::app()->getStore()->getStoreId();
if ($this->isActivePopUp()):
?>
<script type="text/javascript">
    <?php if (is_numeric($this->getCookieLifeTime())): ?>
    EsNewsSubscribers.setCookieLiveTime(<?php echo $this->getCookieLifeTime(); ?>);
    <?php endif; ?>
    <?php if ($this->getCookieName()): ?>
    EsNewsSubscribers.setCookieName('<?php echo $this->getCookieName(); ?>');
    <?php endif; ?>
    EsNewsSubscribers.setBaseUrl('<?php echo $this->getBaseUrl(); ?>');
</script>


    
<div id="esns_background_layer">
    <div id="esns_box">
    
    	<a href="<?php echo Mage::getBaseUrl()?>/sale?cat=62"><div id="esns_box_layer"></div></a>
        <div id="esns_box_close"></div>
 		<span style="font-size: 11px;float: right;color:white;margin-right: 20px;">*Only for men&#39;s SS15 sale items. The discount will be applied automatically during checkout. 100€</span>   
        
    </div>
</div>

<?php endif; ?>