<?php
/**
 * Survey for Magento
 *
 * @category   Belitsoft
 * @package    Belitsoft_Survey
 * @author     Belitsoft <bits@belitsoft.com>
 */

/* @var $this Belitsoft_Survey_Block_Adminhtml_Question_Edit_Fields */
?>

<?php if($this->getQuestionType()): ?>
<?php echo $this->getFields(); ?>
<?php endif; ?>

<?php if(!$this->getQuestionType()): ?>
<?php echo Mage::helper('belitsoft_survey')->__("Please, select Question type to load options"); ?>
<?php endif; ?>

