<div style="width:100%; text-align: center;">
<img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-boost-350.png" alt="" /></div>
Due to extremely high demand and the limited edition character of the sneakers, we believe the most fair way of selling the new Yeezy Boost 350 online, is a raffle. 
Sign up for a chance to buy a pair!
<!--tirita-->
<ul class="products-grid columns3 first odd" style="width:100%;">
    <li class="item first">
        <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_1.jpg" width="245" height="245" alt="Y-3 - LOGO WAXED CAP">
    </li>
    <li class="item first" style="margin: 15px 10%;">
        <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_2.jpg" width="245" height="245" alt="Y-3 - LOGO WAXED CAP">
    </li>
    <li class="item first 152" style="float: right;margin: 0px;margin-top: 15px;">
        <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_3.jpg" width="245" height="245" alt="Y-3 - LOGO WAXED CAP">
    </li>


</ul>
<!--       primera yeezy-->
<ul class="products-grid columns3 first odd" style="width:100%;">
    <li class="item first " style="width: 225px;">
        <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_0.jpg" width="215" height="215" alt="Y-3 - LOGO WAXED CAP">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list">Kanye West</div>
            			<div class="product-name">Yeezy 7</div>
                    </div>      
	    			<div class="price-box">
		              <span class="regular-price" id="product-price-54694"> 
		                  <span class="price">200€</span>      
		              </span>
	      			</div>
    			</div>
			<input type="submit" value="Suscribe">
    </li>
    <li class="item first " style="width: 225px;">
        <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_0.jpg" width="215" height="215" alt="Y-3 - LOGO WAXED CAP">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list">Kanye West</div>
            			<div class="product-name">Yeezy 8</div>
                    </div>      
    				<div class="price-box">
			             <span class="regular-price" id="product-price-54694"> 
			                  <span class="price">200€</span>      
			              </span>
      				</div>
    			</div>
			<input type="submit" value="Suscribe">
    </li>
    <li class="item first " style="width: 225px;">
        <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_0.jpg" width="215" height="215" alt="Y-3 - LOGO WAXED CAP">
                <div class="moreinfo">
                	<div class="product-title">
                    	<div class="manuf-list">Kanye West</div>
            			<div class="product-name">Yeezy 9</div>
                    </div>      
    				<div class="price-box">
			             <span class="regular-price" id="product-price-54694"> 
			                  <span class="price">200€</span>      
			              </span>
      				</div>
    			</div>
			<input type="submit" value="Suscribe">
  	</li>
    <li class="item first " style="width: 225px;">
        <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_0.jpg" width="215" height="215" alt="Y-3 - LOGO WAXED CAP">
                <div class="moreinfo">
                    <div class="product-title">
                        <div class="manuf-list">Kanye West</div>
                        <div class="product-name">Yeezy 10</div>
                    </div>      
                    <div class="price-box">
                         <span class="regular-price" id="product-price-54694"> 
                              <span class="price">200€</span>      
                          </span>
                    </div>
                </div>
            <input type="submit" value="Suscribe">
    </li>

</ul>

<!--       ultima yeezy-->

RAFFLE CONDITIONS<br>
• The raffle starts on Saturday, October 14 at 11.00 AM CET and ends on Monday, October 16 at 11.00 AM CET.<br>
• By signing up for the raffle (in case you haven’t joined us yet), you automatically sign up for our newsletter.<br>
• Only ONE entry per person is allowed. <br>
• The winners will be announced on our social media, and notified via phone and email, including a private link to finish the purchase. In case the winner doesn’t make the purchase within 24hrs, a new winner will be randomly selected from among all signed up participants.<br>
• Return policy: refund within 14 days of the delivery date. <br>
• In case of a return, a new winner will be randomly selected from among all signed up participants.<br>
<div class="box simple_contact7">
 
<form id="simple_contact_form8" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="7">
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value="" class="required-entry input-text" type="text" />
                </div>
 
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value="" class="required-entry input-text validate-email" type="text" />
                </div>
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button class="form-button" type="submit"><span>Submit</span></button>
 
    </div>
</form>
 
</div>
<div class="box simple_contact8">
 
<form id="simple_contact_form9" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="8">
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value="" class="required-entry input-text" type="text" />
                </div>
 
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value="" class="required-entry input-text validate-email" type="text" />
                </div>
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button class="form-button" type="submit"><span>Submit</span></button>
 
    </div>
</form>
 
</div>
<div class="box simple_contact9">
 
<form id="simple_contact_form10" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="9">
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value="" class="required-entry input-text" type="text" />
                </div>
 
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value="" class="required-entry input-text validate-email" type="text" />
                </div>
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button class="form-button" type="submit"><span>Submit</span></button>
 
    </div>
</form>
 
</div>
<div class="box simple_contact10">
 
<form id="simple_contact_form10" name="simple_contact_form" action="<?php echo $this->getUrl('yeezy-raffle/') ?>index/sendemail" method="post">
 
    <fieldset class="group-select">
      <ul>
        <li>
        <input type="hidden" name="talla" value="10">
                <div class="input-box">
                    <label for="name"><?php echo $this->__('Your name') ?><span class="required">*</span></label><br />
 
                    <input name="name" id="name" title="Name" value="" class="required-entry input-text" type="text" />
                </div>
 
                <div class="input-box">
                    <label for="email"><?php echo $this->__('Your email') ?><span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value="" class="required-entry input-text validate-email" type="text" />
                </div>
        </li>
      </ul>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button class="form-button" type="submit"><span>Submit</span></button>
 
    </div>
</form>
 
</div>
<script type="text/javascript">
    //< ![CDATA[
        var customForm1 = new VarienForm('simple_contact_form8');
        var customForm2 = new VarienForm('simple_contact_form9');
        var customForm3 = new VarienForm('simple_contact_form10');
    //]]>
    Validation.add('validate-email', 'Please enter a valid Gmail address. For example johndoe@gmail.com.', function(v) {
    return Validation.get('IsEmpty').test(v) || (/^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$/i.test(v)
});
$( document ).ready(function() {
  $('box').hidden();
});
</script>