<?php if(count($this->getStores())>1): $_i_lang = 0; /*?>
<div class="form-language">
    <?php foreach ($this->getStores() as $_lang): $_i_lang++; ?>
        <div class="lang">
            <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId())?>
            <?php if(!$_selected): ?>
                <?php if($_i_lang != 1):?> <span class="separator">|</span><?php endif; ?><a href="<?php echo $_lang->getCurrentUrl() ?>"><?php echo $this->htmlEscape($_lang->getName()) ?></a>
            <?php else: ?>
                <?php if($_i_lang != 1):?> <span class="separator">|</span><?php endif; ?><?php echo $this->htmlEscape($_lang->getName()) ?>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
    <div style="clear: both;"></div>
</div><?*/?>
<!--<div class="form-language">
    <label for="custom-language-selector"><?php echo $this->__('Your language:') ?></label>
        <select onchange="window.location.href=this.value" name="custom-language-selector" id="custom-language-selector">
            <?php foreach  ($this->getStores() as $_lang): $_i_lang++; ?>
            <option value="<?php echo $_lang->getCurrentUrl() ?>"
            <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId())?>
                <?php 



                if($_selected): ?>
                    selected="SELECTED"
                <?php endif; ?>>
                <?php echo $this->htmlEscape($_lang->getName()) ?>
            </option>
            <?php endforeach; ?>
        </select>
</div>-->

    <div class="form-language">
        <label for="custom-language-selector"style="display: inline-box;"><?php echo $this->__('Your Language:') ?></label>
            <div class="btn-groupl">
                         <?php foreach ($this->getStores() as $_lang): $_i_lang++; ?>
                            <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId())?>
                         <?php if($_selected): 
                            switch($this->htmlEscape($_lang->getName()))
                            {
                                case "ENGLISH":
                                ?><a class="dropdown-toggle" data-toggle="dropdown" id="dropdown" href="#"><img src="http://www.elitestore.es/media/wysiwyg/banderas/GBP.png"> <?php echo $_code ?><?php echo $this->htmlEscape($_lang->getName()) ?> <span class="caret"></span></a><?php
                                break;
                                case "ESPAÑOL":
                                ?><a class="dropdown-toggle" data-toggle="dropdown" id="dropdown" href="#"><img src="http://www.elitestore.es/media/wysiwyg/banderas/ESP.png"> <?php echo $_code ?><?php echo $this->htmlEscape($_lang->getName()) ?> <span class="caret"></span></a><?php
                                break;
                            }
                            ?>
                        <?php endif; ?>                  

                        <?php endforeach; ?>
                <ul class="currencyList" id="currencyListviewl">
                    <?php foreach ($this->getStores() as $_lang): $_i_lang++; ?>
                    <li>
                        <a href="<?php echo $_lang->getCurrentUrl() ?>">
                        <?php switch($this->htmlEscape($_lang->getName()))
                            {
                                case "ENGLISH":
                                ?> <img src="http://www.elitestore.es/media/wysiwyg/banderas/GBP.png"><?php
                                break;
                                case "ESPAÑOL":
                                ?><img src="http://www.elitestore.es/media/wysiwyg/banderas/ESP.png"><?php
                                break;
                            }?>
                         <?php echo $this->htmlEscape($_lang->getName()) ?>
                        </a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
    </div>
<?php endif; ?>