<?php
 //Get Order Number & Order Total 
$order = Mage::getModel('sales/order')->loadByIncrementId(Mage::getSingleton('checkout/session')->getLastRealOrderId()); 
$amount = number_format($order->getGrandTotal(),2); 
$currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();
?>

<!-- Facebook Conversion Code for Promoweb-1 -->
<script>(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', '6019225056434', {'value':'<?php echo $amount ?>','currency':'<?php echo $currency_code ?>'}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6019225056434&amp;cd[value]=<?php echo $amount ?>&amp;cd[currency]=<?php echo $currency_code ?>&amp;noscript=1" /></noscript>
