
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>

<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar" id="desktop-toolbar" >
    <div class="sorter">
		<?php if ($this->getHidePager()){ ?>
			<div class="sort-by toolbar-switch">
				<div class="toolbar-title" id="toolbar-title1" onmouseover="showSortBy()" onmouseout="hideSortBy()"><label><?php echo $this->__('By') ?></label>
					<span class="current">
						<?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
							<?php if($this->isOrderCurrent($_key)): ?><?php echo $this->__($_order) ?><?php endif; ?>
						<?php endforeach; ?>
					</span>
				</div>
				<div class="toolbar-dropdown" id="toolbar-dropdown1" onmouseover="showSortBy()" onmouseout="hideSortBy()">
					<ul id="aa">
						<?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
							<li><a href="<?php echo $this->getOrderUrl($_key, 'asc') ?>"> <?php echo $this->__($_order) ?></a></li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>
			
			<div class="sort-order">
				<?php if($this->getCurrentDirection() == 'desc'): ?>
					<a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>">
						&#61698;
					</a>
				<?php else: ?>
					<a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>">
						&#61699;
					</a>
				<?php endif; ?>
			</div>
		<?php } else { ?>
			<?php echo $this->getPagerHtml() ?>    
		<?php } ?>
    </div>
</div>
</div>
<?php endif ?>


