<?php 
    $count_labels = 0;
	$sale = false;
	if (themeOptions('sale_label'))
	{
		$specialPrice = number_format($_product->getFinalPrice(), 2);
		$regularPrice = number_format($_product->getPrice(), 2);
		if ($specialPrice != $regularPrice){
            $count_labels++;
	       	$sale = true;
		}
	}
    
	$new = false;
	if (themeOptions('new_label'))
	{
        $now = date("Y-m-d H:m:s");   
        $newFromDate = $_product->getNewsFromDate();
        $newToDate = $_product->getNewsToDate();                                               
        if($newFromDate < $now && $newToDate > $now){
            $new = true;
            $count_labels++;
        }
	}
		
	$pre_order_item = false;
	if ($_product->getAttributeText('pre_order_item')!='No')
	{
		$pre_order_item=true;
	}    
    if($new && !$pre_order_item){
        ?>
            <div class="newproduct_grid"><?php echo $this->__('New') ?></div>
        <?php
    }
     
    if($sale){
        ?>
            <div class="saleproduct"><?php echo $this->__('Sale') ?></div>
        <?php
    }
	
		
	if ($pre_order_item){
		?>
            <div class="pre-orderproduct"><?php echo $this->__('Pre-Order Item') ?></div>
        <?php
	}
	
	
?>