<?php
$productId = $this->getProduct_id(); 
$_product = Mage::getModel('catalog/product')->load($productId); //load the product
?>
<h1>holaaaaaaaaaaaaaaaaaaaaaa</h1>
<div style="width: 150px;float: left;">
                                                            	<a href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(150,200) ?>" border="0" height="200px"/></a>
                                                            </div>
                                                            <div style="width: 200px;float: right;">
                                                            	<div class="name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo strtolower($_product->getName());?></a></div>
                                                                <div class="designer"><?php echo strtolower($_product->getAttributeText('manufacturer'));?></div>
                                                               	<?php echo $this->getPriceHtml($_product, true) ?>
                                                                <div style="margin-top:60px; margin-left:40px; margin-right:40px;">
                                                                <div style="float: left;padding-left: 10px;width:150px">
                                                                        <?php if (($_product->getAttributeText('no_shop_button'))=='No'):?>                                                                                <?php if($_product->isSaleable()): ?>
                                													<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                												<?php else: ?>
                                    												<a class="orderrequest_button" href="http://www.elitestore.es/orderrequest?id=<?php echo $_product->getId()?>" rel="shadowbox;width=728 height=700;scroll=none"><?php echo $this->__('Order by Request'); ?></a>
                                												<?php endif; ?>
                            											<?php else: ?>
                            														<a class="orderrequest_button" href="http://www.elitestore.es/orderrequest?id=<?php echo $_product->getId()?>" rel="shadowbox;width=728 height=700;scroll=none"><?php echo $this->__('Order by Request'); ?></a>
                            											<?php endif; ?>
                                                                	
                                                                	</div>
                                                                    <div style="float: left;padding: 10px;"><a class="more-info" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('More Info');?></a></div>
                                                                </div>    
                                                                </div>
                                                            