<?php

class Magestore_Auction_Model_Source_Biddernametype
{
    public function toOptionArray()
    {
        return array(
            array('value'=>1, 'label'=>Mage::helper('auction')->__('Generated by System')),
            array('value'=>2, 'label'=>Mage::helper('auction')->__('Created by Customers')),
            array('value'=>3, 'label'=>Mage::helper('auction')->__('Based on Customer\'s Name')),
        );
    }
}