<?php $paisesUE = array ('DE','AT','BE','BG','CY','HR','DK','SK','SI','ES','EE','FI','FR','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','UK','CZ','RO','SE','GB'); ?>
<?php $paisCustomer = Mage::getSingleton('geoip/country')->getCountry(); ?>
<?php 
$precio=0;
if(in_array($paisCustomer, $paisesUE)):
	$precio=252 . "€";
else: 
	$precio=208.26 . "€";
endif;
$marca="Adidas By Kanye West";
$titulo="Yeezy Boost 350 Moonrock";
?>
<style>
    .box {
        padding: 5px;
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        background: rgba(15,15,15,0.2);
    }
    .cerrar{
        position: absolute;
        right: 14px;
		top: 0;
        font-size: 2em;
        cursor: pointer;
    }
</style>
<?php if($_GET['mensa']):?>
<div id="messages_product_view"><ul class="messages"><li class="success-msg"><ul><li><span>Thanks for your contact.</span></li></ul></li></ul></div>
<?php
endif;
?>
<div style="width:100%; text-align: right; background:url('<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-boost-350.png') no-repeat left center, #fff;height: 342px;">
<div style="float:right; margin: 126px 60px 0px 0px;;">
    <span style=" color: grey; font: lighter 3.5em/100% 'Open Sans';">YEEZY BOOST 350</span><br/>
    <span style="font: lighter 2.8em/100% 'Open Sans';color: grey;letter-spacing: 2.8px;">MOONROCK RAFFLE</span>
</div>
</div>

<?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>
<p style="margin: 3em 0;">
A total of 1953 fashion passionates participated in our YEEZY BOOST 350 MOONROCK RAFFLE, and we want to thank each and every one of you!!!
</p>
<p style="margin: 3em 0;">
And without further ado… here are the lucky winners. Congratulations!!!
</p>
<?php else:?>
<p style="margin: 3em 0;">
Hemos recibido un total de 1.953 solicitudes apasionados participantes en el sorteo de las YEEZY BOOST 350 MOONROCK, y queremos darles las gracias a todos y cada uno de ellos!!
</p>
<p style="margin: 3em 0;">
Y sin más preámbulos ... aquí están los afortunados ganadores. ¡¡¡Felicidades!!!
</p>
<?php endif; ?>
<!--       primera yeezy-->
<ul class="products-grid columns3 first odd" style="width:100%;">
    <li class="item first " style="width: 225px;">
    			<img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_0a.jpg" width="215" height="215" alt="Yeezy" usemap="#mapa4">
                <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 7UK:<?php else: ?>Ganadores talla 7UK:<?php endif ?></div>

                    </div>
				<ul style="margin: 10px 30px;list-style-type: disc;">
               		<li>Nanmi Kim</li>
                    <li>Elena Flores Regueiro</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-size7.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
    </li>
    <li class="item first " style="width: 225px;">
    			<img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_0a.jpg" width="215" height="215" alt="Yeezy" usemap="#mapa4">
                 <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 8UK:<?php else: ?>Ganadores talla 8UK:<?php endif ?></div>

                    </div>
               <ul style="margin: 10px 30px;list-style-type: disc;">
                    <li>Zhiming Yuan</li>
                    <li>Mathew Sutton</li>
                    <li>Mustafaa Hussain</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-size8.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
    </li>
    <li class="item first " style="width: 225px;">
			    <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_0a.jpg" width="215" height="215" alt="Yeezy" usemap="#mapa4">
                 <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 9UK:<?php else: ?>Ganadores talla 9UK:<?php endif ?></div>

                    </div>
               <ul style="margin: 10px 30px;list-style-type: disc;">
                    <li>Grant Yang</li>
                    <li>Maniel Torres</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-size9.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
               </div>
  	</li>
    <li class="item first " style="width: 225px;">
		    <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/yeezy-moonrock_0a.jpg" width="215" height="215" alt="Yeezy" usemap="#mapa4">
             <div class="moreinfo">
                	<div class="product-title">
	                    <div class="manuf-list"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>Winners size 10UK:<?php else: ?>Ganadores talla 10UK:<?php endif ?></div>

                    </div>
               <ul style="margin: 10px 30px;list-style-type: disc;">
                    <li>Amir Saidlar</li>
                    <li><a href="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/aw15/pdf/winners-yeezy-size10.pdf"><?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>See All Participants<?php else: ?>Ver todos los participantes<?php endif ?></a></li>
               </ul>
                <div class="moreinfo">
    </li>

</ul>

<?php if (Mage::app()->getStore()->getId()==2 || Mage::app()->getStore()->getId()==6): ?>
<p style="margin-top: 1em;">
RAFFLE CONDITIONS<br>
• The raffle starts on Saturday, November 14 at 11.00 AM CET and ends on Monday, November 16 at 11.00 AM CET.<br>
• By signing up for the raffle (in case you haven’t joined us yet), you automatically sign up for our newsletter.<br>
• Only ONE entry per person is allowed. <br>
• The winners will be announced on our social media, and notified via phone and email, including a private link to finish the purchase. In case the winner doesn’t make the purchase within 24hrs, a new winner will be randomly selected from among all signed up participants.<br>
• Return policy: refund within 14 days of the delivery date. <br>
• In case of a return, a new winner will be randomly selected from among all signed up participants.<br>
</p>
<?php else:?>
<p style="margin-top: 1em;">
CONDICIONES DE LA SUBASTA<br>
• La subasta comenzará el Sabado 14 de Noviembre a las 11AM (CET) y terminará el Lunes 16 de Noviembre a las 11AM (CET).<br>
• Al enviar su solicitud de inscripción (en el caso en que no lo esté ya), usted será automaticamente inscrito en nuestra lista de newsletter.<br>
• Solo se tendrá en cuenta 1 solicitud de suscripción por persona. <br>
• El ganador será anunciado en nuestras redes sociales, y personalmente via email y teléfono, incluyendo un link privado para formalizar la compra. En caso en que el ganador no formalizase la compra en las siguientes 24h, será seleccionado un nuevo ganador de entre los restantes participantes.<br>
• Política de devolución: El plazo de devolución del artículo es de 14 días desde la recepción del mismo. <br>
• En caso de devolución, se seleccionará un nuevo ganador de entre los restantes participantes.<br>
</p>
<?php endif; ?>
</script>